### ISSUE TITLE
Option<T>  do not loose Null with strict conditions

### ISSUE THREAD

**Issue by Lonli-Lokli** [louthy/language-ext#1006]
Im on .NET 5 project with <Nullable>enable</Nullable> I cannot use implicit Option conversion

```
private Option<string> GetStringNone3()
        {
            // This should be coerced to None
            string? nullStr = null;
            return nullStr;
        }
```

[CS8604] Possible null reference argument for parameter 'a' in 'Option<Document>.implicit operator Option<string>(string a)'.

It happens because operator do not remove null from type
```
[Pure]
[MethodImpl(MethodImplOptions.AggressiveInlining)]
public static implicit operator Option<A>(A a) =>
Optional(a);
```

**Comment by louthy** [comment]
> It happens because operator do not remove null from type

I'm not sure what you mean by this, but the library doesn't have nullable annotations.  You could try:
```c#
   return default;  // this will coerce to None;
   return None; 
   return Optional(nullStr);
```

**Comment by harrhp** [comment]
in my project i use these functions. when this lib is nrt aware they can be deleted
```
public static Option<T> NrtOptional<T>(T? value) where T : class => Optional(value!);

public static T? ToNrt<T>(this Option<T> option) where T : class => option.ValueUnsafe();
```

**Comment by louthy** [comment]
`Option` now supports nullable references (in version `4.0.8-beta`).  So the implicit cast from `null` will now work, as well as calls to `Optional(null)`

**Comment by Lonli-Lokli** [comment]
> > It happens because operator do not remove null from type
> 
> I'm not sure what you mean by this, but the library doesn't have nullable annotations. You could try:
> 
> ```cs
>    return default;  // this will coerce to None;
>    return None; 
>    return Optional(nullStr);
> ```

If you turn on Nullable for Option test package and add test as it is, you will notice same warning as in my original post.

I will later add reference to my clone
