### ISSUE TITLE
Can't use static Seq and preludes in same file

### ISSUE THREAD

**Issue by hallsbyra** [louthy/language-ext#1011]
Maybe it's impossible, but wouldn't you expect this to compile:

![image](https://user-images.githubusercontent.com/2835896/158563204-c2ddb5b6-891f-4e93-ad19-892a0749fc2c.png)

**Comment by CK-LinoPro** [comment]
This is what I usually do:

``` cs
using L = LanguageExt;
using static LanguageExt.Prelude;

var x = Seq(1, 2);
var y = L.Seq.repeat(1, 2);
```
