### ISSUE TITLE
Option.Match fails in a situation it should not fail in.

### ISSUE THREAD

**Issue by EivindAntonsen** [louthy/language-ext#1017]
Hi,
using a method invocation like `maybeValue.Match(some => BuildObjectWithSome(some), BuildObjectWithNone());` it does not seem to accurately match the option. Using the debugger I suspend the method invocation before it is run and confirm `maybeValue.IsSome` . Still, matches the option as `None`.

When I recreate this in a small console application for testing it does work with different types. The type that does not work is simply a public partial class in my solution (EF entity). I am stumped by the fact I can verify the `Option.IsSome` and it doesn't work, but when I do it with a value type such as `int` in the console application it does work.

I am using SDK C# `6.0` targeting `netcoreapp3.1` with `languageExt.Core v4.0.3`

I am relatively new to .Net but struggle making sense of this. I am surely using this wrong. Any ideas? How would you debug this?

**Comment by louthy** [comment]
You're calling the 'None is a value' overload of `Match`, the second argument isn't a lambda, so there's no laziness.  If `BuildObjectWithNone` is `Unit BuildObjectWithNone() { ... }` then you can do this:

```c#
// Note, the parens removed
maybeValue.Match(
    Some: x=> BuildObjectWithSome(x), 
    None: BuildObjectWithNone);  
```

If not, then you can do this:

```c#
maybeValue.Match(
    Some: some => BuildObjectWithSome(some), 
    None: () => BuildObjectWithNone());  
```

The `Some` branch can be simplified too:

```c#
maybeValue.Match(
    Some: BuildObjectWithSome, 
    None: BuildObjectWithNone);  
```

**Comment by EivindAntonsen** [comment]
Thanks a lot for the swift response!

Of the three alternatives you provided, I changed to the second one and then it worked. If you've got a few minutes, can you explain why that worked instead of the alternative I provided in the original question (with 1st arg being a lambda and 2nd arg just being a method?

**Comment by louthy** [comment]
In your original version you're using an overload of `Match` that takes a `Func<A, B>` for the `Some` and a `B` for the `None`.  Values in C# are not lazy, and so by passing `BuildObjectWithNone()` for the second argument, it must first be invoked to get the result of `BuildObjectWithNone()` and that result passed to the `Match` method to be used if the `Option` is `None`.  

Therefore `BuildObjectWithNone()` will always be called, regardless of whether `Option` is `None` or not.  If C# was lazy like Haskell then this wouldn't be a problem.  Therefore, for C# we must do the laziness ourselves, by wrapping the call to `BuildObjectWithNone()` in a lambda, which will only be invoked if `Option` is `None`.

**Comment by louthy** [comment]
You may wonder why the overload that takes a non-lazy value exists, it's for situations like this:

```c#
   option.Match(Some: x => x + 1, None: 0);
```

`0` is already a concrete value, and so we don't need it to be lazy.  This leads to a slight performance gain, because there's no need to allocate a lambda just to wrap the value: `() => 0`.  And so, those overloads are to minimise the overheads can lead to slightly more optimal code where necessary (and less visual clutter).
