### ISSUE TITLE
Using the Collection Initializer of HashSet results in an empty HashSet (but compiles just fine)

### ISSUE THREAD

**Issue by Malgefor** [louthy/language-ext#1018]
Hi!

When you use the collection initializer of a HashSet you end up with an empty HashSet, which I guess is the case because it is an immutable collection, but since I am creating the collection at that point in time and not modifying it after creation I was surprised to see my HashSet was empty. The thing is that this compiles just fine but at runtime the HashSet is empty. Below a comparison between the System and LangExt versions of the type:

```csharp
using System.Collections.Generic;

using Shouldly;

using Xunit;

namespace Tests;

public class HashSetTest
{
    private static readonly LanguageExt.HashSet<string> HashSetLangExt =
        new()
        {
            "value1",
            "value2",
            "value3"
        };

    private static readonly HashSet<string> HashSetSystem =
        new()
        {
            "value1",
            "value2",
            "value3"
        };

    [Fact]
    public void LangExt_ShouldContainItems() => HashSetLangExt.ShouldNotBeEmpty(); // False

    [Fact]
    public void System_ShouldContainItems() => HashSetSystem.ShouldNotBeEmpty(); // True
}
```

I don't know if this is intended behavior or a bug, but it sure is confusing :P

(running the latest version of LangExt btw)

**Comment by louthy** [comment]
There’s nothing I can do about that (as far as I am aware), this is a flaw in C#’s collection initialisation system.  I believe it calls Add after construction, but obviously it’s an immutable collection.  The crux of it is that you can’t use this.

instead use the construction function:

    var ha = HashSet(1, 2, 3)

**Comment by louthy** [comment]
There is a PR open which provides an analyser to warn about this, but it needs some work.

https://github.com/louthy/language-ext/pull/868

**Comment by louthy** [comment]
[I also raised this as an issue on `csharplang` a while back](https://github.com/dotnet/csharplang/issues/3211), but it was basically ignored.

**Comment by Malgefor** [comment]
Ahh I thought something like that was the case, thanks for the explanation! The analyzer would be helpful indeed. Maybe we should tag this issue as documentation for visibility? Anyway, I will close this issue.
