### ISSUE TITLE
Suggestion: Add Bind and BindAsync function to the Result<>

### ISSUE THREAD

**Issue by Grenkin1988** [louthy/language-ext#1023]
It would be nice to add to the library binding of Result<>

```
public Result<B> Bind<B>(Func<A, Result<B>> f)
public async Task<Result<B>> BindAsync<B>(Func<A, Task<Result<B>>> f)
```

**Comment by diab0l** [comment]
From the documentation, direct usage or Result is discouraged.

`Result<A>` is more or less the same as `Either<Exception, A>`, so how about adding a `Result<>.ToEither/ToEitherAsync` method instead of `Bind/BindAsync`?

**Comment by louthy** [comment]
That’s true, I’d like to deprecate it at some point.  The supported equivalent monad is: Fin<A>

**Comment by louthy** [comment]
`Fin<A>` is a synchronous type, so it doesn't make sense to have an `BindAsync` until there's a `FinAsync<A>` pair (like `EitherAsync` for `Either` and `OptionAsync` for `Option`).  Yes, it could return a `Task<Fin<B>>` but that then becomes a future breaking change when I add `FinAsync`.

You might want to consider using `Eff` and `Aff` - as they are effectively wrappers for functions that return `Fin`.  I guess it depends on your use-case, but they are fully featured and are designed to play nice with each other.  You can create success and fail values like so:

```c#
    var mx = SuccessEff(123);
    var my = FailEff(Error.New("error"));
    var mz = FailEff(new Exception());
```
They are lazy though, so you must call `mx.Run()` to get the `Fin` out of it.  Outside of that, the other option would be to use `Either<Error, A>` and `EitherAsync<Error, A>`

**Comment by Grenkin1988** [comment]
Thanks. Going to try
