### ISSUE TITLE
MapFail on Eff?

### ISSUE THREAD

**Issue by guythetechie** [louthy/language-ext#1037]
`Eff` doesn't seem to have `MapFail` (unlike `Aff`). Is there a reason why it shouldn't? Completely understand if it just hasn't been implemented.

In the meantime, my quick/dirty workaround is an extension that does `Eff` -> `Aff` -> `MapFail` -> `Eff`.

Thanks!

**Comment by louthy** [comment]
There is for the RT version, seems there’s an oversight on the non-RT version.  You can use BiMap as a workaround, passing identity for Succ

    ma.BiMap(Succ: identity, Fail: e => …)

**Comment by guythetechie** [comment]
Thank you, will update my extension. Please let me know whether you'd like to close the issue or keep it open for tracking.

**Comment by louthy** [comment]
I’ll leave it open, it needs to be resolved.  Feel free to do a PR if you’re feeling adventurous ;)

**Comment by guythetechie** [comment]
PR #1038 submitted.

**Comment by louthy** [comment]
Released in `4.2.1`.  Thanks for the PR 👍
