### ISSUE TITLE
Just curious why ForEach is not implemented

### ISSUE THREAD

**Issue by khtan** [louthy/language-ext#104]
Hi,
I am reading Enrico Buonanno's Functional Programming in C# ( MEAP ), and he references Language-Ext as a more production quality implementation while his LaYumba is more of a teaching implementation.
While LaYumba implements ForEach, I was not able to find Language-Ext's implementation. Is there a reason for this? Maybe, there is a alternative functional way to achive this in Language-Ext.
Thanks,

**Comment by khtan** [comment]
Sorry, the above is not an issue but I just had a question. Thanks,

**Comment by louthy** [comment]
Hi @khtan, no problem, it's call `Iter` for iteration in lang-ext.

**Comment by khtan** [comment]
Thanks. In case you are interested, a comment on the Iter like // also known as ForEach 
would help beginners like me find the function more quickly. Great work!

**Comment by ceywj** [comment]
ForEach will be trasformed fo "foreach (x in y )" by the VS IDE all the time ,I think call it Iter is a good idea
