### ISSUE TITLE
Question: combine several tryoption

### ISSUE THREAD

**Issue by stenvix** [louthy/language-ext#1043]
Hey, could you point me to docs, where I can read how to combine TryOptions to perform action for both of them when they have some value ? 
![image](https://user-images.githubusercontent.com/7223115/171967223-fb87106e-5018-4ca5-a4ae-7c2f0f29daec.png)

**Comment by louthy** [comment]
One thing to understand is that `TryOption` is a monad.  The behaviour of a monad is to capture all of the boilerplate you're writing by hand in the example above, so you never have to.

When you stop manually unpacking the values and instead let the bind machinery of the monad do it for you, your code will look like this:

```c#
var result = from account          in AccountProvider.FindAsync(request.Order)
             from aggregate        in AccountAggregateFactory.GetAsync(request.Id)
             from existedBuilder   in AccountAggregateFactory.GetAsync(account.Id)
             let oldOrder          =  aggregate.Data.DisplayOrder
             let _1                =  aggregate.Order(request.Order)
             from _2               in aggregate.SaveAsync()
             from accountAggregate in AccountAggregateFactory.GetAsync(account.Id)
             let _3                =  accountAggregate.Order(oldOrder)
             from _4               in accountAggregate.SaveAsync()
             select new UpdateAccountOrderResponse();
```

The next issue you need to be aware of is that you're mixing three different monadic types:

* `Task`
* `TryOption`
* `TryOptionAsync`

They all have different capabilities, and so they're not compatible with each other automatically.  You need to pick the _most capable_ monad and use what's known as a _natural transformation_ to convert from the monads that are less-capable into the most-capable monad.

In your case the most capable monad is `TryOptionAsync`.  It has:

* Exception catching (the `try` part)
* Possibility of returning no-result (Optional)
* Asynchrony

Neither `TryOption` nor `Task` have those capabilities.  So, you need to make your `Task` values and `TryOption` values into `TryOptionAsync` for them to all be usable in the same monadic-expression (LINQ expression).

So, what is a natural-transformation?

The way to think about it is this.  First, think of what a functor is, functors have a `Map` function, that allows me to say map a `Seq<int>` to a `Seq<string>`, or a `Option<Person>` to an `Option<Name>`.  The `Map(Func<A, B> f)` function maps the values _inside_ the functor - but it keeps the same _container_ (the `Seq`, the `Option`, etc.).

A natural-transformation maps the _container_, but keeps the values within.  So the natural-transformation from `IEnumerable<A>` to `Seq<A>` is the `ToSeq()` method.  

So to make your code sing you need to transform `Task<A> -> TryOptionAsync<A>` and `TryOption<A> -> TryOptionAsync<A>`

To convert a `TryOption<A>` to a `TryOptionAsync<A>` call:

```c#
    tryOption.ToAsync()
```

To convert a `Task` to a `TryOptionAsync`, call:

```c#
    TryOptionAsync(task)
```

You will then have everything aligned, and the `result` in the example I wrote above will be a `TryOptionAsync`.  It will automatically deal with exceptions, no-result (`None`), and asynchrony (`await`) without you having to do so.

You also have a few methods there that don't appear to have a return value (i.e. they're not composable in expressions).  Like the `aggregate.Order(...)` and the logging.  They best thing there is to wrap them up into `Unit` returning functions, so they can be used in expressions.

I'd encourage you to [look at the wiki](https://github.com/louthy/language-ext/wiki) for general guidance.  A few key things that will help:

* The [Thinking Functionally](https://github.com/louthy/language-ext/wiki/Thinking-Functionally) series
   * Especially the [What is LINQ really?](https://github.com/louthy/language-ext/wiki/Thinking-Functionally:-What-is-LINQ-really%3F) section

One final thing, I would like to discourage you from using `Try`, `TryOption`, and `TryOptionAsync`.  They have been superseded by `Eff` and `Aff`.

`Try`, `TryOption`, and `TryOptionAsync` are explicitly about code with side-effects (that might throw exceptions), but they're not very opinionated beyond that.  `Eff` and `Aff` (Effect and Async Effect) are opinionated ways to do IO and side-effects and to elegantly handle exceptional and non-exceptional errors, as well as asynchrony.  They also work well together in LINQ expressions (the natural transformations happen automatically).  

Finally, they're shorter to type ;) 

Each type has two flavours:

* `Eff<A>` is the synchronous effect that can result in `Success` or `Fail(Error)`
* `Eff<RT, A>` is the synchronous effect that can result in `Success` or `Fail(Error)`, with an injectable _runtime_.
* `Aff<A>` is the asynchronous effect that can result in `Success` or `Fail(Error)`
* `Aff<RT, A>` is the asynchronous effect that can result in `Success` or `Fail(Error)`, with an injectable _runtime_.

There's a [big section of the wiki about handling IO](https://github.com/louthy/language-ext/wiki/How-to-deal-with-side-effects) (including injectable effects).  It mostly focusses on the _runtime_ (`RT`) versions of the `Eff` and `Aff` monads; just know you don't need to use that to get going.  It's worth understanding why manually unpacking the monads (through `Match`, `IfSomeAsync`, `Run`, etc.) should hardly ever need to be done.  This article starts with that guidance.

There's also [a sample application](https://github.com/louthy/language-ext/tree/main/Samples/EffectsExamples) that demos the capabilities of the `Eff` and `Aff` monads.

I hope that helps!

**Comment by stenvix** [comment]
Very useful information, thank you, I understood the direction of development. You can close an issue.
