### ISSUE TITLE
  Q: What is GroupBy known as in Language-Ext?

### ISSUE THREAD

**Issue by khtan** [louthy/language-ext#105]
I am looking for Linq's GroupBy function in LanguageExt. When I checked Scala and Haskell, they are
also called GroupBy. So I am wondering what name is GroupBy implemented in LanguageExt?

Thanks,

**Comment by louthy** [comment]
`GroupBy` is just an extension method on `IEnumerable<T>`.  All of the collection-types in lang-ext (`Lst<T>`, `Map<K,V>`, `Set<T>`, `Que<T>`) are derived from `IEnumerable<T>` and therefore get the `GroupBy` extension by default.

So just include `using System.Linq` and you're good to go.

**Comment by khtan** [comment]
Belated thanks. Just got confused which functions are standard functional HOF ( Map, Reduce etc ) and which are Microsoft's Linq, like GroupBy.
