### ISSUE TITLE
Eq has no instance for invariant culture string comparison (yet?)

### ISSUE THREAD

**Issue by geluk** [louthy/language-ext#1054]
Hi, I noticed that there are Eq instances for most types of string comparison (`EqString`, `EqStringOrdinal`, and  `EqStringCurrentCulture`, and their case-insensitive variants) except invariant culture comparison.

Writing my own implementation was easy enough, but I was wondering if there is a specific reason for its absence, or if you just didn't get around to it yet. If so, I wouldn't mind submitting a pull request to contribute the implementation.

I'd like to know your opinion on this; if you think it is useful to have, I can prepare a PR (including instances for Hashable, Ord, etc).

**Comment by louthy** [comment]
Released in `v4.2.7` 👍

**Comment by geluk** [comment]
That was quick, thanks @louthy!
