### ISSUE TITLE
Mapping an operation which itself returns Result<T> returns a Result<Result<T>>

### ISSUE THREAD

**Issue by dale-palmer** [louthy/language-ext#1062]
Consider the following code (I have not compiled it so it may be wrong, but should illustrate the point):

```
public interface ISomething<T>
{
    Result<T> DoSomething(int x);
}

public class Runner<T>
{
    private ISomething<T> _something; // Assume this is injected through a constructor

    // Constructor removed for brevity

    public void Run()
    {
        var foo = new Result<int>(123);
        var bar = foo.Map(x => _something.DoSomething(x));
    }
}
```

The desired return value for 'bar' would ideally be the `Result<T>` from the mapped operation. Instead it is of type `Result<Result<T>>`.

Scott Wlaschin (swlaschin) demonstrates a _Bind_ operation in his F# presentations which gives the desired behaviour.

**Comment by evermanwa** [comment]
Which presentation are you referring to? I will note that the Bind and Map functions, if I am not mistaken, are not the same thing.

**Comment by dale-palmer** [comment]
He talks about it in a few of his presentations, most notably the "Railway oriented programming" ones.

You're right that they're not the same thing but the biggest difference is in the return type. Other than that they're fairly similar.

I have used this library in a few projects not and have ended up writing this function as an extension method on more than one occasion so thought I would like to add it to the source code because I'm sure others will be doing the same. `.Map()` doesn't quite fit for most of my use cases where I want to chain processes together.

**Comment by EivindAntonsen** [comment]
If you have two methods that return `Option<T>` and you chain them with `.Map()`, you'll end up with `Option<Option<T>>`. This is where Bind comes in - it flattens the structure to `Option<T>` instead. I realize this is an old post, but hoping this helps (maybe I misunderstood your question).

**Comment by louthy** [comment]
@dale-palmer `Result` isn't designed to be monadic because it's is purely used [as an intermediate value for `Try` and the like](https://github.com/louthy/language-ext/blob/main/LanguageExt.Core/Common/Result/Result.cs#L24).  If you want `Bind` functionality (and support for using with LINQ) then I'd suggest `Fin<A>`, which is the closest to `Result` in capability.

**Comment by louthy** [comment]
https://github.com/louthy/language-ext/wiki/Frequently-Asked-Questions#where-is-result
