### ISSUE TITLE
Issue: Upgrade to language-ext 4.2.8 (codegen) ended in error while build

### ISSUE THREAD

**Issue by LaszloLueck** [louthy/language-ext#1071]
After updating to laguage-ext 4.2.8 i cannot build any project anymore.
Error is
`CGR1001   CodeGeneration.Roslyn.BuildTime.targets(73, 5): [CGR1001] CodeGeneration.Roslyn.Tool (dotnet-codegen) is not available, code generation won't run. Please check https://github.com/AArnott/CodeGeneration.Roslyn for usage instructions.`

I will figure out if it is a specific (sub) library of language-ext

**Comment by LaszloLueck** [comment]
Here it is a more specific information:
Currently the build fails after updating 
LangguageExt.CodeGen to version 4.2.8
After downgrade to 4.2.7 all works fine

**Comment by LaszloLueck** [comment]
Hi,
thats crazy.
Before,
`CodeGeneration.Roslyn` was implicitly installed as version 0.7.63
`CodeGeneration.Roslyn.BuildTime` was implicitly installed as version 0.6.1

I´ve downgraded `CodeGeneration.Roslyn` as you suggested to version 0.6.1 but without luck.
Any version combination fails with `LanguageExt.CodeGen` version 4.2.8

I´ve tested that issue with an new, empty dotnet (6) core console app.
Insert the following imports:
<img width="816" alt="image" src="https://user-images.githubusercontent.com/3159204/176023173-97cb67bf-2170-4c30-8b9b-910e32c711d2.png">


And the build failed.
If i downgrade `LanguageExt.CodeGen` to version 4.2.7 --> the build failed.
If i remove the explicit added
`CodeGeneration.Roslyn`
`CodeGeneration.Roslyn.BuiltTime`
than the build succeeded.
If i changed the implicit imports to the following versions, the build would also be succeeded:
<img width="816" alt="image" src="https://user-images.githubusercontent.com/3159204/176024100-c7f5b3b6-ca83-43ff-8cff-a7d737e73171.png">


But, as i update `LanguageExt.CodeGen` to >4.2.7 the build would failed!


Regards,
Laszlo

**Comment by louthy** [comment]
Have you recently moved to a new machine?  The code-gen library [needs the .NET 2.1 SDK](https://github.com/AArnott/CodeGeneration.Roslyn#prerequisites) to run.

**Comment by LaszloLueck** [comment]
No,
i´ve not moved or removed to or from a machine.
You wrote: 'The code-gen library [needs the .NET 2.1 SDK] https://github.com/AArnott/CodeGeneration.Roslyn#prerequisites) to run.'

That´s confusing, because the version 4.2.7 does not need the .NET 2.1 SDK (because it is working on my machine)?

Here are some informations about my setup.
Ah, and yes, it is on aarm 

```
dotnet --info
.NET SDK (gemäß "global.json"):
 Version:   6.0.301
 Commit:    43f9b18481

Laufzeitumgebung:
 OS Name:     Mac OS X
 OS Version:  12.4
 OS Platform: Darwin
 RID:         osx.12-arm64
 Base Path:   /usr/local/share/dotnet/sdk/6.0.301/

Host (useful for support):
  Version: 6.0.6
  Commit:  7cca709db2

.NET SDKs installed:
  6.0.201 [/usr/local/share/dotnet/sdk]
  6.0.202 [/usr/local/share/dotnet/sdk]
  6.0.203 [/usr/local/share/dotnet/sdk]
  6.0.300 [/usr/local/share/dotnet/sdk]
  6.0.301 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.3 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.4 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.6 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.3 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.4 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.6 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
`
``

**Comment by LaszloLueck** [comment]
No matter what environment (linux, windows, macos, x64, aarm, arm64) I use, the problem is always the same.
I´ve created a completely new dotnet core 6 project, use languageext.codegen (4.2.8 or 4.2.9) from nuget and the build fails.
If i use languageext.codegen <4.2.8 the build works fine.

**Comment by louthy** [comment]
Hmm, does seem odd.  Nothing has changed in the `CodeGen` project.  If using an old version works, it'd be best to stick with that for now.

I've frozen development on the `CodeGen` project, the new Source-Generators based project will eventually take it over and I'll maintain `CodeGen` in a frozen state for those that can't move over.  The only reason the version number keeps going up is because it's part of my standard deployment tooling - it has no dependencies on the other libs, so staying on an old working version won't cause any problems at all.

I will try and find some time over the next few days to take a look though, it does seem a bit strange that it'd just stop working now.

**Comment by LaszloLueck** [comment]
Fine for me. 4.2.7 works perfect for me.
Maybe someone else has the same problem, then it is already addressed here.
Thanks and regards,
Laszlo

**Comment by jvmlet** [comment]
> I've frozen development on the CodeGen project, the new Source-Generators based project will eventually take it over

**Comment by DannyMeister** [comment]
Thank goodness I ran into this thread which caused me to try downgrading to 4.2.7.  That finally let me use codegen in a .NET 7 project.  I had already tried `DOTNET_ROLL_FORWARD=LatestMajor` and `--roll-forward LatestMajor` to no avail (and verified with ProcMon that my msbuild file shenanigans had indeed been properly passed along to the `dotnet codegen` process).  Requiring an older sdk version won't be an option for certain tightly controlled build environments.

**Comment by reza-repo** [comment]
I am also getting this:   `CodeGeneration.Roslyn.BuildTime.targets(73, 5): [CGR1001] CodeGeneration.Roslyn.Tool (dotnet-codegen) is not available, code generation won't run. Please check https://github.com/AArnott/CodeGeneration.Roslyn for usage instructions.`

I tried setting `DOTNET_ROLL_FORWARD=LatestMajor` and it did not help.

I also tried downgrading to `4.2.7` as suggested above (https://github.com/louthy/language-ext/issues/1071#issuecomment-1407122047) and it did not work either.

**Comment by louthy** [comment]
https://github.com/louthy/language-ext/wiki/Frequently-Asked-Questions#why-doesnt-languageextcodegen-work
