### ISSUE TITLE
[Wiki improvement] - Small improvement in [WithLens] example

### ISSUE THREAD

**Issue by kgkoutis** [louthy/language-ext#1077]
The code listings found [here](https://github.com/louthy/language-ext#withlens) and [here](https://github.com/louthy/language-ext/wiki/Code-generation#withlens) are generally speaking ok, but if you copy paste them directly to your project you will probably get squiggly lines. In particular this method
```csharp
// Local function for composing a new lens from 3 other lenses
Lens<Person, ApptState> setState(int id) =>
       lens(Person.appts, Map<int, Appt>.item(id), Appt.state);
```
`Map` might refer to `Prelude.Map` (a method) and `LanguageExt.Map` (a type). Chances are higher that you will miss 5-10 minutes fiddling with your code why it doesn't work until you decide to decompile it and since it involves code generation it becomes more obscure to the untrained eye of this library. Therefore the improvement I propose is to include the namespace like so:

```csharp
// Local function for composing a new lens from 3 other lenses
Lens<Person, ApptState> setState(int id) =>
       lens(Person.appts, LanguageExt.Map<int, Appt>.item(id), Appt.state);
```

Aside from this fix, I do propose to include another gist for the source generated code also for this example (like [Click here to see the generated code](https://gist.github.com/louthy/6cb6c2611569bd29de48b75385c4ac57)) and also for [[WithLens](https://github.com/louthy/language-ext/wiki/Code-generation#with)] section - that basically introduces the `With` method on `A`. What might be evident to some, might seem magic to first time visitors that want to take a grasp on what's going on in the library

**Comment by louthy** [comment]
[CodeGen has been deprecated](https://github.com/louthy/language-ext/wiki/Frequently-Asked-Questions#why-doesnt-languageextcodegen-work) and the README updated.
