### ISSUE TITLE
Request: allow proxying of all interfaces on a type

### ISSUE THREAD

**Issue by OlduwanSteve** [louthy/language-ext#109]
Right now spawn<Interface> + proxy<Interface> only works for one specific interface.

It would be far more powerful if the spawn did not *require* a specific interface and instead used reflection to find all available interfaces (and bases) on the implementation type. Then the call to proxy would need to allow proxying of any of these available interfaces.

The primary benefit would be to allow multiple interface 'aspects' to a single process, e.g. 'public API' and 'internal implementation', while still getting the benefits of the message queue.

It would also make it easier to perform versioning of public interfaces over time, by simply adding newly named interfaces but continuing to maintain implementations of the old versions.

**Comment by louthy** [comment]
@OlduwanSteve Hi Steve, not sure I entirely follow.  It should allow you call the `proxy` function for the same `ProcessId` multiple times for different interfaces.  What behaviour are you seeing when you try this?

**Comment by OlduwanSteve** [comment]
Sorry I realised I didn't need the second interface so I can't now repro the error. I _think_ it was this one:

`return Left<string, object>("Message-type ("+message.GetType().FullName+") doesn't match inbox declared type: " + String.Join(", ", inboxDeclaredType.Map(x => x.FullName)));`

And from that I assumed it wasn't the intended behaviour. It may just have been that the old metadata was registered in redis and hadn't been updated yet. I'll close this for now and reopen if it comes up again.
