### ISSUE TITLE
What happened to the `BindT` extension for Task<Validation<L, A>>?

### ISSUE THREAD

**Issue by ode2code95** [louthy/language-ext#1094]
Today I upgraded a project from 3.5.24-beta to 4.29 (latest stable on NuGet) and the build failed, not finding a `BindT` extension. I pulled the LanguageExt source but am unable to find that extension in the current codebase.

Any suggestions on the new best method to use for this?

Possibly this issue is related to #381 by @TysonMN ?

**Comment by TysonMN** [comment]
Can you link to the method you were previously using?

**Comment by ode2code95** [comment]
Thank you, @TysonMN, the closest version to this method in `main` is [this BindT function](https://github.com/louthy/language-ext/blob/d6fb39a34b973708ab955ce6e6c68bdfc9d2ad51/LanguageExt.Transformers/HKT/Extensions/BindExtensions.Outer.AsyncSync.cs), which returns an OptionAsync.

Let me see if I can find the branch from 4.29-beta. One thing that's confusing to me is I'm not sure which functions are generated by a T4 template and which ones are handwritten.

**Comment by ode2code95** [comment]
Ok this is the commit where this function was introduced (which was indeed related to #381 above according to the message).
https://github.com/louthy/language-ext/commit/5bd425b6762ced30ffc0df46717f81558110dacf

**Comment by louthy** [comment]
Check these release notes: https://github.com/louthy/language-ext/releases/tag/v4.2.0

**Comment by ode2code95** [comment]
Hey thanks! I figured it must have been something simple like that . . . I just didn't know which way to turn.
