### ISSUE TITLE
System.Reactive support

### ISSUE THREAD

**Issue by ncthbrt** [louthy/language-ext#110]
Hi there,

The Nuget package Rx-Core is currently been marked as deprecated, and Reactive Extensions has been moved to https://www.nuget.org/packages/System.Reactive/
This unfortunately is confusing nuget, as I am using a library which has System.Reative as a dependency, resulting in a version conflict between the old and new versions of the package. 
I was wondering if you'd perhaps consider updating the library.

**Comment by louthy** [comment]
Hi Nick, if you build from source then all of the dependencies will be OK.  Unfortunately I can't deploy new versions at the moment, because the latest .NET Core tooling crashes when compiling the project. I've talked to the team at Microsoft and they're unable to work out the cause. My best bet (because they were able to help) is to wait until my new machine arrives (hopefully) this week.

**Comment by ncthbrt** [comment]
Sorry to hear about your issues. 
I've personally been having trouble with visual studio, I've been lately using VSCode's C# extension, because it feels somewhat more stable, but all in all, it hasn't been a smooth ride. :confused:

**Comment by louthy** [comment]
@ncthbrt Visual Studio is indeed a dog these days.  I have spent the past two days with it locking up for 10-20 seconds at a time every few minutes.  Reeeeallly tedious.  Unfortunately the build issues are in the dotnet build system, so even running from the command line causes the build system to crash.

One upside though is that all the very helpful chaps at MS that tried building it, built without problem.  So as soon as my new machine arrives I can get the .NET Core build done and out the door.

**Comment by louthy** [comment]
@ncthbrt Hi Nick, version 1.9.0 is now deployed to nu-get with full .NET Core support (and referencing System.Reactive 3.0.0)

**Comment by ncthbrt** [comment]
Awesome. Thank you.
