### ISSUE TITLE
Question: Why FSharpResult <-> Either Not Included in LanguageExt.FSharp?

### ISSUE THREAD

**Issue by jmojiwat** [louthy/language-ext#1103]
This library got me started on my functional thinking journey and making programming fun again. It has been a huge help in learning F# too.

I was wondering why FSharpResult <-> Either (among others) was not included in LanguageExt.FSharp?

**Comment by louthy** [comment]
More an oversight probably.  Happy to take a MR

**Comment by jmojiwat** [comment]
OK. Will work on it.

**Comment by louthy** [comment]
Released in: https://github.com/louthy/language-ext/releases/tag/v4.4.0
