### ISSUE TITLE
Generate null checks in code-gen

### ISSUE THREAD

**Issue by YuriiNskyi** [louthy/language-ext#1105]
Code generation is great feature, however, it is missing very desired behavior: null checks for properties.

How about to extend code-gen and maybe add special attribute, which indicates that null checks are included. Special constructor, which returns option/either/validation if some of the properties is null is also eligible.

What do you think about this?

**Comment by louthy** [comment]
https://github.com/louthy/language-ext/wiki/Frequently-Asked-Questions#why-doesnt-languageextcodegen-work
