### ISSUE TITLE
Feature Request: Immutable HashMap

### ISSUE THREAD

**Issue by Hinidu** [louthy/language-ext#111]
Hello!
I've just encountered the case when I want something like `Map` with all its goodness like map transformers but the type which I want to use as a key doesn't implement `IComparable` and so I can't use `Map` with it :disappointed:
Another benefit of immutable `HashMap` over `Map` that many operations could be faster.
Sadly I don't know how to implement it right now but I know that it is possible because [Haskell has it](https://hackage.haskell.org/package/unordered-containers-0.2.7.1/docs/Data-HashMap-Strict.html).
Perhaps I could try to do it myself but at least I want to know what do you think about that?
Thanks.

**Comment by louthy** [comment]
Hi Pavel, don't worry I know how to do it.  I think it could be a good addition.  Might be about a week if you can wait?

**Comment by Hinidu** [comment]
Great! I can wait of course! A week would be much faster than I could hope to find time to learn and implement it myself :-)
Thank you in advance!

**Comment by Hinidu** [comment]
Hello! I've just thought that immutable `HashSet` would be useful too. The only small problem that `System.Collections.Generic` already has a class with the same name...

**Comment by louthy** [comment]
@Hinidu Version 1.9.1 on nu-get now contains two new types: `HSet<T>` and `HMap<K, V>`, which are hash-set and hash-map respectively.  There are constructor functions in the prelude:

```c#
    using static LanguageExt.Prelude;

    // Construct a hash-map
    HMap<int, string> hmap = HashMap(Tuple(1,"Hello"), Tuple(2, "World"));

    // Construct a hash-set
    HSet<string> hset = HashSet("Hello", "World");
```
All of the functions available for `Map<K, V>` are available for `HMap<K, V>`, as is the case with `Set<T>` and `HSet<T>`.  They haven't had a huge amount of testing, but they're built on the existing `Map` and `Lst` structures, so I don't expect many problems.  But please let me know if you find any issues.

**Comment by Hinidu** [comment]
Hi @louthy! Sorry for the late response.
I didn't think about such implementation - it is quite straightforward :+1: I think algorithm in unordered containers for Haskell is more fancy.
Sadly I can't update `Language.Ext` to the version with `HashMap` in our project because new version depends on Rx 3.0 and Rx 3.0 requires at least NuGet 2.12 but NuGet 2.12 is not released yet for Visual Studio 2012 which we still use in our company... I hope this problem will be solved soon: perhaps we will switch to NuGet CLI instead of VS extension or we will get new version of VS :smile:
