### ISSUE TITLE
Question about State Monad

### ISSUE THREAD

**Issue by jcoder58** [louthy/language-ext#112]
I'm trying to grok the State Monad and how it should be used and am having issues getting it right.  I'm trying to code the example from [this article](https://dzone.com/articles/do-it-in-java-8-state-monad), which uses the Fibonacci sequence to demonstrate both memorization and the State Monad.  Your library makes memoization  easy, but I'm have trouble with the State Monad.    The article uses a map to implement memoization explicitly using the State Monad and a Map.

Here's the code:

    using System;
    using System.Numerics;
    using System.Diagnostics;

    using LanguageExt;
    using static LanguageExt.Prelude;
    using static LanguageExt.Map;

    namespace Fib {
        class Program {
            static Func<BigInteger,BigInteger> FibMemo = memo<BigInteger,BigInteger>(i => fib(i));
            static BigInteger fib( BigInteger n ) =>
                n == 0 || n == 1 ? n
                    : FibMemo( n - 1 ) + FibMemo( n - 2 );

            static Map<BigInteger,BigInteger> FibMap = Map(
                    Tuple<BigInteger, BigInteger>( 0, 0 ),
                    Tuple<BigInteger, BigInteger>( 1, 1 )
                    );

            static State<Map<BigInteger, BigInteger>, BigInteger> fibState( BigInteger n ) =>
                state => from m in get<Map<BigInteger, BigInteger>>()
                         from sp in put( tryAdd( m, n, fibState( n - 1 )( state ) + fibState( n - 2 )( state ).Value ) )
                         from mp in get<Map<BigInteger, BigInteger>>()
                         select State<Map<BigInteger, BigInteger>, BigInteger>( mp[n] );

            static void Main( string[] args ) {
                Stopwatch watch = new Stopwatch();
                watch.Start();
                var z = FibMemo(0);
                var o = FibMemo(1);
                var f =  fib( 50 );
                watch.Stop();
                Console.WriteLine( $"Fib Memo: {f} {watch.Elapsed}" );
                watch.Start();
                var fState = fibState(50)(FibMap);
                watch.Stop();
                Console.WriteLine( $"Fib State: {fState} {watch.Elapsed}" );
                Console.ReadKey();
            }
        }
    }

I'm getting two errors, both on the Linq expression in fibState:

    Severity    Code    Description Line    File    Project Suppression State
    Error   CS0029  Cannot implicitly convert type 'LanguageExt.State<LanguageExt.Map<System.Numerics.BigInteger, System.Numerics.BigInteger>, LanguageExt.State<LanguageExt.Map<System.Numerics.BigInteger, System.Numerics.BigInteger>, System.Numerics.BigInteger>>' to 'LanguageExt.StateResult<LanguageExt.Map<System.Numerics.BigInteger, System.Numerics.BigInteger>, System.Numerics.BigInteger>'   23  D:\Research\Sunphase\Fib\Program.cs Fib Active
    Error   CS1662  Cannot convert lambda expression to intended delegate type because some of the return types in the block are not implicitly convertible to the delegate return type 23  D:\Research\Sunphase\Fib\Program.cs Fib Active

Any help in getting this working would be appreciated.
`

**Comment by louthy** [comment]
Try this:
```c#
        static State<Map<bigint, bigint>, bigint> fibState(int n) =>
            from m in get<Map<bigint, bigint>>()
            from v in m.ContainsKey(n)
                ? State<Map<bigint, bigint>, bigint>(m[n])
                : n == 0 || n == 1
                    ? State<Map<bigint, bigint>, bigint>(n)
                    : from x  in fibState(n - 1)
                      from y  in fibState(n - 2)
                      from sm in get<Map<bigint, bigint>>()
                      from s  in put(tryAdd(sm, n, x + y))
                      select x + y
            select v;
```
I have also added the check for whether the number is already in the `Map`, and the terminator.

Mostly you shouldn't need to build your own lambda that takes `state =>`, and returns `State(x)`; that is all handled automatically by the bind function and LINQ.  My usage of `State(x)` above is on the right-hand side of the `from` statement, therefore I'm using it to construct a new `State` monad, and they're simply to wrap pre-calced value.

Oh all those `BigInteger` types were hurting my eyes, so I included this to make it a bit more readable:
```c#
    using bigint = System.Numerics.BigInteger;
```

**Comment by jcoder58** [comment]
@louthy ,

Thanks for the response.   Your version works for me.  And it makes it clear what I was doing wrong.

 If I understand this, you're using LINQ expressions similar to the way do/<- syntax works in Haskell, or as a limited form of F#'s computational expressions?

**Comment by louthy** [comment]
LINQ essentially is support for functors (via `Select`) and monads (via `SelectMany`).  So yes, it's exactly the same as `do` notation in Haskell.  Computation expressions are used for monads too, but they have many more features available beside the monadic bind, so LINQ is a subset and as you say a 'limited form of'.
