### ISSUE TITLE
LanguageExt.Sys.Test seems broken

### ISSUE THREAD

**Issue by phidevz** [louthy/language-ext#1127]
To me it seems, that at least the `Directory<RT>.enumerateFolders(...)` implementation is broken in the provided MemoryFS.

Given the following example:
* Given the directory `C:\test\` exists
* There also exists `C:\test\a\`and `C:\test\b\`
* We make the call `Directory<RT>.enumerateFolders("C:\\test\\", "*")` which actually would call `Directory<RT>.enumerateFolders("C:\\test\\", "*", SearchOptions.TopDirectoryOnly)`

Expected result: I get back a `Seq<string>` with the contents `"C:\\test\\a", "C:\\test\\b"`

Observed behavior: I get back `Seq<string>.Empty`

Doing this with the Live runtime works perfectly fine. Maybe @louthy misunderstood the meaning of `SearchOptions.TopDirectoryOnly`. It does not mean that only direct children of the root (in this case `C:\\`) should be considered, bot only direct children of the first parameter of the `enumerateFolders` function (in die case `C:\\test`).

Can you please confirm/deny my observations, and possibly provide a fix? 
Thanks in advance.

**Comment by WarrenCrabb** [comment]
As an alternative you could replace the LanguageExt.Sys in-memory file system with [System.IO.Abstractions.TestingHelpers](https://www.nuget.org/packages/System.IO.Abstractions.TestingHelpers). I have done that in one of my projects and works perfectly for my needs.

**Comment by louthy** [comment]
Fixed in: https://github.com/louthy/language-ext/releases/tag/v4.4.0
