### ISSUE TITLE
How to use nested Result<> functions?

### ISSUE THREAD

**Issue by ildoc** [louthy/language-ext#1128]
How can I get the Result<> exception (if is there one?)

What I'm trying to do is this:

```
private Result<string> GetMyString()
{
    ...
}

public Result<string> MyMethod()
{
   var strResult = GetMyString();
   if (!strResult.IsSuccess)
      return new Result<string>(strResult.GetException()); // <-- ???

   // other things that can return a string or an exception
}
```

Am I missing something?

And if the only correct way is to use just the `Match()` method, how should I do?
because this doesn't work

```
public Result<string> MyMethod()
{
   var strResult = GetMyString();
   return strResult.Match<Result<string>(
      x=> 
      {
          if(something)
              return x;
          else
              return new Result<string>(new Exception("error message"));
      },
      ex => new Result<string>(ex)
   );
}
```

**Comment by evermanwa** [comment]
What about doing something like this? I added a toggle so you can test the exception clause in this case. Perhaps this example with spark some inspiration.

```csharp
private static Result<string> GetMyString(bool throwError)
{
    try
    {
        if (throwError) { throw new Exception("We have an Exception!"); }
        var data = "Success!";
        return new Result<string>(data);
    }
    catch(Exception e)
    {
        return new Result<string>(e);
    }
}

public static Result<string> MyMethod()
{
    var throwException = false;
    return GetMyString(throwException).IfFail(f => f.Message);
}
```

**Comment by louthy** [comment]
I will be deprecating `Result<A>` in a future release, do not use `Result<A>`.  `Fin<A>` is the type you want for representing `Error | A`

**Comment by ildoc** [comment]
how does `Fin<A>` works? is there any documentation?

**Comment by louthy** [comment]
[Check the reference for 'alternative value monads'](https://louthy.github.io/language-ext/LanguageExt.Core/Monads/Alternative%20Value%20Monads/index.html) and the [a subsection on `Fin<A>`](https://louthy.github.io/language-ext/LanguageExt.Core/Monads/Alternative%20Value%20Monads/Fin/index.html)

**Comment by CumpsD** [comment]
What does the `Fin` stand for?

**Comment by louthy** [comment]
Short for `Final`, like `Result`

**Comment by ildoc** [comment]
`Final` is much more intelligible than `Fin`, though

**Comment by louthy** [comment]
You're free to create your own type called `Final`
