### ISSUE TITLE
FileIO trait is fundamentally broken for Test

### ISSUE THREAD

**Issue by phidevz** [louthy/language-ext#1129]
The FileIO trait has a bunch of functions, which return `FileStream` objects. Objects of this class can never be created, because the BCL class does not a parameterless constructor; all constructors either take a file path or a file handle, so the file must actually exist or there is some magical way to obtain a file handle to a memory location (pretty sure that is not possible, at least not without a custom device driver).

I know the idea might be, to be fully API-compatible with the BCL's `File.Open(...)` (or OpenRead/OpenWrite) calls, but this way, it is simply irritating. 

* Approach 1 would be, to drop API compatibility, and replace the return type with just `Stream` instead of `FileStream`.
* Approach 2 would be, at minimum, to mention in the Docs that this does not work at all. Best would be, to separate the current `FileIO` trait into two separate traits, and the one with functions returning `FileStream` is not implemented by the test runtime. That way, at least the developer knows **AT COMPILE TIME that their code won't work -- instead of porting a bunch of their code and tests to LanguageExt.Sys only to find out at runtime of the tests that their work is bascially useless**.

I am open for a discussion on how this could be resolved.

**Comment by louthy** [comment]
Fixed in: https://github.com/louthy/language-ext/releases/tag/v4.4.0

**Comment by phidevz** [comment]
@louthy thank you very much, I did not see that you have resolved this issue!
