### ISSUE TITLE
Option Documentation - Minor Issue

### ISSUE THREAD

**Issue by jerrywiltse** [louthy/language-ext#113]
This section starts out with: 

> Option<T> works in a very similar way to Nullable<T> except it works with all types rather than just value types. It's a struct and therefore can't be null. 

Unfortunately, there is no explanation of how Nullable<T> , which would be very helpful. Please add if you get a chance.

**Comment by andrevdm** [comment]
I like that the language-ext documentation is focused, I don't think that extending it to cover C# features would be useful. A link to e.g. https://msdn.microsoft.com/en-us/library/1t3y8s4s.aspx would be more than sufficient IMO.

**Comment by jerrywiltse** [comment]
Agreed.  I didn't even know that was a c# feature... thank you :)
