### ISSUE TITLE
How can i unwrap multiple monoids ?

### ISSUE THREAD

**Issue by sanzor** [louthy/language-ext#1133]
In my case i have multiple IO Operations which i want to pipeline. Each IO operation needs the previous one to be succesful. Also i need to be able to unwrap multiple monoids in a resulting method and wrap again like this:

In Haskell it would be something like this:

```
do 
   result1 <- IOaction1
   result2 <- IOaction2
   doSomethingWith result1 result2
```
In C# i have this:
```
EitherAsync<string,int> x = TryAsync<int>(new Exception()).ToEither(err=>"sgp");
EitherAsync<string,int> y = TryAsync<int>(new Exception()).ToEither(err => "str");
```

In the case above i need to perform y only if x was succesful and then if succesful , i need to unwrap both x and y and use them in a new method and wrap the result in something else like below:

```
x.Bind y.Bind 
-> (int xUnwrapped,int yUnwrapped) -> RightAsync<string,int>(xUnwrapped+yUnwrapped)
```

**Comment by louthy** [comment]
from result1 in IOAction1
    from result2 in IOAction2
    select doSomethjngWith(result1, result2)

LINQ _is_ the same as Haskell’s do notation
