### ISSUE TITLE
Broken (Value)Task.Cast<>

### ISSUE THREAD

**Issue by tomachristian** [louthy/language-ext#1135]
_Consider this as a draft, I will come back with a cleanup and more explanations_

**Context**
I observed something that I am failing to understand in:

https://github.com/louthy/language-ext/blob/c8e6ed06430964bfce5c046e0651d4316aef2932/LanguageExt.Core/Concurrency/ValueTask/ValueTask.Extensions.cs#L287

```
class PropCache<T>
{
    public static PropertyInfo Info = typeof(T).GetTypeInfo().DeclaredProperties.Where(p => p.Name == "Result").FirstOrDefault();
}

public static async ValueTask<A> Cast<A>(this ValueTask source)
{
    await source.ConfigureAwait(false);
    var prop = PropCache<A>.Info;
    return prop != null
        ? (A) prop.GetValue(source)
        : default(A);
}
```

**Problem statement**

The `ValueTask` type is a struct, so `ValueTask<T>` cannot inherit from `ValueTask` so that `ValueTask<T>` can be a valid `ValueTask`, also there is no implicit conversion from `ValueTask<T>` to `ValueTask`, we can see this in:

```
ValueTask<string> someStringValueTask = default;
ValueTaskExtensions.Cast<string>(someStringValueTask);
```
that yields
```
Argument type 'System.Threading.Tasks.ValueTask<string>' is not assignable to parameter type 'System.Threading.Tasks.ValueTask'
```

Also, from the implementation of `ValueTask` in https://github.com/dotnet/runtime/blob/main/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/ValueTask.cs we can see that the type does not have a `Result` property, so the use of reflection to access the non-existent property will not work, we can see this in:

```
var someStringValueTask = new ValueTask(Task.FromResult("hello there"));
var castValue = await someStringValueTask.Cast<string>();
```
which yields
```
castValue == null
```

so this extension method seems to effectively be broken (if the expected behavior is for it to extract the value and cast it to A, regardless that we are dealing with an untyped ValueTask) or in need of simplification (if the expected behavior is correct; just return `default`).

Some similar problems go for `TaskExtensions` as well.

_Bug in `Task<A> Task.Cast<A>(Task)`_
```
var someStringValueTask = Task.FromResult("hello there");
var castValue = await someStringValueTask.Cast<string>();
```
yields
```
castValue == null
```

because the use of `PropCache<T>` is working on the compile-time type `A` which is clearly a bug. The `Result` property should have been looked up on the runtime type of `source`, not on the compile-time type that we want to cast to.

**Solutions**
- Fix it
- Simplify it
- Constrain it

**Proposal**

Fix the `Task` extension as:

```
public static async Task<A> Cast<A>(this Task source)
{
    ArgumentNullException.ThrowIfNull(source);

    await source.ConfigureAwait(false);

    return source.GetType() switch
    {
        { IsGenericType: true } => (A)((dynamic)source).Result,
        _ => default!
    };
}
```

and then fix the `ValueTask` extension as:

```
public static ValueTask<A> Cast<A>(this ValueTask source) => new(source.AsTask().Cast<A>());
```

**Comment by louthy** [comment]
Fixed in: https://github.com/louthy/language-ext/releases/tag/v4.4.0
