### ISSUE TITLE
Iterate over a traversable while binding and accumulating the result

### ISSUE THREAD

**Issue by sanzor** [louthy/language-ext#1138]
If i have an `IEnumerable<EitherAsync<Error,Unit>>` how can i bind in succession all items ?

I want to iterate over this travrsable and perform a `||` with all computations that result in a  `Unit`

Example:
```
[Error,Unit,Unit,Unit] => Unit
[Error,Error,Error,Error] => Error
[Error,Error,Unit,Error] => Unit
```
I have checked out `Seq`  but i do not fully understand it.

I need something undethe hood like:

`(Unit,item1) >>=  if item1 is Unit then (Unit,item2)>>=  if item2 is Unit then (Unit,Item3) ......`

I basically want to do a `fold` over the results of an `[IO (either Error Unit)]` , starting with an Error , iterate over all members and perform an `||`  whenever i am encountering an Unit.

**Comment by louthy** [comment]
You can use `Fold`:

```c#
IEnumerable<EitherAsync<Error,Unit>> xs = ...

var rs = xs.Fold(RightAsync<Error, Unit>(unit), (ms, mx) => ms | mx);
```

> I have checked out `Seq` but i do not fully understand it.

`Seq` is just like `IEnumerable<T>` (a lazy sequence), but it has at-most-once evaluation (it memoises).  It has also been optimised for consing and appending.  It's a very fast immutable-list data-structure.
