### ISSUE TITLE
Feature Request: Immutable Array

### ISSUE THREAD

**Issue by jcoder58** [louthy/language-ext#114]
Similar to System.Collections.Immutable.ImmutableArray

**Comment by louthy** [comment]
@jcoder58 I will take a look at this soon, but I need to focus on version 2 of lang-ext over the next week or so.  

Do you have an immediate need?  Much of the behaviour of `Lst<T>` matches what an immutable array will do.  The main difference will be the underlying implementation, an immutable-array type will be faster for reads than `Lst<T>`, but much slower for mutation (with `SetItem`, `Filter`, `Map`, `Insert`, etc.).

**Comment by wallymathieu** [comment]
There is a way to work with immutable collections. You can add extensions with "NotImplemented" as implementation and create a copy update expression. I've done it in the library [With](https://www.nuget.org/packages/With) :

[Manipulation_of_enumerable.cs#L76](https://github.com/wallymathieu/with/blob/master/src/Tests/With/Manipulation_of_enumerable.cs#L76)

            const string newValue = "const";
            var ret = myClass.With(m => m.Preferences.Add(newValue));
            Assert.Equal(newValue, ret.Preferences.Last());

Here the property Preferences does not have an Add method (it's an extension method only for the use in expressions).

**Comment by louthy** [comment]
@wallymathieu Hi Oskar, I'm not quite sure why that is relevant?  This library already has many immutable collections, the issue raised by @jcoder58 is merely requesting an immutable-array type to supplement the `Lst<T>`, `Map<K,V>`, `Set<T>`, `Que<T>`, `Stck<T>`, `HMap<K, V>`, and `HSet<T>` types.

Something I will be implementing in the next few months once v2 is complete.

**Comment by wallymathieu** [comment]
I merely wanted to sneak in a suggestion on how to extend the syntax when working with immutable types. So, yes, it's unrelated.

**Comment by louthy** [comment]
@jcoder58 This will land in version 2 very soon.
