### ISSUE TITLE
Fin<T>.GetHashCode Throws an Exception when Fin.Succ is False

### ISSUE THREAD

**Issue by pargall** [louthy/language-ext#1143]
While using Fin<T> in version 4.3.2-beta, we found that the `Fin<T>.GetHashCode()` will throw a `ValueIsNoneException` exception if the Fin is not Successful. 

Here is a trivial example where we'd expect to get back a `int` , but instead the `ValueIsNoneException` exception is thrown.
```csharp
Fin<int> e = Error.New("Some Error");
int hash = e.GetHashCode();
```

I think this is due to this check being inverted:

https://github.com/louthy/language-ext/blob/c8e6ed06430964bfce5c046e0651d4316aef2932/LanguageExt.Core/Monads/Alternative%20Value%20Monads/Fin/Fin.cs#L99-L102

**Comment by louthy** [comment]
Fixed in: https://github.com/louthy/language-ext/releases/tag/v4.4.0
