### ISSUE TITLE
Tuple Functions and Extension Methods for Fst & Snd

### ISSUE THREAD

**Issue by aage** [louthy/language-ext#1156]
When using tuples I often find the need to add these methods, like within `F#` (`fst`, `snd`). Would it be a good idea to add something like this within `language-ext`?
Does this already exist (I couldn't find it)? Or would these already be redundant because of other types/functions that I'm not aware of?

```c#
var data = (1, "Foo");
var num = data.Fst(); // or fst(data);
var str = data.Snd(); // or snd(data);
```

Would absolutely be willing to add a PR, if you point me towards the right files/folders where this should live.

**Comment by evermanwa** [comment]
You can also use named Tuple parameters in your first statement if you wanted. Unless you don't like this approach for some reason, but I'll throw this out there.

```csharp
(int num, string str) data = (1, "Foo");
var num = data.num;
var str = data.str;
```

**Comment by aage** [comment]
Thank you @evermanwa , those indeed are nice too, but I was looking for something more generic that I can use when a function argument (for instance) is `(Name, EmailAddress)` (an example a bit contrived).
I like using constrained types like these and than combining them in tuples when needed.

**Comment by louthy** [comment]
Because `tuple.Item1` and `tuple.Item2` exist it seems unnecessary to have `tuple.Fst()` and `tuple.Snd()`.  There are [`fst` and `snd` lenses](https://github.com/louthy/language-ext/blob/7d311f1e6596efb41a539e47381ae2a4a7af8712/LanguageExt.Core/Lens/Lens.cs#L40) if you want first class functions that do the getting and setting.

**Comment by aage** [comment]
I'll try to use those lenses then, thank you!

Feel free to close this issue.
