### ISSUE TITLE
Should AtomSeq<T>.Empty return an empty AtomSeq?

### ISSUE THREAD

**Issue by guythetechie** [louthy/language-ext#1158]
Calling [``AtomSeq<string>.Empty``](https://github.com/louthy/language-ext/blob/d2416b5d6e049f0d0b6a6c5b54b452470e4cdcaa/LanguageExt.Core/Concurrency/AtomSeq/AtomSeq.cs#L35) returns an empty ``Seq<string>``, not an empty ``AtomSeq<string>``. Is this intentional?

If I want an empty ``AtomSeq``, the easiest way I see is to use ``Prelude.AtomSeq<A>()``. Not a big deal, but I like the explicitness of having ``Empty`` in the method name.

This differs from, say [``AtomHashMap<string, string>.Empty``](https://github.com/louthy/language-ext/blob/d2416b5d6e049f0d0b6a6c5b54b452470e4cdcaa/LanguageExt.Core/Concurrency/AtomHashMap/AtomHashMap.cs#L35), which actually returns an empty ``AtomHashMap``.

**Comment by louthy** [comment]
Gah, that looks like a copy n paste error from when I started the implementation of `AtomSeq` from `Seq`.

To create an empty `AtomSeq`, just do this:
```c#
using static LanguageExt.Prelude;

var xs = AtomSeq<string>();
```
All types have _constructor functions_ in the `Prelude`.
