### ISSUE TITLE
Prelude.OptionalAsync Throws ValueIsNoneException For Null

### ISSUE THREAD

**Issue by pjwilliams2** [louthy/language-ext#1159]
#799 seems to have cropped back up. Also, awaiting the `OptionalAsync` results in an unwrapped value instead of an `Option`. 

LanguageExt version 4.4.0
Dotnet 7.0.0

Sample:

![image](https://user-images.githubusercontent.com/8356520/208568159-7d1c3050-cd08-4009-97bb-366c5192be1d.png)

**Comment by johnetc** [comment]
Yep, similarly it means Task.Delay no longer functions without throwing an exception

**Comment by louthy** [comment]
This works in the [latest release](https://github.com/louthy/language-ext/releases/tag/v4.4.2), but you need to `await` the `Value` property for the above behaviour.
