### ISSUE TITLE
Using Task.Delay with OptionAsync

### ISSUE THREAD

**Issue by johnetc** [louthy/language-ext#1184]
> Hello. I'm having real trouble using Task.Delay with OptionAsync. I always get 

```c#
LanguageExt.ValueIsNoneException: Value is none.  at LanguageExt.OptionAsyncAwaiter`1[A].GetResult ()
```
When I call it with the below code. I've checked through the issues here and I've found a few ([example](https://github.com/louthy/language-ext/issues/1008)) but none of them seem to fix the issue. I can't figure out if it's me or a bug. Thanks for any help anyone can provide

```c#
private async Task<Option<Unit>> ExecuteLoadSteps() {
			for (int i = 0; i < 3; i++) {
				Fin<Unit> result = await AffDelay(200).Run();
			}
			return Unit.Default;

		}


private Aff<Unit> AffDelay(int delay) => Aff<Unit>.EffectMaybe(async ()=> await Task.Delay(200).ToUnit());
```

**Comment by evermanwa** [comment]
Good afternoon, instead of just returning "Unit.Default" try returning."Some(Unit.Default)" instead.

**Comment by johnetc** [comment]
Thanks Evermanwa, but debug shows it's happening during the GetResult from the awaiter, so I'm thinking it might be related to the initial wrapping of the task.

**Comment by louthy** [comment]
This is resolved in the [latest release](https://github.com/louthy/language-ext/releases/tag/v4.4.2).  Note there are breaking changes that mean the `async` awaiter isn't supported anymore.  This was planned for a `v5` release, but I've become increasingly unhappy with the awaiter machinery so I've deprecated it early.  You can still `await` using the `Value` property, which returns a `Task<A?>` or call `ToOption<A>()` to get a `Task<Option<A>>`, or finally use the `Match*` methods.
