### ISSUE TITLE
How to construct `Either<L, R>` without implicit conversions?

### ISSUE THREAD

**Issue by dcastro** [louthy/language-ext#121]
I'm having an issue where I'm being forced not to use implicit conversions:

```csharp
public interface X { }
public class Y : X { }

Either<string, X> a = new Y();          // compiles
Either<string, X> b = new Y() as X;  // Cannot convert initializer type 'X' to target type 'Either<string, X>'
```

This looks like a compiler bug in IMO, but I'm hesitant to rush to such a harsh conclusion.

In any case, because I have an instance of an interface, and not of the concrete class, I have to construct an `Either` using some other means.

Maybe I'm missing something, but the constructors are private, and the two static helpers [`Right`](https://github.com/louthy/language-ext/blob/master/LanguageExt.Core/Either.cs#L627) and [`Left`](https://github.com/louthy/language-ext/blob/master/LanguageExt.Core/Either.cs#L631) are internal.

**Comment by louthy** [comment]
I'm unclear on why you aren't using the one that compiles?

The static functions you're after for explicitly defining left and right
are:  Prelude.Left<string, X>(...) and Prelude.Right<string, X>(...)

**Comment by dcastro** [comment]
Thank you, I hadn't noticed the Prelude.

I'm not using the one that compiles because, in my actual code, I'm being passed an instance of the interface (`X`) and not an instance of the concrete type (`Y`).

**Comment by dcastro** [comment]
Another use case where this happened to me was this:

```csharp
Either<Exception, IEnumerable<T>> F()
{
    return Enumerable.Empty<T>();
}
```

The workaround was to `return new List<T>()` instead, which performs needless allocations.

**Comment by louthy** [comment]
@dcastro It's because implicit operators don't work with interfaces, it's a limitation of C#.  In your IEnumerable example instead use the lang-ext built-in `List<T>()`

```c#
        Either<Exception, IEnumerable<T>> F<T>()
        {
            return List<T>();
        }
```
Make sure you're `using static LanguageExt.Prelude`.  If not, then you can directly use the `Empty` field on the `Lst<T>` type:
```c#
        Either<Exception, IEnumerable<T>> F<T>()
        {
            return Lst<T>.Empty;
        }
```
If you want to do similar behaviour yourself, try this:
```c#
        static class Empty<T>
        {
            public static readonly T[] Enumerable = new T[0];
        }

        Either<Exception, IEnumerable<T>> F<T>()
        {
            return Empty<T>.Enumerable;
        }
```
That will avoid the allocation and will implicitly cast.

**Comment by dcastro** [comment]
Perfect!

Thank you for the explanation, I wasn't aware of this limitation.
