### ISSUE TITLE
Visual Studio 2022 doesn't warn when `TryAsync` is not awaited

### ISSUE THREAD

**Issue by nilvon9wo** [louthy/language-ext#1219]
Not sure if this really should be considered an issue for this extension or whether there is anything which can be done about it within the scope of this repo, but I just thought I'd mention I have some methods which return `TryAsync<Something>`.

When I don't wait these, I get errors.

Normally, I expect Visual Studio to remind me that I should be awaiting something.... but then normally, It would be waiting for `Task<Something>`, so whatever rules it has to work can't be expected to know about `TryAsync`.

As I've seen there are ways to extend these rules (e.g. Roslyn), I guess that can be fixed, but I don't know enough about this to know whether it can be fixed within the scope of this project or whether someone would need to (or perhaps even already has) create(d) such rules that live elsewhere....

**Comment by louthy** [comment]
Closing due to this: https://github.com/louthy/language-ext/discussions/1269
