### ISSUE TITLE
What the heck is "Sidedness"?

### ISSUE THREAD

**Issue by dbmercer** [louthy/language-ext#122]
I'm trying to figure out Parsec. Couldn't find the documentation, so I'm reading the source code. But I can't figure out what `Sidedness` is or is used for.

**Comment by louthy** [comment]
@dbmercer Hi David, it's a property that's useful for implementing white-space significant languages.  See 'The Offside Rule' in this paper: http://www.cs.nott.ac.uk/~pszgmh/monparsing.pdf 

It's not actually used for any parser yet, and in-fact the `indented

**Comment by louthy** [comment]
@dbmercer 

If you're looking for some real-world examples of using the Parsec library, you can take a look at the `LanguageExt.Process` system configuration file parser:

Source: [ProcessSystemConfigParser.cs](https://github.com/louthy/language-ext/blob/master/LanguageExt.Process/Config/ProcessSystemConfigParser.cs)

Example file that it parses: [process.conf](https://github.com/louthy/language-ext/blob/master/Samples/Strategies/process.conf)

It's actually a statically-type mini-language with full support for expressions, operators, etc.

I'm not sure if you've seen the API documentation yet: [louthy.github.io](https://louthy.github.io)  It was generated by another project I wrote especially for it: [best-form](https://github.com/louthy/best-form), and it uses the Parsec library to parse the raw C# source of lang-ext.  This is the parser: [Lang.cs](https://github.com/louthy/best-form/blob/master/bestform.cs/Lang.cs)
