### ISSUE TITLE
Is it worth adding a ToHashMap that takes Key and Value mappers

### ISSUE THREAD

**Issue by guythetechie** [louthy/language-ext#1220]
Prior to discovering this library, I often used [``IEnumerable.ToImmutableDictionary``](https://learn.microsoft.com/en-us/dotnet/api/system.collections.immutable.immutabledictionary.toimmutabledictionary?view=net-8.0#system-collections-immutable-immutabledictionary-toimmutabledictionary-3(system-collections-generic-ienumerable((-0))-system-func((-0-1))-system-func((-0-2)))) to create dictionaries from enumerables. To have similar functionality in language-ext, I often find myself defining extensions like this:

```csharp
public static HashMap<TKey, TValue> ToHashMap<T, TKey, TValue>(this IEnumerable<T> enumerable,
                                                               Func<T, TKey> keyMapper,
                                                               Func<T, TValue> valueMapper) =>
    enumerable.Map(t => (keyMapper(t), valueMapper(t)))
              .ToHashMap();
```

Simple enough to do. That said, is it worth adding this functionality to the library? Happy to create a PR for HashMap and its ilk.

**Comment by louthy** [comment]
[`ToHashMap` already exists](https://github.com/louthy/language-ext/blob/c4d9796b9b71805b9d83fdcc6f30d284964feceb/LanguageExt.Core/Immutable%20Collections/HashMap/HashMap.Extensions.cs#L17), but it takes a `IEnumerable<(K, V)>`.  What that means is you merely have to _map_ to a pair to get the same behaviour.  This maintains a separation of concerns: 1. the mapping, and 2. the conversion of the type.

(Obviously your implementation highlights that, I'm just explaining for those reading along).  

What's better...

This?
```csharp
    people.Map(p => (p.Id, p.Name)).ToHashMap();
```
Or, this?
```csharp
    people.ToHashMap(p => p.Id, p => p.Name)
```

Some of this will be pure personal preference, but I would posit that the first is more declarative.  The second one may judge edge it on convenience, but isn't so declarative.

**Comment by guythetechie** [comment]
Thanks for the perspective. To be clear, I wasn't suggesting replacing the current method signature; just adding a new extension.

That said, it's trivial to implement for those who need it (which might be a minority). And I can certainly appreciate keeping method signatures simple, especially if additional overloads would only serve a small subset of users.

Thanks again for the library. It's one of my favorite in .NET land.
