### ISSUE TITLE
README file

### ISSUE THREAD

**Issue by ArtGangsta** [louthy/language-ext#1224]
I would do this if I knew enough, but I just want to say that the README file doesn't really read very well right now.  There's a lot of historical information there, referring to things that have now become standard in .NET for a long time, as if they are new.

I think it's okay if language-ext had some of these important features earlier, and perhaps better, and no issue with keeping those alternative options.  But the current README file does not read well for someone who is starting with the "current version of .NET" and wants to do better functional languages than what is available out of the box.

Perhaps it's not so much that the README needs to be updated but maybe there ougth to be an entirely separate document that targets this audience.   I feel that this audience is actually the majority of the new people who will look at this library.   They get taste of LINQ with the features that are in C# by default, but want something more, something better, *something more correct*, so they'll inadvertantly end up here.  We should guide such developers better than we do now.

**Comment by louthy** [comment]
The readme is more of an introduction now and I have started my blog (linked from the readme), which I'm using to present more guides and tutorials.
