### ISSUE TITLE
Proposal: Make .Left/.Right public for Either<>

### ISSUE THREAD

**Issue by christosk92** [louthy/language-ext#1238]
There are some cases I do want the left/values explicitly, but right now to get the Left/Right values of an Either<>, I have to do the following:

```cs
 var left = eitherVal.Match(
                Left: x => x,
                Right: _ => throw new Exception("Unexpected right") 
            );
```
or 
```cs
 var right= eitherVal.Match(
                Left: _ => throw new Exception("Unexpected left")
                Right:  x => x
            );
```
Is there any better way of doing this?

I know this goes against FP patterns, where instead we should instead use monads/mappings, but I've encountered a lot of scenarios where this might be useful.

Thoughts?

**Comment by louthy** [comment]
You can use an explicit cast if you really want to do this.
```c#
    if(eitherVal.IsRight)
    {
        var right = (R)eitherVal;
    }

    if(either.IsLeft)
    {
        var left = (L)eitherVal;
    }
```

**Comment by christosk92** [comment]
Wow ! I did not know that existed!! Thank you
