### ISSUE TITLE
BindLeftAsync and MapLeftAsync

### ISSUE THREAD

**Issue by no1melman** [louthy/language-ext#1242]
Hi,

Firstly, great library, been a pleasure to use and really appreciate the hard work and effort that's gone into this.

I was wondering if there has been any ideas around adding `BindLeftAsync` and `MapLeftAsync` as the async counterparts to their pre-existing sync methods.

The use case is when you've hit an error, there could be a chance to correct it, that chance could be in the form of an async call. I'm still not sure on the mechanisms needed to get back to succinct Either after correction though.

Any thoughts would be hugely appreciated!

**Comment by louthy** [comment]
If there's gaps then yep, would accept a PR.  Note that it's important that EitherUnsafe and Fin have the same extensions.

If you're working in an async context, it's usually better to switch to EitherAsync.  Any sync Eithers can be converted using ToAsync.

In terms of getting back to Either from an async context, you can't without Matching the Either away; even then you'll still be in an async context.  Async spreads throughout your app unless you force a blocking wait or launch a fire-and -forget task.

**Comment by louthy** [comment]
https://github.com/louthy/language-ext/discussions/1269
