### ISSUE TITLE
broken codegen

### ISSUE THREAD

**Issue by kasozivincent** [louthy/language-ext#1244]
Hi,
Is there any easy way to generate Unions that is not painful? I am using .Net 7 but nothing seems to work. If there are any easier methods, I will be glad to know of them. Thank you

**Comment by louthy** [comment]
I just tried it on a fresh project and it works ok.  There's a few things you need to make sure you have correct though:

1. Make sure your `csproj` looks like this (i.e. you have the correct versions of the `CodeGeneration` project and the cli-tool reference.

```c#
<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net7.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="LanguageExt.CodeGen" Version="4.4.3" />

      <PackageReference Include="CodeGeneration.Roslyn.BuildTime" Version="0.6.1" PrivateAssets="all" />

      <DotNetCliToolReference Include="dotnet-codegen" Version="0.6.1" />

      <PackageReference Include="LanguageExt.Core" Version="4.4.3" />
    </ItemGroup>

</Project>
```

2. Make sure you have the 2.0 and 2.1 dotnet SDK's installed.  I don't remember which one it is that the codegen tool relies on, but it's one of these (see my list of installed SDK's below).

![image](https://github.com/louthy/language-ext/assets/1991827/8dd50531-9762-44c8-a9c4-612f74253fa7)

I am developing a new codegen library that works with Source Generators, but that's a little way off.  Until then you just need to make sure your dotnet setup is right and all should work OK.

**Comment by kasozivincent** [comment]
Hi @louthy I really appreciate your timely response. I have installed the 2.0 sdks but it seems the problem still persists. Below is the error that I am getting even after copying and pasting your .csproj file

![image](https://github.com/louthy/language-ext/assets/56205969/f17fa21d-1263-4694-bf34-a3a157c9cf52)

**Comment by kasozivincent** [comment]
Oh it worked! It turns out the exact dependency is 2.1.818. Anything else will not work. Thank you so much @louthy. It is time to become functional!!!!!!!!
