### ISSUE TITLE
TryOptionAsync incorrect nullablity

### ISSUE THREAD

**Issue by WhatzGames** [louthy/language-ext#1245]
In the Prelude TryOptionAsync is currently defined as:
```cs
 public static TryOptionAsync<A>(Task<A> v);
 public static TryOptionAsync<A>(Func<Task<A>> f);
```

But it should actually be

```cs
 public static TryOptionAsync<A> TryOptionAsync<A>(Task<A?> v);
 public static TryOptionAsync<A> TryOptionAsync<A>(Func<Task<A?>> f);
```

As the result of a Task is captured inside an Option, the result can not be null anymore.
If the input currently was Task<string?> then the result would be TryOptionAsync<string?> which would result in an OptionalResult<string?>.

**Comment by louthy** [comment]
Yep, that's a part of the library that's not been converted over to use `nullable` markup yet.  I'll get to that eventually.  

In the meantime there's also:
```c#
TryOptionAsync<A>(Option<A> v)
TryOptionAsync<A>(Task<Option<A>> v)
```
Which allows you to construct `TryOptionAsync` from `Option`, so convert your `string?` to an `Option` first using `Prelude.Optional`.

I'd also recommend, (depending on how deep your usage of the `Try*` monads are), to instead use `Eff<A>` and `Aff<A>` - they're much more featureful than `Try*` and are the primary focus of future development; the `Try*` types should be seen as legacy now (although I will keep supporting them, and will update them to nullable, they aren't going to be the future focus).

**Comment by WhatzGames** [comment]
Alright, thanks for the tip.

So I'd assume that (considering the nullability is fixed) I'd have to change

```
TryOptionAsync(SomethingAsync())
```

To

```
Aff(async () => Prelude.Optional(await SomethingAsync())
```

**Comment by louthy** [comment]
Closing due to this: https://github.com/louthy/language-ext/discussions/1269
