### ISSUE TITLE
Applicative validation

### ISSUE THREAD

**Issue by olegdunkan** [louthy/language-ext#1259]
Is there a way to partially apply validation?

Let say first I validated one condition after that I need validate a second condition but for several values

```
Vallidation<Error, int> CheckRoot(int i) => ...
Vallidation<Error, int> CheckChild(int i) => ...

Validation<Error, Func<int, int> GetPartialApplicator(int i)
       => Success<Error, Func<int, int, int>>((x, y) => x + y).Apply(CheckRoot(i)); // but this doesn't work
var root = ...;
var pa = GetPartialApplicator(root);
for (var i = 0; i < CountOfChilds; i++)
{
  pa.Apply(CheckChild(i)).Match(...);
}
```
Yes, I understand that I mix iperative style with functional (more declaretive) but it is the easy way to demonstrate my intention

**Comment by louthy** [comment]
I have added the same `Apply` and `ApplyM` functions to `Validation` as are available in the other monadic types (`v4.4.7`)

For example:

```c#
    static int OnComplete(int x, int y) => x + y;
    static Validation<Error, int> CheckRoot(int i) => ...;
    static Validation<Error, int> CheckChild(int i) => ...;

    var res = Success<Error, Func<int, int, int>>(OnComplete)
        .Apply(CheckRoot(123))
        .Apply(CheckChild(456));
```
This lifts `OnComplete` into the `Validation` monad and then affects the apply operators.  If you only apply one value then you get partial application:
```c#
    var mf = Success<Error, Func<int, int, int>>(OnComplete)
        .Apply(CheckRoot(123));

    // mf is Validation<Error, Func<int, int>>

    var res = mf.Apply(CheckChild(456));
```
