### ISSUE TITLE
Parsec.LanguageDef: Add option to retain comments/whitespace 

### ISSUE THREAD

**Issue by jcoder58** [louthy/language-ext#127]
It appears from reading the code that comments/whitespace are discarded by the language parser.  I need an option where they can be retained and tested for.  I'm writing a code generator and would like for documentation comments from the input to be added to the output.

**Comment by louthy** [comment]
@jcoder58 I want to maintain parity between the LanguageExt.Parsec and the Haskell Parsec libraries, so the easiest way for you to achieve this is to [take the source of `makeTokenParser`](https://github.com/louthy/language-ext/blob/master/LanguageExt.Parsec/Parsers/Token.cs#L44) and build your own variant.

The key code is: 
```c#
    var whiteSpace =
        def.CommentLine == null && def.CommentStart == null ? skipMany(simpleSpace.label(""))
      : def.CommentStart == null ? skipMany(either(simpleSpace, multiLineComment).label(""))
      : def.CommentLine == null ? skipMany(either(simpleSpace, oneLineComment).label(""))
      : skipMany(choice(simpleSpace, oneLineComment, multiLineComment).label(""));
```
If you want to support both one-line comments and multi-line comments then the last line of that is what you need to look at:
```c#
    skipMany(choice(simpleSpace, oneLineComment, multiLineComment))
```
You'll want to build a parser that returns an `IEnumerable<string>` for your comments (or `IEnumerable<Comment>` if you're doing deeper parsing of comments).

You may want to take a look at my [best-form project](https://github.com/louthy/best-form) that has a [C# parser](https://github.com/louthy/best-form/blob/master/bestform.cs/Lang.cs) with [C# XML comments sub-parser](https://github.com/louthy/best-form/blob/master/bestform.cs/Doc.cs).  It's probably not general enough for what you're looking for, but the sub-parser might be useful to you.

**Comment by louthy** [comment]
@jcoder58 And just to be clear, it's not as simple as you think.  Because white-space and comments could appear in many places.   The way the `makeTokenParser` parser works is to always clear trailing white-space (and comments) by default to simplify the process of tokenisation.  If you wanted to maintain similar behaviour then every parser would need to return `T` and an `IEnumerable<Comment>`; obviously that's possible, but it's a different resulting set of parsers for nearly all parsers in `GenTokenParser`.

**Comment by jcoder58** [comment]
@louthy  the best-form C# parser looks like a good starting point for me.  I need to parse C++ headers that use doxygen comments, so there is quite a bit overlap with the C# syntax.  The biggest change will be adding the C++ preprocessor directives and c++ method inline declarations.

**Comment by louthy** [comment]
@jcoder58 One thing to note with my solution (which was purely made to parse the lang-ext source to build the [API reference docs](https://louthy.github.io/languageext.core/LanguageExt/index.htm)) is that I kind of cheat and set the line-comment string to ```// ``` (with a space after the last slash).  This causes it to miss the `///` XML doc comments.  I then manually inject the `documentation` parser at the top of each block that's likely to have them:

* Delegate: https://github.com/louthy/best-form/blob/master/bestform.cs/Lang.cs#L281
* Enum member: https://github.com/louthy/best-form/blob/master/bestform.cs/Lang.cs#L292
* Enum: https://github.com/louthy/best-form/blob/master/bestform.cs/Lang.cs#L303
* Method: https://github.com/louthy/best-form/blob/master/bestform.cs/Lang.cs#L492
* Conversion operators: https://github.com/louthy/best-form/blob/master/bestform.cs/Lang.cs#L515
* Class/interface/structs: https://github.com/louthy/best-form/blob/master/bestform.cs/Lang.cs#L573
* etc.

So it's definitely not as robust as a generalised system that can find doc comments anywhere (as mentioned before).  But if you're working with a known code-base, and you know the docs you want are in well defined places in the source, then it can work.
