### ISSUE TITLE
Conflict between LangugeExt Extension methods and LINQ Extension methods

### ISSUE THREAD

**Issue by attejan** [louthy/language-ext#1282]
### Description
Extension methods are not in any namespace thus causing problems in a large project. Instead of Linq - extension methods, the whole project is forced to use extension methods from LanguageExt. 

### Steps for minimal reproduce

https://github.com/attejan/LanguageExtListExtensionRepro

1. Create a new project 
2. Use Zip and Append in a way that is supported in LINQ. 
```c#
// See https://aka.ms/new-console-template for more information

var foo = new List<Foo>();
var bar = new List<Foo>().Zip(foo).All(c => c.First == c.Second);
var barz = foo.Append(new() { Barz = new Bar[] { } });

internal record Foo
{
    public Bar[] Barz { get; set; }
}

internal record Bar { }
```
![Näyttökuva 2023-11-24 140602](https://github.com/louthy/language-ext/assets/151913781/18bff0b8-d5db-4011-ad44-4f4cdd039505)

3. Install LangugeExtCore
4. Now Zip and Append signatures are different since the whole project is being forced to use LanguageExt - extension methods.
![Näyttökuva 2023-11-24 140620](https://github.com/louthy/language-ext/assets/151913781/10e839e2-579d-4eda-bdc8-940ad3f8212e)

### Expected behavior
 
The extension methods provided by the library should not conflict with the ones provided by LINQ. It should be possible to use both sets of extension methods without any ambiguity.

### Actual behavior

List extension methods from LangugeExt are used and they break.
![Näyttökuva 2023-11-24 135753](https://github.com/louthy/language-ext/assets/151913781/6b433325-e2a8-4be6-86c5-7d06e41948aa)

### Possible fix

Iclude all extension methods in a namespace. 
Theres probably a reason why it was done like this in the first place, but I would be happy to hear some possible solutions to this problem.

### Similar issues
https://github.com/louthy/language-ext/issues/836
https://github.com/louthy/language-ext/issues/445

Please let me know if you require any further information or if there's any way I can assist in resolving this issue.
Thanks for this library!

**Comment by louthy** [comment]
Not sure how that once slipped through, but seeing as there are workarounds I will leave this until after I have completed my [v5 work](https://github.com/louthy/language-ext/discussions/1269), which is more important to me right now and I only have limited time (which also includes not dealing with PRs).  

## Workaround `#1`:

Stop using `List`.  Mutable lists are not the functional way.  Opt for `Seq`, the most performant _immutable_ list type going.

```c#
using static LanguageExt.Prelude;

var foo = Seq<Foo>();
var bar = Seq<Foo>().Zip(foo).ForAll(c => c.Item1 == c.Item2);
var barz = foo.Add(new() { Barz = new Bar[] { } });

internal record Foo
{
    public Bar[] Barz { get; set; }
}

internal record Bar { }
```

## Workaround `#2`: 

Use the actual tuple variable member-names and explicitly specify the type.

```c#
var foo = new List<Foo>();
var bar = new List<Foo>().Zip(foo).All(c => c.Item1 == c.Item2);
var barz = foo.Append(new Foo() { Barz = new Bar[] { } });

internal record Foo
{
    public Bar[] Barz { get; set; }
}

internal record Bar { }
```

**Comment by louthy** [comment]
Fixed in `v5`.
