### ISSUE TITLE
Implicit conversion of int? to Option<int>

### ISSUE THREAD

**Issue by matthew-santiago** [louthy/language-ext#1302]
For some reason I am able to do an implicit conversion of `List<int>?` to `Option<List<int>>` but am unable to do `int?` to `Option<int>`?

**Comment by louthy** [comment]
Implicit conversions work for all types, however `int?` isn't an `int`; `int?` is `Nullable<int>`, so if you use `Option<Nullable<int>>` then implicit conversion will work.  

If however, as I suspect, you want the `null` to become `None`, then you can call:

```c#
int? x = null;
Option<int> mx = Optional(x);
```
That will do the conversion for you.

`Optional` is in the `LanguageExt.Prelude`

**Comment by matthew-santiago** [comment]
I'll close this out since this was the solution I'm looking for.
