### ISSUE TITLE
SequenceParallel performance degradation in 4.4.8

### ISSUE THREAD

**Issue by qklanski** [louthy/language-ext#1305]
After migrating to version 4.4.8, we noticed significant slowdown of our application. 

We noticed, that Contention time and Contention count increased. Thus, after digging, we discovered, that SequenceParallel for IEnumerable<EitherAsync<L,R>> does not behave as expected. Requests are processed sequentially. 

We noticed, that it is related with https://github.com/louthy/language-ext/commit/2006f06a1bc8e9495bb298065650f7acde7ecff3

Code worked as expected in version 4.4.7

**Comment by louthy** [comment]
`EitherAsync` doesn't exist in `v5.0.0`, so I will close this.  The `v4.4.8` version was updated to enforce ordering of results only (so the results are guaranteed in the same order as the input values), so if you don't need that I was just suggest reverting to `v4.4.7`.
