### ISSUE TITLE
Constructor not found for LanguageExt.LongRange

### ISSUE THREAD

**Issue by pilotMike** [louthy/language-ext#1314]
Executing `LongRange.FromMinMax(50, 99, 1)` throws an exception with "The type initializer for LanguageExt.Range`3 threw an exception" with the inner exception being that the constructor wasn't found for LongRange.

IntegerRange works fine.

creating one's own type, ie `class MyLongRange(int start, int end, int step) :  Range<MyLongRange, TLong, long>(from, to, step)` works fine.

**Comment by louthy** [comment]
I'm assuming this is pre-v5, as v5 range has been refactored into a single Range type -- my advice would be to create your own Range type for the element-type that fails or you could grab the latest code from the v5-transducers branch and copy it into your own project until you're ready to upgrade to v5.
