### ISSUE TITLE
Use of subtype of Expected throws InsufficientExecutionStackException due to self referencing Head

### ISSUE THREAD

**Issue by HernanFAR** [louthy/language-ext#1341]
When using a subtype of "expected" in a string.Format throws InsufficientExecutionStackException, and for what I see, is for the self referencing property Head.

![image](https://github.com/user-attachments/assets/608b7a07-23ab-41d4-bae3-4a12d85ee1fa)

This is solvable by just overriding the "ToString" method, to not call "PrintMembers", method created by using records, but i was wondering if this was by design or is a bug.

![image](https://github.com/user-attachments/assets/64e9b647-ea04-44e4-ba7a-5bf599566f65)

The source code is here https://github.com/HernanFAR/language-ext-bug (The same repository that before)

Thanks for all Mr. Louthy! :)

**Comment by louthy** [comment]
I thought I'd dealt with this, but forgot subtypes! Anyway, I have overridden PrintMembers to avoid the infinite loop in the default records implementation.

Available now in v5.0.0-beta-03.

Note: this is also an issue in v4 and should be resolved by providing your own ToString implementation for any Error subtypes.
