### ISSUE TITLE
Async Map?

### ISSUE THREAD

**Issue by marss72** [louthy/language-ext#1354]
Hey, today I ran into an issue. I'm using the following method signature:

```cs
static async Task<Option<OutputType>> ProcessAsync(ulong value)
```

But, it needs to be an async Task. I have the following code in the same class, and I need to map IEnumerable through the ProcessAsync. The async is a problem, as I need to select Somes only. Any ideas?

```cs
foreach (var item in items.Map(async x => await ProcessAsync(x)).Somes())
{
    yield return item;
}
```
This code is invalid. How do I make it valid without changing the behavior? Thanks.

**EDIT**: Just discovered `OptionAsync<T>` but that does not solve my problem, or am I doing something wrong?

**Comment by louthy** [comment]
```c#
static Task<IEnumerable<OutputType>> Foo(IEnumerable<ulong> items) =>
    items.Map(x => ProcessAsync(x).ToAsync())
         .Somes();
```

**Comment by marss72** [comment]
It works as expected, thanks a lot!
