### ISSUE TITLE
Question: Combine two Option<uri> to one 

### ISSUE THREAD

**Issue by stefc** [louthy/language-ext#1356]
Did there exists a shortcut to the following statement. With string?  datatype I before using 

```csharp
string? url = post.imageUrl ?? channel.imageUrl
```

So if the image url doesn't existing I've a fallback to the image url of the channel. 

Would be nice if I can archive the same with the Option<T> datatype ? 

```csharp
var url = post.imageUrl.Match<Option<Uri>>(
                    Some: imageUrl => imageUrl,
                    None: () => channel.imageUrl);
```

**Comment by louthy** [comment]
post.imageUrl || channel.imageUrl

**Comment by stefc** [comment]
Thx!!

Paul Louth ***@***.***> schrieb am Fr. 30. Aug. 2024 um 07:30:
