### ISSUE TITLE
[bug] Language.JavaStyle whitespace parser throws Null exception with multi-line comment

### ISSUE THREAD

**Issue by jcoder58** [louthy/language-ext#136]
This throws a null exception in __ParserExt.SelectMany where self is set to null.   I compiled the following with DotNet Core 1.0

    var jstp = makeTokenParser(Language.JavaStyle);
    var ws = jstp.WhiteSpace;
    var test3 = parse(ws, @"
    /*
    */
    ");

Stack trace:
> LanguageExt.Parsec.dll!___ParserExt.SelectMany.AnonymousMethod__0(LanguageExt.Parsec.PString inp) Line 108	C#
 	LanguageExt.Parsec.dll!LanguageExt.Parsec.Internal.choicei.AnonymousMethod__0(LanguageExt.Parsec.PString inp) Line 59	C#
 	LanguageExt.Parsec.dll!___ParserExt.label.AnonymousMethod__0(LanguageExt.Parsec.PString inp) Line 58	C#
 	LanguageExt.Parsec.dll!___ParserExt.SelectMany.AnonymousMethod__0(LanguageExt.Parsec.PString inp) Line 113	C#
 	LanguageExt.Parsec.dll!LanguageExt.Parsec.Internal.choicei.AnonymousMethod__0(LanguageExt.Parsec.PString inp) Line 59	C#
 	LanguageExt.Parsec.dll!___ParserExt.label.AnonymousMethod__0(LanguageExt.Parsec.PString inp) Line 58	C#
 	LanguageExt.Parsec.dll!LanguageExt.Parsec.Prim.many.AnonymousMethod__0(LanguageExt.Parsec.PString inp) Line 297	C#
 	LanguageExt.Parsec.dll!___ParserExt.SelectMany.AnonymousMethod__0(LanguageExt.Parsec.PString inp) Line 113	C#
 	LanguageExt.Parsec.dll!LanguageExt.Parsec.Prim.either.AnonymousMethod__0(LanguageExt.Parsec.PString inp) Line 134	C#
 	LanguageExt.Parsec.dll!___ParserExt.Parse<LanguageExt.Unit>(LanguageExt.Parsec.Parser<LanguageExt.Unit> self, string input) Line 81	C#
 	LanguageExt.Parsec.dll!LanguageExt.Parsec.Prim.parse<LanguageExt.Unit>(LanguageExt.Parsec.Parser<LanguageExt.Unit> p, string input) Line 28	C#
 	GenDotNetHeaders.dll!GenDotNetHeaders.PreprocessorParser.Parse(GenDotNetHeaders.IncludeFile header) Line 66	C#

**Comment by louthy** [comment]
@jcoder58 This should be fixed in 1.9.2 on nuget now.
