### ISSUE TITLE
IAsyncEnumerable extensions introduced in 5.0.0-beta-08 conflict with System.Linq.Async

### ISSUE THREAD

**Issue by guythetechie** [louthy/language-ext#1360]
Wanted to raise the fact that many developers (150+ million downloads) use [System.Linq.Async](https://www.nuget.org/packages/System.Linq.Async) for LINQ and other operations on IAsyncEnumerable.

The `Select`, `SelectMany`, `Where`, `Skip`, and `Take` extensions [here](https://github.com/louthy/language-ext/blob/293f0c181f64b69517cf99fc5e2d85dee2eaa1bd/LanguageExt.Core/Immutable%20Collections/AsyncEnumerable/AsyncEnumberable.Extensions.cs) conflict with that library. Those of us who use both have to fully qualify the namespace to avoid ambiguity: instead of `myEnumerable.Select(f)`, we have to do something like `LanguageExt.AsyncEnumberableExtensions.Select(myEnumerable, f)`. LINQ expressions are also unusable because of the conflict.

One workaround would be to put your extensions under a subnamespace (e.g. `LanguageExt.AsyncEnumerable`). Another route would be to include most of the operations that make sense in `System.Linq.Async` directly into `LanguageExt`.

I completely understand that you have to code in a manner that makes sense for your library, and addressing potential conflicts with other popular libraries is likely out of scope. Just wanted to make you aware of the conflict while v5 is still in beta.

Thank you for your consideration.

**Comment by louthy** [comment]
>I completely understand that you have to code in a manner that makes sense for your library, and addressing potential conflicts with other popular libraries is likely out of scope. Just wanted to make you aware of the conflict while v5 is still in beta.

There is that, but I also need to be respectful of the fact that many more people use that library than this one (well, at least have downloaded it!).  I have moved the specific LINQ extensions (`Select`, `SelectMany`, `Where`, `Take`, `Skip`) into a new namespace: `LanguageExt.Async.Linq`. 

The other extensions (which I think I can say I have the right to claim) are still in the `LanguageExt` namesapce: `Map`, `Bind`, `Filter`, `AsStream`.

Thanks for the heads-up, I didn't know about that library at all!  Will be deployed in `5.0.0-beta-12`.

**Comment by guythetechie** [comment]
That works. Thank you!
