### ISSUE TITLE
Concerns with Error equality testing.

### ISSUE THREAD

**Issue by hermanda19** [louthy/language-ext#1368]
I'm currently deciding whether to use `Error` as the primary error type in my project.
Doing so would be ideal due to its ubiquity throughout this library.
However, I have a few concerns regarding its notion of equality.

The `Error` type defines equality like so:
```csharp
    public virtual bool Is(Error error) =>
        error is ManyErrors errors
            ? errors.Errors.Exists(Is) 
                : Code == 0
                    ? Message == error.Message
                    : Code == error.Code;

    public virtual bool Equals(Error? other) =>
        other is not null && Is(other);
```

Since `Error` is a record, all of its derivations must be records as well.
The compiler enforces that derived records are only equal to other instances if they are the same type.
This can be seen in the desugared methods of `Expected`:
```csharp
    [NullableContext(2)]
    [CompilerGenerated]
    public override bool Equals(object obj)
    {
        // Only `Expected` instances allowed. Derivations will perform a similar check for their own type.
        return Equals(obj as Expected); 
    }

    [NullableContext(2)]
    [CompilerGenerated]
    public sealed override bool Equals(Error other)
    {
        // Forces execution of above method with type check.
        return Equals((object)other);
    }
```

> As a sidenote, this actually results in redundant checks in the derived types.
> For example, here's `Expected` desugared:
> ```csharp
> [NullableContext(2)]
> [CompilerGenerated]
> public virtual bool Equals(Expected other)
> {
>    return (object)this == other || (
>       base.Equals(other) && //calls Error.Is which unnecessarily checks is ManyErrors and code/message properties
>       EqualityComparer<string>.Default.Equals(<Message>k__BackingField, other.<Message>k__BackingField) && 
>       EqualityComparer<int>.Default.Equals(<Code>k__BackingField, other.<Code>k__BackingField));
> }
> ```
> Note that this generated method does NOT ignore `Error.Message` if `Error.Code != 0`.

Since `Error.Is` does not consider any type other than `ManyErrors`, this results in surprising behavior:
```csharp
var errorUhOh = new Expected("Uh oh...", 0);
var errorExceptional = new Exceptional("Uh oh...", new Exception());

// symmetric equality
Assert(errorUhOh != errorExceptional);
Assert(errorExceptional != errorUhOh);

// asymmetric *is*
Assert(errorUhOh.Is(errorExceptional));
Assert(!errorExceptional.Is(errorUhOh));
```
This issue is compounded by the fact that `Error.Is` and `Error.Equals` appear to be used inconsistently throughout the library.
Take these methods for example:
```csharp
public static partial class FallibleExtensions
{
    // Uses Error.Equals
    public static K<F, A> Catch<E, F, A>(
        this K<F, A> fa,
        Error Match,
        Func<E, K<F, A>> Fail) 
        where F : Fallible<E, F> =>
        F.Catch(fa, e => Match.Equals(e), Fail);
    
    // Uses Error.Is
    public static K<F, A> Catch<F, A>(
        this K<F, A> fa,
        Error Match,
        Func<Error, K<F, A>> Fail) 
        where F : Fallible<F> =>
        F.Catch(fa, e => e.Is(Match), Fail);
}

public static partial class Prelude
{
    // Uses Error.Equals if E is Error.
    public static CatchM<E, M, A> @catch<E, M, A>(E error, Func<E, K<M, A>> Fail) 
        where M : Fallible<E, M> =>
        matchError(e => e?.Equals(error) ?? false, Fail);
}
```

Personally, I'm happy that `Error` is a record since it allows for custom, *sensible* equality checking in bespoke `Error` types.
As an example:
```csharp
var errorTrue = new BespokeError(true);
var errorFalse = new BespokeError(false);

// Custom equality notion despite storing different values. Good!
Assert(errorTrue == errorFalse);
Assert(errorFalse == errorTrue);

var errorUhOh = new Expected("Uh oh...", 0);

// BespokeError instances may "match" Expected instances. Unfortunate, but tolerable.
Assert(errorUhOh.Is(errorTrue));
Assert(!errorUhOh.Is(errorFalse));

// BespokeError instances are NEVER Expected instances. Good!
Assert(errorTrue != errorUhOh);
Assert(errorUhOh != errorTrue);

public partial record BespokeError(bool flag) : Error
{
    public override string Message => flag ? "Uh oh..." : "Oops!";

    public override bool IsExceptional => false;

    public override bool IsExpected => true;

    public override bool Is<E>() => false;
    
    public virtual bool Equals(BespokeError? other)
    {
        return other is { }; //All instances are the same, regardless of flag.
    }
}
```

I'm not entirely sure what the solution here is.
However, I wonder if `Error` might be too opinionated about error equality for such a fundamental type.
At the very least, I would like assurance as to how error-handling functions will behave when using bespoke error types.

**Comment by louthy** [comment]
I think I changed this recently to use Is fir Equals and it felt wrong when I did it. I'm AFK right now, I'll take a look later.

**Comment by louthy** [comment]
Ok, got some time to look at it, and it reminded me why it didn't feel right using `Is` inside of `Equals`: the reason I wrote `Is` in the first place was because of the problems with record equality!  And, clearly I forgot that when I fixed another issue recently.  

> This issue is compounded by the fact that Error.Is and Error.Equals appear to be used inconsistently throughout the library

The inconsistency you highlight is actually a plain and simple bug.  The `Catch<E, F, A>` version should not be matching on `Error`, it should be matching on `E`.  

My solution to the wider problem is this:

* Fix the bug above
* Delete the `Equals` and `GetHashCode` overrides in `Error`.  Reverting back to the structural equality provided by records.
* Rename `Is<E>()  where E : Exception` to `HasException<E>()`
* Add `IsType<E>() where E : Error` - it will test if the current `Error` is of type `E`.  If the type is `ManyErrors` then it will check the collection for the existence of an `Error` of type `E`.

That means if you want to test for structural equality, use `Equals`, if you want to match on error type use `IsType<E>()` or `Is(Error)`.  All of the matching in `@catch` and `.Catch` will use these `IsType<E>()` and `Is(Error)`.

Now I just need to remember why I added the `Equals` overrides in the first-place.  It's been a long day and my brain is tired, so I will dig a little deeper tomorrow.  Hopefully, I'll be able to roll out an update tomorrow afternoon at the latest.

If you think I've missed anything then please let me know below and I'll take it into account tomorrow am.

**Comment by hermanda19** [comment]
Thanks for looking into this! Your solution seems good regarding structural equality.

However, there's still the issue of the asymmetric `Error.Is()` (and now `Error.IsType<E>()`) relations.
The result can depend on the method target.

One particular problem is that the `.Catch` extensions target the `Error` instance inside the `Fallible` structure.
This means the function caller has no way to control what errors are matched against!
A "rogue" `Error` derivation might decide that it simply *is* the error specified by `Match`.
```csharp
// `e` has total control over the match result.
// It could even ignore `Match` entirely!
public static K<F, A> Catch<F, A>(
   this K<F, A> fa,
   Error Match,
   Func<Error, K<F, A>> Fail) 
   where F : Fallible<F> =>
   F.Catch(fa, e => e.Is(Match), Fail);
```

While the current asymmetry is unfortunate, I think the caller should be given the most power in this situation.

**Comment by hermanda19** [comment]
Indeed! My point was to highlight who has control in this situation.

Thanks for addressing this!
