### ISSUE TITLE
Errornous 'ambiguous use of a left associative operator' message

### ISSUE THREAD

**Issue by jcoder58** [louthy/language-ext#137]
The following code fragment gives me the error message "error at (line 1, column 12): ambiguous use of a left associative operator".  The precedence rules should fix the ambiguity, right?

                Operator<ASTNode>[][] table = {
                    new [] { prefix("!"), prefix("~"), prefix("++"), prefix("--"), prefix("-"), prefix("+") },
                    new [] { binary("*", Assoc.Left), binary("/", Assoc.Left), binary("%", Assoc.Left) },
                    new [] { binary("+", Assoc.Left), binary("-", Assoc.Left) },
                    new [] { binary("<", Assoc.Left), binary(">", Assoc.Left), binary(">=", Assoc.Left) , binary("<=", Assoc.Left) },
                    new [] { binary("==", Assoc.Left), binary("!=", Assoc.Left) },
                    new [] { binary("&", Assoc.Left) },
                    new [] { binary("^", Assoc.Left) },
                    new [] { binary("|", Assoc.Left) },
                    new [] { binary("&&", Assoc.Left) },
                    new [] { binary("||", Assoc.Left) },
                    new [] { binary("?", Assoc.Right), binary(":", Assoc.Right) },
                };

                expr = Expr.buildExpressionParser<ASTNode>( table, term );

                 var test1 = parse(expr, "XX + XX != 1");

**Comment by louthy** [comment]
Please don't prefix issues with [Bug], it does jar a little.  I'll confirm it as a bug if it is the case, but I doubt it, as I have written full languages with the Parsec library.  The example in best-form isn't complete, so there may be some issues if you're following it.  The lang-ext Process config system has a [full typed expression parser in it if you want to have a look at that](https://github.com/louthy/language-ext/blob/master/LanguageExt.Process/Config/ProcessSystemConfigParser.cs):

First off make sure that your [`ReservedOpNames`, `OpStart` and `OpLetter` are sound](https://github.com/louthy/language-ext/blob/master/LanguageExt.Process/Config/ProcessSystemConfigParser.cs#L86
) 

If it's possible to share your [term parser](https://github.com/louthy/language-ext/blob/master/LanguageExt.Process/Config/ProcessSystemConfigParser.cs#L370) too that'd be useful (that's passed to `buildExpressionParser`):

Example file that's parsed:

https://github.com/louthy/language-ext/blob/master/Samples/Strategies/process.conf#L8

**Comment by jcoder58** [comment]
User Error :(.

**Comment by louthy** [comment]
They're the best kind :)
