### ISSUE TITLE
An argument for Alternative

### ISSUE THREAD

**Issue by hermanda19** [louthy/language-ext#1394]
I recently wrote a function for combining two arbitrary `Option<A>` values:
```csharp
static Option<A> combineF<A>(Option<A> a, Option<B> b, Func<A, A, A> f) =>
    f.Map(a).Apply(b) || a || b;
```
Then I thought, why not generalize to `MonoidK`?
```csharp
static K<F, A> combineF<F, A>(K<F, A> a, K<F, A> b, Func<A, A, A> f)
    where F : MonoidK<F>, Applicative<F> =>
    f.Map(a).Apply(b).Combine(a).Combine(b);
```
However, it struck me that `||` is intuitively correct but `Combine()` isn't. 
So, I considered the result when using the free monoid, `Seq<A>`:
```csharp
var one = Seq(1);
var two = Seq(2);
var sum = combineF(one, two, (a, b) => a + b);
Console.WriteLine(sum); // [3, 1, 2]
```
This result doesn't make sense to me. At least, its application is not immediately obvious. 

My intention with `combineF()` was to make a "choice" depending on the failure state of the given functors, but `Seq<A>` ends up making an "aggregate" instead. However, maybe I was using `MonoidK` wrong. So, I wondered if this was an issue with other `MonoidK` functions too.
```csharp
var one = Seq(1);
var two = Seq(2);
var three = Seq(3);
var first = MonoidK.oneOf(Seq(one, two, three));
Console.WriteLine(first); // [1, 2, 3]
```
It's strange to me that `oneOf` is, in a sense, returning "all of the values" instead of only "one of the values".
Considering this function was for `Alternative` functors until recently, I think this suggests that trait needs to come back.

# Alternative
I think `Alternative` should be a `MonoidK` where `Combine()` represents a choice between two values.
```csharp
interface Alternative<M> : MonoidK<M>, Applicative<M> where M : Alternative<M>
{
    static abstract K<M, A> Choice<A>(K<M, A> a, K<M, A> b);

    static K<M, A> MonoidK<M>.Combine(K<M, A> a, K<M, A> b) => M.Choice(a, b);
}
```
More specifically, I think an implementation should satisfy these laws:
```csharp
choice(pure(a), pure(b)) = pure(a)
choice(empty(), pure(b)) = pure(b)
choice(pure(a), empty()) = pure(a)
```
In this definition, `Option` is `Alternative` but not `Seq`.

# SemiAlternative
You recently wrote that `Alternative` doesn't make sense without `SemiAlternative`.
However, let's consider its subset of the above laws:
```csharp
choice(pure(a), pure(b)) = pure(a)
//choice(empty(), pure(b)) = pure(b) //No identity element
//choice(pure(a), empty()) = pure(a) //No identity element
```
It's only requirement is that `Choice()` returns the left argument.
However, we don't need `SemigroupK` or even `Applicative` to implement that function:
```csharp
static A left<A>(A a, A b) => a;
```
It can just be called for any type!
For this reason, I don't think `SemiAlternative` is necessary and therefore it's ok to have `Alternative` without it.

# Fallible
A counter-argument to `Alternative` is that `Fallible` is already capable of implementing the `Choice()` function.
In fact, there is already an extension method for it defined:
```csharp
public static K<F, A> Catch<E, F, A>(this K<F, A> fa, K<F, A> alternative) 
    where F : Fallible<E, F>, Applicative<F> => // Applicative<F> not needed
    F.Catch(fa, _ => true, _ => alternative);
```
However, `Fallible<E, F>` requires an explicit failure type `E` to be specified.
That means type-inference doesn't work for the above `Catch()` method since `E` doesn't appear in the parameter type signatures.

Still, I could implement my `combineF()` function using `Fallible`, though it would inherit the same type-inference issue.
```csharp
static K<F, A> combineF<F, A, E>(K<F, A> a, K<F, A> b, Func<A, A, A> f)
    where F : Fallible<E, F>, Applicative<F> =>
    f.Map(a).Apply(b).Catch(a).Catch(b);
```

Another issue with `Fallible` is that there's no "empty" failure state unlike `Alternative`. You must procure a value of `E` to fail the computation. You can use `MonoidK.empty()` if available, but since `Fallible` and `MonoidK` are distinct interfaces, there's no explicit relationship between `MonoidK.empty()`, `MonoidK.combine()`, `Fallible.fail()`, and `Fallible.catch()`. For example, perhaps `MonoidK.empty()` produces an identity *success* state.

> As a side note, perhaps `Alternative` should have a helper interface like `Fallible` that defines a `true`, `false`, and `|` operator.

# Applicative
The laws I presented for `Alternative` don't relate to `Applicative.apply()` although they really ought to. Unfortunately, I'm not sure what those laws should be!

[Typeclassopedia](https://wiki.haskell.org/Typeclassopedia#Failure_and_choice:_Alternative.2C_MonadPlus.2C_ArrowPlus) defines some laws but also states `Alternative` instances only satisfy a subset of them. It also points out the issue that the list monoid violates the "Left Catch" law, which I think is the issue I presented with `Seq<A>`. My proposed laws for `Alternative.Choice()` are stricter than what's described on that page, so the consequence of that may help in specifying the laws for `Applicative.apply()`.

**Comment by hermanda19** [comment]
I thought about this some more and realized that the `Catch(K<F, A>)` extension method may not actually be equivalent to `Combine()` when the type implements `Alternative`.

This is demonstrated with `Fin`'s implementation of these traits:
```csharp
static K<Fin, A> SemigroupK<Fin>.Combine<A>(K<Fin, A> ma, K<Fin, A> mb) =>
    ma switch
    {
        Succ<A> => ma,
        Fail<A> (var e1) => mb switch
                            {
                                Succ<A>          => mb,
                                Fail<A> (var e2) => Fin<A>.Fail(e1 + e2), //preserves error information
                                _                => mb
                            },
        _                => ma
    };

static K<Fin, A> Fallible<Error, Fin>.Catch<A>(
    K<Fin, A> fa, Func<Error, bool> Predicate,
    Func<Error, K<Fin, A>> Fail) => //error preservation depends on function
    fa.As().BindFail(e => Predicate(e) ? Fail(e).As() : Fin<A>.Fail(e));
```
When considering the choice-like `Catch(K<F, A>)` extension method, `Fin` does not preserve the caught error information even though its `Combine()` function does.

If I were to implement a `combineF()` function for `Fin` using `Alternative`, it would have strange results.
```csharp
static Fin<A> combineF<A>(Fin<A> a, Fin<A> b, Func<A, A, A> f) =>
    f.Map(a).Apply(b).Choice(a).Choice(b);

var first = FinFail<Unit>(Error.New("first"));
var second = FinFail<Unit>(Error.New("second"));
var result = combineF(first, second, (_, _) => _);
Console.WriteLine(result); // ["first", "second", "first", "second"]
```
The errors of `first` and `second` appear twice in the resulting `Fin<Unit>`.

What I would actually want is something like this:
```csharp
static Fin<A> combineF<A>(Fin<A> a, Fin<A> b, Func<A, A, A> f) =>
    f.Map(a).Apply(b).Catch(a.Choice(b)); //ignore previous errors with `Catch()`

var first = FinFail<Unit>(Error.New("first"));
var second = FinFail<Unit>(Error.New("second"));
var result = combineF(first, second, (_, _) => _);
Console.WriteLine(result); // ["first", "second"]
```

So, what does this mean? I'm not sure. It does throw a wrench into things, though.

**Comment by louthy** [comment]
Yes, I like this proposal and it makes more sense than just treating `Alternative` as a straight monoidal-applicative.  The `Choice` operator makes much more sense and it allows types like `Seq<A>` to have a `Choice` and `Combine`.  It will certainly read better in code.  It is also the difference between `|` and `+`.  So, I feel good about that.

`Fallible` is different in that it is there to handle a failure value, it is more like an embellished `Choice`.  I'm OK with supporting all: `Combine`, `Choice`, and `Catch`.  They are different and some types will have all 3, some none.

`SemiAlternative` was the thing that bothered me to the most, so leaving that out I think is fine.

I'll get to it.

**Comment by louthy** [comment]
Just a follow-up to this.  I have re-added something similar to `SemiAlternative`, but called it `Choice`:

```c#
public interface Choice<F> : Applicative<F>, SemigroupK<F>
    where F : Choice<F>
{
    static abstract K<F, A> Choose<A>(K<F, A> fa, K<F, A> fb);
    
    static K<F, A> SemigroupK<F>.Combine<A>(K<F, A> fa, K<F, A> fb) => 
        F.Choose(fa, fb);
}
```
The reason for this is that I want all of the monad-transformers to implement `Choice`, so that `|` can be used on a transfomer-stack (and flow down to the transformer/monad that can implement a choice).  For those stacks that don't have any alternative-value (rare, but can happen, `Identity` for example), then there is always a good default implementation for `Choose` (returning the first parameter).  It isn't possible for `Alternative` to be implemented for every transformer because it's not always possible to implement `Empty` all the way down the stack (`Either` for example).

That makes the `Alternative` trait into a combination of `Choice` and `MonoidK`.
```c#
public interface Alternative<F> : Choice<F>, MonoidK<F>
    where F : Alternative<F>;
```
This feels right and `Choice` is a more elegant name than `SemiAlternative`, which always bugged me.  'Choice' and 'Alternative' being synonyms isn't ideal, but they're still easier to learn.

The other thing that I'm considering now and asking for feedback from anyone that reads this:

* The operator that maps to `Choice` is `|`, which coalesces the failures until one 'succeeds'.  For collections, 'success' is a non-empty sequence.
* The operator that maps to `Combine` is '+', which works well for collections, because `+` implies concatenation.  But for types like `Fin`, it aggregates the errors (like `Validation`).  It feels like the operator could be, or maybe _should be_, `&`.  Because it feels like the dual of `Choice`.  

Currently, I'm sticking with `+` as the `Combine` operator.  But I'm open to hearing feedback on whether `&` should be used instead.  

Another approach might be `+` for collections and `&` for other types, but then there's a consistency gap across the types, which has its own problems.

**Comment by hermanda19** [comment]
Glad to hear my proposal is well received!

Regarding the `&` operator, I don't think it makes sense to use it as a synonym for `Combine`.
The way I like to think about `&` and `|` is in relation to their `bool` and short-circuiting counterparts `&&` and `||`.

We can draw a consistent analogy between `bool` and `Alternative` `||`:
```csharp
true || true = true
false || true = true
true || false = true
false || false = false

pure(a) || pure(b) = pure(a)
empty() || pure(b) = pure(b)
pure(a) || empty() = pure(a)
empty() || empty() = empty()

pure(x) = true
empty() = false
```
However, if we try to do this with `&&`, we run into issues:
```csharp
true && true = true
false && true = false
true && false = false
false && false = false

pure(a) && pure(b) = ?          //maybe pure(b) since we don't short-circuit?
empty() && pure(b) = empty()    //violates left-zero law!
pure(a) && empty() = empty()    //violates right-zero law!
empty() && empty() = empty()
```
It appears that `&&` can't be a monoid for an `Applicative` in general.
It's a monoid for `bool` because `true` is the identity element rather than `false`.
However, `pure(a)` may have any number of values and therefore can't be an identity element.
This isn't necessarily an issue (it can be a semigroup), but it's unlike `+`!
```csharp
pure(a) + pure(b) = x
empty() + pure(b) = pure(b)    //left-zero law upheld
pure(a) + empty() = pure(a)    //right-zero law upheld
empty() + empty() = empty()

empty() + pure(b) != empty() && pure(b)
pure(a) + empty() != pure(a) && empty()
empty() + empty() = empty() && empty()
```
Therefore, regardless of what `&` means, I believe it's necessarily distinct from `+` and therefore `Combine`.
> If anything I believe `&` would be closer to a hypothetical `*` operator than to `|` or `+`.
> In Boolean algebra, `|` is analogous to `+` and `&` is analogous to `*`.

**Comment by louthy** [comment]
Yep, I've come to the same conclusions! It's now released.
