### ISSUE TITLE
Any plans to add railway oriented programming features to this library?

### ISSUE THREAD

**Issue by DamianReeves** [louthy/language-ext#140]
[Scott Wlashin](http://fsharpforfunandprofit.com/) has done a lot to popularize what he calls [railway oriented programming](http://fsharpforfunandprofit.com/rop/) are there any plans to bring railway oriented programming to this library?

- See also: http://fsprojects.github.io/Chessie/a-tale-of-3-nightclubs.html

**Comment by louthy** [comment]
'Railway Oriented Programming' isn't really a thing. It was made up on the fsharpforfunandprofit site to avoid using the word 'monad'. See the 'Forbidden Words' section of their site: http://fsharpforfunandprofit.com/about/

I understand why they decided to do this, but it can muddy the water somewhat. But any monad that has multiple execution paths based on its state fits into the railway oriented programming mould:

The ones in this library that have those multiple execution paths are:
```c#
    Option<T>
    OptionUnsafe<T>
    Either<L, R>
    EitherUnsafe<L, R>
    Try<T>
    TryOption<T>
    Parser<T>
    Parser<I, O>
```
I wouldn't get too attached to it as a term, not many people know what railway-oriented programming is.

If you [go to the lang-ext gitter feed](https://gitter.im/louthy/language-ext), and scroll up to my comments from Mar 11th then you'll see a bigger discussion on this, and an implementation of some of the examples from the fsharpforfunandprofit site.  It's not the first time this has been asked ;)

**Comment by DamianReeves** [comment]
I see what you mean. Great stuff. Thanks for the awesome library.

**Comment by c17r** [comment]
Not to necro this issue but in case anyone else is curious about the gitter discussion mentioned above, I scrolled back through and it starts at https://gitter.im/louthy/language-ext?at=56d467a1649ae49a694b59b4

**Comment by CumpsD** [comment]
> Not to necro this issue but in case anyone else is curious about the gitter discussion mentioned above, I scrolled back through and it starts at [gitter.im/louthy/language-ext?at=56d467a1649ae49a694b59b4](https://gitter.im/louthy/language-ext?at=56d467a1649ae49a694b59b4)

Seems to not exist anymore
