### ISSUE TITLE
docs(reference): broken link on `SomeHelp` namespace

### ISSUE THREAD

**Issue by BrainCrumbz** [louthy/language-ext#141]
Hi
going through library documentation: well done, compliments! 

There seems to be a broken link on *SomeHelp* namespace, pointing to https://louthy.github.io/languageext.core/LanguageExt/SomeHelp/index.htm which currently returns 404. Here's a screenshot of the mentioned link.

![somehelp](https://cloud.githubusercontent.com/assets/3185573/18756408/1f7b3e32-80f0-11e6-9423-23e8ca7565dc.png)

HTH

**Comment by louthy** [comment]
This is a big in my best-form project.  Could you report it there pls? 

https://github.com/louthy/best-form

**Comment by BrainCrumbz** [comment]
Sure

**Comment by louthy** [comment]
Thanks Brian, I'm away at the moment. I'll look into it soon.

**Comment by BrainCrumbz** [comment]
... I guess you meant Brain, if that was my team first name :smile:

**Comment by louthy** [comment]
Heh, sorry, replying very quickly on my phone. Not paying close enough
attention :)
