### ISSUE TITLE
[v4] [Bug] PublishReadyToRun publish keep running and don't complete

### ISSUE THREAD

**Issue by GihanSoft** [louthy/language-ext#1421]
### Issue Description
When referencing the `LanguageExt.Core` package (version 4.*) in a .NET 9.0 project and setting `PublishReadyToRun` to `true`, the publishing process continues to run indefinitely, consuming CPU and RAM resources without completing. The process appears to enter a deadlock or loop.

### Steps to Reproduce
1. Create a .NET 9.0 console application.
2. Set the `PublishReadyToRun` property to `true` in the project file.
3. Add the `LanguageExt.Core` package, version 4.*.
4. Implement a method with a return type of `Task<Either<Error, string>>`, for example, using an `HttpClient` within the method.
5. Publish the project for `win-x64`.

### Expected Behavior
The publishing process should complete successfully.

### Actual Behavior
The publishing process continues indefinitely, utilizing CPU and RAM resources without finishing.

**Comment by louthy** [comment]
I suggest you report that issue to Microsoft! I can't fix their compiler.
