### ISSUE TITLE
Request: how-to on building from source

### ISSUE THREAD

**Issue by monkeyhell** [louthy/language-ext#146]
I've spent an hour or so this evening trying to figure out why language-ext.sln doesn't build in VS2015 following a clean `git clone`.  I get the following error:

> Error occurred while restoring NuGet packages: Circular dependency references not supported. Package 'LanguageExt.Parsec'.

Am I doing something wrong?  NuGet does appear to have downloaded all the required packages, but hasn't added references to them to the projects (presumably it didn't get that far, because of the above error), so compilation fails with thousands of errors about not being able to find `System.Reactive` et al.  A quick how-to document on building from source would be much appreciated...

**Comment by louthy** [comment]
There were some broken references from the move from RxMain to System.Reactive.  Please re-sync and try again.

**Comment by monkeyhell** [comment]
@louthy Just tried again from scratch; same error:

> Restoring packages for 'LanguageExt.Parsec'.
> Restoring packages for 'E:\code\github\language-ext\LanguageExt.Parsec\project.json'
> TODO: Read and use lock file
> Using source https://api.nuget.org/v3/index.json
> Restoring packages for .NETFramework,Version=v4.5
> Restoring packages for .NETFramework,Version=v4.6
> Error occurred while restoring NuGet packages: Circular dependency references not supported. Package 'LanguageExt.Parsec'.

**Comment by louthy** [comment]
I have just tried it from scratch too and it worked fine.  Which version of VS 2015 are you on?  Make sure you have the latest service packs.

**Comment by monkeyhell** [comment]
@louthy Installed VS2015 Update 3 overnight.  Notably, the NuGet Package Manager component was upgraded from 3.0.0 to 3.4.4.  It builds fine now.  Thanks!

**Comment by louthy** [comment]
Great :)
