### ISSUE TITLE
Custom JsonConverter

### ISSUE THREAD

**Issue by spyder94** [louthy/language-ext#148]
We have a message that contains a property that is a System.Security.Claims.Claim.  Deserialization of that message fails with this error message:

 Unable to find a constructor to use for type System.Security.Claims.Claim. A class should either have a default constructor, one constructor with arguments or a constructor marked with the JsonConstructor attribute.

I can reproduce the issue with the following code:

            var ss = new JsonSerializerSettings
            {
                TypeNameHandling = TypeNameHandling.All,
                TypeNameAssemblyFormat = FormatterAssemblyStyle.Simple,
                MissingMemberHandling = MissingMemberHandling.Ignore
            };

            var c = new Claim("foo", "bar");
            var so = JsonConvert.SerializeObject(c, ss);
            var o = JsonConvert.DeserializeObject<Claim>(so, ss);

I can fix the problem in the code above by adding a custom JsonConverter for the Claim class but there doesn't seem to be any way to register that converter in the ActorSystemConfig.  I tried registering the converter in the JsonConvert.DefaultSettings but that didn't work.  I believe it doesn't work because the ActorSystemConfig.Default.JsonSerializerSettings always returns a new instance of JsonSerializerSettings.

Is there another way of handling this scenario that I'm missing?

**Comment by louthy** [comment]
Currently there isn't a way to inject custom deserialisers, no.  That was
the initial reason for ActorSystemConfig, I just hadn't gotten around to
generalising it fully.  The only short term suggestion I have is to use a
DTO object of some sort.

**Comment by spyder94** [comment]
I was wrong about using the JsonConvert.DefaultSettings to register custom converters.  Apparently the code where i was doing the registration wasn't getting called.  Adding this in our application entry point corrects the problem.

                Newtonsoft.Json.JsonConvert.DefaultSettings = () => new Newtonsoft.Json.JsonSerializerSettings
                {
                    Converters = new List<Newtonsoft.Json.JsonConverter> { new ClaimConverter() }
                };
