### ISSUE TITLE
The various choose functions do not return the correct result

### ISSUE THREAD

**Issue by Richiban** [louthy/language-ext#149]
More specifically, they do not have the correct signatures. Here's an example:

```csharp
IEnumerable<T> choose<T>(IEnumerable<T> list, Func<T, Option<T>> selector)
```

For reference, the F# documentation looks like this:

```fsharp
('T -> 'U option) -> seq<'T> -> seq<'U>
```

So, by my reckoning, the C# signature should in fact be:

```csharp
IEnumerable<R> choose<T, R>(IEnumerable<T> list, Func<T, Option<R>> selector)
```

Which makes sense because a `choose` operation is essentially a `map` and a `filter` at the same time, so there should be two type parameters, not one.

I have implemented a fix for this (interestingly enough I didn't have to change any implementation at all; I just fixed the signatures and added a test or two) and will get a pull request together later today.

**Comment by Richiban** [comment]
As an example: 

```csharp
	var input = List(
		Some(1),
		Some(2),
		Some(3),
		None,
		Some(4),
		None,
		Some(5));
		
	var actual = input.Choose(x => x);
```

`actual` should be equivalent to `{1, 2, 3, 4, 5}` but instead it simply returns the original sequence of `{		Some(1), Some(2), Some(3), None, Some(4), None, Some(5)}`

**Comment by louthy** [comment]
Yep, blatant bug.  If you have a fix ready I'll hang on for that.
