### ISSUE TITLE
Question regarding new tuple

### ISSUE THREAD

**Issue by tomaszpolanski** [louthy/language-ext#15]
Hey,
Why the With function is called like this?
Wouldn't Map (in case returning non Unit) and Iter (in case Unit) be more intuitive?

Nonetheless, bunch of great ideas!

**Comment by louthy** [comment]
Hi Tomasz, yes `map` would make sense, although I think `iter` would be confusing, as it's not really iteration.  I previously named it `apply`, which was OK, but still not accurate.  Calling both `map` would also work, the mappings would be from `tuple -> T` and `tuple -> unit`, which is fine.  If it returned `void` then `map` wouldn't really make sense.  `decompose` is too long, `decom` not descriptive enough.

Ultimately there wasn't a big idea behind using `with` other than a declaration of putting something in context.  There are other `with` functions which could probably be named `map` also.

I will probably revisit some of the API over the next few weeks (to get everything ready for the proper release of C# 6), so I may take your comments on-board.

Thanks for the feedback :)

Paul

**Comment by tomaszpolanski** [comment]
Thanks for the clarification Paul, keep up the great work!

Cheers,
Tomasz
