### ISSUE TITLE
Threading is in-order execution?

### ISSUE THREAD

**Issue by BrannonKing** [louthy/language-ext#152]
It wasn't obvious from your examples if your threading stuff runs/completes in order of items queued. Running things in order and "skipping all but the currently running and last queued action" are patterns that I use regularly. I have some code for that here: https://github.com/BrannonKing/Kts.Actors . You're welcome to pull from that code (or the ideas there) if you want. 

Also, the Microsoft.Tpl.Dataflow library includes an in-order thread queue processor called ActionBlock. I don't really care for their interface, though.

I was hoping that C# 7 would get enough features we could do inline/attributed method action-type declaration similar to what Ruby does. Have you thought about that much?

**Comment by louthy** [comment]
The 'threading stuff', which I assume you're referring to the Process system is an implementation of the Actor model; it does explicitly state (in the docs) that they're single threaded (and therefore the messages are handled in the order they arrive at the Process inbox).

I've never used Ruby, so I'm not sure what your final paragraph refers to.
