### ISSUE TITLE
HEADS UP: Regarding contributions / pull-requests

### ISSUE THREAD

**Issue by louthy** [louthy/language-ext#166]
I am currently making some changes on another branch, which involves restructuring pretty much all the core types.  Code is moving, files are moving, major new functionality is being added.  Because of this I'd like to forewarn anybody that wants to contribute to the project (and all are welcome) to **please clear it with me first**, because anything that interacts with the Core types or changes the csprojs will probably cause major merge issues.

**Comment by orthoxerox** [comment]
It looks like it's based on Claudio Russo's and Matt Windsor's concepts, awesome stuff. Have you managed to make query expressions work with generic monads?

**Comment by louthy** [comment]
@orthoxerox 

> Claudio Russo's and Matt Windsor's concept

It is, yes. 

I've been fighting the type-system relentlessly over the past few months.  I keep going back and forth between monadic types like `Option<A>`, `Either<L, R>`, etc. deriving from a `Monad<A>` interface; and keeping `Option<A>`, `Either<L, R>` non-monadic but providing `MOption<A>`, `MEither<L, R>`... type-class instances.  

The first method is simplest, and allows LINQ to work, but causes a lot of boxing and loss of specificity.  The second method is the 'type class way', but requires many, many generic arguments.  It allows for truly ad-hoc generic programming, and is pretty awesome.  But LINQ can't infer the types.  

However a few nights ago I had a breakthrough when refactoring the `NewType<A>`, I realised I could get around a lot of the boxing and casting issues I was having by putting the declared type in the generic arguments list.  

So for example, the old way of declaring a `newtype` (say `Hours`) would be:
```c#
    public class Hours : NewType<int> 
    {
        public Hours(int x) : base NewType(x) {}
    }
```
Now you do this:
```c#
    public class Hours : NewType<Hours, int> 
    {
        public Hours(int x) : base NewType(x) {}
    }
```
The `NewType` definition looks like this:
```c#
    public abstract class NewType<NEWTYPE, A> :
        IEquatable<NEWTYPE>,
        IComparable<NEWTYPE>,
        Foldable<NEWTYPE, A>
        where NEWTYPE : NewType<NEWTYPE, A>
```
That allows the derived type to be used in the base-class member declarations.  Which is awesome, because `NewType` is supposed to shortcut creating a strongly-typed single value type.  So things like `Select` and `SelectMany` look like this:
```c#
        public NEWTYPE Select(Func<A, A> map) =>
            New(map(Value));

        public NEWTYPE SelectMany(
            Func<A, NewType<NEWTYPE, A>> bind,
            Func<A, A, A> project) =>
            New(project(Value, bind(Value).Value));
```
That means the end-user of the `NewType` gets a strongly typed version of `Select` and `SelectMany` by default:
```c#
    // Previously this wouldn't compile, because Select and SelectMany 
    // would return a NewType<A>, not Hours
    Hours h = from x in new Hours(24)
              from y in new Hours(24)
              select x + y;
```
Suddenly the _run-time_ checks I'd added to the `NewType` weren't needed anymore, because the compiler is now working with the derived type rather than the base type.  

If I create another `NewType` called `Seconds`:
```c#
    public class Seconds : NewType<Seconds, int> 
    {
        public Seconds(int x) : base NewType(x) {}
    }
```
And try to combine `Hours` and `Seconds`:
```c#
    // This won't compile, whereas it previously did because Select and SelectMany were
    // too generic
    var res = from x in new Hours(24)
              from y in new Seconds(60)
              from x + y;
```
This was the breakthrough that has put me on to the path I'm working on right now:  

* separate type-class instances for monads, functors, etc.  (`MOption<A>`, `FOption<A>`, `MEither<L, R>`, etc.)
* with non-monadic `Option<A>`, `Either<L, R>`, etc. 

> Have you managed to make query expressions work with generic monads?

This can't work with the full type-class approach I'm now taking.  Here are the general-case definitions for `SelectMany` and `Join`.  Take a look at the generic arguments, I'm sure you can see why LINQ has a hard time!
```c#
        public static MC SelectMany<MONADA, MONADB, MONADC, MA, MB, MC, A, B, C>(
            this MA self,
            Func<A, MB> bind,
            Func<A, B, C> project)
            where MONADA : struct, Monad<MA, A>
            where MONADB : struct, Monad<MB, B>
            where MONADC : struct, Monad<MC, C> =>
                default(MONADA).Bind<MONADC, MC, C>( self,    t => 
                default(MONADB).Bind<MONADC, MC, C>( bind(t), u => 
                default(MONADC).Return(project(t, u))));

        public static MD Join<EQ, MONADA, MONADB, MONADD, MA, MB, MD, A, B, C, D>(
            this MA self,
            MB inner,
            Func<A, C> outerKeyMap,
            Func<B, C> innerKeyMap,
            Func<A, B, D> project)
            where EQ     : struct, Eq<C>
            where MONADA : struct, Monad<MA, A>
            where MONADB : struct, Monad<MB, B>
            where MONADD : struct, Monad<MD, D> =>
                default(MONADA).Bind<MONADD, MD, D>(self,  x =>
                default(MONADB).Bind<MONADD, MD, D>(inner, y =>
                    default(EQ).Equals(outerKeyMap(x), innerKeyMap(y))
                        ? default(MONADD).Return(project(x,y))
                        : default(MONADD).Fail()));
```
However not all is lost, because now writing types like `Option<A>` becomes a lot easier.  So for example the `SelectMany` for `Option<A>` is now:
```c#
    public Option<C> SelectMany<B, C>(
        Func<A, Option<B>> bind,
        Func<A, B, C> project) =>
        this.SelectMany<MOption<A>, MOption<B>, MOption<C>, Option<A>, Option<B>, Option<C>, A, B, C>(bind, project);
```
So it calls the general-case version, which uses the instances to invoke the `Bind` and `Return` operations.  

I'm hoping that this allows me to build a much better code-gen system.  if you look at the generic arguments on the call to `SelectMany`, you should be able to see how easy it is to mix and match monadic types.  Here's a couple of examples going from `Option` to `Either`, and `Option` to `TryOption`
```c#
    this.SelectMany<MOption<A>, MEither<L, B>, MEither<L, C>, Option<A>, MEither<L, B>, MEither<L, C>, A, B, C>(bind, project);

    this.SelectMany<MOption<A>, MTryOption<B>, MTryOption<C>, Option<A>, TryOption<B>, TryOption<C>, A, B, C>(bind, project);
```
This is where it gets genuinely exciting, because the type-class instances are doing the work, not a load of bespoke code that's trying to plumb everything together.  

The end goal will be that you can write totally generic code that works with: monads, functors, foldables, optionals, choices, etc.  And you won't need to know about the specific type.  However you will incur the pain of providing the generic arguments.  I think for those rare cases where you want to write super-generic code, it's worth it.  And once it's all in and proven I'll take it to the Rosyln issues page and try and get pressure put on for a couple of improvements:
* We should only have to provide generic arguments that aren't in the parameters list
* Return type inference from the code within the method - this will make nearly all type inference work (and will probably make LINQ work too).

Most of this new stuff isn't committed yet, it's only on my local.
