### ISSUE TITLE
language-ext.With (copy update expression)

### ISSUE THREAD

**Issue by wallymathieu** [louthy/language-ext#167]
I'm thinking about adding a language-ext.With , in order to work with Lst<T>, Map<K,V>, Set<T>, Que<T>, Stck<T>, HMap<K, V>, and HSet<T>. Basically, taking the copy updat expression code from [With](https://github.com/wallymathieu/With) and gearing it towards language-ext. Thoughts?

**Comment by louthy** [comment]
For what benefit?  `with` is usually a feature of record-types; all 'mutating' of the collection types is handled by the various related functions (like `Add`).

**Comment by wallymathieu** [comment]
Exactly. In order to simplify creation of record types in c#.

**Comment by louthy** [comment]
I am unclear what that has to do with Lst, Map, Set, Que, Stck, HMap, and HSet?  

Whilst I think it's impressive what you've done with the `With` library, I do feel it's an overengineered solution and will add complexity to this library that I'd rather not maintain long-term.  It doesn't really add any value, if someone wants that functionality then they can just use your library directly surely?  There's no integration piece here from what I can tell.  Unless I'm missing something?

And there's a prettier (but more manual) way of doing record-type With methods, which is how I do them right now:

https://stackoverflow.com/questions/38575646/general-purpose-immutable-classes-in-c-sharp/38596298#38596298

**Comment by wallymathieu** [comment]
Yes, well, the easiest and prettiest way would be to actually use f# ;)
