### ISSUE TITLE
LanguageExt.Process (more on those later)

### ISSUE THREAD

**Issue by Silv3rcircl3** [louthy/language-ext#17]
Hi, 
I would like to know if you have plans to fill this part ? :-) 
I already checked the sample, test and code, but it seems that there are missing some more parts?!
For example, how to send a completed event to all subscribers?

thanks!

**Comment by louthy** [comment]
@Silv3rcircl3 it's pre-alpha for sure.  At the moment I'm bogged down with other projects, so I don't have time to delve further into this.  The general idea (on top of the other functional friendly aspects of this library) is to build an Erlang-like actor system.  I like the idea of calling them processes, and keeping the idea that each process is an atom of computation.  

I'm currently not happy with the effectful nature of calls to tell, spawn, pub, etc. I'd like to remove them and replace them with a more functional system that hangs off the return value of the process-function.  Then extend that further by supporting a process IO monad that implements lazy IO like the Haskell IO monad.  It can be implemented using a Free monad which would build IO actions (tell, pub, etc.) and continuations.  The result can then be passed to an interpreter which does the execution (that also allows for dependency injection and unit-testing).

All this would mean you could wrap your lovely purely functional code in actors, and the actors can be the state holders with bulletproof messaging between them.

Anyway, yeah that's the goal.  Hopefully I'll get some time to come back to it.  But if you fancy running with it I'd be happy to help and give feedback.

**Comment by Silv3rcircl3** [comment]
@louthy unfortunately I haven't used the actor pattern before, but it sounds great and I have used the process part exactly for what you describe, I think. I used a spawn to loop through a directory, parse every json file content and then used a tell for notify other subscribers. The interpreter part sounds a bit like a [mediator](https://github.com/jbogard/MediatR) I used for the ports and adapter pattern. There I have send a request message to the mediator, which used a container to resolve the handler for this request, wraps the execution with pre and post actions(logging for example) and then executes the handler with the message and returns the result to the caller. 
Anyway, I also haven't actually the time to learn more about the actor pattern or the process part of you library, that's also the reason I hoped you may have some documentation ready ;-)
But as far as I have finished the current project, I will come back to this and hopefully can learn this stuff and maybe can contribute something back, because I used the other parts with great success in the current project :+1: 

thanks.
