### ISSUE TITLE
SkipLast

### ISSUE THREAD

**Issue by kbilsted** [louthy/language-ext#172]
since you have the method Last on an ienumeratble and `Lst`, it would be nice to have the converse, a `SkipLast()`. How do you feel about that?  eg. steal an implementation right of http://stackoverflow.com/questions/1779129/how-to-take-all-but-the-last-element-in-a-sequence-using-linq

**Comment by louthy** [comment]
Good idea.  I'll look into rolling it into the v2 `type-classes` branch.

**Comment by louthy** [comment]
This is now in `v2.0.9-alpha`
