### ISSUE TITLE
DataContract de/serialization of Set<T>

### ISSUE THREAD

**Issue by NickDarvey** [louthy/language-ext#173]
Hello again!

We're having an issue with the deserialization of a `Set<T>` using `DataContractSerializer`. 

It serializes okay, though it gets cast into an array:
```
<Test xmlns="http://schemas.datacontract.org/2004/07/ConsoleApplication2" xmlns:i="http://www.w3.org/2001/XMLSchema-instance">
    <Name>Hello</Name>
    <SetOfStuff xmlns:a="http://schemas.microsoft.com/2003/10/Serialization/Arrays"><a:string>one</a:string><a:string>three</a:string><a:string>two</a:string></SetOfStuff>
</Test>
```
but deserializing results in an empty Set<T>.

I noticed that `Map<K,V>` works (though it's serialization is very explicitly a map) and my rudimentary glance at the differences showed that the `MapItem<K,V>` is annotated with `[Serializable]` but `SetItem<T>` is not.

Have you had any experience with de/serializing collection types using DataContractSerializer? Is it just a missing attribute or is it something more complicated?
(How do you normally handle serialization, do you create schemas that stick to primitives?)

Thanks Paul,
Nick

A gist demonstrating the issue is [here](https://gist.github.com/NickDarvey/5997b9412916f53e5a53bff1fe11c8ac).

**Comment by louthy** [comment]
I am a bit short of time, so I don't have a good answer for you; but obviously you could convert to a list and re-load from a list:
```c#
    var xs = set.ToList();

    var s = Set.createRange(xs);
```
I'm in the process of rewriting the core types;  when I get back to the code next week I'll take a look.

**Comment by louthy** [comment]
@NickDarvey Curiosity got the better of me.  As you mention `SetItem<T>` didn't have `[Serializable]`.  I have now added it if you'd like to test the latest from nuget.  

Please let me know how you get on, because I haven't had time to check.

**Comment by NickDarvey** [comment]
@louthy Cheers Paul, but that didn't work out. It's still serializing as an array and failing to deserialize back into a Set<T>.

In the meantime, converting it to a list does the trick! 

(I'm not sure if supporting DataContractSerialization is within the scope of this project so I'll close this issue.)
