### ISSUE TITLE
License is MIT but really GPL

### ISSUE THREAD

**Issue by samirahmed** [louthy/language-ext#18]
the concurrent dictionary implementation is licensed as GPL

cant use the library for work purposes as a consequence - its there not an alternative implementation that could be used?

**Comment by louthy** [comment]
Hi Samir, I see a couple of options for you:

1. The `WeakDictionary` is used in exactly one place: the `memo` function.  You could fork language-ext, delete that function and remove the `ConcurrentHashTable` folder.  Or...

2. If you can find an MIT licensed `WeakDictionary` equivalent, then I would be happy to update the library to use it.  Or...

3. Feel free to implement the same behaviour of `WeakDictionary` and submit a pull request.

To be clear the behaviour is more than just being a concurrent dictionary, it's a weak-reference concurrent dictionary (with weak keys too).  This is the description of `WeakDictionary`:

    /// Represents a thread-safe collection of key-value pairs that can be accessed
    /// by multiple threads concurrently and has weak references to the values.
    /// Whenever any of the values held by this dictionary is garbage collected the key-value pair holding the value will be removed from the dictionary.

My plan was that usage of the Concurrent Hashtable library would be temporary, so the plan was to take it away.  It's definitely something I will fix eventually, I just can't guarantee when at the moment.
