### ISSUE TITLE
UnCurry Methods

### ISSUE THREAD

**Issue by leandromoh** [louthy/language-ext#182]
I saw that the [project has Curry methods](https://github.com/louthy/language-ext/blob/master/LanguageExt.Core/Prelude_Curry.cs)  to transforms a function but none UnCurry methods.

I'm planning to submit a PR for this.

What do you think?

**Comment by louthy** [comment]
Although I don't see huge value for a C# library, it's likely to have a low maintenance factor.  So yes, sure, go ahead.  Could you please make your changes from the `type-classes` branch.  Thanks.

**Comment by louthy** [comment]
Released in `v2.0.31-beta`
