### ISSUE TITLE
Haskell flip function analogue

### ISSUE THREAD

**Issue by leandromoh** [louthy/language-ext#183]
I saw this project has methods that allow the programmers to use functions as curried and partial applications.

So I thought that would be also cool has a Flip function (like the Haskell one) that works for both curried and uncurried functions.

I'm planning to submit a PR for this.

What do you think?

**Comment by louthy** [comment]
As with uncurry, it's likely to have limited use, but again it's low maintenance, so yes go ahead.  Again, could you make the changes in the type-classes branch.

**Comment by louthy** [comment]
I made some changes to [your pull request](https://github.com/louthy/language-ext/pull/184).  The latest is now in `v2.0.31-beta`.
