### ISSUE TITLE
Fix LanguageExt.Core NuGet Description

### ISSUE THREAD

**Issue by Micha-kun** [louthy/language-ext#188]
@louthy, I understand it's not my project, but I think it's a good idea to maintain separatelly your "Actor Model" library from your Monad type library. Existing pretty strong Actor model libraries like Akka.Net, but lacking on good Monad libraries as yours, I think all would be benefit if Language-Ext NuGet only had the Monad library part. You could do a "language-ext.ActorModel" Nuget with your actor model library as an extension for anyone who wants it.

As written this is my humble opinion, and you're free to do anything with your library :) I'll continue to use your monad lib anyways!

**Comment by louthy** [comment]
@Micha-kun They are separate nu-get packages already, so you don't need to include the `LanguageExt.Process` system to use the `LanguageExt.Core`.  So I disagree with your premise somewhat.  The main reason I kept them all in a single repo was convenience for me.  It allows me to simply press F6 to compile and be confident I haven't broken anything further down the chain.

However!  I am actually in the process of splitting the repos and doing what you suggest.  The key reason is the new csproj/NET Standard builds take __forever__.  It's so annoying, something that compiles in a few seconds on the old build system, takes minutes on the new.  So to cut down the compile times I'm splitting the project.  I figured it would be a good time to split them into separate repos too, so I can have more focused documentation for the Process system.

But just to re-emphasis, the 'monad library' (it's much more than that btw, but I know what you mean) has a nu-get package: [LanguageExt.Core](https://www.nuget.org/packages/LanguageExt.Core)  and the Process system has its own separate nuget package: [LanguageExt.Process](https://www.nuget.org/packages/LanguageExt.Process)

In fact if you look at the README.md, you'll see (right at the top), links to all of the separate packages and what they do :)

Nu-get package | Description
---------------|-------------
[LanguageExt.Core](https://www.nuget.org/packages/LanguageExt.Core) | All of the core types and functional 'prelude'.  __This is all that's needed to get started__.
[LanguageExt.FSharp](https://www.nuget.org/packages/LanguageExt.FSharp) | F# to C# interop library.  Provides interop between the LanguageExt.Core types (like `Option`, `List` and `Map`) to the F# equivalents, as well as interop between core BCL types and F#
[LanguageExt.Parsec](https://www.nuget.org/packages/LanguageExt.Parsec) | Port of the [Haskell parsec library](https://hackage.haskell.org/package/parsec)
[LanguageExt.Process](https://www.nuget.org/packages/LanguageExt.Process) | 'Erlang like' actor system for in-app messaging and massive concurrency
[LanguageExt.Process.Redis](https://www.nuget.org/packages/LanguageExt.Process.Redis) | Cluster support for the `LanguageExt.Process` system for cluster aware processes using Redis for queue and state persistence
[LanguageExt.Process.FSharp](https://www.nuget.org/packages/LanguageExt.Process.FSharp) | F# API to the `LanguageExt.Process` system
[LanguageExt.ProcessJS](https://www.nuget.org/packages/LanguageExt.ProcessJS) | Javascript API to the `LanguageExt.Process` system.  Supports running of Processes in a client browser, with hooks for two-way UI binding.

**Comment by Micha-kun** [comment]
It's already separated? It's good news to hear! :) I think my confusion comes from NuGet package description of LanguageExt.Core:

This library uses and abuses the features of C# 6 to provide a functional 'Base class library', that, if you squint, can look like extensions to the language itself. *It also includes an 'Erlang like' process system (actors) that can optionally persist messages and state to Redis (note you can use it without Redis for in-app messaging). The process system additionally supports Rx streams of messages and state allowing for a complete system of reactive events and message dispatch.*

Is that ok?

**Comment by louthy** [comment]
@Micha-kun Good point!  I will rectify that.
