### ISSUE TITLE
Comments on FSharp to/from LanguageExt possibly mixed up

### ISSUE THREAD

**Issue by donners77** [louthy/language-ext#19]
Hi.

I'm wondering if the comments in https://github.com/louthy/language-ext/blob/master/LanguageExt.FSharp/Prelude.cs should be changed around as follows?

        /// <summary>
        /// Convert a LanguageExt Option into a F# Option ### change to: Convert an F# Option into a LanguageExt Option
        /// </summary>
        public static Option<T> fs<T>(FSharpOption<T> fsOption)

        /// <summary>
        /// Convert an F# Option into a LanguageExt Option ### change to: Convert a LanguageExt Option into a F# Option
        /// </summary>
        public static FSharpOption<T> fs<T>(this Option<T> option)

        /// <summary>
        /// Convert an F# Option into a LanguageExt Option ### change to Convert a LanguageExt Unsafe Option into a F# Option
        /// </summary>
        public static FSharpOption<T> fs<T>(this OptionUnsafe<T> option)

**Comment by louthy** [comment]
Yep, I was convinced I'd changed those!  Ok, I'll sort it.
