### ISSUE TITLE
HashSet contructor bug (always empty)?

### ISSUE THREAD

**Issue by StefanBertels** [louthy/language-ext#190]
`HashSet(1,2,3).IsEmpty == true`

Seems wrong to me.

I had a look into source and it seems the constructor fills a local variable `set` but it is never used:

        internal HSetInternal(IEnumerable<T> items, bool checkUniqueness = false)
        {
            var set = new HSetInternal<T>();

            if (checkUniqueness)
            {
                foreach (var item in items)
                {
                    set = set.TryAdd(item);
                }
            }
            else
            {
                foreach (var item in items)
                {
                    set = set.Add(item);
                }
            }
        }

**Comment by ncthbrt** [comment]
Which version are you working off v1.9.x or v2?

**Comment by StefanBertels** [comment]
1.9.x
Code snippet is taken from master branch.

**Comment by louthy** [comment]
@StefanBertels Thanks for the heads up.  I'll look into it.  As a side note, `HashSet` doesn't get you any wins over `Set` in terms of performance.  So unless you're working with types that aren't comparable then it's worth switching.

**Comment by StefanBertels** [comment]
Thanks for very fast answer and for this fantastic library.

Yes, I already switched to `Set` for key types like int. There are some HashSets left with case-insensitive string keys (e.g. filenames).

**Comment by StefanBertels** [comment]
Thank you for fast bug fixing!
