### ISSUE TITLE
Serializing Option<T>.None with Json.Net

### ISSUE THREAD

**Issue by eggapauli** [louthy/language-ext#191]
I am trying to serialize and deserialize an `Option<T>` with Json.Net.  
The following gives me an error:

    var serialized = JsonConvert.SerializeObject(Option<double>.None);
    // serialized == "\"\""
    var deserialized = JsonConvert.DeserializeObject<Option<double>>(serialized);
    // throws something about a cast not being valid

I don't know how good you know Json.Net, but maybe you can tell me why Json.Net serializes `Option<T>.None` to an empty string. Is it because of the `TypeConverterAttribute` on `Option`? Can I do anything about it (e.g. a custom `JsonConverter`)?

**Comment by louthy** [comment]
@eggapauli Unfortunately Json.net struggles with the immutable types in lang-ext.  There's a couple of options depending on your urgency:

1. Copy your object to a DTO type and make the types nullable
2. Write a `JsonConverter` as you mention
3. Wait for lang-ext v2.0 [where I've Implemented `ISerializable` for all of the core types](https://github.com/louthy/language-ext/blob/type-classes/LanguageExt.Core/DataTypes/Option/Option.cs#L822) to deal with Json.NET not 'getting it' (this could be a month away at the moment, but I'm hoping it will be earlier)

**Comment by eggapauli** [comment]
Wow, thanks for the fast response. Making it nullable seems like the best option for me at the moment.

**Comment by louthy** [comment]
@eggapauli 

For value types: `option.ToNullable()`
For reference types: `option.IfNoneUnsafe(null)`

**Comment by eggapauli** [comment]
Ahh that's great, I didn't know that there was any support for `Nullable`. Thanks.
