### ISSUE TITLE
Add Pure attributes in 2.0

### ISSUE THREAD

**Issue by StefanBertels** [louthy/language-ext#197]
When using e.g. EqStringOrdinalIgnoreCase.Inst.Equals(string, string) I get ReSharpers warning "Impure method is called for readonly field". I guess the solution is to mark all pure functions [Pure]. Since I'm still exploring those functional concepts like purity: is this correct?

Can/will you add [Pure] here?

BTW: Do you prefer pull requests for something like this (do you use code generation)?

**Comment by louthy** [comment]
@StefanBertels Hi Stefan, yeah sorry, some `Pure` attributes were missing from the newer types.  Get the latest and it should be resolved for you.
