### ISSUE TITLE
Process in 2.0 / combine with 2.0

### ISSUE THREAD

**Issue by StefanBertels** [louthy/language-ext#198]
I use some 2.0 core features and want to start using process system (just LanguageExt.Process, no ProcessJs/Redis).

Do you plan to continue LanguageExt.Process in 2.0?

If yes: will it be designed similar (especially actor registration)?

Can I combine Process 1.9 with Core 2.0 and start with Process now or should I wait / avoid Process 1.9?

**Comment by StefanBertels** [comment]
Oh, just seen: both library versions have the same Package ID, so I can't simply use both in the same project. I would have to build it on my own with another package name (maybe separate namepace).

I'm nevertheless interested in your suggestion.

**Comment by StefanBertels** [comment]
Note: Does not work out in practise by simple combining packages (not that I really expected it working...)

> An unhandled exception of type 'System.TypeLoadException' occurred in LanguageExt.Process.dll
> 
> Additional information: Could not load type 'LanguageExt.EnumerableExtensions' from assembly 'LanguageExt.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.

**Comment by louthy** [comment]
@StefanBertels Hi Stefan, I'm breaking the Process system out to its own repo (as well as getting it to work with NET Core).  So for the moment the only way to use the Process system is with 1.9.  I'm just looking into it now, I'll see if I can get an alpha release up quicker.

**Comment by louthy** [comment]
@StefanBertels The Process system has now been broken out to [github.com/louthy/echo-process](https://github.com/louthy/echo-process).  It's had very limited testing, so I wouldn't advise using it for anything that will need to be in production within the next month or so.
