### ISSUE TITLE
FlatMap for Monads

### ISSUE THREAD

**Issue by emiguelt** [louthy/language-ext#199]
Hi, I would like to concatenate to method call that returns Either, something like:
```
Either<A,B> getType(){..}
Either<A,C> getInstance(B type){...}

Either<A,C> getCurrentInstance()
{
  return getType().FlatMap(t => getInstance(t));   <--- FlatMap does not exist
}
```
I had to use the Prelude.match, 
```
Either<A,C> getCurrentInstance()
{
  return match (getType(),
      Right: t => getInstance(t),
      Left:  a => a);
}
```

but it seem strange, is there other way to do that?

Thanks in advance for your help!

Best, 
Miguel.

**Comment by louthy** [comment]
@emiguelt `FlatMap` is also known as `Bind`, and that's what it's called in language-ext:
```c#
    getType().Bind(t => getInstance(t));
```
You can also use LINQ:
```c#
    from t in getType<A, B>()
    from r in getInstance<A, B, C>(t)
    select r;
```

**Comment by emiguelt** [comment]
Thanks a lot @louthy! 
I'm a c# and functional programming learning.
