### ISSUE TITLE
Either and type inferencing issue

### ISSUE THREAD

**Issue by melston** [louthy/language-ext#207]
I'm using the language-ext library in C# and trying to get Tasks returning Either values to compose properly and having a tough time with the type inferencing. It just isn't working out the way I would expect.

There are three methods involved here:

- `Initialization`: Returns a `Task<Either<Exception, ADUser>>`
- `createUserMapping`: Takes an `ADUser` and returns an `Either<Exception, UserMapping>`
- `AddUser`: takes an `UserMapping` and returns a `Task<Either<Exception, int>>`

I would like to return the results of `AddUser`. It seems like a pretty simple application of Bind operations. Somehow, though, the types are just not lining up.

What I have now is this:

```c#
    return Initialization
        .Bind(ead => ead.Bind(createUserMapping).AsTask())
        .Bind(eum => eum.Bind(async u => await AddUser(u)));
```

In the first operation, the outer `Bind` takes the `Either` and calls the (nested) `Bind` which takes the `Right` value (an `ADUser`) and returns an `Either<Exception, UserMapping>` which is wrapped up in a `Task` (as a result of the call to `AsTask()`).  

Likewise, in the second case the outer `Bind` takes the `Either` and calls the (again, nested) `Bind` which takes the `Right` value (a `UserMapping`) and returns a `Task<Either<Exception, int>>`.

That is the theory, anyway.

However, while Intellisense is telling me that the `u` in the last async lambda is of type `UserMapping` (at the point of declaration), when it gets passed into the `AddUser` call I get the error:

    Argument 1: cannot convert from 'System.Exception' to 'UserMapping'

Why is the compiler getting confused as to the type of the parameter when it isn't confused about it at the start of the lambda? Is there a better way of doing this?

One thing that does work, but seems a bit of a hack to me, is to not call `AddUser` directly.  Instead I have a new local method, `addUser`: of type `Either<Exception, UserMapping> -> Task<Either<Exception, int>>`.  It is implemented like this:

```C#
    private async Task<Either<Exception, int>> addUser(Either<Exception, UserMapping> eu)
    {
        var nestedTask = eu.Map(u => uow.ControllerRepository.AddUser(u));

        var rv = nestedTask.Match(
            Right: t => identity(t),
            Left: e => Left<Exception, int>(e).AsTask());
        return await rv;
    }
```
Here, `nestedTask` is of type `Either<Exception, Task<Either<Exception, int>>>`. So I take that apart in the `Match`, returning just the `Right` value directly or the `Left` (Exception) wrapped appropriately - as a `Task<Either<Exception, int>>`. 

I also changed `createUserMapping` to take the `Either` instead of taking a `UserMapping`.

Now my top-level sequence of transformations looks like:

```C#
        return await Initialization
            .Bind(eadu => createUserMapping(eadu).AsTask())  // eadu: Either<Exception, ADUser>
            .Bind(eum => addUser(eum));                      // eum:  Either<Exception, UserMapping>
```

This makes my top-level code simpler and works as I expect it to but still leaves me confused as to why the original code just wouldn't work.

I know that C#'s type inferencing is limited compared to other languages but this has me baffled.  Why would the `u` parameter in the lambda be recognized correctly at the point of declaration but the point that it is used find it switched to another type?

**Comment by louthy** [comment]
@melston Hi Mark,  I haven't fully read through all of this yet.  But if you're mixing types then you will have a bad time, `Bind` explicitly works by binding with other monads of the same type.  So `Either<L, R>` will not work with `Task<Either<L, R>>`.  Also if you want to `Bind` nested monads (`Task<Either<L, R>>`) you will most probably want to use `BindT` which is the transformer version of `Bind` and will dive into the doubly nested type to extract the `R` value in `Task<Either<L, R>>`.

So if you want to make `Either<L, R>` work with `Task<Either<L, R>>` you should lift the `Either<L, R>` with `either.AsTask()`, or you must unwrap the `Either<L, R>` within the `Task<Either<L, R>>`.

Finally, what version are you using?

**Comment by louthy** [comment]
So I have created a test in the unit tests with the following, and it all resolves as you'd like (assuming you're using the `v2`):

```c#
        /// <summary>
        /// https://github.com/louthy/language-ext/issues/207
        /// </summary>
        public Task<Either<Exception, int>> Issue207()
        {
            return Initialization
                .BindT(createUserMapping)
                .BindT(AddUser);
        }

        static Task<Either<Exception, ADUser>> Initialization =>
            Task.FromResult(Right<Exception, ADUser>(ADUser.New("test user")));

        static Either<Exception, UserMapping> createUserMapping(ADUser user) =>
            Right<Exception, UserMapping>(UserMapping.New(user.ToString() + " mapped"));

        static Task<Either<Exception, int>> AddUser(UserMapping user) =>
            Task.FromResult(Right<Exception, int>(user.ToString().Length));
```

**Comment by louthy** [comment]
The reason why this works is because there are two `BindT` extension methods for every nested monad permutation.  And so for `Task<Either<L, R>>` theres:
```c#
public static Task<Either<L, B>> BindT<L, A, B>(this Task<Either<L, A>> ma, Func<A, Either<L, B>> f) =>
    Trans<MTask<Either<L, A>>, Task<Either<L, A>>, MEither<L, A>, Either<L, A>, A>
        .Inst.Bind<MTask<Either<L, B>>, Task<Either<L, B>>, MEither<L, B>, Either<L, B>, B>(ma, f);
``` 
And:
```c#
public static Task<Either<L, B>> BindT<L, A, B>(this Task<Either<L, A>> ma, Func<A, Task<Either<L, B>>> f) =>
    Trans<MTask<Either<L, A>>, Task<Either<L, A>>, MEither<L, A>, Either<L, A>, A>
        .Inst.Bind<MTask<Either<L, B>>, Task<Either<L, B>>, MEither<L, B>, Either<L, B>, B>(ma, f);
```
It may not be obvious from that, but if you look at the second argument `f` for each, they're `Func<A, Either<L, B>>` and `Func<A, Task<Either<L, B>>>`.  So the first one allows you to work exclusively within the inner monad (`Either<L, B>`), the second one allows you to return the outer monad (`Task<Either<L, B>>`).  And so if you want to work in the context of `Task<Either<L, B>>` then `BindT` gives you the maximum flexibility 

btw, there's also `MapT`, `FoldT`, `FoldBackT`, `ExistsT`, `ForAllT`, `IterT`, `FilterT`, `PlusT`, `SubtractT`, `ProductT`, `DivideT`, `AppendT`, `CompareT`, `EqualsT`, `ApplyT`, `SumT`. `CountT`, `Traverse`, and `Sequence`.  All of which allow you to work directly with the bound value of nested monads.

**Comment by melston** [comment]
There must be something different in what I am trying than what you are showing here because I tried `BindT` and got lots of complaints from the compiler.  I will have to check it out again.

**Comment by louthy** [comment]
@melston  What version of lang-ext are you running?

**Comment by melston** [comment]
I'm using 1.9.7.

**Comment by louthy** [comment]
Ok, I can't really support that version.  I would definitely recommend upgrading.  Even though it's beta officially, it's stable (I am mostly updating documentation before I do the release proper).  There were some issues with the transformer types which have been resolved with `v2`, so it's your best course of action.

Please be aware that there may be some breaking changes if you're heavily using the library.

https://github.com/louthy/language-ext/releases/tag/2.0.26-beta

**Comment by melston** [comment]
Ah.  Ok.  I just tried what you suggested and got the same kinds of errors I got before on the second BindT.  Specifically, it complains about the type arguments for method `TaskTMonadT.BindT...`.  When I try fixing these type argument (by explicitly specifying them) I then get other errors.

So, upgrading to the latest beta should fix this?

**Comment by melston** [comment]
OK.  That was easy.  Upgraded, built, and now no errors doing what I thought was the right thing all along (using BindT, which I could never get to work right).

**Comment by louthy** [comment]
Yep, `v1` doesn't have the dual `BindT` implementations.  It's a much more feature rich anyway, so it's worth doing it sooner rather than later.  It looks like you're doing a lot of async work and there's 3 new types explicitly to help there (`OptionAsync`, `TryAsync`, and `TryOptionAsync`).  If I find the time soon I'll also be adding `EitherAsync`.

You could probably still do this on `v1` (this is from memory, rather than guaranteed!):
```c#
    public Task<Either<Exception, int>> Issue207() =>
        Initialization
            .BindT(u => createUserMapping(u).AsTask())
            .BindT(addUser);
```

**Comment by melston** [comment]
Thanks.  I was getting errors on the second BindT so I abandoned that approach. :)  It works now, thanks.

**Comment by trbngr** [comment]
It seems that `Left` cases aren't working properly.

```


        public Task<Either<Exception, int>> Issue207_3() =>
            from us in Left<Exception, ADUser>(new Exception("fail")).AsTask()
            from mu in createUserMapping(us).AsTask()
            from id in addUser(mu)
            select id;

        public Task<Either<Exception, int>> Issue207_4() =>
            Left<Exception, ADUser>(new Exception("fail")).AsTask()
                .BindT(createUserMapping)
                .BindT(addUser);
```
both throw `LanguageExt.BottomException : Value is in a bottom state and therefore not valid.  This can happen when the value was filtered and the predicate returned false and there was no valid state the value could be in.  If you are going to use the type in a filter you should check if the IsBottom flag is set before use.  This can also happen if the struct wasn't initialised properly and then used.
`

**Comment by louthy** [comment]
@trbngr Not sure why you've posted this twice.  But the answer is the same:

The reason it reports a `BottomException` in those examples is because it's doing a _trasnformer_ bind operation, which is a generalised system for monadic binding on two nested monads (in this case `Task<Either<L, R>>`).  When the inner monad bind fails (which it will do because of the initial `Left` state), then so does the outer bind operation.  The outer monad (`Task<...>`) isn't aware of the `Left` type being `Exception` so all it can do is fail with `BottomException` because the `Task` is now in a failed state. 

So essentially you're getting a general failure response from the `Task`.

**Comment by trbngr** [comment]
Sorry. I moved this comment to the correct issue. 

I'm trying to acheive a fail-fast scenario, where the first `Left` will short-circuit the program.

So `Issue207_3()` should return a `Task<Left<Exception>>` and not throw

**Comment by louthy** [comment]
@trbngr You may want to use `Try<A>` and `TryAsync<A>` it captures exceptions and removes the need for nesting monads.  You can create methods that return `Try<A>` and easily make them asynchronous by calling `ToAsync()` or calling any of the `Async` variant functions like `MatchAsync`, `MapAsync`, etc.
```c#
    static Try<int> addUser2(UserMapping user) => () =>
        user.ToString().Length;

    static Try<UserMapping> createUserMapping2(ADUser user) => () =>
        UserMapping.New(user.ToString() + " mapped");

    public TryAsync<int> Issue207_5() =>
        from us in TryAsync<ADUser>(() => throw new Exception("fail"))
        from mu in createUserMapping2(us).ToAsync()
        from id in addUser2(mu).ToAsync()
        select id;

    public async Task<int> Test2()
    {
        return await Issue207_5().Match(
            Succ: value => value,
            Fail: excep => 0);
    }
```
You can use the various conversion functions if you want to use it with `Either` in other places:
```c#
    Issue207_5().ToEither();    // Task<Either<Exception, int>>
```

**Comment by trbngr** [comment]
I figured as much after racking my brain a bit. ;)

Thanks for your help.......and awesome library. It's making C# fun again.

**Comment by louthy** [comment]
@trbngr No problem.  You can definitely think of `Try<A>` as a friendlier `Either<Exception, A>` and `TryAsync<A>` as a friendlier `Task<Either<Exception, A>>`.  

There's also `TryOption<A>` which is basically: `Either<Exception, Option<A>>` and `TryOptionAsync<A>` which is `Task<Either<Exception, Option<A>>>`
