### ISSUE TITLE
Implicit conversion of Some / Option in F# Code

### ISSUE THREAD

**Issue by donners77** [louthy/language-ext#21]
Hi.

I've started writing some unit tests in F# for my C# code which uses the language-ext Some and Option structs.

Ironically, the tests in F# are often more verbose than the equivalent in C# because the F# compiler seems to insist I explicitly wrap values with Some or Option rather than implicitly converting them.

e.g. in C# I can call Foo's constructor by ``new Foo(bar)`` where-as in F# I seem to have to write ``new Foo(new Some<IBar>(bar))``

Is there any way around this?

**Comment by louthy** [comment]
F# doesn't have implicit conversion, but you can provide your own operator to do the job:

```F#
open System
open LanguageExt

let inline (!>) (x:^a) : ^b = ((^a or ^b) : (static member op_Implicit : ^a -> ^b) x)

let test (a : int Some) = 
    Console.WriteLine a
    (int)a

let addTest1 (a : int Some) (b : int Some) = 
    (int)a + (int)b

let addTest2 (a : int Some) (b : int Some) = 
    a.Value + b.Value

[<EntryPoint>]
let main argv = 
    let a = test !> 100
    let b = addTest1 (!> 2) (!> 2)
    let c = addTest1 (!> 2) (!> 2)
    0
```

**Comment by donners77** [comment]
Fantastic!
Thanks.
