### ISSUE TITLE
Is it possible to implement parseEnum?

### ISSUE THREAD

**Issue by solvingJ** [louthy/language-ext#210]
I think this is an easy question.  Enum.TryParse<>() is similar to the other TryParse methods that you've provided alternatives to (for example, parseInt())  I noticed Enum.TryParse was not listed on the main page and thought there might be a fundamental reason why it's not possible to do. I have seen several issues with the way Enum is implemented in C#.

**Comment by louthy** [comment]
@solvingJ No fundamental reason. It just didn't occur to me.  I'm just packing for my vacation, so feel free to submit a pull request and I'll review as soon as I can.

**Comment by jeremysmith1** [comment]
Ran into some issues with Enum, but I think my solution will work. Set up a pull request here [https://github.com/louthy/language-ext/pull/211](url)

**Comment by solvingJ** [comment]
Wow, awesome... link is bad but the PR looks nice.
