### ISSUE TITLE
Cant add library to a UWP/Xamarin application.

### ISSUE THREAD

**Issue by kthompson** [louthy/language-ext#213]
I get this error when attempting to add this library(LanguageExt.Core) to a UWP application:

`System.Reflection.Emit.Lightweight 4.3.0 provides a compile-time reference assembly for System.Reflection.Emit.Lightweight on UAP,Version=v10.0, but there is no run-time assembly compatible with win10-arm-aot.
System.Reflection.Emit.ILGeneration 4.3.0 provides a compile-time reference assembly for System.Reflection.Emit.ILGeneration on UAP,Version=v10.0, but there is no run-time assembly compatible with win10-arm-aot.
One or more packages are incompatible with UAP,Version=v10.0 (win10-arm-aot).
System.Reflection.Emit.Lightweight 4.3.0 provides a compile-time reference assembly for System.Reflection.Emit.Lightweight on UAP,Version=v10.0, but there is no run-time assembly compatible with win10-x64-aot.
System.Reflection.Emit.ILGeneration 4.3.0 provides a compile-time reference assembly for System.Reflection.Emit.ILGeneration on UAP,Version=v10.0, but there is no run-time assembly compatible with win10-x64-aot.
One or more packages are incompatible with UAP,Version=v10.0 (win10-x64-aot).
System.Reflection.Emit.Lightweight 4.3.0 provides a compile-time reference assembly for System.Reflection.Emit.Lightweight on UAP,Version=v10.0, but there is no run-time assembly compatible with win10-x86-aot.
System.Reflection.Emit.ILGeneration 4.3.0 provides a compile-time reference assembly for System.Reflection.Emit.ILGeneration on UAP,Version=v10.0, but there is no run-time assembly compatible with win10-x86-aot.
One or more packages are incompatible with UAP,Version=v10.0 (win10-x86-aot).`

Is there any way to work around this?

I also tried creating a brand new Xamarin Forms app in VS2017 and then adding the LanguageExt.Core but it fails with the above message.

**Comment by louthy** [comment]
@kthompson hi Kevin, I see you closed this, sorry for the lack of reply I'm in holiday atm.  What was your resolution?

**Comment by kthompson** [comment]
I had accidentally closed this issue when making a comment. I have not been able to resolve the issue.

**Comment by louthy** [comment]
@kthompson Hi Kevin, sorry for the slow response, been away on holiday.  I am not sure why this won't work, but it seems others have similar problems.  [This appears to be a work-around](https://github.com/seesharper/LightInject/issues/305#issuecomment-244732626), could you try that?

**Comment by kthompson** [comment]
I will look into that.
