### ISSUE TITLE
int.gethashcode

### ISSUE THREAD

**Issue by jmagaram** [louthy/language-ext#217]
In `EqInt` the hash code of an int should be exactly that int. I think this is wrong...

    public int GetHashCode(int x) => x.GetHashCode();

Should be...

    public int GetHashCode(int x) => x;

**Comment by orthoxerox** [comment]
`int.GetHashCode()` [returns itself](https://referencesource.microsoft.com/#mscorlib/system/int32.cs,86).

**Comment by louthy** [comment]
@orthoxerox Is correct, the behaviour is correct, and if it ever changes for `int` then the code will continue to work.
