### ISSUE TITLE
Recommendation on types that aren't constrained

### ISSUE THREAD

**Issue by jmagaram** [louthy/language-ext#218]
I've made a bunch of domain-specific types like Name, City, Email, etc. Do you recommend I do the same with types that are not constrained at all like `bool IsAlive` and `int Priority`? The benefit I suppose is that all my types will have real-world names and I'll be less dependent on parameter names...

    public class IsAlive : NewType<IsAlive, bool> { public IsAlive(bool value) : base(value) { } }
    public class Priority : NewType<Priority, int> { public Priority(int value) : base(value) { } }

Or should I just use ints and bools for these things?

Updated - I just read some more about this issue. The IsAlive example is a bad idea if I ever wanted to compare that bool to others, like finding people where IsAlive && IsWealthy, whereas it is unlikely I'd ever do math comparing Priority to some other numerics.

**Comment by louthy** [comment]
New-types are definitely not just for constraints, so yes I would.  New-types give not just range constraints but also type constraints where an `int != Priority`, or an `string != Email`, etc.  So it removes a whole class of common errors where _'untyped'_ integers floating around could end up being assigned to the wrong thing.

**Comment by jmagaram** [comment]
Interesting. If you defined custom types for every real-world concept and banished int, string, bool, programs in C# would look quite different than all the example code you see.
