### ISSUE TITLE
Bumping up a level to composite classes, what to do?

### ISSUE THREAD

**Issue by jmagaram** [louthy/language-ext#219]
Ok so I've made a bunch of tiny types like PersonId, Email, Age using the NewType feature. I'm not sure what I'm supposed to do to now create a composite object. It seems like NewType is for primitives not composites. I want my composite object to properly handle all the equality flavors. If I build an `EqPerson : Eq<Person>` I supposed I can use the logic there as the basis for implementing Equals, Equatable, == like I usually would without your library? Is there anything else I'm supposed to do to make my composite object? Any guidance here would be greatly appreciated, and probably useful to others.

    public class PersonID : NewType<PersonID, Guid> { public PersonID(Guid value) : base(value) { } }
    public class Age : NewType<Age, int> { public Age(int value) : base(value) { } }
    public class Email : NewType<Email, string> { public Email(string value) : base(value) { } }

    public class Person : IEquatable<Person>, etc.
    {
        static EqPerson _eq = default(EqPerson); // define this and use it to help build ==, !=, etc.?

        public Person(PersonID id, Age age, Email email)
        {
            Id = id;
            Age = age;
            Email = email;
        }

        public PersonID Id { get; }
        public Age Age { get; }
        public Email Email { get; }
    }

    // Am I supposed to define this? Any others?
    public struct EqPerson : Eq<Person>
    {
        public bool Equals(Person x, Person y)
        {
            if (ReferenceEquals(x, y)) return true; // must i check for null?
            if (ReferenceEquals(x, null) ^ ReferenceEquals(y, null)) return false;
            if (x.GetType() != y.GetType()) return false;
            return x.Id == y.Id && x.Age == y.Age && x.Email == y.Email;
        }

        public int GetHashCode(Person x) => ReferenceEquals(x, null) ? -1 : x.Id.GetHashCode();
    }

Updated - I looked at the source code for your collection classes. Looks like you manually implement the Equals, Equatable, GetHashCode, ==, != etc. in these. I did the same. I did build an EqPerson class and used a default(EqPerson) instance of it in my code. Not sure if this was the right thing to do. I suppose if I want my composite classes IEnumerable etc. I'll have to build that manually too - though not much code. So it looks like the NewType thing is mostly for wrapping small types.

**Comment by louthy** [comment]
As you thought the new-types are for primitive types. The idea is that they hold a single piece of data, and can be constructed with a constructor that takes a single value.  It's not really possible to take that further and implement a 'record' type which would be a composite (well, it may be possible with some inline IL generation, but it would require a reasonable amount of typing by anyone using it, making it less than easy to consume).

By defining `EqPerson` which derives from `Eq<Person>` you're creating a _class instance_ of the `Eq` _type-class_.  What that means is that you can call the `TypeClass.equals` function to compare your `Person` values:
```c#
    using static LanguageExt.TypeClass;

    bool areEqual = equals<EqPerson, Person>(personA, personB);
```
Or use them in any generic function that has a constraint of `Eq<A>`.  This comes into its own with the other types in this library like `Option`, `Lst` etc.  where there are `equals` overrides that allow you to do structural comparisons of `Option<Person>` or `Lst<Person>` (for example).  It is a more explicit way of doing equality which causes compile time errors if you haven't got a class-instance for the type you want to compare.  It removes the need for types like `Option`, `Lst`, `Map`, etc. from having to rely on `EqualityComparer<A>.Default` which won't report at compile-time if your type can't be compared.

It won't (as you suspected) implement the `==` or `!=` operators, or `Equals`, or implement `IEquatable`, you still need to do that (if you want to use those features); but yes, you can implement them using your `EqPerson` class-instance.

```c#
    public bool Equals(Person x, Person y)
    {
        if (ReferenceEquals(x, y)) return true; // must i check for null?
        if (ReferenceEquals(x, null) ^ ReferenceEquals(y, null)) return false;
        if (x.GetType() != y.GetType()) return false;
        return x.Id == y.Id && x.Age == y.Age && x.Email == y.Email;
    }
```
Yes you should still check for `null`.  Again there's no magic here, it's just a different approach which uses the idea of type-classes and instances.  You don't need to check the types with `GetType()`, that is enforced by the compiler.

You don't _need_ to use the type-class system to use the standard systems for equality in .NET.  It depends how deep into the type-class idea you want to go.

**Comment by jmagaram** [comment]
> Yes you should still check for null.

I was thinking that wherever your code makes use of a Eq<T> it could handle the "are both null?" => true, "is just one true?" => false situations generically, before getting to my type-specific code, so my code wouldn't need to worry about it. But I agree that if I'm using a Eq<Person> "manually", then it is safer if it handles all the situations.

> You don't need to check the types with GetType(), that is enforced by the compiler.

I'm not totally sure about this. I was thinking about the case where one type is a sub-type of the other.

**Comment by louthy** [comment]
> I was thinking that wherever your code makes use of a Eq it could handle the "are both null?" => true, "is just one true?" => false situations generically, before getting to my type-specific code, so my code wouldn't need to worry about it. 

That's not possible, because generic functions that expect values that are constrained by the `Eq<A>` type-class call it like so:
```c#
    static bool IsEqualTest<EqA, A>(A x, A y) where EqA : struct, Eq<A> => 
        default(EqA).Equals(x, y);
```
There's no way of enforcing that `A` is not `null` in all uses of the `Eq<A>` instance.

> I'm not totally sure about this. I was thinking about the case where one type is a sub-type of the other.

Ok, fair enough.  I'm so far away from using inheritance for most things these days that it didn't cross my mind.
