### ISSUE TITLE
bug in option comparison operators?

### ISSUE THREAD

**Issue by jmagaram** [louthy/language-ext#220]
exact same code for less than and greater than operators in https://github.com/louthy/language-ext/blob/master/LanguageExt.Core/DataTypes/Option/Option.cs

    public static bool operator <(Option<A> lhs, Option<A> rhs) => compare<OrdDefault<A>,A>(lhs, rhs) < 0;
    public static bool operator >(Option<A> lhs, Option<A> rhs) => compare<OrdDefault<A>,A>(lhs, rhs) < 0;

needle in a haystack.

**Comment by jmagaram** [comment]
same with Either <= and >=
I must be not understanding something

**Comment by louthy** [comment]
Yep, bug.  Fixed in v2.0.61
