### ISSUE TITLE
type class cumbersome, strange

### ISSUE THREAD

**Issue by jmagaram** [louthy/language-ext#222]
I'm getting my head around the type classes and some of it is weird and wonderful compared to idiomatic c#. If you want to make a predicate for use in `NewType` restricting a number to >=5 and <=50 you can do something like this...

    All<GreaterThan<Int,OrdInt,ConstInt5>,LessThan<Int,OrdInt,ConstInt50>>>

It is cool you can do that declaratively. But...

(a) It is very very very verbose especially when you add in all the type constraints. I suppose it is useful to be able to look at the type name and know exactly what you're getting.

(b) It only works when you write a zillion little building-block structs like ConstInt50. Or when you hardwire ForAll to take 2-6 parameters. But if you want the number 23,434 or 12 ForAll parameters you are out of luck. There are some cases where you must write code like a string predicate that uses regular expressions. I'm trying to see the advantage of your approach versus writing a bit of code where there are no artificial restrictions. I could create a new struct like this instead...

    struct WeirdPred : IPred<int> {
        bool IsValid(int i) => i%2==0 && i<-14000 || i>23343;
    }

Or there could be a `virtual bool IsValid`inside NewType where I put my custom validation logic. It seems like this composability approach is kind of fighting the language. It's so much more natural to write a little formula `i>=3 && i<54` and inject it somewhere. I wonder whether there is some limitation in C# that makes this awkward and whether it is less cumbersome or even natural in certain functional languages. I am somewhat familiar with F#.

(c) You can't simplify the type signatures without a lot of duplication. For example, maybe you'd like a "base" `Pred<T,OrdT>` and then have a derived one like `Pred<T> : Pred<T,OrdDefaultT>` but I don't think that is possible. Could you use classes with a new() constraint instead? Seems like if the compiler noticed that the classes had no fields it could treat them like structs.

**Comment by louthy** [comment]
Yes they're cumbersome to use, it's not an ideal situation at all.  But it's there if you want a more declarative approach.  If you don't want to use it, just put your validation in the constructor and don't supply a `PRED` argument.

**Comment by louthy** [comment]
By the way, you can do your first example using `Range`:
```c#
    Range<TInt, int, I5, I50>
```
