### ISSUE TITLE
Identity with Action

### ISSUE THREAD

**Issue by gregberns** [louthy/language-ext#228]
First, thanks for this awesome library. I just started using it on a new project with fantastic results.

I'm looking for a function that's basically identity plus an Action, so it accepts A and an Action<A> and returns an A. This could be used for something like logging. 

```
A -> Action<A> -> A
```

I haven't been able to find a function with this signature.
This is kind of like Iter, but Iter returns Unit. I think I've seen this elsewhere called `Do`.

It could be used to do something like this:

```
list.Map(i => DoSomething(i)) 
     .Do(list => Log(list))
     .Map(j => DoSomethingElse(j))
```

Is there a function that already does this? Or do I need to create an extension?

**Comment by louthy** [comment]
@gregberns 

>First, thanks for this awesome library. I just started using it on a new project with fantastic results.

Great to hear :)

> I'm looking for a function that's basically identity plus an Action, so it accepts A and an Action and returns an A. This could be used for something like logging.

Unfortunately not.  I've kind of resisted it because it goes against the core concepts of functional programming (where we should avoid side-effects).  

Obviously to provide your own extension method for each type would be relatively easy.  I think for `IEnumerable` based types you'd want something like this that is lazy and therefore streams the values through rather than `Do` taking a the outer value:
```c#
    public static class DoExtensions
    {
        public static IEnumerable<A> Do<A>(this IEnumerable<A> self, Action<A> f)
        {
            foreach (var item in self)
            {
                f(item);
                yield return item;
            }
        }
    }
```
Then you could do:
```c#
    list.Map(i => DoSomething(i)) 
         .Do(j => Log(j))
         .Map(k => DoSomethingElse(k))
```
Or more succinctly :)
```c#
    list.Map(DoSomething)
        .Do(Log)
        .Map(DoSomethingElse);
```

Now you could go all in and create a `Writer` monad that works with lists:
```c#
    public delegate (Lst<A> Seq, W Output) WriterSeq<MonoidW, W, A>();

    public static class PreludeExt
    {
        static readonly Lst<Unit> OneUnit = List(unit);

        public static WriterSeq<MonoidW, W, A> WriterSeq<MonoidW, W, A>(Lst<A> seq)
            where MonoidW : struct, Monoid<W> => () =>
            (seq, default(MonoidW).Empty());

        public static WriterSeq<MonoidW, W, Unit> tellSeq<MonoidW, W>(W what)
            where MonoidW : struct, Monoid<W> => () =>
            (OneUnit, what);
    }

    public static class WriterSeqExtensions
    {
        public static WriterSeq<MonoidW, W, B> Map<MonoidW, W, A, B>(
            this WriterSeq<MonoidW, W, A> self, 
            Func<A, B> map)
                where MonoidW : struct, Monoid<W> =>
                    Select(self, map);

        public static WriterSeq<MonoidW, W, B> Select<MonoidW, W, A, B>(
            this WriterSeq<MonoidW, W, A> self, 
            Func<A, B> map) 
                where MonoidW : struct, Monoid<W> => () =>
        {
            var (seqA, output) = self();
            var seqB = List<B>();
            foreach (var a in seqA)
            {
                seqB = seqB.Add(map(a));
            }
            return (seqB, output);
        };

        public static WriterSeq<MonoidW, W, C> SelectMany<MonoidW, W, A, B, C>(
            this WriterSeq<MonoidW, W, A> self, 
            Func<A, WriterSeq<MonoidW, W, B>> bind,
            Func<A, B, C> project)
            where MonoidW : struct, Monoid<W> => () =>
        {
            var (seqA, output) = self();

            var seqC = List<C>();

            foreach (var a in seqA)
            {
                var mseqB = bind(a);
                var (seqB, outputB) = mseqB();
                output = default(MonoidW).Append(output, outputB);

                foreach (var b in seqB)
                {
                    seqC = seqC.Add(project(a, b));
                }
            }
            return (seqC, output);
        };
    }
```
That allows logging to be captured as part of the monadic expression rather than as a side-effect:
```c#
var list = List(1, 2, 3);

var comp =  from num  in WriterSeq<MLst<string>, Lst<string>, int>(list)
            from _    in tellSeq<MLst<string>, Lst<string>>(List($"Number: {num}"))
            let  num2 = TimesTwo(num)
            from __   in tellSeq<MLst<string>, Lst<string>>(List($"Number x 2: {num2}"))
            let  pls1 = PlusOne(num2)
            from ___  in tellSeq<MLst<string>, Lst<string>>(List($"Number x 2 + 1: {pls1}"))
            select pls1;
```
Now that's not super attractive, so you could create helper functions that cover your common use cases:
```c#
        public static WriterSeq<MLst<string>, Lst<string>, A> with<A>(Lst<A> list) =>
            WriterSeq<MLst<string>, Lst<string>, A>(list);

        public static WriterSeq<MLst<string>, Lst<string>, Unit> log(string message) =>
            tellSeq<MLst<string>, Lst<string>>(List(message));
```
Then it starts to look a bit more attractive.
```c#
var comp = from num  in with(list)
           from _    in log($"Number: {num}")
           let  num2 = TimesTwo(num)
           from __   in log($"Number x 2: {num2}")
           let  pls1 = PlusOne(num2)
           from ___  in log($"Number x 2 + 1: {pls1}")
           select pls1;
```
You can then just invoke the `comp` delegate:
```c#
    var (seq, output) = comp();

    Console.WriteLine("Values");
    foreach(var item in seq)
    {
        Console.WriteLine(item);
    }

    Console.WriteLine("Log");
    foreach (var item in output)
    {
        Console.WriteLine(item);
    }
```
And your results and logging are returned. 

That may be overkill for what you want.  But I guess it depends how seriously you want to take the pure/referentially transparent approach.

**Comment by NickDarvey** [comment]
Whoa, this is great @louthy. Is this how you use `Writer` for logging?

**Comment by gregberns** [comment]
@louthy thats awesome. I'm not sure I'm totally ready for monads yet, I'll definitely need to study that one a bit. The Do extension will do just fine for now. I was definitely thinking of implementing with a list, just figured I'd keep the question simple.

Thanks again for the great library, I've been working on understanding functional for 2-3 years now and this really helps me start exploring the next level of FP when I'm in C#. Thanks!!

**Comment by solvingJ** [comment]
Indeed, logging is an extremely common need, so I'm curious how other projects using this library achieve logging if there's no simple and built-in: 
`A -> Action<A> -> A`
