### ISSUE TITLE
Suggestion: Mark documentation/examples issues

### ISSUE THREAD

**Issue by feugen24** [louthy/language-ext#232]
There a lots of interesting discussions in the issues that help more than the documentation, but in order to get to them you need to filter through closed issues (and they are hidden by default)

@louthy You are spending lots of time explaining various scenarios/situations but it mostly helps the person who added the issue.

For example: [https://github.com/louthy/language-ext/issues/231](231) or [https://github.com/louthy/language-ext/issues/209](209)

An concrete explanation that was useful for me was:

> Option<string> value = GetValue(true).Map(name => $"Hello, {name}");
> So instead of jumping back out to the string, you stay in the Option<string> context. You can maintain this for as long as necessary by doing subsequent calls to Map....

It would be helpful to label these issues as documentation/examples since others would want to read them after the issue is closed, and maybe add a link to documentation issues in the documentation page.

**Comment by louthy** [comment]
@feugen24 Great idea!  Now to triage...

**Comment by louthy** [comment]
@feugen24  All issues have now been triaged.  I have also added [a link to the issues](https://github.com/louthy/language-ext/issues?q=is%3Aissue+label%3A%22examples+%2F+documentation%22+is%3Aclosed) on the home page and wiki

**Comment by feugen24** [comment]
@louthy It looks great. Also maybe it would help if the link would sort by 'thumbs up' by default, and you could be explicit in the docs that people can vote on these documentation issues, something like "Remember to vote on helpful items"
