### ISSUE TITLE
Small Issue With Importing "LanguageExt.Trans"

### ISSUE THREAD

**Issue by JHaugh4** [louthy/language-ext#234]
I just downloaded this package today using Nuget and started testing things out. When I got to the section on monad transformers I am getting some strange errors that lead me to believe some small detail is wrong in my setup. The problem arises when I try to put "using LanguageExt.Trans;" into my code as you do in the example. When I do this I get two errors one under "LanguageExt" and one under "Trans". The one under "LanguageExt" is as follows, " Syntax error, '(' expected". The "Trans" error is as follows, "Using the generic type 'Trans<OuterMonad, OuterType, InnerMonad, InnerType, A>' requires 5 type arguments. I have tried several things such as moving the using statement to the top of the file and trying to declare the types explicitly but nothing has worked. If you need anymore details please let me know and I will be happy to provide them. Thank you in advance for any help that you can provide and great work with this package I think I will be able to get a lot out of it.

**Comment by louthy** [comment]
Sorry, that is an old example.  The transformer functions don't need an extra `using` any more. It should be:

```c#
    using LanguageExt;
    using static LanguageExt.Prelude;
    using LanguageExt.ClassInstances; // Required for TInt on Sum (see ad-hoc polymorphism)

    var list = List(Some(1), None, Some(2), None, Some(3));

    var presum = list.SumT<TInt, int>();                                // 6

    list = list.MapT(x => x * 2);

    var postsum = list.SumT<TInt, int>();
```
 However the example  does need an extra `using` for use of `TInt` which allows `SumT` (and `Sum`) to work with any `struct` type that implements `Num<A>`

**Comment by JHaugh4** [comment]
Awesome! Thank you for the quick response I look forward to using this.
