### ISSUE TITLE
Invert boolean predicate

### ISSUE THREAD

**Issue by StefanBertels** [louthy/language-ext#235]
Didn't find something to invert a function returning bool, maybe this is useful for this lib -- or was there any reason not to add this (you already have a `not `function working on bool directly):
```
      static Func<A, bool> not<A>(Func<A, bool> f) => x => !f(x);
      static Func<A, B, bool> not<A, B>(Func<A, B, bool> f) => (x, y) => !f(x, y);
      static Func<A, B, C, bool> not<A, B, C>(Func<A, B, C, bool> f) => (x, y, z) => !f(x, y, z);
```

Use case for me was inverting a predicate to use it with Filter:  ` bla.Filter(not(pred))`....

**Comment by louthy** [comment]
@StefanBertels Added to `v2.0.70` on nu-get now.

Thanks for the suggestion :)
