### ISSUE TITLE
Partial application with EqStringOrdinalIgnoreCase.Inst.Equals 

### ISSUE THREAD

**Issue by StefanBertels** [louthy/language-ext#237]
Is there a shortcut for avoiding x with `...Find(x => EqStringOrdinalIgnoreCase.Inst.Equals(x, "abc"))`?

Is there some option to use partial application similar to giving `"abc".Equals` as parameter to Find?

Maybe add some `Func<T, bool> EqualTo(T arg1)` to EqStringOrdinalIgnoreCase.Inst?

**Comment by louthy** [comment]
@StefanBertels 

You could partially apply the `equals` function in `static LanguageExt.TypeClass`:
```c#
    var eq = par<string, string, bool>(equals<EqStringOrdinalIgnoreCase, string>, "abc");
```
Then your `Find` would be:
```c#
    ...Find(eq);
```
But remember `EqStringOrdinalIgnoreCase.Inst` is just a `static` value, so you can also do:
```c#
    var eq = EqStringOrdinalIgnoreCase.Inst;  
```
Or,
```c#
    var eq = default(EqStringOrdinalIgnoreCase);
```
And then your `Find` would be:
```c#
    ...Find(x => eq.Equals(x, "abc"));
```

**Comment by StefanBertels** [comment]
Thank you.
