### ISSUE TITLE
Chain of Option.IfNone calls

### ISSUE THREAD

**Issue by alex-fomin** [louthy/language-ext#241]
Consider the following example. I have a chain of functions that returns `Option<T>`, I want to get a first not-none value from a list of functions. Something like:

```
// f1 .. fN is Func<Option<T>>
var some = f1().IfNone(()=>f2()).IfNone(()=>f3());
```
`IfNone` now does not support overload `Option<T> IfNone<T>(Func<Option<T>> ifNone)`, so how can I achieve this behavior?

**Comment by louthy** [comment]
```c#
    var some = f1 || f2 || f3;
```

**Comment by louthy** [comment]
@alex-fomin You can also put in a default at the end of the chain.  For example let's say it was `Option<int>` you were working with:
```c#
var result = f1() || f2() || f3() || 100;
```
The `100` will be implicitly converted to `Some(100)`.
