### ISSUE TITLE
Zip Two Dictionaries/Maps Together

### ISSUE THREAD

**Issue by gregberns** [louthy/language-ext#243]
I have two maps/dictionaries that I'd like to combine into a single list by the keys in each map.

I've heard of the [ZipWith function in Rambda](http://ramdajs.com/docs/#zipWith), but that seems to be with lists, not maps.

Seems like ZipWith would just use the index as the way to merge the lists together, and using the key should be just as usable???

Any thoughts on how to do this merge function? Seems like theres a more functional way of accomplishing this.

```
return listOfKeys.Map(k => {
    //The map1 and map2 'key' is the same datatype as 'k' (and is an object)
    //It is possible for map1 or map2 to be missing a key
    Either<Error, DataType1> dt1 = map1.Find(k).IfNone(new Error("not found"))
    Either<Error, DataType2> dt2 = map2.Find(k).IfNone(new Error("not found"))

    // The return object will be the combination of key, dt1 and dt2.
    // Will need to do some work to mash the Either's together, and pass errors back if they occur
    return new OutDataType();
})
```

Thanks again for the great project. I've been building a whole project with it. It forces so much more rigor than usual, which is indicative of the easy/'sloppy' way C# lets you think. Its a great challenge.
And the [RabbitMQ guys said to give hugs to your maintainers.](https://changelog.com/podcast/258), So here's your hug :)

**Comment by louthy** [comment]
@gregberns 

The hug has worked.  `v2.0.91` on nu-get.  `Map` now has:
* `Union` - All items from both maps are kept in the result, keys that are in both are merged using the merge function you provide.
* `Intersect` - Only items that are in both maps are kept in the result, all results are merged used the function you provide
* `Except` (difference) - Items from the second map are removed from the first which becomes the result
* `SymmetricExcept` - Only Items that are in one map or the other are kept in the results

You can call them fluently or functionally.  The functional versions are below.

```c#
[Fact]
public void MapUnionTest1()
{
    var x = Map((1, 1), (2, 2), (3, 3));
    var y = Map((1, 1), (2, 2), (3, 3));

    var z = union(x, y, (k, l, r) => l + r);

    Assert.True(z == Map((1, 2), (2, 4), (3, 6)));
}

[Fact]
public void MapUnionTest2()
{
    var x = Map((1, 1), (2, 2), (3, 3));
    var y = Map((4, 4), (5, 5), (6, 6));

    var z = union(x, y, (k, l, r) => l + r);

    Assert.True(z == Map((1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)));
}

[Fact]
public void MapIntesectTest1()
{
    var x = Map(        (2, 2), (3, 3));
    var y = Map((1, 1), (2, 2)        );

    var z = intersect(x, y, (k, l, r) => l + r);

    Assert.True(z == Map((2, 4)));
}

[Fact]
public void MapExceptTest()
{
    var x = Map((1, 1), (2, 2), (3, 3));
    var y = Map((1, 1));

    var z = except(x, y);

    Assert.True(z == Map((2, 2), (3, 3)));
}

[Fact]
public void MapSymmetricExceptTest()
{
    var x = Map((1, 1), (2, 2), (3, 3));
    var y = Map((1, 1),         (3, 3));

    var z = symmetricExcept(x, y);

    Assert.True(z == Map((2, 2)));
}
```

**Comment by gregberns** [comment]
Dang Paul, not sure how you do it...

With Union, do the types have to match?  Looks like the merge signature takes two of the same type and returns that same type.

```
//Map class
public Map<K, V> Union(Map<K, V> other, Func<K, V, V, V> merge);
```

Can you take two different types into merge and return a third? Is this valid for union??

```
//Map class
public Map<K, X> Union(Map<K, W> other, Func<K, V, W, X> merge);

//or 'union' (this could be slightly off)
public Map<K, X> union(Map<K, V> first, Map<K, W> other, Func<K, V, W, X> merge);
```

Like with map (the function), you go from a -> b. With union can we a -> b -> c?

The case I was looking at I think can be summed up like this:

```
var x = Map<K, J>
var y = Map<K, L>
//with output of
Map<K, M> z = union(x, y, (k, j, l) => new M( j, l))

//Or a more concrete implementation/example
var names = Map<Id, Name>
var ages = Map<Id, Age>
Map<Id, Person> z =  union(names, ages, (k, name, age) => new Person(name, age)
```

I'm not sure if this is even valid for Union? Not familiar enough with the real definition of union.

**Comment by louthy** [comment]
@gregberns 

> With Union, do the types have to match? Looks like the merge signature takes two of the same type and returns that same type.

Currently they must be the same types yes.  I've already started on a version that supports two types for the values, it needs an additional map function for when there isn't a merge, and two map functions when the result value isn't the same as the two input values.  Just ran out of time this evening to complete it. I figured a first pass my be helpful.

The final goal will be to implement a similar system to Haskell's Map merge, which allows for injection of various strategies for missing values and merging.

https://hackage.haskell.org/package/containers-0.5.9.2/docs/Data-Map-Merge-Strict.html

**Comment by gregberns** [comment]
Yea I was looking at the code and it looked like the types had to match up, and like the Haskell doc talks about the signature will have to change to handle the missing cases.
In any case, I can get by without. Thanks for the help.

**Comment by louthy** [comment]
@gregberns `v2.0.92` has:
```c#
Map<K, V> union<K, V>(Map<K, V> left, Map<K, V> right, WhenMatched<K, V, V, V> Merge)
Map<K, A> union<K, A, B>(Map<K, A> left, Map<K, B> right, WhenMissing<K, B, A> MapRight, WhenMatched<K, A, B, A> Merge)
Map<K, B> union<K, A, B>(Map<K, A> left, Map<K, B> right, WhenMissing<K, A, B> MapLeft, WhenMatched<K, A, B, B> Merge)
Map<K, C> union<K, A, B, C>(Map<K, A> left, Map<K, B> right, WhenMissing<K, A, C> MapLeft, WhenMissing<K, B, C> MapRight, WhenMatched<K, A, B, C> Merge)
```
And `intersect` has been _upgraded_ to allow different types for the values and return value:
```c#
Map<K, R> intersect<K, A, B, R>(Map<K, A> left, Map<K, B> right, WhenMatched<K, A, B, R> merge)
```
I haven't gone the whole hog like the Haskell version, but I will when I have more time.

**Comment by gregberns** [comment]
That worked like a charm. Just had to implement IComparable. That really helped simplify the code as well. Thanks for the help.
