### ISSUE TITLE
Convert IEnumerable<KeyValuePair> to Map

### ISSUE THREAD

**Issue by gregberns** [louthy/language-ext#246]
I have an IEnumerable of KeyValuePairs that I'd like to convert into a Map (so I can use Union). I don't see any extension methods that allow this or examples that do this. I have a function that does this, but its not great (Example 1).

Note: To generate the list I'm using `AsParallel`. Could there be any issues with parallel and map? I suspect not, just want to make sure.

While I was writing this I figured Fold would work too (Example 2).

Example 2 with fold looks good enough. Is there a better option?

Example 1
```
Map<A, B> ToMap(IEnumerable<KeyValuePair<A, B>> kvp) {
    var newMap = new Map<A,B>();

    kvp.Iter(kv => {
        newMap = newMap.Add(kv.Key, kv.Value);
    })
   
    return newMap;
}
```

Example 2
```
var list = IEnumerable<KeyValuePair<A, B>>()

list.Fold(new Map<A, B>(), (state, kv) => s.Add(kv.Key, kv.Value));
```

**Comment by louthy** [comment]
`Prelude.toMap(keyValues)`

**Comment by gregberns** [comment]
Of course!
