### ISSUE TITLE
Solution performance in Visual Studio (discussion)

### ISSUE THREAD

**Issue by sharwell** [louthy/language-ext#249]
Someone pointed me to this repository yesterday as an example of a project which has "interesting performance characteristics" in the IDE. I wanted to open a discussion so I can make some notes during my investigation as well as point out some issues that are likely to benefit this project.

The first two items that substantially improve the overall experience for this project were dotnet/roslyn#19258 (part of the 15.3 update release), followed by #248 here. The former reduces the amount of work performed by analyzers to evaluate dotted expressions, such as `Trans<MArr<Arr<A>>, Arr<Arr<A>>, MArr<A>, Arr<A>, A>.Inst.Bind`. The second disables most analyzers (code style and usage) altogether in code which isn't intended to be edited anyway.

The next area where I believe this project is currently negatively influenced involves documentation comments. While I can make some improvements to this quickly, I believe that certain options regarding comments are limited by the language itself. I would encourage you to express support for dotnet/csharplang#401.

I'll be watching for general places where things can be improved, but overall I suspect it will be many small pieces of an overall big puzzle. If you have any specific IDE performance- or behavior-related concerns related to this project you'd like me to look at, please feel free to add them here.

**Comment by louthy** [comment]
@sharwell Thanks for looking into this.  I do have major performance issues with VS 2017, this project is only one of my problems.  My main work project, which unfortunately I can't share, is constantly locking up and has laggy text input.  

One of my suspicions was expressions in general, but especially readonly statics.  I have a project where I use an in-house virtual dom system that bakes to readonly statics, i.e.
```c#
public readonly static DomMap Header =
    WithAppointment(
        SectionHeader("Appointment", "{AppointmentType}", "{prettydate(TimelineDate)}"),
        Details(
            Info("Date and time",
                If<AppointmentModel>(a => a.ArrivedDateTime.IsSome,
                    Then("{shorttime(Start)} to {shorttime(Finish)} on {shortdate(Start)}, arrived at {shorttime(ArrivedDateTime)} on {shortdate(ArrivedDateTime)}"),
                    Else("{shorttime(Start)} to {shorttime(Finish)} on {shortdate(Start)}, not arrived"))),
            Info("Site and location", "{Site}: {Location | (location not specified)}"),
            Info("Attendees", Attendees),
            Where<AppointmentModel>(am => HasServices(am, AppointmentServiceState.Provided),
                Info("Provided services", Services(AppointmentServiceState.Provided))),
            Where<AppointmentModel>(am => HasServices(am, AppointmentServiceState.Cancelled),
                Info("Cancelled services", Services(AppointmentServiceState.Cancelled))),
            Where<AppointmentModel>(am => !String.IsNullOrWhiteSpace(am.Subject ?? ""),
                Info("Subject", "{Subject}")),
            Where<AppointmentModel>(am => !String.IsNullOrWhiteSpace(am.Comments ?? ""),
                Info("Admin notes", "{Comments}")),
            Actions(
                Action("Print", "This.PrintAppt({AppointmentId})"),
                If<AppointmentModel>(a => a.PersonModelType == PersonModelType.Exact,
                    Then(Tool.Action("Expand", "This.ExpandAppt({AppointmentId})")),
                    Else(Tool.Action("Collapse", "This.CollapseAppt({AppointmentId})"))))
            ),
        Divider);
```
I use this type of thing to build pre-constructed expressions that take a state object and spit out HTML.

I have noticed that if I have a code file open with lots of these types of expressions in (that refer to each other) then it will get to the point of being unusable.  That seems pretty crazy.  As much as possible I try to make everything I do into an expression (for the ideological reasons that this library exists) - not just static expressions that build when the ctor fires, but in general throughout my code base; could there be a general issue with deep expressions, or nested lambdas? 

> (part of the 15.3 update release)

What's the ETA for 15.3?

> The next area where I believe this project is currently negatively influenced involves documentation comments. While I can make some improvements to this quickly, I believe that certain options regarding comments are limited by the language itself. 

I don't really follow what you're suggesting here.  But in terms of project comments, I couldn't find any docgen system that could deal with this project properly (having a lot of the core functionality in the `static Prelude` class), so [I rolled my own](https://louthy.github.io/language-ext/LanguageExt.Core/LanguageExt/index.htm) that supported markdown and the like (and can deal with angle brackets in between tags properly).  Are you suggesting that the comments themselves are slowing down VS?  

> I would encourage you to express support for dotnet/csharplang#401.

Support in what way?  

I very much appreciate you looking into this, although I do feel there are just general performance issues and bugginess throughout VS since Roslyn became the driver of all tooling.  I regularly see the refactoring components crashing (yellow bar pops up, I reset it, a few mins later - yellow bar).

**Comment by sharwell** [comment]
> but in general throughout my code base; could there be a general issue with deep expressions, or nested lambdas?

Yes, this is one of the primary things fixed by dotnet/roslyn#19258. However, that fix only applies to one specific analyzer in one specific case (that happens to occur frequently). There's always a possibility that other analyzers are running slow for your use cases. There are a boatload of issues related to this (tracking down specific problems for specific users so 1) they can disable slow analyzers before they cause big problems and 2) we can fix them). Here are a couple of issues:

* dotnet/roslyn#7474
* dotnet/roslyn#3751

> What's the ETA for 15.3?

It's outside my pay grade to say anything on this specifically. However, I've been using 15.3 Preview side-by-side with my normal installation of Visual Studio 2017 (15.2), and the side-by-side experience has been quite good. If you have the hard drive space to spare, you can have one "stable" copy as your primary environment, and a "preview" copy (which should update to each preview as it's made available) to give early feedback on the direction we're headed.

> Support in what way?

A comment saying your project would benefit from the additional expressiveness would be fine.

> Are you suggesting that the comments themselves are slowing down VS?

I can't prove this case yet. My guess is a gut feeling based on two observations:

1. Error cases tend to be slower for compilers than "normal" or "expected" cases
2. According to the compiler, you have a hair over 94,000 syntax problems inside of documentation comments

> I regularly see the refactoring components crashing (yellow bar pops up, I reset it, a few mins later - yellow bar).

My immediate team is *directly* responsible for making sure these issues get resolved. We fixed a bunch of these for 15.3, but I know more are out there. If you have a reproducer, you can file a bug on github/roslyn. Otherwise, sending feedback with Report a Problem (top right of the IDE) is the best way to get us information so this can be fixed.

> My main work project, which unfortunately I can't share, is constantly locking up and has laggy text input.

So we've heard. On the basis that your open source project and work project are likely share certain characteristics, I started here while people try to figure out how best to tackle the investigation related to your closed source projects.

**Comment by louthy** [comment]
> According to the compiler, you have a hair over 94,000 syntax problems inside of documentation comments

Hmm, that's interesting.  I guess I could modify my [doc gen](https://github.com/louthy/best-form) to not just generate documentation, but fix-up the broken comments (although I find the embedding of `<cref>` etc as particularly ugly for the primary users of the source: the coders.  Is there a quick way of getting the doc error output?

> If you have a reproducer, you can file a bug on github/roslyn. 

It's annoyingly random, with no obvious pattern of failure.  Obviously it isn't random!  I will make sure I push the report button when I see it next.  

> So we've heard. On the basis that your open source project and work project are likely share certain characteristics

Some, but they are pretty different to be fair.  It is very large though: 70 projects, mixture of C# and F#, includes about 100 nu-get packages (internal and external).  It's a 'layered' project with an application core, data-access-tier, business-logic, UI, etc.  (each layer comprising of many projects).  I am currently working on the UI only part of the project and have seen major improvements in build time and general responsiveness by building a small SLN projects with just four projects in (build time down from minutes to 35 seconds) .  So it seems there could be some significant performance improvements if you could just stop checking projects that aren't changing?

> If you have the hard drive space to spare, you can have one "stable" copy as your primary environment, and a "preview" copy 

Downloading now.  4.6 gb over a 3mbit connection, will take a while ;)

**Comment by sharwell** [comment]
> Hmm, that's interesting. I guess I could modify my doc gen to not just generate documentation, but fix-up the broken comments

⚠️ I must reiterate that I have not conclusively demonstrated even to myself that this is the source of a true problem. That means even if it changes, there is no guarantee of measurable/observable improvements. I'll submit a couple easy wins as pull requests and you can see if you like them.

> Is there a quick way of getting the doc error output?

Add the following to your project, below where you currently set `FileVersion`:

```xml
<GenerateDocumentationFile>True</GenerateDocumentationFile>
<NoWarn>$(NoWarn),1573,1591,1712</NoWarn>
```

> ... includes about 100 nu-get packages ... So it seems there could be some significant performance improvements if you could just stop checking projects that aren't changing?

There is a *heavy* current emphasis on both of these. The bulk of the improvements are likely to come in 15.5. During 15.3 we took care of some immediate performance concerns in Roslyn and the project system (the latter being driven by Dave Kean). Testing against the 15.3 previews revealed the next primary benefits will come from work on NuGet and the handling of much smarter incremental builds.

**Comment by louthy** [comment]
@sharwell 

Just had `ExtractMethodCodeRefactoringProvider` crash when I was highlighting two lines of code.  I wasn't trying to refactor anything.
```
System.InvalidOperationException : Unexpected false
   at Roslyn.Utilities.Contract.ThrowIfFalse(Boolean condition,String message)
   at Microsoft.CodeAnalysis.ExtractMethod.ExtractMethodMatrix.GetVariableStyle(Boolean captured,Boolean dataFlowIn,Boolean dataFlowOut,Boolean alwaysAssigned,Boolean variableDeclared,Boolean readInside,Boolean writtenInside,Boolean readOutside,Boolean writtenOutside,Boolean unsafeAddressTaken)
   at Microsoft.CodeAnalysis.ExtractMethod.MethodExtractor.Analyzer.GetVariableStyle(Dictionary`2 symbolMap,ISymbol symbol,SemanticModel model,ITypeSymbol type,Boolean captured,Boolean dataFlowIn,Boolean dataFlowOut,Boolean alwaysAssigned,Boolean variableDeclared,Boolean readInside,Boolean writtenInside,Boolean readOutside,Boolean writtenOutside,Boolean unsafeAddressTaken)
   at Microsoft.CodeAnalysis.ExtractMethod.MethodExtractor.Analyzer.GenerateVariableInfoMap(SemanticModel model,DataFlowAnalysis dataFlowAnalysisData,Dictionary`2 symbolMap)
   at async Microsoft.CodeAnalysis.ExtractMethod.MethodExtractor.Analyzer.AnalyzeAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.ExtractMethod.MethodExtractor.ExtractMethodAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.ExtractMethod.AbstractExtractMethodService`3.ExtractMethodAsync[TValidator,TExtractor,TResult](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeRefactorings.ExtractMethod.ExtractMethodCodeRefactoringProvider.GetCodeActionAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeRefactorings.ExtractMethod.ExtractMethodCodeRefactoringProvider.ComputeRefactoringsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringService.GetRefactoringFromProviderAsync(<Unknown Parameters>)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

Code looks like this:

```c#
                return await stream.MatchAsync(
                    Right: async value =>
                    {
                        var choiceDSL = inner[value % inner.Length];
                        ChoiceActions.SetChoiceState(id, choiceDSL.Item1).IfFailThrow();
                        inner.Where(t => t.Item1 != choiceDSL.Item1 && t.Item1.Value > 0)
                             .Iter(t => TaskStateActions.SaveSkippedTaskAndChildren(t.Item1).IfFailThrow());

                        return await chooseChoice(value);
                    },
                    Left: async type => type == TaskStateType.Shutdown
                                            ? await CancelledTask<TaskState>()
                                            : TaskStateActions.UpdateTaskState(taskState.SetTaskStateType(type)).IfFailThrow());
```
I highlighted:
```c#
                        ChoiceActions.SetChoiceState(id, choiceDSL.Item1).IfFailThrow();
                        inner.Where(t => t.Item1 != choiceDSL.Item1 && t.Item1.Value > 0)
```

**Comment by sharwell** [comment]
> Just had ExtractMethodCodeRefactoringProvider crash when I was highlighting two lines of code.

We fixed several cases of this in 15.3. They fell into a couple main "buckets" of causes; I can look them up if you're interested or you can wait and see if it goes away in 15.3.

**Comment by louthy** [comment]
Let's wait, no point looking for fixes that have already been done.  I'm firing it up now.

**Comment by louthy** [comment]
Doesn't seem to like F# (I did pick it from the install list)

> 1>error MSB4057: The target "GetTargetFrameworkProperties" does not exist in the project.
> 2>error MSB4020: The value "" of the "Project" attribute in element <Import> is invalid.

**Comment by sharwell** [comment]
Any chance it's caused by Microsoft/visualfsharp#2819?

**Comment by sharwell** [comment]
I'm not the expert on F#. I linked other people on the team to your comment but they might be doing other things on Saturday. 😄 If there was a way to reproduce it in an open source project, that might help me track it down.

**Comment by louthy** [comment]
Not using Ionide, so unlikely.  Just added the F# projects to the solution as normal.  

I will probably have to pause this testing as I have a big deadline to meet for monday.  I have my main solution open in 15.3, so that should be enough to do some decent testing (it failed on a standalone service project)

**Comment by louthy** [comment]
@sharwell Going to close this down for now.  15.3 seems to be an improvement so far.  I'll report anything else through the normal channels.  Thanks for your help  👍
