### ISSUE TITLE
Bind implementation for very nested things

### ISSUE THREAD

**Issue by NickDarvey** [louthy/language-ext#251]
Hi Paul,

I was hoping you could sanity check my approach to something.
I want to take an arbitrary collection of operations and use them to process a record.

```c#
var computation = List<Operation<string>>(
    x => Lift(x + " is all we need."),
    x => Lift(x + Environment.NewLine + "Powered by language-ext."))
.Fold(state: Lift("Paul Louth"), folder: (x, s) => x.Bind(r => s(r)));
```

All that lifting is because an `Operation` is actually modelled as:
`delegate Task<Either<Error, Option<T>>> Operation<T>(T source);` 
and because there's a whole bunch o' levels there, I can't use the built-in binding functions.

Right now, I was going to add my own `Bind`, like:
```c#
public static Task<Either<Error, Option<T>>> Bind<T>(this Task<Either<Error, Option<T>>> ma, Operation<T> f) =>
    ma.BindAsync(x => x.Map(r => f(r))
    .Match(Some: r => r, None: () => Right<Error, Option<T>>(None).AsTask()));
```
but are there primitives in Language Extensions which I should be using to build it? The only thing I could find is two levels deep, like [HKT/Trans](https://github.com/louthy/language-ext/blob/3b081513f664c9592451f5752b1263e57d1f7c89/LanguageExt.Core/HKT/Trans.cs).

Also, if this is a ridiculous approach to what I'm trying to do, please call me out.

Kind regards,
Nick

[Full Gist here](https://gist.github.com/NickDarvey/6135d70dec9464be790f455b3dbd3a8d).

**Comment by louthy** [comment]
@NickDarvey Hi Nick, yes if you go three levels deep with the monads you will need to manually lift to the outer monad.  The HKT stuff as you probably know is auto-generated, it generates 26 functions for 17^2 'transformer' types: which is 7514 functions.  I could in theory make it work for 3 levels deep, but then we're at 127,738 functions, and probably a very large DLL (not withstanding the trouble that Visual Studio already has with the HKT files.

One thing that strikes me is that you could just use: `TryOptionAsync<A>` which is the equivalent to `Task<Either<Exception, Option<A>>`.  If you call `ToEither` on a `TryOptionAsyc<A>` then you get a `Task<Either<Exception, Option<A>>>`.

So you could have something to wrap your `Error` type in an `Exception`:
```c#
public class ErrorException : Exception
{
    public readonly Error Error;
    public ErrorException(Error error) : base(error.Value) =>
        Error = error;
}
```
Then some conversion extensions to make it easier to jump between your `Either<Error, Option<A>>` and `Task<Either<Error, Option<A>>>` and `TryOptionAsync<A>`:
```c#
public static TryOptionAsync<A> AsTryOptionAsync<A>(this Either<Error, Option<A>> ma) =>
    ma.Match(
        Right: r => TryOptionAsync(r),
        Left:  e => TryOptionAsync<A>(new ErrorException(e)));

public static TryOption<A> AsTryOption<A>(this Either<Error, Option<A>> ma) =>
    ma.Match(
        Right: r => TryOption(r),
        Left: e => TryOption<A>(new ErrorException(e)));

public static TryOptionAsync<A> AsTryOptionAsync<A>(this Task<Either<Error, Option<A>>> ma) =>
    ma.Map(either => either.AsTryOption()).ToAsync();

public static Error AsError(this Exception ex) =>
    ex is ErrorException err
        ? err.Error
        : Error.New(ex.Message);
```
Then you can benefit from the plethora of async functionality attached to `TryOptionAsync`.  

When you match on the type to extract either the `Some`, `None`, or `Fail` states you can use the `AsError()` extension to go back to your `Error` type:
```c#
var m1 = Task.FromResult(Right<Error, Option<string>>("Testing"));

await m1.AsTryOptionAsync()
        .Match(
            Some: va => Console.WriteLine(va),
            None: () => Console.WriteLine("none"),
            Fail: ex => Console.WriteLine(ex.AsError()));
```
An additional benefit to this approach is that you can then nest the `TryOptionAsync<A>` too, so for example:  `List(tryOptionA, tryOptionB, tryOptionC, tryOptionD)`, you can then `BindT`, `MapT`, `Sequence`, etc.

**Comment by NickDarvey** [comment]
You are my favourite. Thank you so much, that's a fantastic solution!
