### ISSUE TITLE
Propose to change the wording of the readme with regard to functional / camelCase methods

### ISSUE THREAD

**Issue by kasajian** [louthy/language-ext#254]
I propose that the Readme downplay the issue with the camelCase, etc, especially minimizing phrasing such as "It won't always sit well with the seasoned C# OO programmer".

Instead, the Readme should have a small section titled something like "Functional style".
  "for those who prefer the style from the functional world, and with camelCase and global functions, the recommendation is to use the C#7 syntax to elevate the static methods of the Prelude class, etc.....   This is is the style I use in my projects and I highly recommend it"

So that way, you're both promoting and encouraging the style while minimizing the somewhat mildly patronizing tone toward "OO" programmers.   Personally I think it will make the library even more accessible to the more traditional developers.

**Comment by louthy** [comment]
Hmm, I never intended it to be patronising, it was more a comment on how C# land is mostly populated by OO devs and that there is a definite expectation that libraries follow the BCL style.  

I'm not against changing the wording, but I wonder if you've read a bit too much into it?  

I'm open to feedback here, so I'll leave this for others to comment before making a final decision.

**Comment by Maximusya** [comment]
The stuff you are mentioning is in the Introduction section. The Introduction to a Functional language extension IS EXPECTED to contain OOP vs FS points!
The project has the personal touch and style everywhere. I - as a traditional seasoned C# OO programmer - like it very much to use and READ advices and overall thoughts of a sain person. That things do not deserve small section ghetto :)

**Comment by kasajian** [comment]
Yeah, no worries.   If I were you, I'd probably see if others agree or not, especially if no one else agrees.

I think it's perfectly fine as an internet open-source project.   But if this thing is to become more mainstreamed, and sponsored by the .NET Foundation, my thinking is that it might need to get modified. 

Good work, otherwise.

**Comment by louthy** [comment]
Going to close this down.  3 months on and nobody seems too bothered, so I'm going to leave it.  Thanks for the input though.
