### ISSUE TITLE
Deconstruct Record Type

### ISSUE THREAD

**Issue by gregberns** [louthy/language-ext#258]
In C#7, they've added the ability to deconstruct a class. Unfortunately it doesn't seem to be very flexible because you have to define the deconstructor prior to use. If you wanted get X property in one case, Y in another case, and both X and Y in a third, you have to define three overloaded methods. Also, you have to use the `out` keyword, which we know is [aweful](https://github.com/louthy/language-ext#the-awful-out-parameter). 

It seems like using deconstruction and Records would go well together, and its quite helpful in JS and other langs. Is there any magic that we could use to get values out of records?

Setup:
```
public class Point
{
    public Point(double x, double y)
    {
        this.X = x;
        this.Y = y;
    }

    public double X { get; }
    public double Y { get; }

    //This is required for the deconstruction
    public void Deconstruct(out double x, out double y)
    {
        x = this.X;
        y = this.Y;
    }
}
```

Usage:
```
var p = new Point(3.14, 2.71);
(double X, double Y) = p;
```

Would be nice to use it like this:
```
public class Point : Record<Point>
{
    public Point(double x, double y)
    {
        this.X = x;
        this.Y = y;
    }
}
//possible usage?
var p = new Point(3.14, 2.71);
(double X) = p;
(double Y) = p;
(double X, double Y) = p;
```

**Comment by louthy** [comment]
@gregberns Unfortunately I can't create types and methods on the fly, they need to exist at the time of compilation; and because each Deconstruct function has a different shape based on the type it's not possible to provide a standard implementation.

**Comment by gregberns** [comment]
I figured. Thanks Paul
