### ISSUE TITLE
Validation on List of Items

### ISSUE THREAD

**Issue by gregberns** [louthy/language-ext#259]
I've been exploring the `Validation` class and have it working on validating a single item, but I want to validate each item in a list and return a single Validate item.

Example: I have a list of numbers, and I want to validate each of their lengths is less than 5.

From my understanding, the `Error` is actually a `Seq` which is appendable (a monoid?). 

Can I get a Validate with any errors appended? 
I assume the type of Validation would also need to change from `Validation<Error, string>` to `Validation<Error, List<string>>` during this transition.

```
var list = new List<string>() { "1234", "12", "123456" };
var ValidateString = fun((string s) => s.Length < 5 ? Success<Error, string>(s) : Fail<Error, string>(Error.New("Too long")));

// would like a `Validation<Error, List<string>>` back, with both sides aggregated.
IEnumerable<Validation<Error, string>> validList = list.Map(t => ValidateString(t));

IEnumerable<Validation<Error, string>> validList = from i in list
                                                              select ValidateString(i);

 public class Error : NewType<Error, string>
    {
        public Error(string e) : base(e) { }
    }
```

The real use case is to take a list of emails, validate them, and return the list, if thats of any value.

**Comment by louthy** [comment]
On my phone, so can't give a full answer, but just call .Sequence(), it
will flip the inner and outer monads.

**Comment by gregberns** [comment]
Thanks Paul. We've discussed that before, now I remember.

Here's the resulting code change. Map over the strings to generate a `IEnumerable<Validation<Error, string>>`, then use Sequence to 'flip' the enumerable in and the validation out.

```csharp
var list = new List<string>() { "1234", "12", "123456" };
var ValidateString = fun((string s) => s.Length < 5 ? Success<Error, string>(s) : Fail<Error, string>(Error.New("Too long")));

Validation<Error, IEnumerable<string>> validation = 
                list.Map(t => ValidateString(t))
                    .Sequence();
```

**Comment by gregberns** [comment]
I'm going to dig a little further into Validation.

Once we have a Validation object we can operate on the Sucess with `Map`. But how do we operate on the errors? More specifically, how can we Fold/Aggregate the errors into a single error to return to the user?

Since I'm familiar with `Either`, I can call `ToEither()`, and then use `MapLeft`, but its a little ugly. Any better options?

```csharp
Validation<Error, IEnumerable<string>> validation2 = Error.New("");

validation
                .ToEither()
                .MapLeft(es =>
                    es.Aggregate("Validation Errors: ", (a, b) => a + ", " + b.Value)
                        .Apply(err => Error.New(err)));
```

Thanks

**Comment by trbngr** [comment]
I would just use match.
```csharp
validation.Match(
    Succ: identity,
    Fail: errors => errors.Map(x => x.Value)
);
```

**Comment by gregberns** [comment]
Not sure why I didn't think of that obvious option. Thanks Chris
