### ISSUE TITLE
Continue targeting netstandard1.3 +

### ISSUE THREAD

**Issue by trbngr** [louthy/language-ext#268]
We have some projects that we aren't able to upgrade to netstandard2.0 and the latest `Core`  stopped building for anything previous to that.

Is there something you need in netstandard2.0 for this library?

Thanks

**Comment by louthy** [comment]
@trbngr Hi Chris, it was covered in the release notes:

https://github.com/louthy/language-ext/releases/tag/2.1.20

**Comment by trbngr** [comment]
Makes sense. Thanks.
