### ISSUE TITLE
Can library stay with netstandard 1.3?

### ISSUE THREAD

**Issue by GiuseppePiscopo** [louthy/language-ext#269]
Hello
I was updating library version in one of our .NET Core projects and just found that latest version (2.1.21) is not compatible with .NET Core 1.1. Going backward, [this](https://github.com/louthy/language-ext/commit/8ea698c75add883feaf67799c6656a71e9b353a6) seems to be the interested commit, and the last available version for that framework should be 2.1.18.

I was just wondering if it's possible to backport to pre-netstandard 2.0, as that seems still a little bit "volatile" in terms of issues, dependencies and tools.

In case, is a big effort needed? Could we talk about a PR? 

Thanks for your work on this library.

**Comment by alastairs** [comment]
Thanks @GiuseppePiscopo for doing the necessary detective work, I've just run into this same issue myself. I can use 2.1.18 as a workaround for now.

**Comment by GiuseppePiscopo** [comment]
Let's hope is a temp workaround and not a stable thing. I just gave a rough look at the commit so I could not really tell if there was a specific requirement to switch over netstandard 2

**Comment by trbngr** [comment]
I asked about this the other day. This is the explanation.
https://github.com/louthy/language-ext/releases/tag/2.1.20

**Comment by GiuseppePiscopo** [comment]
Ouch. Thanks for pointing to that, I did not find those info in my initial search.

Well, I guess this can be closed now.
