### ISSUE TITLE
Windows 10 support

### ISSUE THREAD

**Issue by tomaszpolanski** [louthy/language-ext#27]
Big fan of the library!
I already use it for my WP8.1 projects.

I tried to include it withing my Windows 10 project, but with no success. Still I cannot reference anything from the library.

As I know, creating the proper NuGet package is usually a hassle. Is the current one (1.0.0) supporting UWP applications?

Cheers,
Tomasz

**Comment by louthy** [comment]
Hi @tomaszpolanski , thanks for the props :)

Re: Support for W10, I'm not 100% what's required here?  I'm more of a web guy, so never really deal with phone or Store apps.  If you have any pointers/guidance then I'm happy to help.

**Comment by tomaszpolanski** [comment]
thanks for the response.
For now I've only tried to use the NuGet package and they still glitchy overall in Win10 and VS 2015.
I will investigate this issue a bit more and also try using sources instead to pinpoint the issue.
Will get back to you after I investigate it.

**Comment by louthy** [comment]
Hi @tomaszpolanski - Am I to understand that everything is OK now on Win10?

**Comment by tomaszpolanski** [comment]
Hi @louthy, I did not have time before to try it out again. Today I will do it and give you feedback.

**Comment by tomaszpolanski** [comment]
I've investigated the issue more closely.
It seems that nuget is not the issue. 
The issue is that the library is not Portable, so no wonder that it cannot be used inside Universal application/library.

@louthy, is there a reason why your library is not Portable?

Cheers,
Tomasz

**Comment by louthy** [comment]
Hi @tomaszpolanski - I refer you to this issue:  https://github.com/louthy/language-ext/issues/70

It covers to progress of the migration to .NET Core (which I assume will give you W10 support).  There are versions on nuget now, but please take a look at the table in the issue comments for the level of support for things like LanguageExt.Process.Redis.

**Comment by tomaszpolanski** [comment]
Great, thanks for the response!

T
