### ISSUE TITLE
Feature proposal: IQueryable Option for first/single item

### ISSUE THREAD

**Issue by BrainCrumbz** [louthy/language-ext#271]
`IQueryable<>` offers `FirstOrDefault`, `SingleOrDefault` and `Single` - plus their async counterparts - in order to grab the first/single item from a query, or else a default value, or an exception in some other circumstance.

We often find ourselves wanting to grab the first item and convert that into an `Option<>`, so that query results either in a `Some` or a `None` value, so we take `FirstOrDefault` or `FirstOrDefaultAsync` and then map that to an option. We have not thought about it, but there might be some common desired behaviour also for `Single` and `SingleOrDefault`.

Maybe it could be helpful to others as well if language-ext had, among its extensions, also something covering those cases.

Please feel free to close this issue if deemed not helpful.

**Comment by louthy** [comment]
@BrainCrumbz 
```c#
    Option<A> result = queryable.HeadOrNone();
```
There isn't currently an async version I'm afraid.

**Comment by louthy** [comment]
@BrainCrumbz 

The full set of `IQueryable<A>` extensions and functions are here:

https://github.com/louthy/language-ext/blob/master/LanguageExt.Core/Extensions/Query.cs

**Comment by BrainCrumbz** [comment]
Doh! Thanks for pointing to the right bits. 

Would you consider a doc PR mentioning this somewhere in readme?
