### ISSUE TITLE
Have you seen the new writeup of C# concepts prototype?

### ISSUE THREAD

**Issue by orthoxerox** [louthy/language-ext#276]
https://github.com/MattWindsor91/roslyn/blob/2017-stable/concepts/docs/writeup.docx

It now includes associated types, which allow C# to simulate HKTs and infer correct concrete types. The paper says the implementation is an ugly hack, though.

**Comment by louthy** [comment]
@orthoxerox Thanks for sharing, I haven't got an enormous amount of time to dig into it.  But, from a quick scan, I don't see anything relating to higher kinds?  It just seems to be refining the earlier proposal.  Am I missing something?

**Comment by orthoxerox** [comment]
Associated types will allow compile-time type-safe emulation of HKTs and therefore concepts like monoids and monads, if I'm reading the proposal right.

**Comment by louthy** [comment]
@orthoxerox From what I can tell (from my very brief look) is that there's still no way to parameterise a higher-kind.  Something like this:

```c#
    public interface Monad<M<>, A>
    {
        M<B> Bind<B>(M<A> ma, Func<A, M<B>> f);
    }
```
Any thoughts on how a `concept`, `instance`, and associated type could work in that case?  The member _return_ types for higher-kinded types are the biggest obstacle I find to a really robust solution (obviously the type-inference is problematic too).

In lang-ext right now I do this:
```c#
    public interface Monad<MA, A>
    {
        MB Bind<MonadB, MB, B>(MA ma, Func<A, MA> f) where MonadB : struct, Monad<MB, B>;
    }
```

> It's more complex than that, but you get the idea.

Obviously, the problem with that is that even though the return type is constrained to be a monad, it's not constrained to the instance monad (so `Option.Bind` could return a `Either`, for example).

I'll dig a bit deeper with this next week, maybe there's some cunning tricks that can be done to coerce the types.  

I know you watch the Rosyln repo carefully, is there now competing approaches with _shapes_ and _concepts_?

**Comment by orthoxerox** [comment]
I think it's the same approach. The document says they still haven't finalized the names. After all, that's one of the hardest problems in computer science. 😬
