### ISSUE TITLE
Should HashMap implement IReadOnlyDictionary?

### ISSUE THREAD

**Issue by bradphelan** [louthy/language-ext#280]
Is there something about IReadOnlyDictionary that precludes this?

**Comment by louthy** [comment]
It inherits all the mutable functionality of ICollection, which leaves lots
of functionality with NotImplementedExceptions.

This is widely acknowledged as a mistake by the .NET team when they tried
to bolt on read-only behaviour to collections.  I don't want to propagate
it.

**Comment by bradphelan** [comment]
yeah you are totally right. i keep forgetting about the total mess the
collections api interfaces are.

im converting over all my system.collections.immutable code to lang ext
types now. its much cleaner.

**Comment by bradphelan** [comment]
MS also screwed up the immutable collections API in that they dont
implement equality. I remember some half baked reason they gave for it. So
in the end two immutable list with identical contents use reference
equality and thus are considered not equal.

 So they dont work with your magic Record base class.

thus i swap to your collections which do implement equality.

great work. thanks
