### ISSUE TITLE
static properties cause Record::Equals to crash

### ISSUE THREAD

**Issue by bradphelan** [louthy/language-ext#281]
I have the following test case

```
using static LanguageExt.Prelude;using LanguageExt;
using LanguageExt;
using Xunit;
using FluentAssertions;
using Ninject.Infrastructure.Language;
using static LanguageExt.Prelude;

namespace Utils.Spec
{

    public class LanguageExtRecords
    {
        public class Foo : Record<Foo>
        {
            public static Foo Default { get; private set; }

            static Foo()
            {
                Default = new Foo( 10,20,List(1,2) );
            }

            public Foo(int age, int s, Lst<int> numbers)
            {
                Age = age;
                String = s;
                Numbers = numbers;
            }
            public int Age { get; }
            public int String { get; }
            public Lst<int> Numbers { get; }
        }

        [Fact]
        public void EqualRecordsShouldBeEqual()
        {

            var a = new Foo( 10, 20, List( 0, 1, 2 ) );
            var b = new Foo( 10, 20, List( 0, 1, 2 ) );

            a.Equals( b ).Should().Be( true );

        }

        [Fact]
        public void NonEqualRecordsShouldBeNotEqual()
        {

            var a = new Foo( 10, 20, List( 0, 1, 2 ) );
            var b = new Foo( 10, 20, List( 0, -1, 2 ) );

            a.Equals( b ).Should().Be( false );

        }
    }
}

```

and it fails with the following error

> System.TypeInitializationException : The type initializer for 'LanguageExt.RecordType`1' threw an exception.
> ---- System.ArgumentException : 'Default' is not a member of type 'Utils.Spec.LanguageExtRecords+Foo'
>    at LanguageExt.Record`1.Equals(RECORDTYPE other)
>    at Utils.Spec.LanguageExtRecords.EqualRecordsShouldBeEqual()
> ----- Inner Stack Trace -----
>    at System.Linq.Expressions.Expression.PropertyOrField(Expression expression, String propertyOrFieldName)
>    at LanguageExt.IL.<>c__DisplayClass10_0`1.<<GetHashCode>g__Fields2>d.MoveNext()
>    at LanguageExt.List.fold[S,T](IEnumerable`1 list, S state, Func`3 folder)
>    at LanguageExt.IL.GetHashCode[A]()
>    at LanguageExt.RecordType`1..cctor()

It looks like it is mistakenly thinking the **Default** is an instance property.

**Comment by bradphelan** [comment]
If I change the static property to a static field

    public static Foo Default;

then the two tests pass

**Comment by bradphelan** [comment]
I'll try and fix it. I've found the problem in the code

**Comment by bradphelan** [comment]
tracking https://github.com/bradphelan/language-ext/tree/static-props-fail

**Comment by louthy** [comment]
On `v2.1.24` on nu-get now.
