### ISSUE TITLE
Match on implicit Try<T>

### ISSUE THREAD

**Issue by Profpatsch** [louthy/language-ext#29]
Is there a way to implicitly match on a function that can throw an error with Try?

I tried:

```c#
match( toMailAdress(address-string),
    Succ m => …,
    Fail e => …);
```

But that doesn’t seem to work.

**Comment by louthy** [comment]
Does `toMailAddress` return a `Try<T>` ?

**Comment by louthy** [comment]
This is covered in another issue, so closing it down.
