### ISSUE TITLE
Middleware pipeline

### ISSUE THREAD

**Issue by LubosBehensky** [louthy/language-ext#291]
Hello,

I am reading the book Functional programming in C# and I was just wondering if language-ext offers some support to solve the problem that is referenced in the book as middleware pipeline. The bit I understand it's about composing nested functions. The examples desribe action like opening database connection and performing actions before and after the opening. If it is something obvious then sorry, I am  pretty confused from all the functional stuff and not a pro programmer.

Thanks 

Lubos

**Comment by louthy** [comment]
@LubosBehensky Unfortunately not, this is more of a functional 'prelude' than a middle-ware library.  So it's more of a toolkit for building your own functional systems.

**Comment by LubosBehensky** [comment]
Ok, I will try the implementation described in the book. Thanks.
