### ISSUE TITLE
BottomException with Task<Option<T>> and ToEitherAsync()

### ISSUE THREAD

**Issue by GiuseppePiscopo** [louthy/language-ext#292]
I cannot wrap my head around while a bit of code is throwing said exception. A tiny repro solution is available at https://github.com/GiuseppePiscopo/LangExtAsyncOptFail: it's a tiny console app showing the issue within 100 lines of *Program.cs*.

For simplicity, here's the entry point of processing emulating what happens in a real life project. Just pretend `int` stands for some type of custom returned error:

``` c#
static Task<Either<int, User>> ValidateAsync()
{
    var result =

        from loaded in FindUserAsync("zzz").ToEitherAsync(()
            => -1)

        from transformed in VerifyUser(loaded).ToEitherAsync(()
            => -2)

        select transformed;

    return result;
}
```

where:

```c#
static Task<Option<User>> FindUserAsync(string name)
{
    var users= GetUsers()
        .Where(n => (string)n == name);

    var firstFound = users.FirstOrDefaultAsync();

    var result = firstFound.Map(Optional);

    return result;
}
```

`GetUsers` returns a (dummy) queryable: this could be from an EF DbSet, but a simple array is enough to show the problem.

Error shows up when the name is not found. Exception stacktrace refers to the top-level line invoking and waiting for the task (in repro is `RunIssue().Wait();`), but going step by step it seems to me the error rises somewhere around `firstFound.Map(Optional)` or the outer `ToEitherAsync(() => -1)`.

What am I doing wrong? Thanks all

**Comment by GiuseppePiscopo** [comment]
Generated exception, the one wrapped in an *AggregateException* due to `.Wait()`,  is reported on repro project page. Here it is for simplicity:

**Type:**  
> LanguageExt.BottomException

**Message:**  
> Value is in a bottom state and therefore not valid.  This can happen when the value was filtered and the predicate returned false and there was no valid state the value could be in.  If you are going to use the type in a filter you should check if the IsBottom flag is set before use.  This can also happen if the struct wasn't initialised properly and then used.

**Stacktrace:**  
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()  
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)  
   at TaskExtensions.<SelectMany>d__5`3.MoveNext()

**Comment by louthy** [comment]
@GiuseppePiscopo Hi Giuseppe, I haven't quite got time to look at this now, but I suspect it's because you're working with nested monads `Task<Option<` and `Task<Either<` and the higher-kinded LINQ provider is considering a failed inner monad of `Task<Option<` (which would be `Task<None>`) to also be a failed outer monad, and because a failed `Task` must have an exception, you get `BottomException`.  

Take a look at these extensions that I wrote for a similar (probably the same) issue: https://github.com/louthy/language-ext/issues/242#issuecomment-318335885

**Comment by GiuseppePiscopo** [comment]
Hi there, thanks again for support. Yes, it seems to me as well that is the same issue. The extensions you wrote fit well on repro project. I'm still struggling applying that on real life project, as left type is an interface and `Where` implementation complains about *Only assignment, call, increment, decrement, and new object expressions can be used as a statement*:

![image](https://user-images.githubusercontent.com/1991814/32107849-16c50e32-bb30-11e7-92c5-0ad05f08e11b.png)

Any idea?

Apart from this, one downside is that I guess I have other cases like that in code, and so one should go hunting them down and add appropriate extension methods on a type-by-type basis. I don't completely agree with @trbngr nice gist, as you're forced to create exceptions just for the sake of it, and at a first thought I don't feel great about that.

> You can definitely think of Try<A> as a friendlier Either<Exception, A> and TryAsync<A> as a friendlier Task<Either<Exception, A>>.
> There's also TryOption<A> which is basically: Either<Exception, Option<A>> and TryOptionAsync<A> which is Task<Either<Exception, Option<A>>>

Sadly there seems to be nothing similar to `Task<Either<SomeType, A>>` where left-side is not `Exception`, and I'm not yet really familiar with Try/Option/TryOptionAsync anyway.

For future readers, I've successfully applied the workaround (LINQ extensions methods specific to the left-type) onto repro project. It's in [fix/left-type-extensions](https://github.com/GiuseppePiscopo/LangExtAsyncOptFail/compare/master...fix/left-type-extensions) branch.

Again, thanks for support.

**Comment by GiuseppePiscopo** [comment]
Re. compile time error, nevermind: it was enough to replace `? r` with `? Right<IAuthValidationTag, A>(r)` and `l => l` with `l => Left<IAuthValidationTag, A>(l)`.
