### ISSUE TITLE
How to get Ord<Record<T>> working when members are Set<U> or Arr<U>

### ISSUE THREAD

**Issue by bradphelan** [louthy/language-ext#293]
I have the following test

```
    public class ContainerOrderingTests
    {
        public class WithSet : Record<WithSet>
        {
            public WithSet(int i, Set<int> s)
            {
                I = i;
                S = s;
            }

            public int I { get; }
            public Set<int> S { get; }
        }

        [Fact]
        public void SetOrderingWorks()
        {
            var a = new WithSet(0, Prelude.Set(0,1,2));
            var b = new WithSet(0, Prelude.Set(0,1,2));
            Assert.Equal(0,a.CompareTo( b )) ;
        }
    }

```

which fails with the fact that Set does not implement IComparable. But somehow I'm sure you have thought of this but the solution is non obvious.

**Comment by bradphelan** [comment]
I tried

```
    public class ContainerOrderingTests
    {
        public class WithSet : Record<WithSet>
        {
            public WithSet(int i, Set<OrdInt,int> s)
            {
                I = i;
                S = s;
            }

            public int I { get; }
            public Set<OrdInt,int> S { get; }
        }

        [Fact]
        public void SetOrderingWorks()
        {
            var a = new WithSet(0, Prelude.Set<OrdInt,int>(0,1,2));
            var b = new WithSet(0, Prelude.Set<OrdInt,int>(0,1,2));
            Assert.Equal(0,a.CompareTo( b )) ;
        }
    }
```

but I think that is really just the same as the first example

**Comment by bradphelan** [comment]
Progress. I now have

        public static Option<Type> GetOrderableContainerOrd()
        {

            Option<TypeInfo> ArityOneGeneric(TypeInfo baseInfo)
            {
                return baseInfo.GenericTypeArguments == null || baseInfo.GenericTypeArguments.Length != 1
                    ? (Option<TypeInfo>) None
                    : baseInfo.GenericTypeArguments[0].GetTypeInfo();
            }

            string RemoveGenerics(string name) => FirstCharToUpper(OrdNameMaps(name.Split( '`' ).Head()));

            var mType = typeof(A).GetTypeInfo();


            return
                from nType in ArityOneGeneric( mType )
                from tType in ArityOneGeneric( nType )
                let mnTypeName = RemoveGenerics( mType.Name ) + RemoveGenerics( nType.Name ) + "`2"
                let mtTypeName = RemoveGenerics( mType.Name ) + RemoveGenerics( tType.Name )
                let tTypeName = RemoveGenerics( tType.Name )
                from mnType in ClassInstancesAssembly.Structs.Where( t => t.Name == mnTypeName ).HeadOrNone()
                from ntType in ClassInstancesAssembly.Structs.Where( t => t.Name == mtTypeName ).HeadOrNone()
                select mnType.MakeGenericType( ntType, tType );

        }

        static string OrdNameMaps(string typename)
        {
            switch (typename)
            {
                case "Int32": return "Int";
                case "Int64": return "Long";
                default: return typename;
            }
        }


        public static string FirstCharToUpper(string input)
        {
            switch (input)
            {
                case null: throw new ArgumentNullException(nameof(input));
                case "": throw new ArgumentException($"{nameof(input)} cannot be empty", nameof(input));
                default: return input.First().ToString().ToUpper() + input.Substring(1);
            }
        }

which can resolve the test

        [Fact]
        public void GetOrderableContainerOrderWorks()
        {
            var type = Class<Ord<Set<int>>>.GetOrderableContainerOrd();
            Assert.True( type.IsSome );

        }

**Comment by louthy** [comment]
@bradphelan Hi Brad, I've been away for a week or so, so I'll take a look at this once my head is back in gear.

**Comment by louthy** [comment]
@bradphelan Hi Brad, sorry for the delay.  `Map<K,V>`, `Map<OrdK, K, V>`, `Set<A>`, `Set<OrdA, A>`, `Lst<A>`, `Lst<PredA, A>`, `Lst<PredList, PredItem, A>` now all support `IComparable` as well as the `<`, `<=`, `>=`, `>` operators

**Comment by bradphelan** [comment]
Super :)
