### ISSUE TITLE
Is Traverse correct?

### ISSUE THREAD

**Issue by sholland1** [louthy/language-ext#296]
Since the type signature of traverse in Haskell is
```haskell
traverse :: (Applicative f, Traversable t) => (a -> f b) -> t a -> f (t b)
```
I was expecting something like the below to be possible, but it isn't.
```c#
[Fact] 
public static void TraverseTest() 
{
    var x = List(1, 2, 3, 4, 5); 

    var y = x.Traverse(a => Some(a)); 

    Assert.True(y == Some(List(1, 2, 3, 4, 5))); 
} 
```
Is this intentional?

**Comment by louthy** [comment]
@sholland1 Yes it was intentional, it's very difficult to generalise the Haskell version of `traverse`.  When I get some more time I may look into trying to formulate it (and the `Traversable` type-class) again.

**Comment by louthy** [comment]
@sholland1 btw, you can achieve the same behaviour with `x.Map(a => Some(a)).Sequence()`; although it's less efficient than bespoke traverse functionality obviously.

**Comment by sholland1** [comment]
Ok, thanks.
