### ISSUE TITLE
monadic Result<T> ?

### ISSUE THREAD

**Issue by 3dGrabber** [louthy/language-ext#298]
Is there a reason why it is not possible to chain `Result<T>`s using `Bind` ?  
I would like to use `Result<T>`  as a way to explicitly declare Exceptions without the lazyness of `Try`.
    
    Try<Int32> r1 = new Try<Int32>(() => 42)
                   .Bind(x => Try(x / maybeZero));

    Result<Int32> r2 = new Result<Int32>(42)
                      .Bind(x => Try(x / maybeZero).Try());

Why does `r1` work but `r2` not?  
  
Even nicer would be

    Result<Int32> r3 = new Result<Int32>(4)
                      .Bind(x => x / maybeZero);

with try-catch being taken care of by `Bind`

**Comment by 3dGrabber** [comment]
Just realized that the `r3` example would have the wrong signature for `Bind`. Should probably have another name?

**Comment by louthy** [comment]
The `Result` type is meant as an intermediate value, so I'm probably not going to make it fully monadic.  If I were to do it I'd probably create a new type called `TryStrict` or something like that.

But you could add the extensions yourself:
```c#
public static class ResultConstruct
{
    /// <summary>
    /// Ctor function
    /// </summary>
    public static Result<A> Result<A>(A value) =>
        new LanguageExt.Result<A>(value);

    /// <summary>
    /// Ctor function
    /// </summary>
    public static Result<A> Result<A>(Func<A> f)
    {
        try
        {
            return Result(f());
        }
        catch (Exception e)
        {
            return new LanguageExt.Result<A>(e);
        }
    }
}

public static class ResultExt
{ 
    public static Result<B> Map<A, B>(this Result<A> ma, Func<A, B> f) =>
        ma.IsBottom
            ? LanguageExt.Result<B>.Bottom
            : ma.Match(
                Succ: v => new Result<B>(f(v)),
                Fail: e => new Result<B>(e));

    public static Result<B> Bind<A, B>(this Result<A> ma, Func<A, Result<B>> f) =>
        ma.IsBottom
            ? LanguageExt.Result<B>.Bottom
            : ma.Match(
                Succ: v => f(v),
                Fail: e => new Result<B>(e));

    public static Result<B> Select<A, B>(this Result<A> ma, Func<A, B> f) =>
        ma.Map(f);

    public static Result<C> SelectMany<A, B, C>(this Result<A> ma, Func<A, Result<B>> bind, Func<A, B, C> project) =>
        ma.Bind(a => bind(a).Map(b => project(a, b)));

    public static Unit Iter<A>(this Result<A> ma, Action<A> f) =>
        ma.IsBottom
            ? unit
            : ma.Match(a => { f(a); return unit; }, _ => unit);

    public static bool Exists<A>(this Result<A> ma, Func<A, bool> f) =>
        ma.IsBottom || ma.Match(f, _ => true);

    public static bool ForAll<A>(this Result<A> ma, Func<A, bool> f) =>
        ma.IsBottom
            ? false
            : ma.Match(f, _ => false);

    public static S Fold<S, A>(this Result<A> ma, S state, Func<S, A, S> f) =>
        ma.IsBottom
            ? state
            : ma.Match(a => f(state, a), _ => state);

    public static Result<A> Filter<A>(this Result<A> ma, Func<A, bool> f) =>
        ma.IsBottom || ma.IsFaulted
            ? ma
            : ma.Match(
                Succ: a => f(a),
                Fail: _ => false)
                ? ma
                : LanguageExt.Result<A>.Bottom;

    public static Result<A> Where<A>(this Result<A> ma, Func<A, bool> f) =>
        ma.Filter(f);
}
```
Then you can include it with: `using static ResultConstruct` to get the constructor functions:

This will catch exceptions:
```c#
   var x = Result(() => 123);
```
This is the simpler value ctor:
```c#
   var x = Result(123);
```
All the LINQ operations and common functions are then available through the extensions.

Another option is to provide an extension to `Try` to force it to evaluate:
```c#
    public static class TryExt
    {
        public static Try<A> Strict<A>(Try<A> f)
        {
            var r = f.Try();
            return () => r;
        }
    }
```
Which you can call:
```c#
   Try<A> x = ....;
   var y = x.Strict();
```
_NOTE_: That even though `Try` is lazy, it memoizes the result when evaluating, so even if you `Match` on it multiple times you'll only evaluate the expression once (which is the case for all of the functions that cause an evaluation).

**Comment by louthy** [comment]
@3dGrabber _Updated the `ResultExt` type to catch all exceptions._

**Comment by 3dGrabber** [comment]
Whoa, thanks a lot for the detailed response!  
This will be handy.

> The Result type is meant as an intermediate value, so I'm probably not going to make it fully monadic.

Ok, got it, so it is a design decision.  
I thought maybe `MResult<T>` would somehow subtly break the monad laws...
