### ISSUE TITLE
Task<Option<>>.BiIterAsync() takes wrong route when None

### ISSUE THREAD

**Issue by BrainCrumbz** [louthy/language-ext#299]
Hi there.

We are experiencing what seems to be a bug. Description follows:

### Details

At some point in code you have some `Task<Option<T>>` value. You then run `.BiIterAsync()` method on value, finally returning result of such method.  
When wrapped option ends up evaluating to `None`, one would expect that the `Some:` branch is executed. Instead it seems like the `None:` branch is run. 
 
There's a small repro solution at https://github.com/GiuseppePiscopo/LangExtOptBiIterAsync. The gist of it is:

```c#
Task<Option<string>> textOptTask = Task.Run(() => (Option<string>)None);

Task<Unit> doActionTask = textOptTask.BiIterAsync(
    None: () =>
        Console.WriteLine("Do Action None"),
    Some: text =>
        Console.WriteLine($"Do Action Some: '{text ?? "<null>"}'"));

return doActionTask;
```

### Steps to reproduce

1. Clone repro project from https://github.com/GiuseppePiscopo/LangExtOptBiIterAsync
1. Restore packages
1. Run from Visual Studio or command line
1. Press a key to actually start processing

### Expected result

Console should show:

```
Do Action None
```

### Actual result

Console shows:

```
Do Action Some: '<null>'
```

### Environment

* Package: LanguageExt.Core 2.1.18
* Platform: Microsoft.NETCore.App 1.1.4
* Framework: netcoreapp1.1

**Comment by BrainCrumbz** [comment]
Not sure wether it's the same issue or what, so just posting here another test we did. We turned code gist to use *async*/*await*:

```
static async Task<Unit> ValidateAsync()
{
    Option<string> textOpt = await Task.Run(() => (Option<string>)None);

    Unit doAction = textOpt.BiIter(
        None: () =>
            Console.WriteLine("Do Action None"),
        Some: text =>
            Console.WriteLine($"Do Action Some: '{text ?? "<null>"}'"));

    return doAction;
}
```

With such code we incur into a *ValueIsNoneException* with following stacktrace:


```
at LanguageExt.OptionData`1.get_Value()
at LanguageExt.Option`1.get_Value()
at LanguageExt.ClassInstances.MOption`1.BiFold[S](Option`1 ma, S state, Func`3 fa, Func`3 fb)
at LanguageExt.TypeClass.biFold[FOLD,F,A,B,S](F foldable, S state, Func`3 fa, Func`3 fb)
at LanguageExt.TypeClass.biIter[FOLD,F,A,B](F foldable, Action`1 fa, Action`1 fb)
at LanguageExt.Option`1.BiIter(Action`1 Some, Action None)
at LangExtOptBiIterFail.Program.<ValidateAsync>d__2.MoveNext() in [...]\Program.cs:line 30
```

There's a similar repro project [here](https://github.com/GiuseppePiscopo/LangExtOptBiIterFail) for such scenario as well.

We can create a separate issue if needed. Thanks

**Comment by louthy** [comment]
@BrainCrumbz The `ValidateAsync` code snippet works for me.  It calls the `None` branch as expected.  I'd suggest upgrading to the latest version `2.1.25`.  Perhaps it was fixed with the previous bi-iter issue.

**Comment by BrainCrumbz** [comment]
Thanks for feedback. At the moment we're on .NET Core 1.1.4, no netstandard 2.0, thus we're stuck at language-ext 2.1.18.

Trying to trace back commits related to package versions, [this](https://github.com/louthy/language-ext/compare/a75463c7f0e3e5266c44850b7d036fddde557ca2...master) seems to be the closest comparison. Skimming through changes, there are some cases where an `IsNone` was turned into an `IsSome`, in particular those within *MOption.cs* `BiFold` and `BiFoldBack`. So it might as well be that there was a fix. But as said, right now we're not switching framework version.

Please, feel free to close this issue if you think it's solved.

Cheers!

**Comment by louthy** [comment]
Yes, this was fixed.  So an upgrade will be required I'm afraid.
