### ISSUE TITLE
Compiler can't choose method group for "IfSome"

### ISSUE THREAD

**Issue by feugen24** [louthy/language-ext#30]
From docs:
// Invokes an Action<T> if in the Some state.
optional.IfSome(Console.WriteLine);

This won't work probably after IfSome(Func<int, Unit> x) overload was added, maybe you can update docs:
optional.IfSome(i => WriteLine(i));
Or maybe change the overload? the docs version looks much better with static imports: 
optional.IfSome(WriteLine);

**Comment by louthy** [comment]
Thanks for the heads up, I'll take a look tomorrow.

**Comment by louthy** [comment]
Checked it, and yeah the variants of `IfSome` (and others) mean the docs were wrong.  I have fixed the docs rather than change the code.  I'm trying to avoid breaking changes now that the library is in heavy use; and the only way to make it work would be to have uniquely named variants of `IfSome`.
