### ISSUE TITLE
Record<A> and inheritance

### ISSUE THREAD

**Issue by SirUppyPancakes** [louthy/language-ext#303]
How does Record<A> handle inheritance (if at all)? Consider:

```
public class Test : Record<Test>
{
    public int A { get; }

    public string B { get; }

    public Lst<string> C { get; }

    public Test(int a, string b, Lst<string> c)
    {
        A = a;
        B = b;
        C = c;
    }
}

public class TestSub : Test
{
    public double D { get; }

    public TestSub(double d)
    {
        D = d;
    }
}
```

I am already a little nervous from something like this since the signature `Test.Equals(Test)` exists but not `TestSub.Equals(TestSub)`. However, trying to get something unexpected to happen doesn't work. Consider:

`var a = new Test(123, "abc", List("a", "b", "c")) == new Test(123, "abc", List("a", "b", "c"));`
a is true.
`var b = new TestSub(123, "abc", List("a", "b", "c"), 123.456) == new TestSub(123, "abc", List("a", "b", "c"), 123.456);`
b is true.
`var c = new TestSub(123, "abc", List("a", "b", "c"), 123.456) == new Test(123, "abc", List("a", "b", "c"));`
c is false.
`var d = new Test(123, "abc", List("a", "b", "c")) == new TestSub(123, "abc", List("a", "b", "c"), 123.456);`
d is false.

Does this mean that inheriting from Record<A>, and then inheriting again is a valid pattern?

**Comment by louthy** [comment]
There is no support for Record inheritance (which is also the case in
functional languages that have record data types). The best approach is to
use composition instead.

**Comment by SirUppyPancakes** [comment]
Makes sense, thanks.
Love the library so far!
