### ISSUE TITLE
The document on currying doesn't actually compile

### ISSUE THREAD

**Issue by bradphelan** [louthy/language-ext#308]
The documentation here

https://github.com/louthy/language-ext/wiki/Thinking-Functionally:-Currying

doesn't actually work with the C# type system

![image](https://user-images.githubusercontent.com/17650/33060775-b9b7ba50-ce99-11e7-9a71-e429a4e957b9.png)

But if you cast the PrintTwoParameters to a Func first then currying works. 

![image](https://user-images.githubusercontent.com/17650/33060849-f9261948-ce99-11e7-8543-a4525fb8b754.png)

C# can't make the two step jump from method group to lambda to type inference. I've been bitten by this a few times. Generally every time I think I'm being clever I'll find this restriction.

**Comment by louthy** [comment]
@bradphelan I have added a similar disclaimer to the partial-application page to the bottom of the currying page.  

> NOTE: When using a method as an argument to `par` and `curry` you will need to provide the generic arguments that represent the arguments in the method being partially-applied or curried.  I have omitted them from the examples above for clarity.  No such limitation exists when using `Func` however.

C# doesn't support inference with method-groups, even if there's a single method in the method group.  It's such a shitty situation.  Anyway, the best approach is to just provide the generic arguments.
```c#
    var f = curry<int, int, Unit>(PrintTwoParameters);
```
