### ISSUE TITLE
Question: Is there a way of chaining Try's?

### ISSUE THREAD

**Issue by NickSeagull** [louthy/language-ext#310]
Hello, first of all, thanks for making this awesome library.

Is there a way to write this Haskell code using LanguageExt? _(I'll use concepts from here)_

```haskell
foo :: Try Unit
foo = do
  deleteFolder "..."      -- deleteFolder returns "Try Unit", but it throws
  accessDB            -- Same with accessDB

main =
  case foo of
    Succ unit -> putStrLn "All correct"
    Fail e -> putStrLn (toString e)
```

The code on top will print the exception that deleteFolder caused, because of how do notation
in Haskell works.

If I try to write

```cs
match(
  from r in DeleteFolder("...")
  from s in AccessDB("...)
  select s,
  Succ: (Unit _) => PrintLine("All correct")
  Fail: (Exception e) => PrintLine(e.ToString())
```

It crashes due to the DeleteFolder exception, as it is not being captured.

Is there a way of chaining Try's without having to rely on matching each one of them?

Thanks!

**Comment by NickSeagull** [comment]
Nevermind, just solved it by myself:

```cs
            var result =
                from r in DeleteOutputFolder("...")
                from s in AccessDB("...")
                select r;

            result.Try().Match(
                Succ: (Unit _) => PrintLine("All correct"),
                Fail: ShowException
            );
```

**Comment by louthy** [comment]
@NickSeagull Your first example should work.   I'll re-open, because I'll need to check.

**Comment by louthy** [comment]
@NickSeagull Everything seems to work as it should.  Without seeing your definition of `DeleteFolder` I can't really dig much deeper.  But if it's defined like so:
```c#
    static Try<Unit> DeleteFolder(string x) => 
        throw new DirectoryNotFoundException();
```
Then yes, it will throw, because it's not a lambda.  It needs to be defined like this:
```c#
    static Try<Unit> DeleteFolder(string x) => () =>
        throw new DirectoryNotFoundException();
```
This is the full implementation I used to test:
```c#
    static Try<Unit> DeleteFolder(string x) => () =>
        throw new DirectoryNotFoundException();

    static Try<Unit> AccessDB(string x) => () =>
        throw new ArgumentOutOfRangeException();

    static Unit PrintLine(string x)
    {
        Console.WriteLine(x);
        return unit;
    }

    static void Issue310()
    {
        match(
          from r in DeleteFolder("...")
          from s in AccessDB("...")
          select s,
          Succ: (Unit _) => PrintLine("All correct"),
          Fail: (Exception e) => PrintLine(e.ToString()));
    }
```

**Comment by NickSeagull** [comment]
Oh, understood, the problem was that `DeleteFolder` wasn't defined like a lambda 😄 .

Closing this, thanks!
