### ISSUE TITLE
Value Tuple Versioning

### ISSUE THREAD

**Issue by CharlesTaylor7** [louthy/language-ext#311]
I'd like to start by saying, that I am very impressed with this library. I hope it can make functional programming more ubiquitous in C#. 

I am trying to get the Record functionality to work, but I'm getting the following error whenever I run code code against a class which inherits Record functionality: 
~~~~
System.TypeInitializationException : The type initializer for 'LanguageExt.RecordType`1' threw an exception.
  ----> System.TypeInitializationException : The type initializer for 'LanguageExt.ClassInstances.Class`1' threw an exception.
  ----> System.IO.FileNotFoundException : Could not load file or assembly 'System.ValueTuple, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.
   at LanguageExt.Record`1.Equals(RECORDTYPE other)
   at [MyProjectNameRedacted]:line 22
--TypeInitializationException
   at LanguageExt.IL.GetHashCode[A]()
   at LanguageExt.RecordType`1..cctor()
--FileNotFoundException
   at LanguageExt.ClassInstances.Class`1..cctor()
~~~~

I've double checked and System.ValueTuple 4.4.0 is installed in my project. 
Am I doing something wrong? 
Is it likely I am missing some transitive dependency?

**Comment by louthy** [comment]
I'm not at a pc at the moment to check if this is a Lang-ext dependency
issue or your one. But as a temporary solution have you tried an assembly
redirect in your app.config/web.config?

**Comment by CharlesTaylor7** [comment]
There was an existing redirect in our app.config, deleting it made it work. Thank you.
