### ISSUE TITLE
Using applicatives in c# with language ext

### ISSUE THREAD

**Issue by abdulkaderjeelani** [louthy/language-ext#318]
Please see the so link 
https://stackoverflow.com/questions/47886421/language-ext-how-to-use-applicatives-in-c

Any help / pointers is greatly appreciated.

**Comment by louthy** [comment]
@abdulkaderjeelani You're looking for the `Validation` type in language-ext to implement the example.  I won't do all the work for you, but you can take a look at [one of the units tests](https://github.com/louthy/language-ext/blob/master/LanguageExt.Tests/ValidationTests.cs) which has a real-world example of using the applicative behaviour of the `Validation` type. 

Most of the core types in language-ext support applicative behaviour [through the `apply` function](https://louthy.github.io/language-ext/LanguageExt.Core/LanguageExt/Prelude_.htm#apply<A,%20B,%20C>).

**Comment by abdulkaderjeelani** [comment]
Great! Thanks,
One more struggle is in schema modeling (Value Objects and Entities) with Language -ext record type,
In the sample, banking schema the if PersonName is a value object, and Account is an entity. Can they both be treated as RecordTypes? where getting structural equality of Value Object is extremely wonderful, What do do in case of entity, Can I model my entities without record types?
