### ISSUE TITLE
Documentation on how to use Try<T>

### ISSUE THREAD

**Issue by Profpatsch** [louthy/language-ext#32]
I’m not sure how to use it, how to create a Try, what implicitly converts to them and how exactly they work.

e.g. will this create a Try or break out of it:

```csharp
                catch (Exception e)
                {
                    if (e is MailAddressException || e is MailServiceException)
                    {
                         throw e;
                    }
                }
```

**Comment by louthy** [comment]
`Try<T>` is a delegate, so you should use it like so:

__In C# 6__
```C#
    Try<int> Divide(int x, int y) => () => 
        x / y;
```
__In C# 5 or older__
```C#
    Try<int> Divide(int x, int y)
    { 
        return () => x / y;
    }
```
Calling `Divide` with zero for `y` will return a `Try<int>` which when matched upon will give a `Fail` state, otherwise a `Succ` state, i.e.:

```C#
    var res = match( Divide(10,0),
                     Succ: v => v,
                     Fail: 0 );
```
The primary benefit is that the exception is treated as a return value like anything else, and you can chain the `Try`s together in a LINQ statement where an exception will cause the expression to 'early out'

Take a look at the unit tests for more examples: https://github.com/louthy/language-ext/blob/master/LanguageExt.Tests/TryMonadTests.cs

`TryOption<T>` gives the 3 possible states a function can return:
* Some value
* No value (usually `null` is used for this)
* Exceptional value

https://github.com/louthy/language-ext/blob/master/LanguageExt.Tests/TryOptionMonadTests.cs

**Comment by Profpatsch** [comment]
So everything that returns a `Func<T>` is also a `Try<T>`? Can I treat them as such? Or do I still somehow have to convert them? (Haskell guy, not much experience with C#’s type system.)

I’ve got a function that should only catch two types of exception, is it possible to achieve that, too? As I read in the code, `Try` basically does a `catch (Exception e)`; how would I narrow that down?

**Comment by fazouane-marouane** [comment]
You can create a `Try<T>` from any `Func<T>` using `LanguageExt.Prelude.Try`.

Example:
```csharp
using LanguageExt;
//...
var x = 0;
var f =Try(() => 1 / x);
f.Match(
    Succ: v => Console.WriteLine("Value: "+v),
    Fail: e => Console.WriteLine("Bang! " + e)
);
//...
```

(irrelevant to the issue: @louthy Thanks for your awesome work! I've just discovered LanguageExt an hour ago. This project implements all the most needed/helpful paradigms seen in other systems & languages. Thanks for bringing in this into C#.)

**Comment by Profpatsch** [comment]
I wonder why there is no implicit conversion from `Func<(),T>` to Try<T>; or is there?

**Comment by louthy** [comment]
`Try<T>` is defined thus:
```C#
    delegate TryResult<T> Try<T>();
```
Which is equivalent to:
```C#
    Func<T,TryResult<T>>
```
All of the support functions for `Try<T>` (like `Match`) are extension methods.  C# _will_ do implicit conversion in certain circumstances.  For example, the return value from a function:
```C#
    Try<T> Foo()
    {
        return () => ... ;      // This lambda is implicitly converted.
    }
```
Or an inline lambda where you specify the type of `res`
```C#
   Try<int> res = () => 123;   // This lambda is implicitly converted.
```
But not here:
```C#
   var res = () => 123;   // This won't even compile because C#'s type inference is poor for lambdas.
   res.Match(...);
```
The main reason for the `Try` function is to use it mid-expression.

**Comment by louthy** [comment]
@fazouane-marouane 
> irrelevant to the issue: @louthy Thanks for your awesome work! I've just discovered LanguageExt an hour ago. This project implements all the most needed/helpful paradigms seen in other systems & languages. Thanks for bringing in this into C#

Thank you, that's very nice to hear!  :)

**Comment by mookeyGit** [comment]
> `Try<T>` is defined thus:
> 
> ```cs
>     delegate TryResult<T> Try<T>();
> ```
> 
> Which is equivalent to:
> 
> ```cs
>     Func<TryResult<T>>
> ```
> 
> All of the support functions for `Try<T>` (like `Match`) are extension methods. C# _will_ do implicit conversion in certain circumstances. For example, the return value from a function:
> 
> ```cs
>     Try<T> Foo()
>     {
>         return () => ... ;      // This lambda is implicitly converted.
>     }
> ```
> 
> Or an inline lambda where you specify the type of `res`
> 
> ```cs
>    Try<int> res = () => 123;   // This lambda is implicitly converted.
> ```
> 
> But not here:
> 
> ```cs
>    var res = () => 123;   // This won't even compile because C#'s type inference is poor for lambdas.
>    res.Match(...);
> ```
> 
> The main reason for the `Try` function is to use it mid-expression.
> 
> > As I read in the code, Try basically does a catch (Exception e); how would I narrow that down?
> 
> There are extension methods for `Exception` (can be found in ExceptionMatch.cs) that can be used like so:
> 
> ```cs
>     Exception ex;
> 
>     var res =ex.Match()
>         .With<NotSupportedException>( e => "Not supported")
>         .With<NotImplementedException>( e => "Not implemented")
>         .Otherwise("An error");
> ```
> 
> `Otherwise` can either be a default value (as above), or a map (`Func<Exception,R>`). You can also use `OtherwiseReThrow()`.
> 
> It's not super pretty I'm afraid. You'd need to do the above in the `Fail` part of the `Try`. I could add something similar to the `Try` extension methods, let me know if you'd find that useful.

When I try your example, I get the following error: 
![image](https://user-images.githubusercontent.com/56838422/85596538-6b594a80-b60f-11ea-8956-91a201023c84.png)

I have the following using statements present.
```
using LanguageExt;
using static LanguageExt.Prelude;
```
What must I do to fix this? Thank you for your consideration.

**Comment by louthy** [comment]
> I wonder why there is no implicit conversion from Func<(),T> to Try<T>; or is there?

Implicit conversions can't be defined for delegates.  That's why I'm building a new `IO<A>` monad that will capture all of what `Try` is used for and more (it will be a `struct` that wraps a thunk).  

> When I try your example, I get the following error: 
> ![image](https://user-images.githubusercontent.com/56838422/85596538-6b594a80-b60f-11ea-8956-91a201023c84.png)

With `Try`, there's an `IfFail` override that gives you exception matching if needed:
```c#
    var res = try.IfFail()
                .With<NotSupported....
```

**Comment by mookeyGit** [comment]
> > I wonder why there is no implicit conversion from Func<(),T> to Try; or is there?
> 
> Implicit conversions can't be defined for delegates. That's why I'm building a new `IO<A>` monad that will capture all of what `Try` is used for and more (it will be a `struct` that wraps a thunk).
> 
> > When I try your example, I get the following error:
> > ![image](https://user-images.githubusercontent.com/56838422/85596538-6b594a80-b60f-11ea-8956-91a201023c84.png)
> 
> With `Try`, there's an `IfFail` override that gives you exception matching if needed:
> 
> ```cs
>     var res = try.IfFail()
>                 .With<NotSupported....
> ```

Okay, thank you for clarifying! :)
