### ISSUE TITLE
Method Naming Conventions in Prelude.cs

### ISSUE THREAD

**Issue by bender2k14** [louthy/language-ext#326]
Among the methods names in `Prelude.cs` that are more than one word, some include a capital letter to indicate the word split while others use only lowercase letters.

Only Lowercase Letters
1. `failwith` (2)
2. `raiseapp`
3. `isnull`
4. `notnull`

One Capital Letter
1. `exceptionIs`
2. `isDefault`
3. `notDefault`
4. `toString`

Is this intentional?  Would it be desirable to be more consistent in the use of capital letters when naming methods in `Prelude.cs`?

It would be reasonable to consider the naming (conventions) of methods in the other partial implementations of the `Prelude` type.  Instead on considering every method defined in the entirety of `Prelude`, I have only considered those in `Prelude.cs` in order to save time.

**Comment by louthy** [comment]
Purely elegance and sometimes to match naming in F#.  I don't want any of them renamed.  But, new functions should be `camelCase` where possible (as long as it's the most elegant, but I can make a judgement on commits)
