### ISSUE TITLE
Two inconsistenies among the parseT methods

### ISSUE THREAD

**Issue by bender2k14** [louthy/language-ext#331]
I have noticed two inconsistencies among the family `parseT` methods.

First, there is no `parseSByte` method.

Would you like this method added?

Second, in the documentation at the end of [the awful out parameter](https://github.com/louthy/language-ext#the-awful-out-parameter) section where it says (for example)
> `Int32.TryParse` becomes `parseInt`,
sometimes the `TryParse` method is referenced from the class (such as `Int32` in the above example) and sometimes it is from the alias keyword (such as in the example "`bool.TryParse` becomes `parseBool`).

I would like this to be consistent: either always use the class or always use the alias keyword.  The implementations of the `parseT` methods were also inconsistent in this way, and I changed them all to the use the alias keyword.  I find it easier to read code when it uses the alias keywords.  I don't have a preference about how this documentation should be.

Do you have a preference?  If not, then I will go with the class name.

**Comment by louthy** [comment]
>Int32.TryParse becomes parseInt,
sometimes the TryParse method is referenced from the class (such as Int32 in the above example) and sometimes it is from the alias keyword (such as in the example "bool.TryParse becomes parseBool).

Not sure what you're referring to here, that quote isn't related to the link.  Anyway, they're both aliases: `int` and `bool`, it's not using `Int32` or `Boolean`.  So, aliases are the preferred approach.  If you want to add `parseSByte`, go ahead.

**Comment by bender2k14** [comment]
Ah, that was a markdown typo.  Only the first line was meat to be quoted.  I fixed it now.

Very explicitly, I would like to change [the awful out parameter documentation](https://github.com/louthy/language-ext#the-awful-out-parameter) by changing

> `Int32.TryParse` becomes `parseInt`
> `Int64.TryParse` becomes `parseLong`
> `Int16.TryParse` becomes `parseShort`
> `Char.TryParse` becomes `parseChar`
> `Byte.TryParse` becomes `parseByte`
> `UInt64.TryParse` becomes `parseULong`
> `UInt32.TryParse` becomes `parseUInt`
> `UInt16.TryParse` becomes `parseUShort`

to

> `int.TryParse` becomes `parseInt`
> `long.TryParse` becomes `parseLong`
> `short.TryParse` becomes `parseShort`
> `char.TryParse` becomes `parseChar`
> `byte.TryParse` becomes `parseByte`
> `ulong.TryParse` becomes `parseULong`
> `uint.TryParse` becomes `parseUInt`
> `ushort.TryParse` becomes `parseUShort`
