### ISSUE TITLE
Prelude_UnitsOfMeasure.cs field names inconsistent

### ISSUE THREAD

**Issue by bender2k14** [louthy/language-ext#333]
The names of the fields in Prelude_UnitsOfMeasure.cs are inconsistent.

There are three fields with acronyms for identifiers and that represent a ratio of other units of measure.  

Two of them use the letter "p" to to indicate where the ratio is
1. `mph = miles/hour`
2. `kph = km/hour`

and one of them does not
1. `ms2 = m/s/s`.

**Comment by louthy** [comment]
It's based on common real world usage.
