### ISSUE TITLE
Possible missing type constraint for Record<>

### ISSUE THREAD

**Issue by bender2k14** [louthy/language-ext#334]
The main documentation this projects has a [section about records types](https://github.com/louthy/language-ext#difficulty-in-creating-immutable-record-types).  The first sentence of that documentation says
>This can now be achieved simply by deriving your type from `Record<A>` where `A` is the type you want to have structural equality and ordering.

and all of the examples that extend `Record<>` being of the form `class T : Record<T> {...}` for various types `T`.

From this, I expected to see, in the implementation of `Record<T>`, the type constraint `T : Record<T>`.  However, this constraint is not [there](https://github.com/louthy/language-ext/blob/aa9d77689daf4c9218f712e88363551fb4096610/LanguageExt.Core/DataTypes/Record/Record.cs#L14).

Should this constraint be added?

**Comment by louthy** [comment]
Yep, bit of an oversight there.  Fixed.
