### ISSUE TITLE
Use of reflection in Range<,,>

### ISSUE THREAD

**Issue by bender2k14** [louthy/language-ext#335]
The `Range<,,>` class [uses](https://github.com/louthy/language-ext/blob/aa9d77689daf4c9218f712e88363551fb4096610/LanguageExt.Core/DataTypes/Range/Range.cs#L22) reflection to obtain access to the constructor of a derived type.  To compensate for this, an exception is [thrown](https://github.com/louthy/language-ext/blob/aa9d77689daf4c9218f712e88363551fb4096610/LanguageExt.Core/Utility/IL.cs#L25) if the expected constructor doesn't exist.

Instead of using reflection to solve this problem, I would have made `Range<SELF, MonoidOrdA, A>` into an `abstract class` and added `protected abstract SELF Create(A min, A max, A step);` to provide `Range<,,>` the ability to instantiate instances of its derived type.  Using this approach, if the code compiles, then it is correct...which is to say, it is not possible to get into the situation that would have caused the exception to be thrown using the reflection approach.  This approach that I would take is known as the "factory method pattern".

Although `Range<SELF, MonoidOrdA, A>` is not currently abstract, one of its type constraints is `SELF : Range<SELF, MonoidOrdA, A>`, which, at least in spirit, conveys the intent that `Range<,,>` _not_ intended to be directly instantiated (i.e., the conveyed intent is that its constructors should only be called from a derived class).

Is there a reason that reflection is used here instead of the factory method pattern?

**Comment by louthy** [comment]
> Is there a reason that reflection is used here instead of the factory method pattern?

Good luck trying to make a virtual static method ;)  You can't have an abstract `Create` method when you don't have an instance to call it on.
