### ISSUE TITLE
Possible strengthening of Functor<FA, FB, A, B>

### ISSUE THREAD

**Issue by bender2k14** [louthy/language-ext#337]
The type class `Functor<FA, FB, A, B>` has four type parameters, but no formal constraints among them.  I think the intended constraints are that `FA` (resp. `FB`) is a category and `A` (resp. `B`) is the type of elements in that category.

Have you ever considered adding additional interfaces like `Category<T>` and then additional type constraints on `Functor<FA, FB, A, B>` like `where FA : Category<A>`?

**Comment by louthy** [comment]
Not really.  `FA` and `FB` are just data-types, and you can use any data-type you like as long as `FA` can be mapped to `FB` with a `Map` function that takes a delegate of `Func<A, B>`.  

It's not trivial to implement the `Map` function when `FA` isn't `F<A>` and `FB` isn't `F<B>` (other than something that just throws an exception).  So, the `Map` function is pretty much the constraining force here.

It's not ideal, but I think it will always be a bit of a rubbish solution without higher-kinds in C#.
