### ISSUE TITLE
Satisfy Left Catch for MTryAsync, MTryOptionAsync, and TMask MonadPlus

### ISSUE THREAD

**Issue by gwintering** [louthy/language-ext#339]
In the current Plus implementations for MTryAsync, MTryOptionAsync, and MTask, the left and right operations race and the first non faulted result is returned.  I think we should change these implementations to satisfy Left Catch, where the right operation is returned only if the left is faulted (or None in the case of MTryOptionAsync).  This would make the semantics of MTryAsync and MTryOptionAsync consistent with their non Async counterparts, as well a satisfy the conventional MonadPlus expectations.

I'd be happy to work on this if you agree with the goals but I wanted to get your thoughts first.  I could also add the extension method from #270 to each of the instances.

**Comment by bender2k14** [comment]
This definitely looks like something that should be changed.

The async monads are getting quite the overhaul right now in the branch [async-refactor](https://github.com/louthy/language-ext/tree/async-refactor) stemming from an issue raised in #317.  Not sure if it would be better to fix the issue you found before or after this branch is merged into master.

**Comment by louthy** [comment]
The race is a feature.  They provide something over the other operators.  There is no 'right' way to implement `Plus`, each type can use its own decision making to combine the result - so the fact they don't match their sync counterparts is irrelevant (and actually a benefit).  There are real benefits to taking the first successful result.

**Comment by gwintering** [comment]
>The race is a feature.

Yes, there are uses for racing.  But racing semantics hidden deep in a library are highly unexpected.  Most of the time we work very hard to prevent races because it's a particularly nasty form of non-determinism.

You seem committed to keeping racing as a feature, so as a compromise we could limit this change to `Try`s while allowing `Tasks` to race.  Accordingly, the rest of this comment does not apply to `MTask`.

>There is no 'right' way to implement Plus, each type can use its own decision making to combine the result

Of course the implementation is going to vary by type, but there are [some laws](https://wiki.haskell.org/Typeclassopedia#Laws_6) that most types try to support so they behave intuitively.  Racing left and right supports none of those laws, which leads to very unintuitive behavior.  `Try`s are all about handling errors, so it makes the most sense for them to support Left Catch.

>the fact they don't match their sync counterparts is irrelevant

The inconsistency is highly relevant.  Their names suggest they are related, and names are the first order documentation of a library.

> There are real benefits to taking the first successful result.

I'm sure there are, but we should consider the overall purpose of `Try`s, which is functional error handling.
There's a very nice symmetry to representing all your fault prone operations in the various `Try`s, which allows you to compose them to defer error handling till you have the context to do it properly.  Intuitively, you'd select the `Try` to use based on whether the operation might not produce a value (`Option`) and whether the process is inherently asynchronous (`Async`).  But if you follow that intuition, you get this extra racing behavior in the asynchronous case that hampers the monad's use in error handling.

It's be great if all the `Try`s hand similar semantics so you could uniformly write processes that mean "Try this, but if that fails try this other thing", irrespective of whether you were working with synchronous or asynchronous operations.  But now the asynchronous `Try`s have a performance optimization that prevents this consistent form.

**Comment by bender2k14** [comment]
I think the difference is the existence or absence of order.  @gwintering wants a monadic data type that represents the first task from an ordered collection that successfully completed while @louthy wants the same thing but for an unordered collection.

Before we try to solve the impossible problem of naming, I have a different question.  Are both of these monadic data types useful?

**Comment by louthy** [comment]
@gwintering Hi Greg, I've decent to relent on this one.  I have made the default behaviour of `MTryAsync.Plus`, `MTryOptionAsync.Plus`, and `MTask.Plus` to what you suggested.

As well, I have:
* Added `MTryFirstAsync`, `MTryOptionFirstAsync`, and `MTaskFirst`.  It seems sensible to make use of the ad-hoc polymorphic system to give the option to the programmer.  These _class-instances_ use the previous behaviour of racing to the first value.
* Added `Plus` and `PlusFirst` extensions to `TryAsync`, `TryOptionAsync`, and `Task`. 
* Added `plus` and `plusFirst` extensions to the Prelude for `TryAsync`, `TryOptionAsync`, and `Task`. 

This is in the `v2.2.4-beta` release.

**Comment by gwintering** [comment]
Thanks Paul!  Good call on the separate type to support racing.  That's where I was hoping we could move the behavior to.
