### ISSUE TITLE
Dependency of Rx

### ISSUE THREAD

**Issue by pnowosie** [louthy/language-ext#34]
Since version 1.5.0 Language-Ext is depended on 5 Rx packages, which makes me confused as I really need just Option, Either and tuples and list helpers. 
I wonder if it will be an effort to minimize dependencies of the Lang-Ext.Core?

**Comment by louthy** [comment]
The Core relies on `Rx-Main`, which brings in the other 4.  I have reduced that to only needing `Rx-Core` (which also brings in `Rx-Interfaces`) and `RxLinq`.  This reduces the dependency requirement.

Rx is a definitely a large part of the functional story in .NET; I want LangExt to be part of that story and not ignore it.  There are functions in `Option` that use it (`MatchObservable` for example) and some other support functions like `delay` for scheduling execution of a `Func<T>`.

And whilst I could split some of the functions out into a `LanguageExt.Core.Rx` dll; not all can.  The value of the `Prelude` partial class is that you can write `using static LanguageExt.Prelude` once and then you get the functional world in C#.  Unfortunately `partial` classes can't span multiple assemblies, and therefore I'd have to split the `Prelude` which I'd rather not do.

LangExt did previously depend on `System.Collections.Immutable` and a WeakConcurrency project which it now doesn't.  So hopefully the overhead isn't too bad.
