### ISSUE TITLE
Improve Memo for TryAsync, TryOptionAsync

### ISSUE THREAD

**Issue by gwintering** [louthy/language-ext#345]
The `Memo` implementations for both `TryAsync` and `TryOptionAsync` cache the  task _result_, which is wrapped up into a monad on subsequent calls.  But tasks already cache their results, so we should cache the  _task_ as soon as it's available and return it on subsequent calls.  This way we can provide the memoized value sooner and avoid unnecessary `Try` calls.

**Comment by bender2k14** [comment]
Can you provide links to these implementations?

**Comment by gwintering** [comment]
Here ya go: 3e268ceb450ecb06eb589966d68cab3ebb103105

**Comment by bender2k14** [comment]
Thanks.  Your change seems good.

Is this code supposed to be thread safe?

**Comment by gwintering** [comment]
Good question.  No, it's not thread safe in the sense that multiple threads could be racing to provide the memoized value, just like the current function.  The difference here is that the memoized value is just a `Task`, which can be produced quickly upon initiation of the underlying process, and not a `Result`, which wouldn't be available until the underlying process completes.  So there's a chance multiple `Task`s are created and all but one of them is thrown away.  And if the `Try`s produce a side effect that side effect could be caused multiple times.  But that chance is drastically reduced with this implementation because we can produce the memoized value quickly.

We could use `Lazy` to lock out other threads while one of them is providing the memoized value.  I actually think there's a strong case for that in the non async `Try`s.  But here it might be overkill because a `Task` itself is not a slow or expensive value to create.

We could provide both options with `Memo` and `MemoUnsafe` methods, but that would raise the issue of which one to use throughout the library, which frequently memoizes as part of other methods.

**Comment by louthy** [comment]
I don't think thread-safeness is important here.  It will be such a minor issue in the use-case of `TryAsync` and `TryOptionAsync` that the occasional double evaluation is acceptable.  The user can obviously use locks if they want to enforce thread-safety - and I'm fine with that.

Thanks for the work here @gwintering
