### ISSUE TITLE
Keeping global state in an ergonomic way.

### ISSUE THREAD

**Issue by jaccarmac** [louthy/language-ext#351]
Thanks for all the work on the library! It's a real pleasure to be able to work functionally in C# and has helped develop some intuition about functional programming.

At work I'm solving a problem which requires keeping track of a connection object to make various requests to a couple of different APIs. I'd like to be able to monadically access that connection so that every little function I write doesn't need an explicit connection parameter. I got a prototype up and running with Free, but Free involves a lot of boilerplate and the AST transformations it enabled weren't really applicable. So, I've switched to a typeclass-driven approach, and I'm running into some problems.

At first I had issues getting state passing between function invocations to work at all, but recently got a prototype for monadic I/O with state up and running. My sample code (which I unfortunately am not able to link to at the moment) can read and write from standard input and keeps track of how many times a read or write is performed. There's a record holding the states and return value, a monad instance with read and write, and the logic is in Bind so the state passing isn't done in parameters.

I'd like to do something similar, with wrapping of functions which require a connection, for the connection-related code, but noticed a quirk in the way LINQ works. When code is written out something like:

```
from _ in write("First line.")
from __ in write("Second line.")
from input in read()
select write(input)
```

state is not maintained between the unused results. I assume this is because LINQ doesn't have to structure the queries the way I would when writing in the fluent syntax, which accurately keeps track of state:

```
write("First line.").Bind(_ => write("Second line.")).Bind(_ => read()).Bind(input => write(input))
```

So is there a way to maintain the state of a given monad instantiation between function calls which may or may not use previous calls' results, or do I need to manually bind everything in the correct order because of limitations in LINQ? Is there a simpler solution that I'm missing? I've noticed that while there are quite a few interesting monads like State implemented IO is not, so perhaps trying to create a monadic global container is an anti-pattern and I should just stick with what C# has.

**Comment by louthy** [comment]
I'm not sure how `write` is working.  Normally you wouldn't use `from` with `write` *and* `select` with `write`.  Because `select` isn't monadic, it's merely a map at the end.  So your LINQ expression is more like:
```c#
write("First line").Bind(_ => write("Second line")).Bind(__ => read()).Map(input => write());
```
Which would give you a nested monad.

Without seeing your implementation I can't really comment on exactly what you need - but it seems like the connection is something that is fixed for the whole LINQ expression (i.e. it's not state that can change, but an 'environment').  You should probably look at the `Reader<Env, A>` monad for passing through an environment value:

First I'll create a basic `Connection` type that represents whatever it is you use to connect to your APIs:
```c#
    public class Connection : IDisposable
    {
        public static Connection Open() => new Connection();
        public Unit Close() => unit;

        public void Dispose()
        {
        }
    }
```
Then I add some handy overrides for working with a `Reader` monad that has a `Connection` environment:
```c#
    public static class Conn
    {
        public static Reader<Connection, Unit> write(string value) =>
            conn =>
            {
                // Do the code for writing
                return (unit, false);
            };

        public static Reader<Connection, string> read() =>
            conn =>
            {
                // Do the code for reading
                return ("", false);
            };

        public static Option<A> Use<A>(string url, Reader<Connection, A> ma)
        {
            var conn = new Connection(); // TODO: Actually connect to your API
            try
            {
                var (a, isFaulted) = ma(conn);
                return isFaulted
                    ? None
                    : Some(a);
            }
            catch(Exception)
            {
                return None;  // TODO: You may want to expose this, so return Try<A> 
                              //       instead of Option<A>
            }
            finally
            {
                conn.Dispose();
            }
        }

        public static Reader<Connection, A> Return<A>(A value) =>
            _ => (value, false);
    }
```
Here's a little test app based on your original:
```c#
    public static class Test
    {
        public static void F()
        {
            var expr = from _     in Conn.write("First line")
                       from __    in Conn.write("Second line")
                       from input in Conn.read()
                       select input;

            var result = Conn.Use("http://yourapi.com", expr);
        }
    }
```

**Comment by jaccarmac** [comment]
Thanks, this is exactly what I was looking for. Using delegates as monads wasn't clicking for me for whatever reason, but now that I see it applied to my specific use-case it's much more clear.
