### ISSUE TITLE
Record<RECORDTYPE> comparison operators doesn't use CompareTo override

### ISSUE THREAD

**Issue by faeriedust** [louthy/language-ext#355]
I made a class public class `VersionNumber : Record<VersionNumber>` and overrode `CompareTo` and called the following code, and it didn't call my ovveride?

`var a = new VersionNumber();
var b = new VersionNumber();
var c = a < b;`

I also couldn't tell from the code with ease or the documentation whether it was supposed to call my override or not, but I feel it's inconsistent that the CompareTo method is virtual and the comparison operators are defined but don't use the CompareTo method.

**Comment by louthy** [comment]
`CompareTo` is implemented automatically.  Why are you overriding it?

**Comment by bender2k14** [comment]
In defense of @faeriedust, why is `CompareTo` declared as `virtual` if you (@louthy) don't expect anyone to override it?  Is the presence of this key word a mistake?

(`Equals` and `GetObjectData` are also declared as `virtual`.  Is the presence of this key words a mistake?)

**Comment by louthy** [comment]
You can override it if you like.  But you’re not getting any functionality for free.  That’s not the problem of the Record type, it’s the problem of the programmer who wants bespoke behaviour over what the Record type provides.

I am not prohibiting overriding because it may be useful in certain circumstances,  but if you want operators you must implement them.

**Comment by faeriedust** [comment]
Can we at least make it more clear via documentation what the implementations for the operators are doing then, if not calling .CompareTo?

There was no documentation, so I stared at the code for like 10 min before giving up, lol.

Is there a reason they can't call the .CompareTo method? Isn't calling .CompareTo normally the expected thing to do for those operators?

**Comment by bender2k14** [comment]
In your PR, what `x` is `null`?

**Comment by faeriedust** [comment]
I was drunkenly and thought that it couldn't be null before, i'll fix it, my bad

**Comment by faeriedust** [comment]
I was drunkenly is the short answer.
I see there are some tests for that case as well, I just had to run them.

`TestClass x = new TestClass(1, "Hello", Guid.Empty);
TestClass y = null;
TestClass z = null;

Assert.True(x > y);
Assert.True(x >= y);
Assert.True(y < x);
Assert.True(y <= x);
Assert.True(y == z);
Assert.True(z == y);`

https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/nullable-types/using-nullable-types

**Comment by faeriedust** [comment]
I was drunkenly is the short answer.
I see there are some tests for that case as well, I just had to run them.

This tests seems backwards compared to what I would expect, but I guess I can match it for now.
```
TestClass x = new TestClass(1, "Hello", Guid.Empty);
TestClass y = null;
TestClass z = null;

Assert.True(x > y);
Assert.True(x >= y);
Assert.True(y < x);
Assert.True(y <= x);
Assert.True(y == z);
Assert.True(z == y);
```

Normally if one side is null, the comparison goes to false, not true, in C#
https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/nullable-types/using-nullable-types

**Comment by faeriedust** [comment]
I updated my PR to match the original behavior for null orderings.. They seem quite odd to me.

Should we consider changing the default implementation to CompareTo (and the operators) to match the MSDN convention for null comparisons?

**Comment by louthy** [comment]
I have added this to the documentation

NOTE: Inheritance is not supported in Record derived types. So, if you derive a type from a type that derives from Record then you won't magically inherit any equality, ordering, hash-code, etc. behaviours. This feature is explicitly here to implement record-like functionality, which - in other functional languages - do not support inheritance. Equality of origin is explicitly checked for also.

**Comment by faeriedust** [comment]
My issue had nothing to do with inheriting from a Record derived type.
I simply derived from Record and overrode the virtual .CompareTo method.

My PR preserved the exact same existing functionality, except made it more intuitive what will happen if you override the CompareTo method.

Also I don't understand what the performance hit you mentioned is.

**Comment by bender2k14** [comment]
> Also I don't understand what the performance hit you mentioned is.

You replaced a static call with a virtual call.  Virtual methods involve a layer of indirection that static ones don't.  Therefore, you code is slightly slower.
