### ISSUE TITLE
Order of IgnoreBaseAttribute

### ISSUE THREAD

**Issue by bender2k14** [louthy/language-ext#359]
[This code](https://github.com/louthy/language-ext/blob/async-refactor/LanguageExt.Core/DataTypes/Record/RecordType.cs#L18) (new in `async-refactor`) only considers the first attribute.  If the `IgnoreBaseAttribute` wasn't the only attribute and it didn't come first, then it equivalent to not using it at all.

Can I change to code to consider all attributes instead of just the first?

**Comment by louthy** [comment]
That's a bug, yes.  Should probably change to:
```c#
bool includeBase = !(typeof(A).CustomAttributes
                              .Exists(a => a.AttributeType.Name == "IgnoreBaseAttribute"));
```

**Comment by bender2k14** [comment]
*sigh* Sorry about all those closed PRs.  I was having some difficulties this morning.  Everything should be good now.
