### ISSUE TITLE
What is unsafe about MatchUnsafeAsync<>?

### ISSUE THREAD

**Issue by bender2k14** [louthy/language-ext#369]
In the `async-refactor` branch, what is unsafe about [the](https://github.com/louthy/language-ext/blob/async-refactor/LanguageExt.Core/ClassInstances/Monad/MTaskFirst.cs#L228) [three](https://github.com/louthy/language-ext/blob/async-refactor/LanguageExt.Core/ClassInstances/Monad/MTaskFirst.cs#L245) [methods](https://github.com/louthy/language-ext/blob/async-refactor/LanguageExt.Core/ClassInstances/Monad/MTaskFirst.cs#L262) in `MTaskFirst<>` called `MatchUnsafeAsync<>`?  Their implementations look identical to their `MatchAsync<>` counterparts.

**Comment by louthy** [comment]
This has highlighted another area that needed a refactor, which I've started on in the async branch (that branch should really be seen as 'next major release', perhaps even version `3.0`).  Anyway, the 'Unsafe' suffix is always used to indicate that you may get a `null` value returned.  I have been less aggressive with enforcing it with some types (like `Task`).  

It seems clear to me that `Unsafe` is similar to `Async` in that they're variants on core types and should have their own type-class support.  

So, I have added `OptionalUnsafe`, `OptionalUnsafeAsync`, ChoiceUnsafe`, and `ChoiceUnsafeAsync` (actually the last one still needs adding).  The types which are safe by default (`Option`, `Either`, etc.) now have their class-instances (`MOption`, `MEither`, etc.) derive from both the safe and unsafe type-classes.  

But. the types that are unsafe by default (`OptionUnsafe`, `EitherUnsafe`, etc.) now have their class-instances derive only from the unsafe type-classes.

The theory here is that you can make a safe value unsafe, but not make an unsafe value safe.

I have made some types safe by default that weren't before: `Task`, `Try`, `TryAsync`, `TryOption`, `TryOptionAsync`.

It's still early and will continue along with the provision of the `...Async` types when I get time (or if anybody wants to volunteer).

Anyway, this is all in `v2.1.13-beta`
