### ISSUE TITLE
Add EditorConfig file

### ISSUE THREAD

**Issue by bender2k14** [louthy/language-ext#370]
I would like to add an [EditorConfig](https://docs.microsoft.com/en-us/visualstudio/ide/create-portable-custom-editor-options) file to the root of language-ext to automatically enforce its coding conventions, such at indentation style (tabs vs spaces) and indent size.  These settings would override a developer's personal settings in Visual Studio.

Do you @louthy like this idea?

If so, feel free to state you what values you want for the [supported settings](https://docs.microsoft.com/en-us/visualstudio/ide/create-portable-custom-editor-options#supported-settings).  Otherwise, I will infer the settings based on the current files.

**Comment by louthy** [comment]
Seems reasonable.  I didn't even know of the existence of this, so give me a bit of time to look into it.  I'm super busy atm.

**Comment by bender2k14** [comment]
No hurry.  Take your time.

I only recently heard about this myself.  Support for Visual Studio used to come by way of [an extension](https://github.com/editorconfig/editorconfig-visualstudio) but as of Visual Studio 2017 (specifically [version 15.0](https://docs.microsoft.com/en-us/visualstudio/releasenotes/vs2017-relnotes-v15.0)), the support is built in.
