### ISSUE TITLE
None of the types are recognised

### ISSUE THREAD

**Issue by MrYossu** [louthy/language-ext#371]
Hello,

just started a new C# console app in VS2017, added the LanguageExt.Cire Nuget package, and typed the following line of code inside Main()...

`  var ab = Tuple("a","b");`

This gave an error on Tuple, as it seems to be trying to use the System.Tuple. I tried typing...

`  var optional = Some(123);`

...but got an error that Some does not exist in the context.

I have a using for LanguageExt, and have tried various combinations of the namespaces within, but nothing seems to help. Even ReSharper doesn't have any suggestions as to where to find the types.

What am I doing wrong? Thanks

**Comment by louthy** [comment]
You need to add:

    using static LanguageExt.Prelude;

It’s right there in the documentation ;)

**Comment by MrYossu** [comment]
Ah, I was working my way down the [main project page](https://github.com/louthy/language-ext), trying the examples there. Didn't mention anything about usings there, so didn't know about this one :)

Thanks for the reply.

**Comment by louthy** [comment]
I guess you missed it: https://github.com/louthy/language-ext/blob/master/README.md#getting-started

**Comment by MrYossu** [comment]
OK, you got me there :)
