### ISSUE TITLE
Chain of asynchronous operations that return Either using LINQ's from...select syntax

### ISSUE THREAD

**Issue by crodriguezvega** [louthy/language-ext#376]
I posted a [question](https://stackoverflow.com/questions/48866353/chain-asynchronous-operations-that-return-either-using-language-ext-in-c-sharp) in StackOverflow regarding the use of LINQ's `from...select` syntax to chain asynchronous operations that return `Either<,>`. I haven't got an answer yet that satisfies me fully, so I thought of asking here as well.

Assuming that I have these functions:

	public static async Task<Either<string, int>> Op1()
	{
		return await Task.FromResult(1);
	}

	public static async Task<Either<string, int>> Op2()
	{
		return await Task.FromResult(2);
	}

	public static async Task<Either<string, int>> Op3()
	{
		return await Task.FromResult("error");
	}

	public static async Task<Either<string, int>> Calculate(int x, int y, int z)
	{
		return await Task.FromResult(x + y + z);
	}

I would like to write code like this to chain the operations:

	var res = await (from x in Op1()
                     from y in Op2()
	                 from z in Op3()
	                 from w in Calculate(x, y, z)
		         select w);

But the compiler complains with `cannot convert from 'LanguageExt.Either<string, int>' to 'int'` for the arguments of `Calculate`.

Thanks to the comments in StackOverflow , I got it working by writing the code instead like this:

            var res = await Op1()
                .BindAsync(x => Op2()
                .BindAsync(y => Op3()
                .BindAsync(z => Calculate(x, y, z)
                .BindAsync(w => (Either<string, int>)w))));

But I would rather use the cleaner `from...select` syntax. In StackOverflow I was also suggested to used the `EitherAsync<,>` type instead of `Task<Either<,>>`, but then the compiler complains with `The return type of an async method must be void, Task, Task<T>, ValueTask<T> or another tasklike type`. 

Is the `EitherAsync<,>` type meant to be used together with `async...await` and `from...select` syntaxes? Is it supposed to be a `tasklike` type?

I installed version 2.2.11-beta of the package from Nuget.

**Comment by bender2k14** [comment]
> Is the `EitherAsync<,>` type meant to be used together with `async...await` and `from...select` syntaxes? Is it supposed to be a `Task`-like type?

It is.  Now that I try your code myself, it seems that `EitherAsync<,>` is missing some plumping required to make the `async...await` and `from...select` syntaxes work.  This is something that I don't fully understand yet.  I tried to add the methods that I thought were necessary, but it still didn't work.

**Comment by crodriguezvega** [comment]
> It is.

Thanks. Knowing that the intention is to make the type task-compatible is good enough for me for now.

**Comment by louthy** [comment]
@crodriguezvega Hi Carlos, sorry for the slow reply, been hella busy and am only just getting round to a backlog of questions here.

Your first example should work as you expected it to do.  I've been trying to investigate this evening, but it's a weird one.  

If you include:
```c#
    public static class Ext
    {
        public static Task<Either<L, C>> SelectMany<L, A, B, C>(
            this Task<Either<L, A>> ma,
            Func<A, Task<Either<L, B>>> bind,
            Func<A, B, C> project) =>
            ma.BindT(a =>
                bind(a).BindT(b =>
                    default(MEither<L, C>).Return(project(a, b))));
    }
```
In your project it should work.  But bizarrely that code already exists in lang-ext and for some unknown reason the compiler isn't spotting it for use with LINQ.  If I copy it to the source file then it does pick it up.  So, I'll need to do some digging.  It's either an idiotic mistake that I can't quite see right now or a possible compiler issue.

As mentioned you can use `EitherAsync`.  I'm not sure what missing plumbing is being talked about, because you can create them in a number of ways, from values or Tasks.
```c#
    public class Issue376
    {
        static Task<int> Number(int n) => n.AsTask();
        static Task<string> Error(string err) => err.AsTask();

        public static EitherAsync<string, int> Op1() =>
            Number(1);

        public static EitherAsync<string, int> Op2() =>
            RightAsync<string, int>(Task.FromResult(2));

        public static EitherAsync<string, int> Op3() =>
            Error("error");

        public static EitherAsync<string, int> Calculate(int x, int y, int z) =>
            (x + y + z);

        public static async Task Test()
        {
            var res = await (from x in Op1()
                             from y in Op2()
                             from z in Op3()
                             from w in Calculate(x, y, z)
                             select w)
                            .IfLeft(0);
        }
    }
```
If you desperately want to use `Task<Either<L, R>>` then you can easily convert one to an `EitherAsync<L, R>` by calling `ToAsync()` on it (you will need the latest version for that)
```c#
    public class Issue376_2
    {
        public static async Task<Either<string, int>> Op1()
        {
            return await Task.FromResult(1);
        }

        public static async Task<Either<string, int>> Op2()
        {
            return await Task.FromResult(2);
        }

        public static async Task<Either<string, int>> Op3()
        {
            return await Task.FromResult("error");
        }

        public static async Task<Either<string, int>> Calculate(int x, int y, int z)
        {
            return await Task.FromResult(x + y + z);
        }

        public static async Task Test()
        {
            var res = await (from x in Op1().ToAsync()
                             from y in Op2().ToAsync()
                             from z in Op3().ToAsync()
                             from w in Calculate(x, y, z).ToAsync()
                             select w)
                            .IfLeft(0);
        }
    }
```

**Comment by bender2k14** [comment]
> I'm not sure what missing plumbing is being talked about

I was referring to this `SelectMany` method that you @louthy included in your comment.  Because I couldn't get the `from...select` LINQ syntax working for this type, I assumed that LanguageExt was missing the needed method and that I didn't understand this feature of C# well enough yet to figure out what method was missing.

> But bizarrely that code already exists in lang-ext and for some unknown reason the compiler isn't spotting it for use with LINQ. If I copy it to the source file then it does pick it up. So, I'll need to do some digging. It's either an idiotic mistake that I can't quite see right now or a possible compiler issue.

I am very interested now to see what the fix is.  If this problem doesn't get solved right away, then I will try my hand at it.

**Comment by crodriguezvega** [comment]
@louthy Thanks for the answer, Paul, and sorry for this late reply. 

I tried using `EitherAsync<L, R>` as the return type of my functions, but then I could not get the code to compile if I wanted to use await inside the implementation of the method. I am getting the error 
`The return type of an async method must be void, Task, Task<T>, ValueTask<T> or another tasklike type`. Is this expected behavior? I have tested this on version 2.2.18-beta.

So I fall back to using `Task<Either<L, R>>` as the return type and call `ToAsync()` on the functions that I want to chain using `from...select` syntax. This works fine with `async...await` functions.

Amazing library, by the way.

**Comment by bender2k14** [comment]
> Is this expected behavior? I have tested this on version 2.2.18-beta.

Can you share the code that is giving you this error?

**Comment by crodriguezvega** [comment]
@bender2k14 I am just trying to write some code like this:

    public static async  EitherAsync<string, int> Op1()
    {
        return await Task.FromResult(1);
    }

But the compiler complains with `The return type of an async method must be void, Task, Task<T>, ValueTask<T> or another tasklike type`.

**Comment by bender2k14** [comment]
`EitherAsync<,>` has these four implicit operators:
```
public static implicit operator EitherAsync<L, R>(Task<L> value);
public static implicit operator EitherAsync<L, R>(L value);
public static implicit operator EitherAsync<L, R>(Task<R> value);
public static implicit operator EitherAsync<L, R>(R value);
```

so you can just write

```
public static EitherAsync<string, int> Op1() =>
  Task.FromResult(1);
```

or even just

```
public static EitherAsync<string, int> Op2() =>
  1;
```

**Comment by crodriguezvega** [comment]
The statement `await Task.FromResult(1)` was just an example; it's not literally what I am trying to achieve in my case. :-)

Inside of method `Op1` I would like to be able to await other asynchronous calls, like to a database or an http request. The results of those calls determine whether Op1 returns the `L` or the `R` values.

**Comment by crodriguezvega** [comment]
@bender2k14 In my case I am trying to do something like the following:

    public async EitherAsync<string, User> GetUserAsync(int id)
    {
       var user = await _userRepository.GetAsync(id);
       return (user == null) ? "Could not find user" : user;
    }

where `_userRepository` is a class member object to access a database.

There is for sure a better FP way of writing this code (similar to your example in the previous comment), but I am just curious to know if it is possible to await an asynchronous call inside a method that returns `EitherAsync<L, R>`.

**Comment by bender2k14** [comment]
I think using `async`/`await` usually means that you are _not_ doing things functionally.

Ideally you can avoid using `null`.  I would recommend having the return type of `_userRepository.GetAsync` be `OptionAsync<User>`.  Then you could write
```
public static EitherAsync<string, User> GetUserAsync(int id) =>
  _GetUserBool(id).ToEither("Could not find user");
private static OptionAsync<User> _GetUserBool(int id) =>
  new User();
public class User { }
```

Otherwise, you can first turn the type of the return value into `OptionAsync<User>` then do as above, like
```
public static EitherAsync<string, User> GetUserAsync(int id) =>
  _GetUserBool(id).Map(Some).ToAsync().ToEither("Could not find user");
private static Task<User> _GetUserBool(int id) =>
  new User().AsTask();
public class User { }
```

**Comment by crodriguezvega** [comment]
Thanks for the examples. I understand then that the `EitherAsync<L, R>` type is best used when the method does not await the task, but just returns it and somewhere higher up in the call stack it is awaited.
