### ISSUE TITLE
Unneeded code following Task.WhenAll

### ISSUE THREAD

**Issue by bender2k14** [louthy/language-ext#377]
Recall issue #367.  The [method in question](https://github.com/louthy/language-ext/blob/master/LanguageExt.Core/ClassInstances/Monad/MTask.cs#L197) looks like
```
public async Task<A> Apply(Func<A, A, A> f, Task<A> fa, Task<A> fb) 
{
    await Task.WhenAll(fa, fb);
    return !fa.IsFaulted && !fb.IsFaulted
        ? f(fa.Result, fb.Result)
        : throw fa.Exception;
}
```

I said that this method might be throwing the wrong exception.  Actually, I was wrong.

The [documentation of `Task.WhenAll`](https://msdn.microsoft.com/en-us/library/hh160374(v=vs.110).aspx) says

> If any of the supplied tasks completes in a faulted state, the returned task will also complete in a TaskStatus.Faulted state, where its exceptions will contain the aggregation of the set of unwrapped exceptions from each of the supplied tasks.

and the [documentation of await](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/await) says

> If you await a task-returning async method that causes an exception, the await operator rethrows the exception.
...
> A single task that is in a faulted state can reflect multiple exceptions. For example, the task might be the result of a call to Task.WhenAll.  When you await such a task, the await operation rethrows only one of the exceptions. However, you can't predict which of the exceptions is rethrown.

Therefore, the above method contains unneeded code.  It is equivalent to this simpler method
```
public async Task<A> Apply(Func<A, A, A> f, Task<A> fa, Task<A> fb) 
{
    await Task.WhenAll(fa, fb);
    return f(fa.Result, fb.Result);
}
```

The case is similar for canceled tasks.  The same `Task.WhenAll` documentation says

> If none of the supplied tasks faulted but at least one of them was canceled, the returned task will end in the TaskStatus.Canceled state.

and the same `await` documentation says

> If you await a task-returning async method that's canceled, the await operator rethrows an OperationCanceledException.

[Here](https://github.com/louthy/language-ext/blob/async-refactor/LanguageExt.Core/ClassInstances/Monad/MEitherAsync.cs#L33) is an example in the `async-refactor` branch that includes a call to `Task.IsCanceled` after `await`ing the same task (via a call to `Task.WhenAll`).

I have not yet identified all locations in Language.Ext that use this kind of unneeded code.  I volunteer to find all such locations in the `async-refactor` branch and create a PR that removes the unneeded code.

**Comment by louthy** [comment]
Sure, go ahead. Just be careful in TryAsync and TryOptionAsync which does
need to check the Faulted state of the Result

**Comment by bender2k14** [comment]
I definitely noticed that `LanguageExt.Result<>.IsFaulted` could be confused with `System.Threading.Tasks.Task.IsFaulted`.

For `TryAsync` and `TryOptionAsync`, I will maintain the intent, which is to return a `Result<>` containing the exception instead of throwing the exception.  For the remaining cases, my plan is to maintain the behavior.  Certainly let me know if you would like any of these intents to replace the current behavior.
