### ISSUE TITLE
Replacing Match with Map call?

### ISSUE THREAD

**Issue by NightWatchman** [louthy/language-ext#379]
I have this construct, and I feel like there's a cleaner way to do it, but I don't know how.
If you'll note the `Left` calls all do the same thing on the same type, and I think I'm "unwrapping" the either needlessly. 
```C#
return await DataAccessModule.Connect(connectionString).Match<Task<Either<DataAccessException, string>>>(
            Right: async db =>
            {
              // RecordExists() returns Task<Either<DataAccessException, bool>>
              return await (await RecordExists(db, request.FshApplicationKey).ConfigureAwait(false))
                  .Match<Task<Either<DataAccessException, string>>>(
                      Right: async isExistingRec => isExistingRec
                          // UpdateRequest() and InsertRequest() both return Task<Either<DataAccessException, string>>
                          ? await UpdateRequest(db, request).ConfigureAwait(false)
                          : await InsertRequest(db, request).ConfigureAwait(false),
                      Left: ex => throw ex).ConfigureAwait(false);
            },
            Left: ex => throw ex).ConfigureAwait(false);
```

Since calls to .Map on an either are designed to ignore the `Left` state and just pass it up the chain, while mapping the `Right` results I feel like I should be able to do a .Map call and then one call to .Match instead of two. Something like this, but I can't get the types and async to work.
```C#
return await DataAccessModule.Connect(connectionString).Match<Task<Either<DataAccessException, string>>>(
            Right: async db =>
            {
              var recExists = await RecordExists(db, request.FshApplicationKey).ConfigureAwait(false);
              // Mapping bool -> string, with side effects
              return await recExists.MapAsync<Task<string>>(async isExistingRec => isExistingRec
                  ? await UpdateRequest(db, request).ConfigureAwait(false)
                  : await InsertRequest(db, request).ConfigureAwait(false));
            },
            Left: ex => throw ex).ConfigureAwait(false);
```
Can you help me figure out what it is I'm doing wrong?

Thanks for all the work you've put into this library, it's appreciated!

**Comment by bender2k14** [comment]
What is the return type of `DataAccessModule.Connect`?

**Comment by bender2k14** [comment]
Your two occurrences of `Left: ex => throw ex` are unexpected.  I don't think you meant to do that.  It seems your intended return type for this code is `Task<Either<DataAccessException, string>>`.  In which case, you can just return these two instances of `DataAccessException` instead of throwing them.

I think the method you are looking for is `BindAsync`.  Here is my attempt to use that method to simplify your code.  I stubbed everything out so that the following code complies.  Please let me know if I got any of the specifications incorrect.

```
internal class MyClass
{
    internal Task<Either<DataAccessException, string>> Method(
        string connectionString,
        MyRequest request
    ) => DataAccessModule
        .Connect(connectionString)
        .BindAsync(db =>
            RecordExists(db, request.FshApplicationKey)
                .BindAsync(isExistingRec => isExistingRec
                    ? UpdateRequest(db, request)
                    : InsertRequest(db, request)));

    private Task<Either<DataAccessException, bool>> RecordExists(MyDatabase db, FshApplicationKey fshApplicationKey) => throw new NotImplementedException();
    private Task<Either<DataAccessException, string>> UpdateRequest(MyDatabase db, MyRequest request) => throw new NotImplementedException();
    private Task<Either<DataAccessException, string>> InsertRequest(MyDatabase db, MyRequest request) => throw new NotImplementedException();
}

internal class MyRequest
{
    public FshApplicationKey FshApplicationKey { get; }
}

internal class DataAccessModule
{
    internal static Either<DataAccessException, MyDatabase> Connect(string connectionString) => throw new NotImplementedException();
}

internal class FshApplicationKey { }
internal class MyDatabase { }
internal class DataAccessException : Exception { }
```

**Comment by NightWatchman** [comment]
Hey thanks! That looks like what I need. I'll have to research BindAsync and see how it works.
I thought I had gotten closer by trying this, but I had trouble because `UpdateRequest` and `InsertRequest` return a `Task<Either<DataAccessException, String>>` so it wouldn't return from that `Map` call because that call wanted a `Task<string>`, not a `Task<Either<DataAccessException, String>>`. I was also unsure of when to use `Map` and when to use `MapAsync`.

```C#
return await DataAccessModule.Connect(connectionString).MapAsync(db =>
        {
          return RecordExists(db, request.FshApplicationKey).Map(exists =>
          {
            var result = exists
                ? UpdateRequest(db, request)
                : InsertRequest(db, request);
            // return result; // What I wanted to do,
            return ""; // Returning a string as an experiment got the code to compile.
          });
        }).ConfigureAwait(false);
```

**Comment by louthy** [comment]
@NightWatchman Hi Eric, it really is about trying to stick to a common monadic type throughout or lifting/mapping to that common type.  If I were you I'd like at `EitherAsync<L, R>` and try to use that rather than `Task<Either<L, R>>`.   If you have an `Either` and you want it to work with other `EitherAsync` types then call `either.ToAsync()` to make it into one.

Then it's important to understand the difference between `Map` and `Bind` (or the async versions `MapAsync` and `BindAsync`).  So, head over [to the Thinking Functionally section of the Wiki for a discussion on this](https://github.com/louthy/language-ext/wiki/Thinking-Functionally:-What-is-LINQ-really%3F)

Once you've groked that then you'll see how to compose these types together.  Take a look at @bender2k14 's example, but replace the `Task<Either<>>`s with `EitherAsync`.  Also, take a look at my version using LINQ for the `Method`.  It's easier to understand than the chain of `Bind` calls (even though that's what it's doing behind the scenes)

```c#
internal class MyClass
{
    internal EitherAsync<DataAccessException, string> ProcessReq(string connectionString, MyRequest request) =>
        from db in DataAccessModule.Connect(connectionString).ToAsync()
        from ex in RecordExists(db, request.FshApplicationKey)
        from rs in ex
            ? UpdateRequest(db, request)
            : InsertRequest(db, request)
        select rs;

    private EitherAsync<DataAccessException, bool> RecordExists(MyDatabase db, FshApplicationKey fshApplicationKey) => throw new NotImplementedException();
    private EitherAsync<DataAccessException, string> UpdateRequest(MyDatabase db, MyRequest request) => throw new NotImplementedException();
    private EitherAsync<DataAccessException, string> InsertRequest(MyDatabase db, MyRequest request) => throw new NotImplementedException();
}

internal class MyRequest
{
    public FshApplicationKey FshApplicationKey { get; }
}

internal class DataAccessModule
{
    internal static Either<DataAccessException, MyDatabase> Connect(string connectionString) => throw new NotImplementedException();
}

internal class FshApplicationKey { }
internal class MyDatabase { }
internal class DataAccessException : Exception { }
```

**Comment by NightWatchman** [comment]
@louthy Thanks for chiming in! My own research into bind vs map has enlightened me as to why I needed bind and not map in the previous construct and things are going pretty well for me. I hadn't thought about using EitherAsync so I'll probably start doing that. Your LINQ example is quite neat, and indeed easier to understand. I appreciate y'all taking the time to maintain this project and also to engage with it's users. I'm going to go ahead and close this "issue" since my understanding of these constructs is much more complete now.

**Comment by bender2k14** [comment]
> but replace the `Task<Either<>>`s with `EitherAsync`

`EitherAsync<,>` is in the pre-released version of LanguageExt but no the released version.

**Comment by NightWatchman** [comment]
Ah, good to know. Thanks!
