### ISSUE TITLE
Intent of SeqList<A>.New(IList<A> seq, int index = 0, int count = -1)

### ISSUE THREAD

**Issue by bender2k14** [louthy/language-ext#383]
I am wondering about the intent of [this static constructor function](https://github.com/louthy/language-ext/blob/master/LanguageExt.Core/DataTypes/Seq/SeqList.cs#L33) for `SeqList<>`.

```
public static Seq<A> New(IList<A> seq, int index = 0, int count = -1) =>
    seq.Count == 0
        ? Empty
        : new SeqList<A>(seq, index, count);
```

The only caller within LanguageExt doesn't provide arguments for the optional parameters.

Is the intent that
- one can pass in a positive value for `index` in order to exclude the beginning of `seq`,
- one can pass in a value less than `seq.Count` for `count` in order to exclude the end of `seq`, and
- the behavior is unspecified if one passes in inconsistent values for `seq`, `index`, and `count` (such as `index = -1`)?

**Comment by louthy** [comment]
Seq<A> doesn't contain a method called New

**Comment by bender2k14** [comment]
Oh, I meant `SeqList<>`.  Sorry for the confusion.  I added a link to the code (which I should have done initially).

**Comment by louthy** [comment]
Scroll down, you’ll see its use case - even if it isn’t used directly

**Comment by louthy** [comment]
The intended behaviour is to create a windowing system into the backed list - so that there is no need to create sub-lists when doing operations like Take and Skip - which are big pain points in IEnumerable.  Where do you see the 'advantage of making it slightly faster'?  It's designed for performance already, is there something that you think isn't as fast as it could be, because I can't see much area for improvement when just manipulating integers.  

Remember SeqList isn't public and `New` will never be seen by a user (nor will the constructors).

**Comment by bender2k14** [comment]
The constructor has [this ternary operator](https://github.com/louthy/language-ext/blob/master/LanguageExt.Core/DataTypes/Seq/SeqList.cs#L19), and I think it can be removed.

The only time we expect `count == -1` to be true is when this constructor is called from the `New` method in my original post.  There might be bugs in this class that put it into an invalid state from which it is possible to get `-1` passed in for `count` in one of the other three calls.  Otherwise, an invariant of `SeqList<>` is that `count > 0`.

One of the bugs could be the behavior of [`Skip`](https://github.com/louthy/language-ext/blob/master/LanguageExt.Core/DataTypes/Seq/SeqList.cs#L67) when the parameter is a negative value.  The documentation for the `IEnumerable<>` extension method `Skip<>` [says](https://msdn.microsoft.com/en-us/library/bb358985(v=vs.110).aspx)
> If count is less than or equal to zero, all elements of source are yielded.

Oh, I didn't notice that `SeqList<>` is `internal`.  So after first investigating some bugs, we should be able to simplify this code while also improving the performance (ever so slightly ;) ).

**Comment by bender2k14** [comment]
Can you elaborate on the desired output of [`ISeq<>.Skip`](https://github.com/louthy/language-ext/blob/master/LanguageExt.Core/DataTypes/Seq/ISeq.cs#L175) and [`ISeq<>.Take`](https://github.com/louthy/language-ext/blob/master/LanguageExt.Core/DataTypes/Seq/ISeq.cs#L180)?  Do you want them to be the same as [`Enumerable.Skip<>`](https://msdn.microsoft.com/en-us/library/bb358985(v=vs.110).aspx) and [`Enumerable.Take<>`](https://msdn.microsoft.com/en-us/library/bb503062(v=vs.110).aspx)?

Specifically for `Skip`, if the parameter `count` is less than `0`, should the same sequence be returned?

Specifically for `Take`, if the parameter `count` is less than or equal to `0`, should an empty sequence be returned?

I ask because the behavior of `SeqList<>` differs in those two cases.

I would like `SeqList<>` to have the class invariant

1. `1 <= count`  (i.e. nonempty)
2. `0 <= index < list.Count`  (i.e. `index` is a valid index into `list`)
3. `index + count <= list.Count`  (i.e. represents a valid subsequence of `list`)

but the behavior of `Skip` allows each of `index` and `count` to be any negative value.

The alternate behavior for `Take` doesn't break my desired class invariant, but I still think its semantics are wrong. If you `Take` zero items, then you should have zero items, not all of them.  This behavior seems especially egregious when you see that `TakeWhile` is defined in terms of `Take`, so passing in `_ => false` to `TakeWhile` returns the entire sequence.

I recommend requiring the output of `Take` and `Skip` to match the output form their corresponding counterparts on the `Enumerable` class.  However, if they differ on negative values the way that `SeqList<>.Take` currently does (i.e by not violating my desired class invariant), then this seems like a reasonable choice to me as well.

**Comment by bender2k14** [comment]
Oh boy.  The classes `SeqArr<>`, `SeqArray<>`, and `SeqLst<>`, being what appears to be copy/pasted code, have the same issues as `SeqList<>`.  I want to make further improvements to `SeqList<>` (in a yet-to-be-created GitHub issue).  Then I will remove the duplicated logic among these classes.
