### ISSUE TITLE
Volunteering to write Unit Tests and examples.

### ISSUE THREAD

**Issue by brotherbill** [louthy/language-ext#385]
Greetings, I am newbie to language-ext and using git for pulls, etc, so will need some assistance to get started with the process.  Also, when using Windows with Visual Studio 2017 Community edition, can't get code to build.

I notice that Unit Tests are not comprehensive, such as for Tuples.

If someone can guide me in getting started with getting language-ext to build, get code from github, do pull requests (whatever they are), I would be happy to do the following:
  1. Write Unit Tests (may need some help understanding the method and how to call it)
  2. Write small example programs for the documentation, so readers can follow it.
      For example, I have no idea what a Semigroup is, but if the example is clear, I can just use it.
  3. Add code comments, explaining what the code is doing and why.

**Comment by bender2k14** [comment]
Hello @brotherbill.  I can try to help you out.

Let's start with your problem building the code.  Can you share more about what specifically isn't working for you?

BTW, you can read [the Wikipedia article on Semigroup](https://en.wikipedia.org/wiki/Semigroup) to start learning more about what that is.

**Comment by brotherbill** [comment]
0. On Windows 10
1. Clone or download code.
   Save file language-ext-master.zip
   Extract code to language-ext-master directory
2. Open Visual Studio 2017 (with latest updates)
   Drag language-ext.sln to Visual Studio
   Run pack.bat
3. Build | Clean Solution
4. Error Messages
 
   CS0006	
   Metadata file 'C:\Users\William\Downloads\language-ext-master\language-ext-LanguageExt.Core\bin\Debug\net451\LanguageExt.Core.dll' could not be found

   The current .NET SDK does not support targeting .NET Core 2.0.
   Either target .NET Core 1.1 or lower, or use a version of the .NET SDK that supports .NET Core 2.0.

   The current .NET SDK does not support targeting .NET Standard 2.0.
   Either target .NET Core 1.6 or lower, or use a version of the .NET SDK that supports .NET Standard 2.0.a

**Comment by bender2k14** [comment]
Try installing this
https://www.microsoft.com/net/download/windows/build

**Comment by brotherbill** [comment]
Reinstalled both.  No change.

**Comment by louthy** [comment]
@brotherbill I'm using VS Community 2017 too (v15.6.4) with no issues.

Try switching to the async-refactor branch - that's the active version branch for the next major release.

RE: Writing unit tests - yes, please, that would be awesome - the more the merrier.  I don't really have time to do any hand-holding, so it's probably best you start on areas that you understand clearly.  There's plenty of areas of the library that could benefit from additional tests (the collection types for example).

**Comment by bender2k14** [comment]
I am willing to provide you some guidance @brotherbill.  Just now sure right now how to fix the problem with your development environment :(

**Comment by thehoglet** [comment]
I get the same error messages as @brotherbill when I try to build the source, as is, in Visual Studio. My VS is 2017 Enterprise 15.6.6 on Windows 10.

When I run ```dotnet --info``` from a command prompt, the product version reported is ```2.1.104```.

If I replace the version specified in [global.json](https://github.com/louthy/language-ext/blob/master/global.json) with 2.1.104, and restart VS, language-ext builds without error. Also, simply deleting this file fixes the problem.

I am new to Core, but my gut tells me this is unnecessary problem. Can someone explain in a sentence why it is necessary to enforce a particular version for this lib? I can't help wondering if there's some mechanism/policy, maybe similar to assembly version redirects, that fixes this on a particular system.

**Comment by louthy** [comment]
@thehoglet That could well just be legacy from the horror DNX/.NETCore 1 days when everything was in flux and nothing worked.  I won't be able to test this for a few days, but it could well be time to drop it.  Thanks for the heads up.

**Comment by thehoglet** [comment]
@louthy Thank you for this library. It's impressive.
