### ISSUE TITLE
Bugs in SeqTaken<>

### ISSUE THREAD

**Issue by bender2k14** [louthy/language-ext#387]
I am far from convinced about the correctness of `SeqTaken<>`.

Let's start [`Tail`](https://github.com/louthy/language-ext/blob/master/LanguageExt.Core/DataTypes/Seq/SeqTake.cs#L22):

```
public override Seq<A> Tail => 
    seq.Tail;
```

I think this is incorrect because it completely ignores the `taken` field.  What I expected to see is

```
public override Seq<A> Tail => 
    new SeqTaken<A>(seq.Tail, taken - 1);
```

This also highlights an issue that I pointed out in #383.  In order to use this implementation, `Take(some_negative_value)` needs to return an empty sequence.  Maybe this is the behavior of the implementation of [`Take`](https://github.com/louthy/language-ext/blob/master/LanguageExt.Core/DataTypes/Seq/SeqTake.cs#L58) in `SeqTaken<>`

```
public override Seq<A> Take(int count) =>
    count >= taken
        ? this
        : new SeqTake<A>(seq, count);
```
but that is far from clear.  Much clearer (and probably more efficient in the long run) would be to return an empty sequence straight away if `count <= 0`.

Now let's look at [`Count`](https://github.com/louthy/language-ext/blob/master/LanguageExt.Core/DataTypes/Seq/SeqTake.cs#L28):

```
public override int Count =>
   taken;
```

I think this is incorrect because it completely ignores the `seq` field.  What I expected to see is

```
public override int Count =>
   Math.Min(count, seq.Count);
```

Lastly, let's look at [`IsEmpty`](https://github.com/louthy/language-ext/blob/master/LanguageExt.Core/DataTypes/Seq/SeqTake.cs#L25):

```
public override bool IsEmpty =>
    taken == 0;
````

It is certainly true that `taken == 0` is a sufficient condition for being empty, but it is far from clear to me that this is necessary.  In order for this condition to be both necessary and sufficient, we need `SeqTake<>` to satisfy the class invariant `seq.Count > 0`.  My intuition is that this invariant doesn't hold because the purpose of `SeqTake<>` is that the underlying sequence has not been enumerated, so we don't know the value of `seq.Count`.  However, is possible to know if `seq.Count > 0` without also knowing `seq.Count`.  I think I need a better understanding of the class invariants for the other seq types in order to determine if this implementation of `IsEmpty` is correct or not.

A class invariant that I would like `SeqTake` to satisfy is `taken > 0`.  When taking zero or a negative number of items, I would prefer that an empty sequence is returned instead of creating a new `SeqTake<>`.  In that case, I think the correct implementation of `IsEmpty` is simply `seq.IsEmpty`.  However, an interesting conclusion is if the class invariant of `SeqTake<>` also includes `!seq.IsEmpty`.  Then we could implement `IsEmpty` by directly returning `false`.

These seq types exist in order to avoid the

> [issues of multiple evaluation](https://github.com/louthy/language-ext/blob/master/LanguageExt.Core/DataTypes/Seq/ISeq.cs#L12).

One thing that I would like to verify is that this behavior is achieved.  At present, my feeling is that I could find such a multiple evaluation issue, but I don't know of one yet.

**Comment by louthy** [comment]
Certainly looked fishy so I've killed it.  It's probably not quite as efficient as stick it in a List anyway, which is what I've done now.

At some point I'm going to come back to all these types to see if I can do something interesting with Span<T>, I think there's some performance mileage there (maybe).

> At present, my feeling is that I could find such a multiple evaluation issue, but I don't know of one yet.

Good luck.  You won't find it ;)

**Comment by bender2k14** [comment]
For reference
> ...so I've killed it.

happened in [this commit](https://github.com/louthy/language-ext/commit/bfead566b698d1daec56da99f73a2629993d1318).
