### ISSUE TITLE
Most efficiently enumerating a SeqLst

### ISSUE THREAD

**Issue by bender2k14** [louthy/language-ext#389]
On `Lst<>`, the implementation and documentation of [`FindRange`](https://github.com/louthy/language-ext/blob/master/LanguageExt.Core/DataTypes/List/Lst.cs#L227) looks like this
```
/// <summary>
/// Returns an enumerable range from the collection.  This is the fastest way of
/// iterating sub-ranges of the collection.
/// </summary>
/// <param name="index">Index into the collection</param>
/// <param name="count">Number of items to find</param>
/// <returns>IEnumerable of items</returns>
[Pure]
public IEnumerable<A> FindRange(int index, int count) =>
    Value.FindRange(index, count);
```

In particular, it claims that
> This is the fastest way of iterating sub-ranges of the collection.

However, `SeqLst<>.AsEnumerable()` is not defined in terms of this `FindRange` method but instead via the indexer property.
```
public override IEnumerable<A> AsEnumerable()
{
    for (int i = index; i < index + count; i++)
    {
        yield return list[i];
    }
}
```

Should this implementation be changed to use `FindRange`?

**Comment by louthy** [comment]
That's a bug

**Comment by louthy** [comment]
Fixed
