### ISSUE TITLE
SeqArr and SeqArray?

### ISSUE THREAD

**Issue by bender2k14** [louthy/language-ext#390]
Is there really a need for [`SeqArr<>`](https://github.com/louthy/language-ext/blob/master/LanguageExt.Core/DataTypes/Seq/SeqArr.cs)?

The thought I had is to implement all calls of the form
```
SeqArr<A>.New(value)
```

with
```
SeqArray<A>.New(value.Value);
```

**Comment by louthy** [comment]
Sure, I doubt Arr will veer too far from the underlying array type.

**Comment by louthy** [comment]
SeqArr removed

**Comment by bender2k14** [comment]
For reference, [this commit](https://github.com/louthy/language-ext/commit/de630d5255ff94369594bdd937211ede6f4fdbb0).
