### ISSUE TITLE
Should OptionalResult<T> equal Result<Option<T>> or Option<Result<T>> ?

### ISSUE THREAD

**Issue by xlecoustillier** [louthy/language-ext#395]
Playing with Language-ext (xUnit 2.3.1, FluentAssertions 5.2.0, LanguageExt.Core 2.1.32), I discovered that those tests didn't pass : 

        [Fact]
        public void OptionalResult_Should_Be_Same_As_Result_Of_Option()
        {
            var t = new OptionalResult<int>(1);
            var u = new Result<Option<int>>(Option<int>.Some(1));
            t.Should().Be(u);
        }

        [Fact]
        public void OptionalResult_Should_Be_Same_As_Option_Of_Result()
        {
            var t = new OptionalResult<int>(1);
            var u = Option<Result<int>>.Some(new Result<int>(1));
            t.Should().Be(u);
        }

Shouldn't they pass ? Or at least the second one ? What is the difference between an optional result and and option of result, semantically speaking ?

**Comment by bender2k14** [comment]
Specifically replying to the question in your title, what do you mean by equal?

**Comment by xlecoustillier** [comment]
As described in the test, in my mind, this would make sense that at least

    var t = new OptionalResult<int>(1);
    var u = Option<Result<int>>.Some(new Result<int>(1));
    t.Equals(u).Should().BeTrue();

To answer your question: "Equal" means "a call the Equals method in this case returns true", as they seem to be equivalent. They also could implement implicit conversion operators, for the same reason, I think.

**Comment by louthy** [comment]
> Should OptionalResult<T> equal Result<Option<T>>

No, they're different types and therefore will never be equal.

**Comment by bender2k14** [comment]
Yes, I think they are semantically equivalent.  I think both types exist on purpose.  In particular, `OptionalResult<>` is easier to use than `Option<Result<>>`.

Something you can do is use this (custom) extension method to convert an `Option<Result<A>>` into a OptionalResult<A>`.

```
public static OptionalResult<A> ToOptionalResult<A>(this Option<Result<A>> mma) =>
    mma.Match(
        ma => ma.Match(
            a => new OptionalResult<A>(Some(a)),
            e => new OptionalResult<A>(e)),
        () => new OptionalResult<A>(None));
```

However, [it wasn't @louthy's intent](https://github.com/louthy/language-ext/issues/382#issuecomment-376299969) that `Result<>` and `OptionalResult<>` be used so extensively outside of LanguageExt, so it would be best to limit your dependence on them.

**Comment by xlecoustillier** [comment]
Yes, I read another discussion about their intermediate state in the meantime.  This solves the problem in fact. Thanks !
