### ISSUE TITLE
Non Generic Result (or something else) for commands

### ISSUE THREAD

**Issue by xlecoustillier** [louthy/language-ext#396]
Is there a way for a method to return a Result or something that would replace a void return in a command ?

A use case is very well described on [Vladimir Khorikov's blog](http://enterprisecraftsmanship.com/2015/03/20/functional-c-handling-failures-input-errors/) that allows to use Result for commands the same way it's already used in queries (in CQS context). I find this really useful and would love to see this implemented in language-ext.

Is there already a way to do that that I missed ?

**Comment by louthy** [comment]
It may share the same name, but it’s not the same.  The Lang-ext type that matches that blog is Either.

**Comment by xlecoustillier** [comment]
Hi Paul,

Thanks for the quick reply.

I know about Either, and indeed it matches the behavior for queries, but I don't see how it matches for commands, as they're not supposed to return anything.

For instance:

```
public void Save(Stuff stuff)
{
    // bla
    SaveMethodThatCanThrow(stuff);
}

```
is rewritten there as something like

```
public Result Save(Stuff stuff)
{
    try
    {
        // bla
        SaveMethodThatCanThrow(stuff);
        return Result.Ok();
    }
    catch(Exception e)
    {
        return Result.Fail("some msg");
    }
}
```

So in this case, how could I use Either if I don't have anything to put on the right side ?

I guess I could use Option, but this seems like bending its usage to something it's not designed for, and I feel that would hurt readability.

**Comment by louthy** [comment]
The whole thing reeks of bad design to be honest.  The point of this library is to improve life in C# by leveraging the type-system to reduce common classes of errors.  If you want an untyped Either then use `IEither` (which is what `Either<A, B>` derives from).  But you'll only be able to `Match` on `object` values.  

You could add your own extension methods for `IEither` to cast to the typed values you want, but that is outside the scope of this project.

**Comment by xlecoustillier** [comment]
I agree with you that sticking with Either to do that doesn't smell really good.

I didn't cover everything in the library yet, so I didn't know Try, but this looks promising for my use case. 

Thanks!

**Comment by bender2k14** [comment]
> Is there a way for a method to return a Result or something that would replace a void return in a command?

You can replace
```
DoWork(); // returns void
```

with
```
fun(DoWork)(); // return Unit
```

where `Language.Prelude.fun` can be used like above if you include `using static Language.Prelude` at the top of your source file.

Then you can use `Either<L, R>` with the "success" type being `Unit`.

**Comment by xlecoustillier** [comment]
Ok, I guess I have what I was looking for. This issue can be closed as far as I'm concerned.

Thanks to both of you :)
