### ISSUE TITLE
Targetting .NET 4.5

### ISSUE THREAD

**Issue by flcdrg** [louthy/language-ext#399]
Would it be possible to to add .NET 4.5 as a target. I see 4.5.1 is there at the moment. My problem is I have a solution that for the short/medium term needs to target 4.5 and that's currently a blocker for adopting language-ext.

I did a quick experiment and adding ";net45" to the targetFrameworks element seemed to work, so I'd be happy to contribute a PR if that was ok.

**Comment by louthy** [comment]
@flcdrg Hi David, I have no plans for this in the short term, each target adds a large compilation time overhead which I'd rather not incur.  I'd suggest (if it's for a short term problem) that you fork the solution and maintain a net45 build until you're ready to move.  You can call `pack.bat` in the root to build the nu-get packages.

**Comment by bender2k14** [comment]
Would there be an issue with replacing the current target of `net451` with `net45`?

**Comment by louthy** [comment]
@flcdrg Hi David, after splitting out the Rx project I decided to downgrade the .NET framework requirement.  It's now at `net45` if you haven't already upgraded your projects.
