### ISSUE TITLE
Design of Option<>'s implementation

### ISSUE THREAD

**Issue by bender2k14** [louthy/language-ext#404]
I am trying to understand the design of `Option<>`'s implementation.

What I expected to see was something that is more like the symbiotic relationship between [`SeqEmpty<>`](https://github.com/louthy/language-ext/blob/master/LanguageExt.Core/DataTypes/Seq/SeqEmpty.cs) and [`SeqList<>`](https://github.com/louthy/language-ext/blob/master/LanguageExt.Core/DataTypes/Seq/SeqList.cs).  In that case, both types are used publically as the weaker type [`Seq<>`](https://github.com/louthy/language-ext/blob/master/LanguageExt.Core/DataTypes/Seq/Seq.cs).  The implementation of `SeqEmpty<>` is utterly clear, and the symbiosis with `SeqList<>` is that `SeqList<>` is nonempty.  This assumption (together with the other class invariants) makes the implementation of `SeqList<>` clearer that it would be without those assumptions.

So in the case of `Option<>`, what I expected to see was some private state with a bit weaker compile-type type that either had the runtime type
- of [`Some<>`](https://github.com/louthy/language-ext/blob/master/LanguageExt.Core/DataTypes/Some/Some.cs),
- that is a generic version of [`OptionNone`](https://github.com/louthy/language-ext/blob/master/LanguageExt.Core/DataTypes/Option-Shared/OptionNone.cs), or
- that is somewhat like the delegate [`OptionLazy<>`](https://github.com/louthy/language-ext/blob/master/LanguageExt.Core/DataTypes/Option-Shared/OptionLazy.cs).

Then each of these three types could implement the needed interface in special ways that should result in clearer code as well as a more efficient implementation.

Here is a [method](https://github.com/louthy/language-ext/blob/master/LanguageExt.Core/ClassInstances/Monad/MOption.cs#L25) that I feel like suffers the worst in the current design.
```
public MB Bind<MonadB, MB, B>(Option<A> ma, Func<A, MB> f) where MonadB : struct, Monad<Unit, Unit, MB, B> =>
    ma.IsLazy
        ? default(MonadB).Run(_ =>
            ma.IsSome && f != null
                ? f(ma.Value)
                : default(MonadB).Fail(ValueIsNoneException.Default))
        : ma.IsSome && f != null
            ? f(ma.Value)
            : default(MonadB).Fail(ValueIsNoneException.Default);
```

So for example, every time we bind onto an `Option<>` in the none state, we have to check both `IsLazy` property as well as the `IsSome` property.  In contrast, the approach I was thinking of would have just one virtual method invocation when the wrapping `Option<>` type delegates the implementation of `Bind` to some internal type like `AbstratctOption<>` with runtime type `OptionNone<>`.

That `Bind` method is on [`MOption<>`](https://github.com/louthy/language-ext/blob/master/LanguageExt.Core/ClassInstances/Monad/MOption.cs) and exists because that type implements the interface [`Monad<,>`](https://github.com/louthy/language-ext/blob/master/LanguageExt.Core/TypeClasses/Monad/Monad.cs).  I don't think I understand the value of this interface implementation.  As best I can tell, `MOption<>.Bind` is called exactly once ([from `Option<>.Bind`](https://github.com/louthy/language-ext/blob/master/LanguageExt.Core/DataTypes/Option/Option.cs#L344)).  As such, its existence doesn't seem worth it to me.

**Comment by bender2k14** [comment]
Oh, about `MOption<>.Bind`, I also meant to say this.

My current understanding of the concept of monads is that `Bind` is a method that "flattens" a particular monad.  For example, if `ma` is of type `Option<int>` and `f` returns maps `int` to `Option<bool>`, then we should call `Bind` so that the return type is `Option<bool>` instead of calling `Map` where the return type would be `Option<Option<bool>>`.

Base on that understanding, this `MOption<>.Bind` (from the interface method `Monad<,>`) seems overly general because it permits binding in the case that the two monads involved are different.  For example, one can write this
```
Option<int> ma = None;
Either<string, int> either = 1;
var mb = MOption<int>.Inst.Bind<MEither<string, int>, Either<string, int>, int>(ma, _ => either);
```

This type of binding for the option type is not exposed from `Option<>` itself.

**Comment by louthy** [comment]
* Option's implementation is for efficiency reasons - the user never needs to see the underlying complexity.
* MOption is used, because it's part of the public API - it's there for generalist programming of monads (it's also heavily used in the HKT generated code)
* Bind can't be constrained to return the same type because C#'s type system doesn't allow it.  Until C# can do higher kinds we can't constrain the return value.  The system I have created is actually still valid in that it uses Monad.Return and Monad.Fail to construct a valid monad, so although, yes, you can return a different monad type, it's still entirely type safe (and arguably 'a better monad').
