### ISSUE TITLE
Foldable<,,>.FoldBack<> documentation

### ISSUE THREAD

**Issue by bender2k14** [louthy/language-ext#405]
I think the documentation of [`Foldable<,,>.FoldBack<>`](https://github.com/louthy/language-ext/blob/master/LanguageExt.Core/TypeClasses/Foldable/Foldable.cs#L46) might be wrong.  It appears to me to have a copy-paste error from [`Fold<>`](https://github.com/louthy/language-ext/blob/master/LanguageExt.Core/TypeClasses/Foldable/Foldable.cs#L30) just above it.

The documentation for both `Fold<>` and `FoldBack<>` say
> reduces the list using the binary operator, from left to right.

My understanding is that this documentation is correct for `Fold<>` and that `FoldBack<>` reduces the list using the binary operator from right to left.

For the record, the documentation does appear to be correct (based on a sampling of implementations) when it says for `FoldBack<>` that
> a starting value(typically the left-identity of the operator)

At first I was slightly suspicious that this might be a copy-paste error as well, but In hindsight, I think this is correct.  With this specification, `ma.Reverse().Fold(s, f)` and `ma.FoldBack(s, f)` have the same behavior.

**Comment by louthy** [comment]
Yup will be a copy and paste issue
