### ISSUE TITLE
Trans<,,,,> vs SeqTrans<,,,,>

### ISSUE THREAD

**Issue by bender2k14** [louthy/language-ext#406]
I am trying to understand the difference between [`Trans<,,,,>`](https://github.com/louthy/language-ext/blob/master/LanguageExt.Core/HKT/Trans.cs) and [`SeqTrans<,,,,>`](https://github.com/louthy/language-ext/blob/master/LanguageExt.Core/HKT/SeqTrans.cs).  I have noticed some differences, but some other things are identical, including the documentation of these two types as well as the type constraints of their type parameters.

Something else that is identical is one of the `Bind<,,,,>` methods.  Namely, [these](https://github.com/louthy/language-ext/blob/master/LanguageExt.Core/HKT/Trans.cs#L27) [two](https://github.com/louthy/language-ext/blob/master/LanguageExt.Core/HKT/SeqTrans.cs#L22), which look like
```
public NewOuterType Bind<NewOuterMonad, NewOuterType, NewInnerMonad, NewInnerType, B>(OuterType ma, Func<A, NewInnerType> f)
    where NewOuterMonad : struct, Monad<NewOuterType, NewInnerType>
    where NewInnerMonad : struct, Monad<NewInnerType, B> =>
        MOuter.Bind<NewOuterMonad, NewOuterType, NewInnerType>(ma, inner =>
            default(NewOuterMonad).Return(
                MInner.Bind<NewInnerMonad, NewInnerType, B>(inner, f)));
```

Should one of these methods be implemented by calling the other?

**Comment by louthy** [comment]
Leave it for now.  It's a system I will be replacing eventually.

**Comment by bender2k14** [comment]
How will you be replacing it?

**Comment by louthy** [comment]
@bender2k14 Eventually with code-gen that works on pairs of types
