### ISSUE TITLE
How to turn a method group into a Func<A, B>

### ISSUE THREAD

**Issue by bender2k14** [louthy/language-ext#407]
Today I had a reason to express the method (group) [`string.IsNullOrEmpty`](https://msdn.microsoft.com/en-us/library/system.string.isnullorempty(v=vs.110).aspx) as the type `Func<string, bool>`.  I thought I could do this via the (overloaded) method `Prelude.fun` by writing `fun(string.IsNullOrEmpty)`.  However, this gives me a compile error saying
> [Error CS1503](https://docs.microsoft.com/en-us/dotnet/csharp/misc/cs1503) Argument 1: cannot convert from 'method group' to 'Action'

If I copy-paste the [two](https://github.com/louthy/language-ext/blob/master/LanguageExt.Core/Prelude/Prelude_Func.cs#L41) `Prelude.fun` [methods](https://github.com/louthy/language-ext/blob/master/LanguageExt.Core/Prelude/Prelude_Func.cs#L194) with two type parameters to a different location and ask the compiler to pick the correct one, it still has a compile error.  This time the error is different.  The error is
> [Error CS0411](https://docs.microsoft.com/en-us/dotnet/csharp/misc/cs0411) The type arguments for method 'fun<T1, R>(Func<T1, R>)' cannot be inferred from the usage. Try specifying the type arguments explicitly.

If I also add to this different location the [overload](https://github.com/louthy/language-ext/blob/master/LanguageExt.Core/Prelude/Prelude_Func.cs#L296) of `Prelude.fun` that just takes an `Action`, then I get the original compiler error again.

In all three cases, if I specify the type parameters explicitly, then the correct overload is selected.  Another work around is to eta expand the argument to `Prelude.fun`.

Is it possible to directly turn a method group into the appropriate `Action` and `Func` type (i.e. without having to explicitly specify the type parameters or do an eta expansion)?

**Comment by louthy** [comment]
> Is it possible to directly turn a method group into the appropriate Action and Func type 

Only if all the types are known.  Welcome to C# - the language that can’t infer the types from a single method in a method-group.

I’ve complained about this on csharplang before.  Nothing is going to change in this area, which is super annoying

**Comment by bender2k14** [comment]
> Only if all the types are known.

All the input types, right?

Because I just realized that `fun(new StringReader("").ReadLine)` complies and correctly returns `Func<string>` while `fun(DoWork)` (with a method `void DoWork()`) also complies and correctly returns `Action<Unit>` (which means the method group was correctly converted to be of type `Action`).

I think I understand this (limitation of C# ;) ) now.
