### ISSUE TITLE
Memo memory leak?

### ISSUE THREAD

**Issue by ntwilson** [louthy/language-ext#409]
Wonderful library.  I can't imagine having to write C# code without LanguageExt.

I've been intermittently seeing OutOfMemoryExceptions occurring from memoizing some of my functions.  Unfortunately, the code base I'm working with is proprietary, and I can't give much information about how to reproduce the problem.  All I can give you is a partial stack trace:
```
System.AggregateException: One or more errors occurred. ---> System.OutOfMemoryException: Insufficient memory to continue the execution of the program.
    at LanguageExt.Prelude.WeakDict`2.GetOrAdd(T key, Func`2 addFunc)
   at LanguageExt.Prelude.<>c__DisplayClass341_1`2.<memo>b__2()
   at LanguageExt.Prelude.<>c__DisplayClass341_0`2.<memo>b__0(T inp)
```
My understanding is that this _shouldn't_ be possible, given that the memoizer is using a WeakDictionary, and should be clearing results out before the memory pressure gets too large.  I'm wondering if anyone has any ideas on what could be causing it to run out of memory, or what the next steps would be in diagnosing it.
It ends up being pretty rare.  I've probably seen this exception occur maybe 5 times and have been using it for many months now.

Thanks for any help!

**Comment by louthy** [comment]
@ntwilson Closing as I've had no follow up.
