### ISSUE TITLE
More compostional or fluent handling of Eithers with varied Right Results 

### ISSUE THREAD

**Issue by imranypatel** [louthy/language-ext#410]
Simple commented code:
```
       public static Either<string, string> GetTestMessageType(JObject msg)
        {
            // after some lookup/validation msg, suppose return as:
            return Right("GET_AUTHORS");
        }

        public static Either<string ,Func<JObject, MessageResult>> GetTestHandler(string key)
        {
            try
            {
                // Handlers Dictonary lookup sucsess
                return Right(Handlers.Get(key));
            }
            catch (Exception e)
            {
                // Handlers Dictonary lookup failed
                return Left($"Handler {key} not found. ({e.Message})");
            }
        }

        public static string TestMessageResultError(string err)
        {
            return $"Error:{err}";
        }

        public static object HandleTestMessage(JObject msg)
        {

            // Valid message type? 
            var x = GetTestMessageType(msg);

            // if not return error
            if (x.IsLeft)
            {
                return TestMessageResultError(x.Match(Left: l => l, Right: _ => ""));
            }

            // extract Message Type
            var mt = x.Match(Left: l => l, Right: r => r);

            // Handler exist? 
            var h = GetTestHandler(mt);

            // if not Return error Message Type cannot be handled
            if (h.IsLeft)
                return TestMessageResultError(h.Match(Left: l => l, Right: _ => ""));

            // extract handler func
            var f = h.Match(Left: l => null, Right: r => r);

            // Execute Handler func with msg
            return f(msg);

        }

```
GetTestMessageType and GetTestHandler return Either with varied Right results. 

HandleTestMessage uses both to for handling ```msg``` but in verbose manner.  

Any suggestion to make it more compostional or fluent style?

**Comment by imranypatel** [comment]
Thank you. 
result/2/3 will remain in the context of Either so when, finally one needs to extract result value and output it to e.g. error log if it is Left (or error) or save it to e.g. db if it is Right (or success), then what alternative ways would you suggest to choose from?

**Comment by bender2k14** [comment]
@imranypatel, can you provide sample code that is self contained (i.e. compiles as is)?

**Comment by trbngr** [comment]
@imranypatel Without a concrete example, I'd stick to the same patterns as above (in whatever style you prefer).

ie.

```csharp
class MessageResult
{
}

static Either<string, string> GetTestMessageType(JObject msg) => Right("GET_AUTHORS");
static Either<string, Func<JObject, MessageResult>> GetTestHandler(string key) => Left("");
static string TestMessageResultError(string err) => $"Error:{err}";

static Either<string, MessageResult> HandleTestMessage(JObject msg) => match(
    from type in GetTestMessageType(msg)
    from handler in GetTestHandler(type)
    select handler,
    Left: er => Left<string, MessageResult>(TestMessageResultError(er)),
    Right: handle => handle(msg)
);

static void CallsHandleTestMessage() => match(
    HandleTestMessage(JObject.Parse(@"{""name"": ""chris""}")),
    Left: error => Log(error).AsTask(),
    Right: SaveToDb
);

static Unit Log(string error) => unit;
static Task<Unit> SaveToDb(MessageResult result) => unit.AsTask();
```

**Comment by bender2k14** [comment]
This doesn't compile either.

**Comment by trbngr** [comment]
1. Not my code.
2. Yes it does. Put it in a class.

**Comment by louthy** [comment]
`HandleTestMessage` can just be this:

```c#
            static Either<string, MessageResult> HandleTestMessage(JObject msg) => 
                from type in GetTestMessageType(msg)
                from handler in GetTestHandler(type)
                select handler(msg);

```

**Comment by imranypatel** [comment]
Thank you.

Worth mentioning that attempt to code ```GetHandler``` in expression oriented style as following was not success:

```
     static Either<string, Func<JObject, MessageResult>> GetTestHandlerExp(string type) =>
            (type == "GET_AUTHORS")
            ? Right(HandleGetAuthors)
            Left($"Invalid Message type {type}");
```
Not compiling withe error 
> Type of conditional expression cannot be determined because there is no implicit conversion...

Explicit casting would be the solution but couldn't figure out one so got away with ```if...then...else``` statement instead of expression style.

**Comment by bender2k14** [comment]
> Explicit casting would be the solution but couldn't figure out one

@louthy said how to do this in [some recent release notes](https://github.com/louthy/language-ext/releases/tag/v2.2.23-beta).  The relavent part is

> you can consider `Bind` to simply be a cast operation for the `R` value that doesn't exist.

So you make the expression body style work like this

```
static Either<string, int> GetTestHandlerExp(bool b) =>
    b
    ? 1
    : Left("Fail").Bind<int>();
```

**Comment by bender2k14** [comment]
> Not my code.
> Yes it does. Put it in a class.

Oh, sorry @trbngr.  I thought that was @imranypatel replying to me.

Even so, it doesn't compile even after you put it in a class.  You are still missing some usings.

**Comment by imranypatel** [comment]
@bender2k14  Thank you.

Just for completeness and documentation for beginners like myself, based on your response, here is the revised version in expression style:
```
    static Either<string, Func<JObject, MessageResult>> GetTestHandler(string type) =>
            (type == "GET_AUTHORS")
            ? Right(HandleGetAuthors)
            : Left($"Invalid Message type {type}").Bind<Func<JObject, MessageResult>>()
```

**Comment by louthy** [comment]
Just to be clear, this is a limitation of C#.  When you use the ternary operator:
```c#
   a = b ? c : d;
```
If there isn't a common base type shared by `c` and `d` then C# will claim it can't infer the type of the expression.  Even if the type of `a` is known.  

* The return type for `Right<R>(r)` is `EitherRight<R>`
* The return type for `Left<L>` is `EitherLeft<L>(l)`.

__They don't share the same base type__

And therefore C# can't work out what's going on.  So, you can't do this:

```c#
    var a = b 
        ? Right<R>(r) 
        : Left<L>(l);
```

* The return type for `Right<L, R>(r)` is `Either<L, R>`
* The return type for `Left<L, R>(l)` is `Either<L, R>`.  

Which clearly share the same return type (note both `L` and `R` are provided for both), and so __you can__ call:

```c#
    var a = b 
        ? Right<L, R>(r) 
        : Left<L, R>(l);
```
Now the `Bind` function that can be called on `EitherLeft<L>` or `EitherRight<R>` is there to provide _the other type_ in the `Either` 

So,
* For `EitherLeft<L>` the `Bind` operation provides the `R` type.  
* For `EitherRight<R>` the `Bind` operation provides the `L` type.  

So, there are 3 ways you can do this.  And the one you chose should probably be based on the resulting attractiveness/readability of the code:

```c#
    static Either<string, Func<JObject, MessageResult>> GetTestHandler(string type) =>
        type == "GET_AUTHORS"
            ? Right(HandleGetAuthors)
            : Left($"Invalid Message type {type}").Bind<Func<JObject, MessageResult>>();

    static Either<string, Func<JObject, MessageResult>> GetTestHandler(string type) =>
        type == "GET_AUTHORS"
            ? Right(HandleGetAuthors).Bind<string>()
            : Left($"Invalid Message type {type}");

    static Either<string, Func<JObject, MessageResult>> GetTestHandler(string type) =>
        type == "GET_AUTHORS"
            ? Right<string, Func<JObject, MessageResult>>(HandleGetAuthors)
            : Left<string, Func<JObject, MessageResult>>($"Invalid Message type {type}");
```
