### ISSUE TITLE
Writer usage with async

### ISSUE THREAD

**Issue by trbngr** [louthy/language-ext#413]
I can not wrap my head around `Writer` usage with async code.

Is there a test around this scenario?

here's the concrete example of what I'd like to accomplish.
https://github.com/trbngr/infusio/blob/dev/src/Infusio/Interpreter.cs#L113

I'd like to provide an alternative that will return, in addition to the existing return, a log for this function.

Or maybe `State` would be a better option.

**Comment by louthy** [comment]
> here's the concrete example of what I'd like to accomplish.

But there's no `Writer` used?  Am I missing something?

**Comment by trbngr** [comment]
No you’re not. I can’t seem to work out how to mix writer into that.

**Comment by louthy** [comment]
> I'd like to provide an alternative that will return, in addition to the existing return, a log for this function.

I just read this fully.  

So, it looks from the code that you're trying to follow the free-monad approach.  So, the easiest thing is to use the interpreter state to propagate the logged values, and then return it with the result.  

I've done a pull request on your repo to demonstrate: https://github.com/trbngr/infusio/pull/5

**Comment by louthy** [comment]
btw, other approaches I've used is to have a `Subject<LogMessage>` in the interpreter state.  Then the `Log` action can call `state.Output.OnNext(msg)` and external 'stuff' can subscribe to the messages coming through (might be better for the async approach, which is where I've used this before).

**Comment by louthy** [comment]
You could also just have the Log function push to some mutable state.  Less functional obviously, but in some ways the point of the interpreter is to package up all the messy stuff, so as long as its controlled it doesn't really matter (i.e. you could push logs to a DB, or to a txt file, or whatever)

**Comment by trbngr** [comment]
Thank you! I'll drive in a bit later
