### ISSUE TITLE
OutExtensions ambiguous

### ISSUE THREAD

**Issue by iSOcH** [louthy/language-ext#414]
Code:

```
public void ShowTryGetValueAmbiguous() {
    var dict = new Dictionary<string, object>();
    dict.TryGetValue("key").Map(o => o.GetHashCode());
}
```

Leads to this Error:
```
CS0121	The call is ambiguous between the following methods or properties: 'OutExtensions.TryGetValue<K, V>(IDictionary<K, V>, K)' and 'OutExtensions.TryGetValue<K, V>(IReadOnlyDictionary<K, V>, K)'
```

Because `System.Collections.Generic.Dictionary<TKey, TValue>` is both `IDictionary<TKey, TValue>` as well as `IReadOnlyDictionary<TKey, TValue>`.

Would it be a problem to also provide an overload for `Dictionary<TKey, TValue>` directly instead of "only" for the interfaces?

**Comment by louthy** [comment]
@iSOcH  This is 'fixed' on `v3.0.2` you should use named arguments to pick the correct overload:

`var y = x.TryGetValue(Key: k);`
