### ISSUE TITLE
how to get NewType serialized and deserialized with XML

### ISSUE THREAD

**Issue by honginstarbucks** [louthy/language-ext#417]
I declare a new type called `SalesType`, which is just a string with a fixed number of possible values. 

I am using YAXLib for XML serialization. 
For some reason, the serialized XML always has null for that field. 

Here is the code: 

```
	[Serializable]
	public class SalesType : NewType<SalesType, string>
	{
		public SalesType(string value) : base(value)
		{
			if (!(value.Equals("Create", StringComparison.InvariantCultureIgnoreCase) ||
				value.Equals("Void", StringComparison.InvariantCultureIgnoreCase)))
			{
				throw new ArgumentException("SalesType must be either Create or Void");
			}
		}

		public SalesType(SerializationInfo info, StreamingContext context) : base(info, context)
		{
		}
	}
```

I tried to override the ToString and explicitly returns the value. Didn't help at all. 

Just want to know if I really have to write a custom serializer. 
Thanks

**Comment by louthy** [comment]
I would suggest talking to the authors of YAXLib. Json.net will use the
constructor to build immutable types, maybe YAXLib it doesn’t.

For your explicit example above try adding ISerializable to the inherited
interfaces
