### ISSUE TITLE
"With" Behaviour for Record Types?

### ISSUE THREAD

**Issue by thehoglet** [louthy/language-ext#422]
Please see [this gist](https://gist.github.com/thehoglet/a96570dd0098741c49bef84a185f9467).

I couldn't see an alternative with the current library. Disabuse me if I'm wrong.

Is there a better way than reflection and an anonymous type? IL generation?

If sticking with reflection, does this need a deep-copy (e.g. [this](https://github.com/Burtsev-Alexey/net-object-deep-copy), as discussed [here](https://stackoverflow.com/questions/129389/how-do-you-do-a-deep-copy-of-an-object-in-net-c-specifically))?

**Comment by louthy** [comment]
There's no shortcut really, aside from writing a Roslyn plugin that rewrites the syntax tree of your compilations.

I use [this approach that I outlined on stackoverflow a while back](https://stackoverflow.com/questions/38575646/general-purpose-immutable-classes-in-c-sharp/38596298#38596298)

**Comment by Richiban** [comment]
Wouldn't it be possible to have a method on the `RecordType` base class with this signature:

```csharp
public abstract class RecordType<T>
{
	...

	public T With<TProp>(Expression<Func<T, TProp>> propSelector, TProp newValue)
	{
		// Some of Louthy's magic here?
	}
}
```

Usage would then look like this:

```csharp
var r = new MyRecord(value : "Hello world");

var r2 = x.With(x => x.Value, "Goodbye, cruel world!");
```

It's similar to how mocking frameworks such as Moq work:

```csharp
var m = new Mock<IMyInterface>();

m.Setup(x => x.Foo()).Returns("My new value");

m.Object.Foo(); // Returns "My new value"
```

It's definitely possible with reflection which I hope means that, Louthy, you could sprinkle some of your IL-generation magic to make it perform much better.

The main problem that I see with this is that there are a lot of cases that would have to result in an exception. For example, there's nothing to force the user from passing in a lambda that actually references a property on the object. Also, you might have some trouble matching property names to constructor argument names.

**Comment by bender2k14** [comment]
> The main problem that I see with this is that there are a lot of cases that would have to result in an exception.

I think this is a fundamental problem.  It is preferable to write code that won't fail at runtime.

**Comment by trbngr** [comment]
I keep thinking of a way to make this possible at compile-time. 

Now that Rider supports Roslyn analyzers, it wouldn't be a VS-only hack. So that's a good solution.

I wonder if it would be possible with Fody?

**Comment by Richiban** [comment]
@trbngr Fody might be a good choice, since it can not only verify at compile-time that the call written by the user is correct but could also rewrite the call to `With` into a direct call to the constructor:

```csharp
public class MyRecord : RecordType<MyRecord>
{
	public MyRecord(int x, int y, int z) => (X, Y, Z) = (x, y, z);

	public int X { get; }
	public int Y { get; }
	public int Z { get; }
}
```

Given the type definition above the following:

```csharp
var record = new MyRecord(4, 5, 6);

var record2 = record.With(r => r.X, 10);
```

would be rewritten to:

```csharp
var record = new MyRecord(4, 5, 6);

var record2 = new MyRecord(10, record.Y, record.Z);
```

**Comment by trbngr** [comment]
I would prefer the syntax that @louthy uses. Maybe I'll try to implement it tonight.

**Comment by trbngr** [comment]
OK. Here's the beginning of this effort.

https://github.com/trbngr/LanguageExt.Fody

I still need to emit the IL - which is the hard part ;)

**Comment by trbngr** [comment]
OK. After thinking this through, I'm not sure the Fody way is very beneficial at all. We won't get dev-time `With` methods. Only after compilation. I'm not sure I'll follow through with this one.

When I get some downtime, I will probably opt for a simple Roslyn Analyzer and/or Rider plugin that will be able to generate the `With` at dev-time.

Until the C# team decides to give us real Records, this is probably the best we'll get.
