### ISSUE TITLE
Either.MapAsync overload

### ISSUE THREAD

**Issue by nojaf** [louthy/language-ext#430]
It be nice if we could go from an `Either<A,B>` to an `EitherAsync<A,C>` via a `MapAsync` overload.
Example:

```csharp
        public static async Task Main(string[] args)
        {
            var x =
                args.HeadOrNone()
                    .ToEither("Nothing was inputted")
                    .ToAsync() // this bugs me!!!
                    .MapAsync(AnswerOfTheUniverse)
                    .Match(ans =>
                    {
                        Console.Write($"Answer is {ans}");
                        return Unit.Default;
                    }, err =>
                    {
                        Console.WriteLine($"No answer found, {err}");
                        return Unit.Default;
                    });
            
            Console.WriteLine(x);
            await x;
        }

        static Task<int> AnswerOfTheUniverse(string question)
        {
            return Task.FromResult(42);
        }
```

That `ToAsync` call is merely to use the `MapAsync`, the value at that point should not be lifted.

**Comment by bender2k14** [comment]
It seems more natural to me to combine the `ToEither` and `ToAsync` calls.  What do you think of that @nojaf?

**Comment by bender2k14** [comment]
Is [this](https://github.com/louthy/language-ext/blob/master/LanguageExt.Core/DataTypes/Option/Option.Extensions.Async.cs#L144) what you want?

**Comment by nojaf** [comment]
No, I still want to pass a mapping function.

**Comment by bender2k14** [comment]
My understanding is that the relevant part of your initial example is
```
args.HeadOrNone()
       .ToEither("Nothing was inputted")
       .ToAsync() // this bugs me!!!
       .MapAsync(AnswerOfTheUniverse)
```

and that your primary concern is finding a nearly identical solution that avoids having to call `.ToAsycn()`.  The solution I proposed would change your code to look like
```
args.HeadOrNone()
       .ToEitherAsync("Nothing was inputted")
       .MapAsync(AnswerOfTheUniverse)
```

You can still pass your mapping function into `MapAsync`.

To this solution, you said
> No, I still want to pass a mapping function.

I don't think I understand.  What don't you like about my suggestion?

**Comment by nojaf** [comment]
Mixed feelings about going to `ToEitherAsync` because the `.ToEither("Nothing was inputted")` has no need for anything `Async`. But it is getting nitpicking at this point. 

```csharp
        public static EitherAsync<A, C> MapAsync<A, B, C>(this Either<A,B> either, Func<B,Task<C>> mapFn)
        {
            return either.ToAsync().MapAsync(mapFn);
        }
```

I rather go to `Async` only when the code requires it.
Feel free to close this as it might be to opinionated.

**Comment by bender2k14** [comment]
My preference is to combine function calls like `ToEither` and `ToAsync` because they map between types of monads that have the same inner type(s) while function calls like `Map` and `Bind` map between the same monad but with a different inner type (or types).

**Comment by louthy** [comment]
[`ToEitherAsync` already exists from `Option<A>`](https://github.com/louthy/language-ext/blob/master/LanguageExt.Core/DataTypes/Option/Option.Extensions.Async.cs#L144), the other extensions (because it's not only `MapAsync` requires a fair amount of typing), so I'd stick with `ToEitherAsync` for now.
