### ISSUE TITLE
Issue with the way NuGet package versions are specified

### ISSUE THREAD

**Issue by SeanFarrow** [louthy/language-ext#431]
Currently, the NuGet packages LanguageExt depends on are specified as exact versions. This means that any other NuGet package resolving a package on which LanguageExt also takes a dependency (System.Reactive.Linq) in this case will not be able to upgrade. Would it be possible to change the way LanguageExt specifies it's dependencies to use a minimum allowable version, in this case v3.1.1+. I can downgrade the package I use for now as a short term measure.

**Comment by bender2k14** [comment]
Another solution discussed in #163 (but which lacked favor) is to remove the dependency on System.Reactive.Linq.

**Comment by louthy** [comment]
> Would it be possible to change the way LanguageExt specifies it's dependencies to use a minimum allowable version

Does anyone know how to do this in the new `csproj` reference spec?  I was able to do it when `project.json` was a thing, but googling this is remarkably difficult.

**Comment by SeanFarrow** [comment]
@louthy
I’ll have a look at this on Wednesday and submit a Pr.

**Comment by SeanFarrow** [comment]
@louthy,
What does the LanguageExt.RX package contain?
Do you want me to look at the version issue for that package?

**Comment by louthy** [comment]
I managed to convince nu-get to use a range using :

`<PackageReference Include="System.Reactive" Version="[3.0.0,5.0]" />`
