### ISSUE TITLE
Why is ToAsync() implemented with Task.Run instead of Task.FromResult?

### ISSUE THREAD

**Issue by SirUppyPancakes** [louthy/language-ext#434]
Just wondering if there is a reason for doing:

```
    public static TryAsync<A> ToAsync<A>(this Try<A> self) => () =>
        Task.Run(() => self.Try());
```
Instead of:
```
    public static TryAsync<A> ToAsync<A>(this Try<A> self) => () =>
        Task.FromResult(self.Try());
```

The only difference in functionality is the `Task.Run` one off-loads to the thread pool, while the `Task.FromResult` one uses the original context (which can cause deadlocks in some scenarios).
Was this a preventative measure against deadlocks?

Love to see all the progress this library has been making, good stuff!

**Comment by bender2k14** [comment]
Can you provide the link to the code where this happens?

**Comment by louthy** [comment]
I thought I'd found all Task.Runs in the async refactor, seems not.  Anyway, this is fixed now and deployed.
