### ISSUE TITLE
Unused type parameter in parser combinator count

### ISSUE THREAD

**Issue by bender2k14** [louthy/language-ext#435]
The parser combinator called [`count`](https://github.com/louthy/language-ext/blob/master/LanguageExt.Parsec/Parsers/Prim.cs#L512) has an unused type parameter.
> Parser<Seq<T>> count<S, T>(int n, Parser<T> p)

Should this unused type parameter be removed?

**Comment by louthy** [comment]
Yep, it’s probably a copy and paste bug
