### ISSUE TITLE
NewType's static New constructor

### ISSUE THREAD

**Issue by michael-wolfenden** [louthy/language-ext#442]
I'm trying to create a class that wraps a primitive value but also prevents it's invariants.

`NewType` allows a `predicate` to be passed however this causes an exception to be thrown.

Instead I want to build a list of validation errors to be returned to the caller.

For example, given the following:

```csharp
public class Error : NewType<Error, string> { public Error(string value) : base(value) { } }

public static Validation<Error, string> AsciiOnly(string str) =>
    str.ForAll(c => c <= 0x7f)
        ? Success<Error, string>(str)
        : Fail<Error, string>(Error.New("only ascii characters are allowed"));

public static Func<string, Validation<Error, string>> MaxStrLength(int max) =>
    str =>
        str.Length <= max
            ? Success<Error, string>(str)
            : Fail<Error, string>(Error.New($"can not exceed {max} characters"));
            
public class CardHolder : NewType<CardHolder, string>
{
    private CardHolder(string value) : base(value) { }

    public static Validation<Error, CardHolder> Create(string cardHolder) =>
        (AsciiOnly(cardHolder) | MaxStrLength(30)(cardHolder))
            .Map(value => new CardHolder(value));
}
```

The idea is that `CardHolder` can only be created by calling `CardHolder.Create` forcing the caller to handle an validation errors.

The issue is the the `NewType`'s static `New` constructor allows calling `CardHolder.New` thus circumventing any validation.

IMHO, this prevents one of `NewType` greatest benifits, the ability to wrap primitives types with protected invariants.

It prevents code like the following:

```csharp
public class Customer : Record<Customer>
{
    public Customer(CustomerId id, PersonalName name, EmailAddress emailAddress)
}

// gather all the validation errors
from id in CustomerId.Create(1)
from name in PersonalName.Create('test')
from emailAddress in EmailAddress.Create('some@email.com')
select new Customer(id, name, emailAddress)
```

**Comment by louthy** [comment]
@michael-wolfenden That would require a whole new version of `NewType` that supported `Validation`, because any changes here would break lots of users' code.  I don't think it's a trivial job, so I'll need to leave it on the nice-to-have list for now.

As a stop-gap I have added `NewTry(A value)` and `NewOption(A value)` to `NewType`, `NumType`, and `FloatType` - that return `Try<NEWTYPE>` and `Option<NEWTYPE>` respectively.  The will both capture exceptions.

It's not quite the solution you're looking for, but it's a bit closer.

**Comment by michael-wolfenden** [comment]
Thanks for the response @louthy, I suspected as much. I will close out the issue.

On another note, I just wanted to say thank-you for the work you have done on this project. It has made my life 💯 easier.
