### ISSUE TITLE
System.Collection.Generic.HashMap namespace is shadowed by LanguageExt

### ISSUE THREAD

**Issue by Ephasme** [louthy/language-ext#444]
Hello,

I want to use LanguageExt in my codebase but I noticed that for all collections that you reimplemented you carefully chose not to shadow the .NET base name (List, Dictionnary, etc.) except for HashSet.
This is annoying because I have TON of HashSets in my code and I'm forced to write System.Collection.Generic.HashMap everywhere.

Is it possible to rename LanguageExt.HashSet to LanguageExt.HshSet for example in order to be consistent with the other LanguageExt collection's naming pattern?

Thanks.

**Comment by louthy** [comment]
I won't be renaming it, it'll break lots of users' existing code.  What I do is this
```c#
using G = System.Collections.Generic;
```
Then I can reference the BCL HashSet as `G.HashSet`

Obviously you could do it the other way around if you have lots of usage of the Generic types:

```c#
using L = LanguageExt;
```
Then you can reference the Language-Ext HashSet as `L.HashSet`
