### ISSUE TITLE
Transforming a Try to a Validation of my own Error type

### ISSUE THREAD

**Issue by Zordid** [louthy/language-ext#447]
I have a problem here.

I tried around with Try (*pun*) ... so something that potentially throws an Exception.

    var x = Try( ...... );

This gives me a Try<MyType>. But in my system I use Validation<Error, MyType> for collecting all potential errors. Now, I try to transform that Try to a Validation and I found ToValidation() method - but that yields a Validation<Exception, MyType> - and not a Validation<Error, MyType>...

I hoped that I could supply my own function to create the FAIL type - but it does Exception only. How can I transform the FAIL type of a Validation?

**Comment by bender2k14** [comment]
In `Validation<Error, MyType>`, what is `Error`?  Is that a type you defined, a type in Language Ext, or something else?

**Comment by trbngr** [comment]
There are multiple way to get what you want. The two easiest that come to mind are:

note: my `X()` is an int. Yours probably isn't ;)


```csharp
            var validationFromTry = X().Match(
                Succ: Success<Error, int>,
                Fail: e => Error.New(e.Message)
            );

            var validationFromEither = X()
                .ToEither()
                .MapLeft(e => Error.New(e.Message))
                .ToValidation();
```

**Comment by Zordid** [comment]
Sounds perfect! @trbngr, you were right - it's `class Error : NewType<Error, string>`.

Your solutions look promising - but I really ask myself why there isn't a simple overload of `Try.ToValidation` that takes a func to transform the Exception to an arbitrary Error object...

Thanks!

**Comment by trbngr** [comment]
I agree. There should be. And it Should be a very easy PR ;)

**Comment by louthy** [comment]
`ToValidation` and `ToEither` extensions now allow an optional mapping function.  It is still better to build bespoke extension methods for your projects, as it's likely to be repeated effort, but these new conversion methods will help.

https://github.com/louthy/language-ext/releases/tag/v3.0.19
