### ISSUE TITLE
Bind for the Try Monad can produce side effects

### ISSUE THREAD

**Issue by afifmohammed** [louthy/language-ext#449]
Under LanguageExt.Core/DataTypes/Try/Try.Extensions.cs there is [this](https://github.com/louthy/language-ext/blob/d4623a0885207c1f39f0d31c573222a4b227532e/LanguageExt.Core/DataTypes/Try/Try.Extensions.cs#L439) method 

```
public static Try<B> Bind<A, B>(this Try<A> self, Func<A, Try<B>> binder) =>
   MTry<A>.Inst.Bind<MTry<B>, Try<B>, B>(self, binder);
```

And the `Bind` method takes you to 
```
public MB Bind<MONADB, MB, B>(Try<A> ma, Func<A, MB> f) 
   where MONADB : struct, Monad<Unit, Unit, MB, B>
{
   var mr = ma.Try();
   if (mr.IsFaulted) return default(MONADB).Fail(mr.Exception);
   return f(mr.Value);
}
```

As we can see the first line evaluates the monad by calling `Try`. My understanding of Monadic composition is that it does not produce effects as a result of the composition. If we stick with the current implementation it will as `Try` wraps a function that makes a network call that can throw an Exception or produce a result. So my question is 

1. If I am reading this correctly, what are the motivations to have a `Bind` implementation that produces effects as part of the composition?
2. Is there a more appropriate `Bind` function for a `Try` monad in the library? 
3. The implementation that doesn't eagerly evaluate is pretty simple, I am happy to submit a PR for a  `Bind` implementation that will compose without the evaluation. Is that all there is to it?

I am new to the library. Great work BTW.

**Comment by louthy** [comment]
> My understanding of Monadic composition is that it does not produce effects as a result of the composition

That's not strictly true.  It all depends on whether the type is lazy or strict.  All the Option, Either, Seq, etc. monads are strict and invoke immediately too.  In this case the type _is_ a lazy type and therefore it probably should be changed.

**Comment by afifmohammed** [comment]
The monadic types you have quoted are pure computations hence don’t produce side effects when composed. We are saying the same thing using different terminology.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by louthy** [comment]
No we’re not.  They’re all pure.  The computations only stop being pure if they perform operations that interact with the outside world.  There’s no obligation for Try to be lazy or strict, it’s merely a side-effect if Try being implemented as a delegate that makes it lazy.  But it could just have easily been implemented strictly.  

The moment of execution of the computation has nothing to do with its  referential transparency

**Comment by afifmohammed** [comment]
For an implementation where `Try` is not interacting with the outside world (i.e not making network calls), I agree. So what are the next steps here?

**Comment by afifmohammed** [comment]
> My understanding of Monadic composition is that it does not produce effects as a result of the composition.

BTW when I say that I literally mean `Bind` invocations should not result in interactions with the outside world, i.e. make network calls.

**Comment by afifmohammed** [comment]
My issue is not about how any function in C# can technically be impure hence bind is impure. 
In the case of composing Try’s, given Try is a lazy construct, does the composition warrant strict evaluation? 
My comments around bind producing side effects (calls to the outside world) is based of my (work in progress) understanding that a Try monad exists to wrap an impure operation.

**Comment by bender2k14** [comment]
> My issue is not about how any function in C# can technically be impure hence bind is impure.

I not sure I made my point clearly enough.  I will try and say it another way.  I am saying that `Bind` is pure _even if_ it is possible to pass an impure delegate into it.  Or said another way.  In absolute terms, `Bind` is pure.  But relatively speaking, maybe one can say "This particular call to `Bind` is impure because the delegate passed to it is impure".  Not exactly sure about this wording though.  This is how I think and speak about it, but maybe that is not how others think and speak about it.

> In the case of composing Try’s, given Try is a lazy construct, does the composition warrant strict evaluation?

No, you are correct; it does not. Recall that @louthy said

> In this case the type is a lazy type and therefore it probably should be changed.

in agreement with you on that point.

**Comment by bender2k14** [comment]
So how would you like this fixed @louthy?

I don't see how to do this with the existing methods and their implementations.

I think I could do it if [the method](https://github.com/louthy/language-ext/blob/master/LanguageExt.Core/ClassInstances/Monad/MTry.cs#L179)
```
public Try<A> Run(Func<Unit, Try<A>> ma) =>
    ma(unit);
```
were lazy instead of also being eager.

**Comment by afifmohammed** [comment]
This is how I had modified it to ensure the laziness is intact.

```
public static Try<B> Bind<A, B>(this Try<A> self, Func<A, Try<B>> binder) => () =>  
  self.Try().Match(
    Succ: a => binder(a).Try(), 
    Fail: e => new Result<B>(e)); 
```

Also the [`SelectMany`](https://github.com/louthy/language-ext/blob/d4623a0885207c1f39f0d31c573222a4b227532e/LanguageExt.Core/DataTypes/Try/Try.Extensions.cs#L485) extension that enables the `LINQ` style composition (current implementation included below for reference) has the same issue of strict evaluation. 
```
public static Try<C> SelectMany<A, B, C>(
  this Try<A> self,
  Func<A, Try<B>> bind,
  Func<A, B, C> project) =>
    MTry<A>.Inst.Bind<MTry<C>, Try<C>, C>(self, a =>
      MTry<B>.Inst.Bind<MTry<C>, Try<C>, C>(bind(a), b =>
        MTry<C>.Inst.Return(project(a, b))));
```

I modified it to be the following to keep the laziness intact.
``` 
public static Try<C> SelectMany<A, B, C>(
  this Try<A> self,
  Func<A, Try<B>> bind,
  Func<A, B, C> project) => () =>
    self.Try().Match(
      Succ: a => bind(a).Try().Match(
        Succ: b => project(a, b), 
        Fail: ex => new Result<C>(ex)),
     Fail: ex => new Result<C>(ex));
```

Beyond that I am not aware if I have missed something around conventions in the library around how to build implementations from underlying functions.

**Comment by afifmohammed** [comment]
Looking through [Try Extensions](https://github.com/louthy/language-ext/blob/d4623a0885207c1f39f0d31c573222a4b227532e/LanguageExt.Core/DataTypes/Try/Try.Extensions.cs) there a few other functions in that class that take a `Try` for input and return a `Try` and are strict in evaluation. @louthy would you consider changing them all to preserve the laziness?

**Comment by bender2k14** [comment]
Sure, but you didn't change the second `Bind` you referenced to be lazy. That is what I don't know how to do with the currently available methods.

**Comment by afifmohammed** [comment]
I don't understand the second `Bind` completely as it returns an `MB` abstraction. Haven't dug enough in the library to follow the Generic abstractions.

**Comment by bender2k14** [comment]
That method is trying to implement `Bind` "from" the `Try` monad "to" any other monad.  So what your issue has made me think is that methods like this have to be implemented lazily in case the target monad is lazy.
