### ISSUE TITLE
Sugestion: Continuations

### ISSUE THREAD

**Issue by lucasteles** [louthy/language-ext#453]
I have knew a library called Tango, and its very similar in purpose in comparison with this project, Is younger, but have a feature i think can be useful

a "pipeline operator", something like

```cs
Continuation<bool, int> continuation = 5;
Option<int> optionResult = 
    continuation 
    > (value => value + 5)
    > (value => value + 10)
    > (value => value + 10)
```

more here:
https://gabrielschade.gitbooks.io/tango/content/Types/Continuation/Introduction.html

**Comment by louthy** [comment]
@lucasteles Hi Lucas, we already have this as the `Cond` type.  I think continuations are of limited use to be honest, and I don't think it gets much usage.  I would much prefer to try and formulate a general case Free monad which would be the ultimate mechanism for chaining computations.

**Comment by lucasteles** [comment]
@louthy  Makes sense, 

By the way, i liked the Idea off using the ’>’ e ’>=’ operators for simulate fsharp ’|>’ 

Did we have something like it?

**Comment by louthy** [comment]
> By the way, i liked the Idea off using the ’>’ e ’>=’ operators for simulate fsharp ’|>’

I've considered it a number of times, but I'm not 100% sure it's a good idea.  I think it can look quite elegant if you know what it is, but to an outsider who's looking at your code and is a C# programmer they will probably be a bit confused.

I tend to use `||` and `|` for `mplus` but that's about the extent of it (relying on LINQ instead for bind)
