### ISSUE TITLE
Validation's .Succ and .Fail fluent methods ?

### ISSUE THREAD

**Issue by xlecoustillier** [louthy/language-ext#455]
Hi,

Hoping this question has not been asked yet (didn't find it).

Is there a reason why there is no Succ() and Fail() fluent methods available for Validation type, as we have Left() and Right() for Either ?

I don't really mind using `val.Match(Succ: /**/, Fail: /**/)`, but as we already use a lot of fluent syntax on other types like Either and Option in our codebase, that would be more consistent.

Anyway, thanks for the great work, this library is amazing! 🎉

**Comment by louthy** [comment]
@xlecoustillier 

> Is there a reason why there is no Succ() and Fail() fluent methods available for Validation type

Yep, sometimes I'm lazy ;)  I have added the fluent versions and they'll be in the next release.

**Comment by louthy** [comment]
Released in `v2.0.30`
