### ISSUE TITLE
Unneeded code in Task.Cast<>

### ISSUE THREAD

**Issue by bender2k14** [louthy/language-ext#462]
In the `Task` Extension [`Cast<>`](https://github.com/louthy/language-ext/blob/019fb022f0eec732d307b24f06e7e150391b4390/LanguageExt.Core/DataTypes/Task/Task.Extensions.cs#L244), which is
```
public static async Task<T> Cast<T>(this Task source)
{
    await source;
    if (source == null) return default(T);
    return (T)PropCache<T>.Info.GetValue(source);
}
```

the `if`'s predicate is always `false` since `await`ing a `null` `Task` causes a `NullReferenceException` to be thrown.

**Comment by bender2k14** [comment]
Oh, I think the intended semantics are as follows.  If the runtime type of source is `Task<T>`, then something semantically equivalent to this instance is returned with the stronger type.  Otherwise, the runtime type matches the compile-time type of `Task` but we still return an instance of `Task<T>` that completes when `source` completes and then returns `default<T>`.

Unfortunately, neither case has this behavior.  The middle line is essentially dead code (as described above) and the last line, if reached, throws an excretion (as described [here](https://github.com/louthy/language-ext/issues/463)).

If you would like @louthy , I can make a PR that modifies this method to achieve the behavior I described above.

**Comment by louthy** [comment]
Yep, the `source` check should be removed and should just `throw` an `ArgumentNullException` as the first line.

**Comment by bender2k14** [comment]
What about the case when `source` is not `null`?  I also think that behavior is incorrect (see [#463](https://github.com/louthy/language-ext/issues/463)).

**Comment by louthy** [comment]
I have a fix for this ready, just not currently at the computer it's on, so don't worry about doing a PR
