### ISSUE TITLE
Add the capability to parse an IP address to the Prelude.Parse module

### ISSUE THREAD

**Issue by SeanFarrow** [louthy/language-ext#469]
It would be nice if the Prelude.Parse module allowed parsing an IP address from a string.

**Comment by louthy** [comment]
Not totally against the idea, but it would add an extra dependency which might be undesirable.  Open to opinions.

**Comment by SeanFarrow** [comment]
It only adds system.net, which is part of the BCL.
If things like this are undesirable in the core, have you considered a contrib project where things like this could live?

**Comment by louthy** [comment]
Yup, less concerned about .NET Framework, more concerned with .NET Core
dependencies. I’ve not checked if it’s available by-default or requires
another nuget include

**Comment by louthy** [comment]
Great, thanks for checking.  Unless anybody else has any major concerns then I'm happy to accept a pull-request for this.

**Comment by louthy** [comment]
This is now deployed.

**Comment by louthy** [comment]
Scratch that, wrong issue!

**Comment by bender2k14** [comment]
I didn't check if it is released, but you accepted PR #470 that resolves this issue.

**Comment by louthy** [comment]
Ha, ok, yes, this is released!
