### ISSUE TITLE
"throwing their toys out of their prams"

### ISSUE THREAD

**Issue by puffnfresh** [louthy/language-ext#472]
I was reading the README and came across this:

> I'm not an academic, but I'm sure there will be someone throwing their toys out of their prams at this point.

I'm not entirely sure what it means nor the point but I don't want to spend time on it. I think the sentence goes against the Code of Conduct:

> * Using welcoming and inclusive language
> * Being respectful of differing viewpoints and experiences

**Comment by bender2k14** [comment]
> I'm not entirely sure what it means nor the point but I don't want to spend time on it.

I am not sure that I understand. If you don't want to spend time on this, then why did you create this issue? Are you saying that you will not reply to any questions asked of you on this issue?

**Comment by louthy** [comment]
It was meant to be tongue-in-cheek, I'll change it.
