### ISSUE TITLE
Reader / State bool return value meaning

### ISSUE THREAD

**Issue by slimshader** [louthy/language-ext#473]
Hi,

I am trying to replace my custom Reader and State monads with the ones from LangExt but not sure what is the bool return value is in ValueTuple<A, bool> is for (from Reader<> docs). I also looked at [csharp-monad](https://github.com/louthy/csharp-monad) for clues but no dice. Along this this line: would it be possible to add short examples (a la csharp-monads to the Monad docs?), would be really helpful for newcomers.

**Comment by louthy** [comment]
Often [the source-code](https://github.com/louthy/language-ext/blob/master/LanguageExt.Core/DataTypes/Reader/Reader.cs) can help ;)
```c#
namespace LanguageExt
{
    public delegate (A Value, bool IsFaulted) Reader<Env, A>(Env env);
}
```

**Comment by slimshader** [comment]
@louthy While the definition of delegate obviously clarifies everything and renders the concept of documentation obsolete, as a a newcomer to I'd still appreciate one ;P

Thanks a lot for pointing me to examples, will study them in detail but in my defense, I did look for StateTests and ReaderTests in the Test folder.
