### ISSUE TITLE
No documentation in intellisense.

### ISSUE THREAD

**Issue by rantri** [louthy/language-ext#479]
Xml documentation is not included in the NuGet packages.
So we can't see functions documentation in Visual Studio Intellisense.

This can be easily solved by adding:
`<DocumentationFile>bin\$(Configuration)\$(TargetFramework)\$(AssemblyName).xml</DocumentationFile>`

in csproj property group.

**Comment by bender2k14** [comment]
Hello @rantri. That is great that you think you know the fix. This issue also bothers me. I opened issue #436 about it some time ago, but I haven't put enough time into it to find the solution. I hope your solution works!

**Comment by louthy** [comment]
Didn't mean to close this.  Anyway, I have added the suggested entry in the csproj and deployed the nuget packages (`v3.0.23`).  I haven't tried adding them to a test project yet, but I guess we'll get to find out if this helps soon :)

**Comment by louthy** [comment]
Fixed, thanks @rantri

**Comment by CK-LinoPro** [comment]
This problem seems to have been reintroduced when moving from netstandard2.0 to netstandard2.1:
https://github.com/louthy/language-ext/commit/01bec9f47e962b88292c30083b776be0ab860bff#diff-a2eb26bcfe1e5d97500c75f6d3698b0dL27
