### ISSUE TITLE
Units of measure seem to produce the wrong numbers

### ISSUE THREAD

**Issue by MrYossu** [louthy/language-ext#484]
I've just discovered the units of measure, and was very excited until I discovered that I was getting the wrong numbers!

For example, if I create a variable as follows...

`Velocity speedLimit = 30 * mph;`

...then I would expect the following to produce 30...

`speedLimit.MilesPerHour`

Instead, it produces 2.31481481481481E-06.

`speedLimit.MetresPerSecond` produces 13.4112000000536, which is correct, but `speedLimit.KilometresPerHour` produces 3.72533333334823E-06, which is wrong, as it should be 48.2803.

What did I do wrong? Thanks

**Comment by louthy** [comment]
It seems there’s a bug in the per hour calculations (a divide by 3600 instead of multiply).  Use the per second calculations until I get to it.

**Comment by louthy** [comment]
Fixed in `v3.0.28`
