### ISSUE TITLE
Why no units of measure for mass?

### ISSUE THREAD

**Issue by MrYossu** [louthy/language-ext#485]
Sorry, seem to be asking a lot of questions!

Why aren't there any units of measure for mass? Seems like a very basic unit to be missing.

Thanks

**Comment by louthy** [comment]
Because I don’t have infinite time. Feel free to create a pull request.

**Comment by MrYossu** [comment]
Hee hee, great answer!

Like all your other users, I'm extremely grateful for all the time you've put into this amazing library. I'll have a look at opening a pull request (never done that before, but I'm sure it doesn't need a PhD!).

Thanks

**Comment by MrYossu** [comment]
Hmm, just been reading the guidelines. Pull requests are for clever people who know how to fix things. Not sure I'm in that category! I'm good at asking stupid questions, but I don't think I'd know how to do this.

Can I make a feature request instead? That way you get to do all the hard work! Seriously, I'll have a look at your code and see if I can figure it out, but don't hold your breath. If you (or anyone else) knows how to do this, it's more likely to get done.

Thanks again.

**Comment by louthy** [comment]
Deployed in `3.1.6-beta`.  Thanks for contributing @MrYossu
