### ISSUE TITLE
How can I use the TryConfig?

### ISSUE THREAD

**Issue by TonyHernandezAtMS** [louthy/language-ext#495]
I've come across this class and was wondering what the intended purpose is and how I can leverage it. Would be great if I could hook it up to my instrumentation service and have all my exceptions go there instead of bubbling up.

```csharp
using System;

namespace LanguageExt
{
    public static class TryConfig
    {
        public static Action<Exception> ErrorLogger = ex => { };
    }
}
```

**Comment by louthy** [comment]
It's a mutable field, so you can just set it directly:
```c#
   TryConfig.ErrorLoger = (Exception ex) =>
    {
        // Your error handler here
    };
```
Whenever `Try`, `TryAsync`, `TryOption`, or `TryOptionAsync` catch an `Exception` they call this method.

In hindsight it probably would have been better as an observable or an event.
