### ISSUE TITLE
Request: ConfigureAwait(false) within async LanguageExt code (await...)

### ISSUE THREAD

**Issue by StefanBertels** [louthy/language-ext#501]
Hi, I had a (obscure) dead-lock problem when using OptionAsync / BindAsync.

The reason was: async code is called by sync code (i.e. Task.Wait or Task.Result or Task.GetAwaiter().GetResult) and there were other things going (probably other async code in a different library) that mattered (consumes threads / task contexts).

I know blocking async code is bad and I should either avoid async calls at all or refactor everything to async.

But the problem can be solved* by calling ConfigureAwait(false) on Task before calling blocking functions (Wait/Result).
I do this in my code (buying the drawbacks) but have still hit a dead-lock when calling BindAsync because BindAsync internally uses awaitwithout ConfigureAwait(false).

Question / suggestion: could LanguageExt use ConfigureAwait(false) so sync callers will not dead-lock?

Background information: it does not dead-lock always, depends on other code around. The critical thing is that without ConfigureAwait(false) the code after await will run on the same context (thread) as the code before. If this context is not available (in use elsewhere) this will block. With ConfigureAwait(false)the code is allowed to continue in another context (thread) which in most cases is no problem (if you don't need the same thread context like in GUI code). This will nearly always result in a working solution (no dead-locks) as long as you don't exhaust the used thread pool -- too many blocking functions (Wait/Result) at the same time.

https://medium.com/bynder-tech/c-why-you-should-use-configureawait-false-in-your-library-code-d7837dce3d7f
https://msdn.microsoft.com/en-us/magazine/jj991977.aspx

**Comment by bender2k14** [comment]
You can create a failing test like I did in #317

**Comment by bender2k14** [comment]
I have put a lot of thought into this. I don't think it is so obvious when to use `ConfigureAwait(false)`. I used to follow the advice from articles like the one to which you linked. In particular, I have had some PRs included into Language Ext that used `ConfigureAwait(false)`. However, I not do sure now.

Suppose you write a failing test and then contribute a PR on which your test passes. Then I think that I can write a test that passes on `master` but fails on your commit. More specifically, my test would include context-sensitive code that I would have executed in the correct context on `master` but in the wrong context on your commit.

As it says in the article to which you linked, my test fail because an exception would be thrown.  In contrast, your test would fail (at least in principle) because a deadlock occurred.

To be clear, I would prefer to debug "my" thrown exception than "your" deadlock. So I do agree with your request to add more calls to `ConfigureAwait(false)`.

**Comment by StefanBertels** [comment]
It's difficult to build a good real-world test because the dead-lock might not occur. I might try to build a synthetic one just to show the difference...

This is a conceptional problem. I think using `ConfigureAwait(false)` will in summary be better, because:

1. LanguageExt is most useful in business code and library code, perhaps more than in GUI code (very poor argument, I know  ;-)).

2. Dead-lock problems are very ugly in general and hard to isolate in task context. Depends on how tasks are assigned to contexts. IMHO this is nothing you should have to care about in general.

3. Using `ConfigureAwait(false)` might result in local issues (as @bender2k14  mentioned: exceptions will help). You can find (local) workarounds there. If you use other libraries with async features, you have to care about context things, too (i.e. be sure about library internals or better don't rely on them). 
_
In mixed code (sync calling async) the status quo will result in issues (dead-locks) that occur somewhere but have to be handled more generally, which means: change your calling code to be async. 
I did this for my use case (replacing OptionAsync with Task<Option> ...) and it resulted in a really ugly code mix. If someone tries to make this code nice (again) he will produce code with the dead-lock issue again without knowing -- the dead-lock probably will not occur in tests-cases and perhaps will arise in production a lot later. 
In my situation a completely unrelated piece of code made the difference (dead-lock yes or no). This other code wasn't async at all but used a library which at least caused a different context behaviour of the task scheduler (maybe internally using Tasks). Even after reproducing the dead-lock it took some time to build a fix for this.

For the GUI part: I'm not sure what a real-world example using LanguageExt async types would look like that causes an exception. @bender2k14: Do you have something in mind?

**Comment by bender2k14** [comment]
Suppose Language Ext always calls `ConfigureAwait(false)` after `await`ing a task.  Then executing
```
public void async OnButtonClick(...) => await unit
  .AsTask()
  .Map(async _ => {
    await Task.Delay(1);
    return unit;
  })
  .Map(_SomeContextSenstiveMethod);
```
will throw the exception in `_SomeContextSenstiveMethod` because it is not executed in the correct context.

**Comment by StefanBertels** [comment]
Here is a GUI example that shows the problem and a potential solution.

```
        // This example requires a simple Windows Forms application with a button "copy" and a textbox "txtOutput"

        /// <summary>
        /// Helper function to make sure the passed async function gets our synchronisation context
        /// </summary>
        /// <typeparam name="T"></typeparam>
        /// <typeparam name="TResult"></typeparam>
        /// <param name="someAsyncFunction"></param>
        /// <returns></returns>
        Func<T, Task<TResult>> WithCurrentContext<T, TResult>(Func<T, Task<TResult>> someAsyncFunction)
        {
            var scheduler = TaskScheduler.FromCurrentSynchronizationContext();
            return x => Task.Factory.StartNew(
                () => someAsyncFunction(x),
                CancellationToken.None,
                TaskCreationOptions.None,
                scheduler).Unwrap();
        }

        /// <summary>
        /// some library function using ConfigureAwait(false) when awaiting a passed async function
        /// </summary>
        /// <typeparam name="T"></typeparam>
        /// <typeparam name="TResult"></typeparam>
        /// <param name="input"></param>
        /// <param name="mapper"></param>
        /// <returns></returns>
        async Task<TResult> Apply<T, TResult>(T input, Func<T, Task<TResult>> mapper)
        {
            await Task.Delay(1).ConfigureAwait(false);
            return await mapper(input).ConfigureAwait(false);
        }

        async Task<bool> ShowText(string text)
        {
            await Task.Delay(1000);
            txtOutput.Text = text;
            return true;
        }

        private async void copy_Click(object sender, EventArgs e)
        {
            txtOutput.Text = "processing...";

            // will work
            await Apply($"{DateTime.Now}", WithCurrentContext<string, bool>(ShowText));

            // will throw error:
            await Apply($"{DateTime.Now}", ShowText);
        }
```

- `copy_Click` is the async method attached to the event handler
- `ShowText` is some user function doing a side effect to GUI element (context sensitive function)
- `Apply` is a place holder for any library function (could be BindAsync or any other higher-order async LanguageExt function) using ConfigureAwait(false)
- finally `WithCurrentContext` is an example how this can be fixed locally without changing code structure

**Comment by StefanBertels** [comment]
Just found an interesting link:

https://blogs.msdn.microsoft.com/benwilli/2017/02/09/an-alternative-to-configureawaitfalse-everywhere/

I'm not sure whether this might solve my issue / make this request obsolete.

Another (probably bad) idea: should/could this be configurable? Like setting some global option (generally a bad idea) `SetConfigureAwait(bool)` and using that value all over? Hmm.
