### ISSUE TITLE
Is this supposed to be named ApplEither instead of ApplyEither?

### ISSUE THREAD

**Issue by Protiguous** [louthy/language-ext#504]
In **ApplEither.cs**, you have it named "**ApplEither**".. just wondering if this a typo?
At language-ext/LanguageExt.Core/ClassInstances/Applicative/ApplEither.cs

Still trying to wrap my head around your project.. it seems awesome!

**Comment by Protiguous** [comment]
language-ext/LanguageExt.Core/ClassInstances/Applicative/ApplEither.cs

**Comment by bender2k14** [comment]
I think `Appl` is short for `Applicative`, not `Apply`.

**Comment by Protiguous** [comment]
Ah! I see. Thanks.
