### ISSUE TITLE
Should/could OptionAsync, EitherAsync be equatable?

### ISSUE THREAD

**Issue by StefanBertels** [louthy/language-ext#510]
Should/could async types implement `Equals`?

This unit test fails because it is missing now:

```
   [Fact]
        public async Task Equality()
        {
            var x = SomeAsync(3);
            var y = SomeAsync(3);
             Assert.Equal(x, y);
            Assert.True(x.Equals(y));
            // Assert.True(x == y);
        }
```

Currently we cannot compare async types OptionAsync / EitherAsync in a meaningful way. 
As these types contain lazy evaluated inner values comparison is only possible if

(a) any contained lazy computation is executed
(b) the comparision is an async operation itself (`EqualsAsync` -- non-standard)

I think there are fewer cases where equality for async types is useful as the point of async types is that we probably want to pass lazyness around (everything should be an async expression somehow).

But for unit tests this would reduce code and having some variant for (b) would be nice, too. Like:

Task<bool> equal =  SomeAsync(1).EqualsAsync(SomeAsync(2))

One problem might be GetHashCode(). I think there are three options there:

(1) execute lazy computation and create a good hash code (use values)
(2) always return 0
(3) no implementation (probably different for different instances)

There's probably very limited use for types like OptionAsync to be used as hash table key which could make (2) an acceptable choice (very easy to imlement, might result in performance penalty when used). Solution (3) would break some rules (hash code will be different for equal items).

Any thoughts on this?

**Comment by bender2k14** [comment]
> hash code will be different for equal items

That is unacceptable.

**Comment by louthy** [comment]
`EqualsAsync` would be good if it's missing from anywhere, but `Equals` shouldn't exist.  Option and Either are not the same, so a conversion should be used to unify the types before equality.  PRs welcome for `EqualsAsync`
