### ISSUE TITLE
Unexpected behavior when calling Option.Map to null value.

### ISSUE THREAD

**Issue by faeriedust** [louthy/language-ext#517]
I stumbled on this by happenchance earlier, but this test passes, which felt very strange to me.

```
[Fact]
public void ThisPasses() {
  object x = null;

  Option<object> result = Some(new object())
    .Map(_ => x);

  Assert.Equal(None, result);
}
```

I was expecting to get a `LanguageExt.ValueIsNullException`.

If I had intended this behavior, then my impression is that I should have called `.Bind`, not `.Map`

**Comment by bender2k14** [comment]
Here is how I would present this bug.

My expectation is that this test would pass...

```
[Fact] // fails
public void OptionMap_ToNull_ThrowsValueIsNullException()
{
    var option = Some(new object());
    Assert.Throws<ValueIsNullException>(() => option.Map(_ => (object)null));
}
```

...because then the behavior would be consistent with other monads like `Either<,>`:
```
[Fact] // passes
public void EitherMap_ToNull_ThrowsValueIsNullException()
{
    var either = Right(new object()).Bind<Unit>();
    Assert.ThrowsAny<Exception>(() => either.Map(_ => (object)null));
}
```

Instead, I expect this test to fail, but it passes:
```
[Fact] // passes
public void OptionMap_ToNull_FailByThrowningValueIsNullException()
{
    var option = Some(new object())
        .Map(_ => (object)null);
    Assert.Equal(None, option);
}

**Comment by louthy** [comment]
The bug is [caused by this](https://github.com/louthy/language-ext/blob/master/LanguageExt.Core/ClassInstances/Monad/MOption.cs#L198).  I don't have any time at the moment to look at the extent of the fallout if I change it to `Some(x)`, so I'll just leave this here as a reminder for when I do.

**Comment by bender2k14** [comment]
Maybe changing [`Return` of `Option<>`](https://github.com/louthy/language-ext/blob/master/LanguageExt.Core/ClassInstances/Monad/MOption.cs#L198) is correct.

At least the behavior for [`Map` of `FOption`](https://github.com/louthy/language-ext/blob/master/LanguageExt.Core/ClassInstances/Functor/FOption.cs#L19) should be changed, either directly or indirectly.  I achieved this in PR #518 by directly changing that function.
