### ISSUE TITLE
Add `public Either<L, R> IfRight(Action<R> right)`

### ISSUE THREAD

**Issue by ceddlyburge** [louthy/language-ext#521]
Hi There

I would like to add an overload of `IfRight` that returns the Either. This would allow me to write some things in fluent syntax. I realise that its not a pure function, but it would still be useful (and IfRight is already not a functional thing).

At the moment I have to write code like this

```cs
Either<String, ApplicationRunner> applicationRunnerOrError = new ApplicationRunner();

applicationRunnerOrError = applicationRunnerOrError.Bind(CheckAlreadyRunning);
applicationRunnerOrError.IfRight(u => Initialize());
applicationRunnerOrError = applicationRunnerOrError.Bind(CheckPermissions);
applicationRunnerOrError.Match(Run, ShowErrorMessage);
```

but with the proposed function I could do this

```cs
new ApplicationRunner()
    .Bind(CheckAlreadyRunning)
    .IfRight(u => Initialize());
    .Bind(CheckPermissions);
    .Match(Run, ShowErrorMessage);
```

I'd be happy to submit a PR with the change if you would like.

Cheers

Cedd

**Comment by bender2k14** [comment]
I don't think this is a good idea.

> At the moment I have to write code like this

"have to" is a strong phrase.  There is very little that you have to do.

Here is a fluent workaround using the existing API.

```
public void Method() =>
    new ApplicationRunner()
        .Bind(CheckAlreadyRunning)
        .Map(Initialize);
        .Bind(CheckPermissions);
        .Match(Run, ShowErrorMessage);

private T Initialize<T>(T t) {
    // do initializing work
    return t;
}
```

**Comment by ceddlyburge** [comment]
There is a simple workaround, it's a good point.

I don't know why you don't think it is a good idea though?

**Comment by bender2k14** [comment]
There is already a method called `IfRight` with input type `Action<>` (that returns `Unit`), so you can't add `public Either<L, R> IfRight(Action<R> right)` like you are requesting without removing that method.

**Comment by ceddlyburge** [comment]
Ok, this is a also a fair point.

I wasn't meaning to replace the existing method, but to add a new method.

How would you feel if I change the title to the following:

Add `public Either<L, R> IfRightFluent(Action<R> right)`

**Comment by louthy** [comment]
@ceddlyburge Use the `Do` function in the latest release.  It's the same as `Iter` on all of the monadic and collection types, except it returns the original structure, allowing for fluent side-effects.

Use at your own peril ;)
