### ISSUE TITLE
Queryable.HeadOrNone Constructs Query for more than 1 item

### ISSUE THREAD

**Issue by faeriedust** [louthy/language-ext#523]
In a earlier fix for #488 , we changed the implementation of `Query.headOrNone<T>` from `list.ToSeq().HeadOrNone()` to `list.AsEnumerable().HeadOrNone()`.

However this still isn't ideal behavior as the constructed query now is asking for all of the items instead of just the required single item.

Therefore, I propose we change it to `list.Take(1).AsEnumerable().HeadOrNone()` (and fix similar cases)

**Comment by louthy** [comment]
Seems reasonable
