### ISSUE TITLE
TryAsnyc with non generic task

### ISSUE THREAD

**Issue by eisendle** [louthy/language-ext#525]
Hi Paul,

I accidentally used TryAsync with a non generic Task. When calling TryAsync.Match, I expected that the task is being awaited, but as there is no overload for TryAync with Task, instead this overload was used:

`public static TryAsync<A> TryAsync<A>(A v)`

As the success function of match didn´t use the result (in this case Task), this misbehaviour was hard to spot.

In order to make TryAsync work with Task correctly and prevent other users to fall into this pifall, I´d like to propose two new overloads for TryAsync:

` public static TryAsync<Unit> TryAsync(Task v))`

 `public static TryAsync<Unit> TryAsync(Func<Task> f)`

I´m happy to supply a pull request, if you agree to add the overloads

**Comment by bender2k14** [comment]
`Task` is the asynchronous equivalent of`void`.  Neither are consistent with functional style..

In my local project, I have created an extension method that lifts `Task` to `Task<Unit>`.  I prefer adding this one method than adding overloads everywhere for `Task`.

**Comment by WarrenFerrell** [comment]
Could a funasync method be added to Prelude so the lift function is already provided.

**Comment by louthy** [comment]
@WarrenFerrell `task.ToUnit()` already exists, which then gives all the other fuctionality.

**Comment by WarrenFerrell** [comment]
@louthy Thank you, I figured there had to be something but this post was the only thing I was able to find... I added a PR #741 since a significant number of client libraries are deprecating their synchronous apis and this is likely to be an issue going forward.
