### ISSUE TITLE
Confused about using Try in an enumerable

### ISSUE THREAD

**Issue by MrYossu** [louthy/language-ext#526]
OK, bear with me with this silly example, but I'm still trying to get my head around all this stuff.

Suppose I have the following (admittedly stupid) situation: I have a `Func<int, float>` that might throw an exception, for example...

    Func<int, float> f = n => 1 / n;

Obviously, if you pass zero into this function it will throw an exception. Suppose I also have an `Enumerable<int>` and want to apply the `Func` to it...

    var result = nums.Select(n => f(n));

I guess I need to use `Try` to handle the fact that `f` might throw an exception...

    var result = nums.Select(n => Try(() => f(n));

This gives me an `IEnumerable<Try<float>>`. What do I do with this now? Let's say I have two different requirements (probably not at the same time)...

1) End up with an `IEnumerable<float>` that includes only the results that didn't throw an exception
2) End up with (something) that includes the exceptions. I guess this would be an `IEnumerable<Exception>` but am not sure

Anyone able to explain how I would achieve each of these goals? Thanks

Again, please forgive the silly examples, but I find playing around like this helps me understand what's going on.

**Comment by bender2k14** [comment]
First, some small comments.

Since `1 / n` return `int` when `n` is an `int`, the type of `f` is more specifically `Func<int, int>`.

You can eta reduce `nums.Select(n => f(n))` to simply `nums.Select(f)`. Also, `Select` is probably not the best name for this behavior.  Microsoft picked it because of its similarity to the concept with the same name in SQL.  In functional programming, this behavior is known as `Map`.  Language Ext contains a function called `Map` that just calls this `Select`.  That way, you can write `nums.Map(f)`.

Now to answer your question, here is the first thing that comes to mind for me.
```
IEnumerable<Either<Exception, double>> result = Range(0, 10)
    .Map(n => Try(() => 1.0 / n))
    .Map(t => t.ToEither());
//Requirement 1
IEnumerable<double> r1 = result.Rights();
//Requirement 2
IEnumerable<Exception> r2 = result.Lefts();
```

> ...I find playing around like this helps me understand what's going on.

You are right, and you should continue to do so.

**Comment by MrYossu** [comment]
@bender2k14 That's brilliant, thanks so much for the reply.

Only question is that I don't get anything in the Lefts, and the Rights include "infinity" for the divide-by-zero cases. I thought the idea of Try was that it would produce a left (if you know what I mean) in the case of an exception.

Any ideas? I slightly modified your code to throw more exceptions...

    IEnumerable<Either<Exception, double>> result = Range(0, 10)
        .Map(n => Try(() => 1.0 / (n % 3)))
        .Map(t => t.ToEither());
    IEnumerable<double> r1 = result.Rights().Dump();
    IEnumerable<Exception> r2 = result.Lefts().Dump();

If you run this in LinqPad (where I do all of my playing), you'll see what I mean.

Thanks again.

**Comment by MrYossu** [comment]
Hmm, not sure if this is to do with `Try` or not. If I change the second line to the following...

    .Map(n => Try(() => n % 3 == 0 ? throw new ArgumentException("Jim") : 1.0 / (n % 3)))

...then I get the expected result. It looks like `Try` is swallowing the exception. Does that makes sense?

Thanks again

**Comment by colethecoder** [comment]
In C# a double divided by zero is Infinity, so you wouldn't get any exceptions, it's nothing to do with LanguageExt's Try.

If you go back to your original function `n => 1 / n` you should see the exceptions.

You can also avoid the ToEither bit in the example as there are extensions to support IEnumerable<Try<T>> so you can simply do:

```csharp
IEnumerable<Try<int>> result = Range(0, 10)
                .Map(n => Try(() => 1 / n));
IEnumerable<int> r1 = result.Succs();
IEnumerable<Exception> r2 = result.Fails();
```
