### ISSUE TITLE
Readable nested ternary operators

### ISSUE THREAD

**Issue by bender2k14** [louthy/language-ext#534]
I recall reading examples by @louthy for how to format nested ternary operators to make them readable, but now I can't seem to find any of them.

Can someone link me to one of those examples?

Alternatively, was this the formatting?
```
var n = b1 ? n1 :
        b2 ? n2 :
             n3;
```

**Comment by louthy** [comment]
I usually do:

    var x = p1 ? t1
          : p2 ? t2
          : el;

Writing this on my phone, so hopefully it comes out ok!

**Comment by bender2k14** [comment]
Looks perfect.  Thanks! :)
