### ISSUE TITLE
parse family of methods are not pure

### ISSUE THREAD

**Issue by bender2k14** [louthy/language-ext#535]
All the parse methods in [Prelude_Parse.cs](https://github.com/louthy/language-ext/blob/b81f45ce7ab358e707e16785c193aed6ebbc5a95/LanguageExt.Core/Prelude/Prelude_Parse.cs) (such as `parseInt` and `parseBool`) have the `Pure` attribute on them.

However, some are not pure.  As I was just reading in [this blog post](https://www.dotnetcurry.com/csharp/1464/pure-code-csharp), the behavior of some of those standard library parse calls depends on global formatting state.

As a side note, what do people use the `Pure` attribute for?  We used to use it along with [Microsoft's code contracts](https://docs.microsoft.com/en-us/dotnet/framework/debug-trace-profile/code-contracts), but we don't do that any more.

**Comment by louthy** [comment]
The `Pure` attribute was requested by someone using Resharper, I think it gives useful warnings if you don't consume the result of a pure method.  In terms of whether the parse functions are pure or not.  Yeah, I see your point, but for all intents and purposes they're pure, it's pretty unlikely that global formatting will be changed mid-operation.  But I agree it doesn't totally fall into pure territory.  

If you want to remove the `Pure` attribute and add `<remarks>` for the lack of purity then I'd be happy to accept.

**Comment by bender2k14** [comment]
I don't see the value using the `Pure` attribute, so I am indifferent about removing it.
