### ISSUE TITLE
 MTOUCH : error MT3001: Could not AOT the assembly 

### ISSUE THREAD

**Issue by asgarddesigns** [louthy/language-ext#537]
I've encountered a pretty strange issue when building on certain machines where the build will fail:

` MTOUCH : error MT3001: Could not AOT the assembly '/Library/TeamCity/buildAgent/work/dd40a4b36aa73d6e/iOS/obj/iPhone/Debug/mtouch-cache/3-Build/LanguageExt.Core.dll' [/Library/TeamCity/buildAgent/work/dd40a4b36aa73d6e/iOS/Project.iOS.csproj]`

This, most importantly, fails on both of our build servers. So definitely a clean build each time. One dev also has this issue, while the other can build with no issue.

I've spent ages trying to determine the difference and had no luck whatsoever. Xamarin versions are  the same, VS up to date, xcode versions are identical, I've checked LLVM is the same....
Build logs don't have anything that sticks out in them, all seems to go fine until that point.
I have also tried `-linkskip=LanguageExt.Core` with no joy.

if I revert to 3.0.31 the build passes on all machines. I've tried 3.1.13, 3.1.14 and 3.1.10

I know I am probably not giving you much to go on. I know you're pretty busy right now, for the moment, bumping to 3.0.31 is _fine_, if you can suggest anything I may have missed....

**Comment by bender2k14** [comment]
So 3.0.3.31 works for you and 3.1.13, 3.1.14 and 3.1.10 don't work for you.

What is the first/oldest version after 3.0.3.31 that doesn't work for you?

**Comment by asgarddesigns** [comment]
In NuGet, 3.1.10 is the next version, so 3.0.3.31 is the last working version published (for my build servers at least).

**Comment by bender2k14** [comment]
Here are the commits that defined those two versions:

- [3.0.31](https://github.com/louthy/language-ext/commit/34813df886ad3bba231c72a4052ef8c1b33bfb4b)
- [3.1.10](https://github.com/louthy/language-ext/commit/ea467301bcd6d96a2bd8040d776dc6cf7b4a1837)

**Comment by bender2k14** [comment]
You could try creating your own NuGet packages for commits between those two commits and seeing if your build passes.  If you do that, I recommend trying those two commits first and confirming that you are able to reproduce the current behavior.

**Comment by asgarddesigns** [comment]
Thanks guys, that gives me somewhere to start when I get back in!

**Comment by mrpantsuit** [comment]
I get this error, too. Setting the linker behaviour to "Link All" seems to resolve the issue (solution recommended here https://forums.xamarin.com/discussion/457/error-could-not-aot-the-assembly-servicestack-text-monotouch-dll), but I'm worried that's going to give me some runtime errors.  Perhaps, as the content in the link suggests, this lib is just too big to use on iOS w/o using the linker on it.

**Comment by louthy** [comment]
I assume this is because the HKT T4 templates generates a ton of extension methods, and that might be pushing some limit.  It's potentially possible to split lang-ext into `Core` and `HKT`, but obviously if you want the transformer extension methods then the problem will continue.
