### ISSUE TITLE
What is the recommended way to get [Pure] attribute recognized?

### ISSUE THREAD

**Issue by mysticfall** [louthy/language-ext#538]
Hi, it's a question rather than an issue. So, please excuse me if it is a wrong place to ask.

I'm using this library in my project via NuGet and my IDE (Rider) complains about _"Impure Method is called for readonly field of value type"_ when I declare an `Option<T>` field as readonly, and try to invoke its method like `Bind`.

I think it shouldn't be the case as the method in question is annotated with `[Pure]`, so I assume that the problem happens because the assembly I get with NuGet strips the attribute, since it is defined with conditional symbol `CONTRACTS_FULL`.

So, my question is, what is the recommended way to use _Language-Ext_ in a project and makes it recognize `[Pure]` attributes that the library contains?

I'm relatively new to .NET so I'm not sure if there's any mechanism I can use by which I can get an assembly for a dependency with debug configuration.

I'd appreciate if anyone could direct me to the right direction.

Thanks!

**Comment by bender2k14** [comment]
I don't even see `PureAttribute` on `Option<>.Bind<>` when using reflection within the Language Ext solution.

**Comment by louthy** [comment]
Do you see other attributes like `NonRecord`, `NonEq`, etc. that are used for `Record` exclusion?  If so, I'd suggest that something is trying to be 'smart' by hiding the `Pure` attribute.

**Comment by bender2k14** [comment]
> I think it shouldn't be the case as the method in question is annotated with `[Pure]`, so I assume that the problem happens because the assembly I get with NuGet strips the attribute, since it is defined with conditional symbol `CONTRACTS_FULL`.
> 
> So, my question is, what is the recommended way to use _Language-Ext_ in a project and makes it recognize `[Pure]` attributes that the library contains?

> I don't even see `PureAttribute` on `Option<>.Bind<>` when using reflection within the Language Ext solution.

Ok.  I figured out what is going on.

As @mysticfall pointed out, `PureAttribute` is defined with the attribute `Conditional("CONTRACTS_FULL")`.  Language Ext doesn't have the symbol `CONTRACTS_FULL` defined and @louthy doesn't define it (temporarily) during the build that creates the NuGet package, so this attribute gets ignored.

@louthy, here is how to include `PureAttribute` in the assembly.

Via Visual Studio:
![screenshot 2019-02-10 20 33 27](https://user-images.githubusercontent.com/34664007/52544013-983af380-2d73-11e9-98ac-c66aafd36bcc.png)

Which corresponds to this source file change:
![screenshot 2019-02-10 20 33 21](https://user-images.githubusercontent.com/34664007/52544021-a557e280-2d73-11e9-8d3a-182ee0e6f7b2.png)

**Comment by louthy** [comment]
Fixed in the next release
