### ISSUE TITLE
Does language-ext have a Using() function?

### ISSUE THREAD

**Issue by MrYossu** [louthy/language-ext#544]
Hello,

One of the functions Enrico Buonanno shows in Functional Programming In C# is the following...
```
static R Using<TDisp, R>(TDisp disposable, Func<TDisp, R> f) where TDisp : IDisposable {
  using (disposable) return f(disposable);
}
```

Does language-ext have such a function?

**Comment by MrYossu** [comment]
@bender2k14 Thanks for the reply. I assumed there would be, but I can't see them mentioned anywhere. I looked in the list on the main project page, but couldn't see anything.

Where can I find docs on these functions?

Thanks again.

**Comment by ceywj** [comment]
public static B use<A, B>(A disposable, System.Func<A, B> f)
	where A : System.IDisposable
    LanguageExt.Prelude 的成员

摘要:
Functional implementation of the using(...) { } pattern

**Comment by bender2k14** [comment]
I am not sure what docs you are expecting to find or if such docs exists.

Here are [tests of all the `use` methods](https://github.com/louthy/language-ext/blob/5c7ed466226435fab512041651d33bae14cb6c9f/LanguageExt.Tests/UseFamilyTests.cs).  That should help you figure out what you would like to know.

**Comment by MrYossu** [comment]
@bender2k14 I was hoping for something like you see on the project's main page, where there are links to things like [Try<A>()](https://louthy.github.io/language-ext/LanguageExt.Core/LanguageExt/Try_A.htm). There's not much there in the way of documentation, but at least you can see that the function exists.

Bear in mind that I'm not familiar with all the features of the package, it's very hard finding out what's in there and what it all does.

Thanks anyway, at least now I know `use` exists, I can play with it.
