### ISSUE TITLE
Overload for IfNone to accept an action

### ISSUE THREAD

**Issue by B-Reif** [louthy/language-ext#550]
Currently I'm using `Option`'s `IfSome` action overload to execute side effects, e.g.
```cs
optional.IfSome(value => DoImpureThings(value));
```

I noticed that `IfNone` doesn't have a similar signature that takes an `Action`.
```cs
optional.IfNone(() => DoImpureThings()); // <-- interpreted as a Func<T>, returns null, throws
```

To achieve the same thing I'm using the unsafe signature and returning null explicitly.

```cs
optional.IfNoneUnsafe(() => {
  DoImpureThings();
  return null;
});
```

My expectation was that the `IfNone` API would match the `IfSome` API. Should `IfNone` have an `Action` overload? Is this even the idiomatic way to do a side effect based on an `Option`?

**Comment by bender2k14** [comment]
> My expectation was that the `IfNone` API would match the `IfSome` API.

I have also been surprised by this inconsistency.

> To achieve the same thing I'm using the unsafe signature and returning null explicitly.

You don't have to return `null` though.  You can return `Unit`, which is one of the ways in FP to indicate that a function has a side effect.

**Comment by B-Reif** [comment]
Trying to do that gives me a type error; the signature expects a return value of a `T`.

**Comment by bender2k14** [comment]
Oh, I see.  Then your approach wouldn't work with a value type.

In general, I think `ma.Match(Some, () => { DoImpureThings(); return None; })` would work.  I am just trying to think of a way to avoid using `null`.

**Comment by B-Reif** [comment]
I mean, I'm deliberately not interested in having any kind of return value in this case.

**Comment by bender2k14** [comment]
How about `ma.Match(_ => unit, () => { DoImpureThings(); return unit; })` ?
