### ISSUE TITLE
Calling .Sequence on a left state Either<L, Task<R>> is returning bottom value

### ISSUE THREAD

**Issue by zhengbli** [louthy/language-ext#552]
Example code:

```csharp
var before = Left<string, Task<int>>("Failed");
var after = await before.Sequence();
```
I'm expecting `after` to be a left value of the type `Either<string, int>`, but in reality it is a bottom value.

Nuget version: 3.1.15

**Comment by zhengbli** [comment]
If anyone is also having this issue, I solved it with an extension method:
```csharp
        public static Task<Either<L, R>> Flip<L, R>(this Either<L, Task<R>> either)
        {
            return either.MatchAsync(
                Right<L, R>,
                Left<L, R>
            );
        }
```

**Comment by dancrn** [comment]
also suffering this issue :(

in the more general sense, i think it stems from the asymmetry in left vs. right instances: right instances are more "favorable" than left. the issue can be invoked on an either with any monadic type for right, i think:

```csharp
Either<string, Seq<int>> r1 = Prelude.Seq(1,2,3);
Seq<Either<string, int>> r2 = r1.Sequence();
Either<string, Seq<int>> r3 = r2.Sequence(); // Right(Seq(1,2,3))

Either<string, Seq<int>> l1 = "left";
Seq<Either<string, int>> l2 = l1.Sequence(); // []
Either<string, Seq<int>> l3 = l2.Sequence(); // Bottom 
```

tbh, i think there are two ways forward with this;

1. `Either<L,M<R>>.Sequence()` have a return type of `M<R>`, or,
1. it should treat left values a bit more "fairly".

in the mean time, extension methods will have to do..

**Comment by louthy** [comment]
> in the more general sense, i think it stems from the asymmetry in left vs. right instances

It's caused by `Monad.Zero` being `Bottom` for `Task`.  `Sequence` folds and starts with an initial state of `Monad.Zero`.  This can be fixed manually, but the transformer code in generated via T4 templates.  It is something I will get around to fix eventually, probably by using the same tech as the `LanguageExt.CodeGen`, but in the mean time the best way to deal with this is to [use the approach that @zhengbli documented above](https://github.com/louthy/language-ext/issues/552#issuecomment-463058650)

**Comment by louthy** [comment]
Just to follow up, this is a problem for all inner monads that don't have a good default for `Monad.Zero`.  i.e. there's no good default for `Left` or `Right`, whereas a good default for `Seq` is an empty list.

**Comment by bender2k14** [comment]
> ...this is a problem for all inner monads that don't have a good default for `Monad.Zero`.

Isn't that because it isn't a monad that has a "zero" but a [monoid](https://en.wikipedia.org/wiki/Monoid)?

**Comment by louthy** [comment]
> Isn't that because it isn't a monad that has a "zero" but a monoid?

No, that's 'Empty'.  Monads in language-ext follow the p`MonadPlus` type-class design](https://hackage.haskell.org/package/base-4.12.0.0/docs/Control-Monad.html#t:MonadPlus).  But, it's not valid for all monads, so things like this happens.  It's just a limitation that I've had to deal with when trying to formalise the type-class/class-instance system.  I think there's a better approach (via code-gen), but it takes time to get all this into my head (the implementing it is a whole other bundle of joy ;-) )

```haskell
-- | Monads that also support choice and failure.
class (Alternative m, Monad m) => MonadPlus m where
   -- | The identity of 'mplus'.  It should also satisfy the equations
   --
   -- > mzero >>= f  =  mzero
   -- > v >> mzero   =  mzero
   --
   -- The default definition is
   --
   -- @
   -- mzero = 'empty'
   -- @
   mzero :: m a
   mzero = empty

   -- | An associative operation. The default definition is
   --
   -- @
   -- mplus = ('<|>')
   -- @
   mplus :: m a -> m a -> m a
   mplus = (<|>)
```

**Comment by louthy** [comment]
If you take a look at the implementation, you'll see why it needs `Zero` and `Plus`:

```c#
public NewOuterType Traverse<NewOuterMonad, NewOuterType, NewInnerMonad, NewInnerType, B>(OuterType ma, Func<A, B> f)
    where NewOuterMonad : struct, Monad<NewOuterType, NewInnerType>
    where NewInnerMonad : struct, Monad<NewInnerType, B> =>
        MOuter.Fold(ma, default(NewOuterMonad).Return(default(NewInnerMonad).Zero()), (outerState, innerA) =>
            Trans<NewOuterMonad, NewOuterType, NewInnerMonad, NewInnerType, B>.Inst.Plus(outerState,
                MInner.Bind<NewOuterMonad, NewOuterType, NewInnerType>(innerA, a =>
                    default(NewOuterMonad).Return(default(NewInnerMonad).Return(f(a))))))(unit);
```
It's really hard to see through the generics, but there's a fold on the outer monad, it takes the inner-monad's `Zero` value as its initial state (the beginning of the problem).  The folder function calls `Plus` to combine the inner monadic values together.

Pretty much the main reason for implementing the monads as `MonadPlus` was to enable the T4 code-gen, so that'll probably go away for the monads that can't support it once I have a better solution.

**Comment by louthy** [comment]
The latest `beta` has the issues in this thread fixed:

```c#
var before = Left<string, Task<int>>("Failed");
var after = await before.Sequence();  // Left("Failed")
```


```c#
Either<string, Seq<int>> r1 = Prelude.Seq(1,2,3);
Seq<Either<string, int>> r2 = r1.Sequence(); // [Right(1), Right(2), Right(3)]
Either<string, Seq<int>> r3 = r2.Sequence(); // Right(Seq(1,2,3))

Either<string, Seq<int>> l1 = "left";
Seq<Either<string, int>> l2 = l1.Sequence(); // []
Either<string, Seq<int>> l3 = l2.Sequence(); // Right([])
```

The notion of symmetry when calling `Sequence` twice isn't a contract of the function, and couldn't possibly be maintained for all pairs of monads.  `Traverse` and `Sequence` both work by applying the monad rules of the inner and outer type repeatedly for the all of the items in the transformer type; that can be destructive in the case of monad can short-cut an operation (`Option`, `Either`, etc.), and so data can be lost in the operation, that obviously means it can't be recovered by calling `Sequence` again.
