### ISSUE TITLE
Special Apply overloads with Tasks?

### ISSUE THREAD

**Issue by bender2k14** [louthy/language-ext#553]
Given that we have the extension method
```
public static B Apply<A, B>(this A a, Func<A, B> f)
```

in the namespace `LanguageExt` and the class [`Cond`](https://github.com/louthy/language-ext/blob/c412a962fac7110845b80d0f80a467cc929637ff/LanguageExt.Core/DataTypes/Cond/Cond.cs#L69), what is the purpose of the extension methods
```
public static Task<B> Apply<A, B>(this A a, Func<A, Task<B>> f)
```

and
```
public static Task<B> Apply<A, B>(this Task<A> taskA, Func<Task<A>, Task<B>> f)
```

also in the namespace `LanguageExt` but in class `CondAsyncExt` (on lines [58](https://github.com/louthy/language-ext/blob/c412a962fac7110845b80d0f80a467cc929637ff/LanguageExt.Core/DataTypes/Cond/CondAsync.cs#L58) and [94](https://github.com/louthy/language-ext/blob/c412a962fac7110845b80d0f80a467cc929637ff/LanguageExt.Core/DataTypes/Cond/CondAsync.cs#L94) respectively)?

The last two extension methods are special cases of the first.

**Comment by louthy** [comment]
Removed in the next release.
