### ISSUE TITLE
Task.Apply overload equivalent to Task.Bind

### ISSUE THREAD

**Issue by bender2k14** [louthy/language-ext#554]
Why does `Task<>` have the extension method
```
public static Task<B> Apply<A, B>(this Task<A> taskA, Func<A, Task<B>> f)
```

in the namespace `LanguageExt` and class [`CondAsyncExt`](https://github.com/louthy/language-ext/blob/c412a962fac7110845b80d0f80a467cc929637ff/LanguageExt.Core/DataTypes/Cond/CondAsync.cs#L75) given that it is equivalent to
```
public static Task<U> Bind<T, U>(this Task<T> self, Func<T, Task<U>> bind)
```

also in the namespace `LanguageExt` but in the class [`TaskExtensions`](https://github.com/louthy/language-ext/blob/30976b2212d28fed20bca16566e8769acc7beecd/LanguageExt.Core/DataTypes/Task/Task.Extensions.cs#L121)?

**Comment by louthy** [comment]
Removed in the next release.
