### ISSUE TITLE
Enrico's Continuation Monad

### ISSUE THREAD

**Issue by bender2k14** [louthy/language-ext#555]
Does Language Ext have the continuation monad as defined by Enrico Buonanno in chapter 11 of [Functional Programming in C#](https://www.manning.com/books/functional-programming-in-c-sharp)?

There was a similar Language Ext issue (#453) about a continuation monad, but I don't think this is the same monad that Enrcio describes.

Enrico also refers to this monad as `Middleware<T>`.  My understanding is that this is the FP equivalent of the [decorator pattern](https://en.wikipedia.org/wiki/Decorator_pattern) from OOP.

**Comment by damiensawyer** [comment]
#291 would suggest not.

**Comment by louthy** [comment]
`Cond` works a bit like this, but I'd be open to a PR if someone wants to put the effort in.
