### ISSUE TITLE
Advantages of Seq over IEnumerable

### ISSUE THREAD

**Issue by slimshader** [louthy/language-ext#558]
Hi,

I am adapting more and more LanguageExt in my project (notably Option and Validation) but was wondering of benefits of possibly replacing IEnumerable<T> with Seq<T>. At first glance it seems that the main benefit comes from better Match() support for Seq (Empty, One, etc.). What else? Should Seq<> become the default (instead of IEnumerable<>) when doing FP with LangExt?

**Comment by bender2k14** [comment]
I think another intended benefit of `Seq<>` is that its lazy variant is [idempotent](https://en.wikipedia.org/wiki/Idempotence), i.e. enumerating it twice is equivalent to enumerating it once.  This is not the case for `IEnumerable<>`.  Only once have I ever intentionally used this behavior of `IEnumerable<>`.  Every other time it either caused a bug or decreased performance.

However, achieving that idempotent behavior is tricky.  I have seen many bugs related to it.  Because of that, I have been leary of replacing `IEnumerable<>` with `Seq<>` in my code.

**Comment by louthy** [comment]
> However, achieving that idempotent behavior is tricky. I have seen many bugs related to it. Because of that, I have been leary of replacing IEnumerable<> with Seq<> in my code.

I use it heavily.  Including in a language compiler where it gets really nailed.  I'd say your concerns are unfounded now we've ironed out the edge cases.

**Comment by louthy** [comment]
Just to answer the original point, the benefits of `Seq` are:

* At most once evaluation of the lazy sequence
* Has performance characteristics that are similar to `List<T>` in .NET for `Cons` (prepending) and `Add` (appending)
* Contiguous memory allocation, which means high performance iteration of the sequence of items, especially if the lazy sequence has been evaluated once.

Down-side:

* The at-most-once-evaluation requires caching of the evaluated values, which means infinite sequences are not possible
* The above also means that there's a memory cost to evaluating a sequence whereas a lazy `IEnumerable` sequence may never be stored

It's my go-to structure in lang-ext now, I prefer it over `Lst<A>` for all list like operations other than where mid-sequence inserts/removals are required.

**Comment by kgkoutis** [comment]
> I think another intended benefit of Seq<> is that its lazy variant is [idempotent](https://en.wikipedia.org/wiki/Idempotence), i.e. enumerating it twice is equivalent to enumerating it once.

I had trouble getting completely the difference between IEnumerable and Seq so I wrote an example here that I hope clarifies the concept of "at-most-once lazy streaming" to others. The fact that we use here `Count` doesn't really play a role - any LINQ operation would do.

```csharp
void Main()
{
	var sw = new Stopwatch();
	sw.Start();
	bool DoWithString(string e)
	{
		Console.WriteLine("Called");
		Console.WriteLine(sw.Elapsed);
		return true;
	}

	var ie = YieldStrings();
	
	ie.Count(s => DoWithString(s)); // finishes in about 3 seconds
	sw.Restart();
	ie.Count(s => DoWithString(s)); // again, finishes in about 3 seconds

	var sq = ie.ToSeq();
	sw.Restart();
	sq.Count(s => DoWithString(s)); // finishes in about 3 seconds
	sw.Restart();
	sq.Count(s => DoWithString(s)); // finishes almost instantaneously, with the output printed to the Console
}

public IEnumerable<string> YieldStrings()
{
	Thread.Sleep(1000);
	yield return "One";
	Thread.Sleep(1000);
	yield return "Two";
	Thread.Sleep(1000);
	yield return "Three";
}
```
