### ISSUE TITLE
IEnumerable<Either<L,A>>.BindT extension method is eager

### ISSUE THREAD

**Issue by chyczewski-maciej** [louthy/language-ext#564]
BindT extension method both takes and returns IEnumerable type which suggests it'll be lazily evaluated, instead it's processed right away for all the elements.
If it is an expected behavior shouldn't it return a different type instead? 

![cmd_2019-03-08_08-36-05](https://user-images.githubusercontent.com/17740400/54014685-d0b8cc00-417d-11e9-8fd6-b92efdf8d1b1.png)
![cmd_2019-03-08_08-35-42](https://user-images.githubusercontent.com/17740400/54014686-d0b8cc00-417d-11e9-82ce-c9a453a92271.png)
![cmd_2019-03-08_08-42-19](https://user-images.githubusercontent.com/17740400/54014837-27260a80-417e-11e9-8cf8-edfd7f866a2e.png)
![cmd_2019-03-08_08-42-41](https://user-images.githubusercontent.com/17740400/54014838-27bea100-417e-11e9-8fe0-5a526b9a2b7c.png)

**Comment by bender2k14** [comment]
Here is my attempt to simplify your tests.  This tests fails but the expectation is that it should pass.
```
[Fact]
public void IEnumerableOptionBindT_NotEnumerabled_NotEvaluated()
{
    var evaluted = false;
    var list = Seq1(unit)
        .AsEnumerable()
        .Select(_ =>
        {
            evaluted = true;
            return unit;
        })
        .Select(Some)
        .BindT(Some);
    Assert.False(evaluted);
}
```

**Comment by louthy** [comment]
The HKT functions (with the `T` suffix) are auto-generated, so this might have something causing the eagerness.

**Comment by chyczewski-maciej** [comment]
@bender2k14, here's an even simplier version :)

```        
public static void IEnumerableOptionBindT_NotEnumerabled_NotEvaluated()
{
    new[] { unit }
            .Select<Unit, Option<Unit>>(x => throw new Exception("Some proper message"))
            .BindT(Some);
}
```

or this 

```
public static void IEnumerableOptionBindT_NotEnumerabled_NotEvaluated()
{
    ThrowOnEnumeration().BindT(Some);

    IEnumerable<Option<Unit>> ThrowOnEnumeration()
    {
        throw new Exception("Some proper message");
        yield return unit; // Do not remove this line. This is required to generate a lazy IEnumerable sequence.
    }
}
```

**Comment by louthy** [comment]
Fixed in the next release
