### ISSUE TITLE
Feature: Resource Monad

### ISSUE THREAD

**Issue by gwintering** [louthy/language-ext#567]
This is a proposal to provide more safety around `IDisposable` resources by putting them in  the library's monadic framework.  The inspiration comes from Haskell's [resource monad](https://www.fpcomplete.com/blog/2017/06/understanding-resourcet).

The current `use` family of methods all require you provide a single projection to run with the resource, after which it is disposed.  This pattern has several drawbacks:
1. Despite the lazy, monadic nature of`Try`, you can't return in the `Try` anything that has lazy behavior itself, like a file line iterator or `DbContext` lazy loading proxy.  The problem is that the resource is disposed after producing the first object mapped in the `Try`.
2. The method expects the entire projection at once, which hampers composability.  You can't, for example, call `tryuse` to return a `Try<Connection>` from a method, because the `tryuse` factory also expects you to specify everything you'd like to do with the connection
3. Each method is bespoke logic despite a common pattern
4. We're missing several more use cases (`TryOption`, `TryAsync`, `TryOptionAsync`)

Please take a look at gwintering/language-ext@6ad4ef52 for some sample usage and features.

**Comment by louthy** [comment]
@gwintering I'm not against the idea of a resource monad.  I had problems implementing a general disposal mechanism before with `Try` and other types, so I dropped it.  I am still in the midst of massive time-pressures, so if you want to put something together then I'd be happy to give feedback 👍

**Comment by louthy** [comment]
This is now supported by `Proxy`, which can lift `Aff` and `Eff` monads into its domain.  `Aff` and `Eff` cover the same behaviours (+more) of `Try`, `TryOption`, `TryAsync`, and `TryOptionAsync`;  so I'm going to close this down.
