### ISSUE TITLE
Lenses for LangExt

### ISSUE THREAD

**Issue by slimshader** [louthy/language-ext#568]
Hi,

I now try to use immutable data structures as much as possible but they become more and more complex ant they have become really difficult to work with. Changing a property on a "leaf" record, nested inside list inside other record must result in new instance of root object which is very cumbersome. After some research it turns out is is actually an issue in F# (which is super surprising considering data manipulation is at core of FP) and the solution is what they call Lenses:

[http://bugsquash.blogspot.com/2011/11/lenses-in-f.html](url)

How to implement something like that in C#? Any chance of something like that added to LangExt?

**Comment by louthy** [comment]
I have been thinking about lenses recently.  The version in the blog isn't the same as Haskell lenses, so if I was to build them into lang-ext I'd prefer to try to do them fully.  [The full story for lenses](http://hackage.haskell.org/package/lens) is quite enormous though, so I doubt I'll be adding anything soon.

This is a working example of the blog version though:

```c#
using LanguageExt;
using static LanguageExt.Prelude;
using System;

namespace ConsoleApp15
{
    class Program
    {
        static void Main(string[] args)
        {
            var car = new Car("Maserati", "Ghibli", 20000);
            var editor = new Editor("Joe Bloggs", 50000, car);
            var book = new Book("Editors of the World", "Sarah Bloggs", editor);

            // let bookEditorCarMileage = Book.editor >>| Editor.car >>| Car.mileage
            // let mileage = bookEditorCarMileage.Get aBook
            // let book2 = aBook |> bookEditorCarMileage.Set 1000

            var bookEditorCarMileage = Lens.Compose(Book.editor, Editor.car, Car.mileage);
            var mileage = bookEditorCarMileage.Get(book);
            var book2 = bookEditorCarMileage.Set(25000)(book);

            // let promote =
            //     state {
            //         let! oldSalary = Lens.getState Editor.salary
            //         do! Editor.salary += 1000
            //         return oldSalary
            //     }
            // let oldSalary, promotedTom = promote tom

            var promote = from oldSalary in Lens.getState(Editor.salary)
                          from _         in Lens.setState(Editor.salary, oldSalary + 1000)
                          select oldSalary;

            var promoted = promote(editor);
        }
    }

    public class Car : Record<Car>
    {
        public readonly string Make;
        public readonly string Model;
        public readonly int Mileage;

        public Car(string make, string model, int mileage)
        {
            Make = make;
            Model = model;
            Mileage = mileage;
        }

        public Car With(string Make = null, string Model = null, int? Mileage = null) =>
            new Car(Make ?? this.Make, Model ?? this.Model, Mileage ?? this.Mileage);

        public static Lens<Car, int> mileage =>
            Lens<Car, int>.New(
                Get: car => car.Mileage,
                Set: v => car => car.With(Mileage: v));
    }

    public class Editor : Record<Editor>
    {
        public readonly string Name;
        public readonly int Salary;
        public readonly Car Car;

        public Editor(string name, int salary, Car car)
        {
            Name = name;
            Salary = salary;
            Car = car;
        }

        public Editor With(string Name = null, int? Salary = null, Car Car = null) =>
            new Editor(Name ?? this.Name, Salary ?? this.Salary, Car ?? this.Car);

        public static Lens<Editor, Car> car =>
            Lens<Editor, Car>.New(
                Get: editor => editor.Car,
                Set: v => editor => editor.With(Car: v));

        public static Lens<Editor, int> salary =>
            Lens<Editor, int>.New(
                Get: editor => editor.Salary,
                Set: v => editor => editor.With(Salary: v));
    }

    public class Book : Record<Book>
    {
        public readonly string Name;
        public readonly string Author;
        public readonly Editor Editor;

        public Book(string name, string author, Editor editor)
        {
            Name = name;
            Author = author;
            Editor = editor;
        }

        public Book With(string Name = null, string Author = null, Editor Editor = null) =>
            new Book(Name ?? this.Name, Author ?? this.Author, Editor ?? this.Editor);

        public static Lens<Book, Editor> editor =>
            Lens<Book, Editor>.New(
                Get: book => book.Editor,
                Set: v => book => book.With(Editor: v));
    }

    public class Lens<A, B> : Record<Lens<A, B>>
    {
        public readonly Func<A, B> Get;
        public readonly Func<B, Func<A, A>> Set;

        Lens(Func<A, B> get, Func<B, Func<A, A>> set)
        {
            Get = get;
            Set = set;
        }

        public static Lens<A, B> New(Func<A, B> Get, Func<B, Func<A, A>> Set) =>
            new Lens<A, B>(Get, Set);

        public Func<A, A> Update(Func<B, B> f) => a =>
        {
            var value = Get(a);
            var newValue = f(value);
            return Set(newValue)(a);
        };
    }

    public static class Lens
    {
        public static Lens<A, C> Compose<A, B, C>(Lens<A, B> la, Lens<B, C> lb) =>
            Lens<A, C>.New(
                Get: a => lb.Get(la.Get(a)),
                Set: v => la.Update(lb.Set(v)));

        public static Lens<A, D> Compose<A, B, C, D>(Lens<A, B> la, Lens<B, C> lb, Lens<C, D> lc) =>
            Lens.Compose(Lens.Compose(la, lb), lc);

        public static Lens<A, E> Compose<A, B, C, D, E>(Lens<A, B> la, Lens<B, C> lb, Lens<C, D> lc, Lens<D, E> ld) =>
            Lens.Compose(Lens.Compose(la, lb, lc), ld);

        public static Lens<A, F> Compose<A, B, C, D, E, F>(Lens<A, B> la, Lens<B, C> lb, Lens<C, D> lc, Lens<D, E> ld, Lens<E, F> le) =>
            Lens.Compose(Lens.Compose(la, lb, lc, ld), le);

        public static Lens<A, G> Compose<A, B, C, D, E, F, G>(Lens<A, B> la, Lens<B, C> lb, Lens<C, D> lc, Lens<D, E> ld, Lens<E, F> le, Lens<F, G> lf) =>
            Lens.Compose(Lens.Compose(la, lb, lc, ld, le), lf);

        public static State<A, B> getState<A, B>(Lens<A, B> la) =>
            from a in get<A>()
            select la.Get(a);

        public static State<A, Unit> setState<A, B>(Lens<A, B> la, B value) =>
            from a in get<A>()
            from _ in put(la.Set(value)(a))
            select unit;
    }
}
```

**Comment by louthy** [comment]
I spent a bit of time this evening trying to formulate the Haskell lens types, and frankly it's not looking possible.  Not without jumping through a lot of hoops and having quite an ugly solution at the end (lots of generic args).  So, I'm [starting to implement something similar to the code above](https://github.com/louthy/language-ext/tree/master/LanguageExt.Core/Lens).  It will require a lot more typing to be useful, so it might be a while. 

It could really do with a code-generator plugin (for VS and VSCode) for the `static` lens fields (and the `With` function).  If anybody fancies looking into that, that'd be awesome.  It should probably generate for all types that derive from `Record<A>`, or maybe have some attributes `[With]` and `[Lens]` or something that can help a code generator find the types that should have their readonly fields decorated.

**Comment by louthy** [comment]
Some interesting unit tests: https://github.com/louthy/language-ext/blob/master/LanguageExt.Tests/LensTests.cs#L25

**Comment by slimshader** [comment]
wow you are the best! Looking at commits I see you are already adding lenses for most common data structures, also this means that using immutable data structures in C# with LangExt will be easier to use out-of-the-box than in F# :)

**Comment by slimshader** [comment]
How can I update a value based on its previous value tho? A  a -= b in mutable world that is. Looking at your example promote() Lens seems to do that but it has "100" "hardcoded".

**Comment by louthy** [comment]
To update you call lens.Update(f) where f is the update function

**Comment by slimshader** [comment]
> To update you call lens.Update(f) where f is the update function

Ah, right, thanks. So when is the Leans release coming? :)

**Comment by louthy** [comment]
Sorry, I was writing the last comment on the train, there are two `Update` functions.  The one I posted above which returns a `Func<A, A>`, so you can store your update function as a field/property.  The other is:
```c#
    a = lens.Update(f, a);
```
They both compose `Get` and `Set` with `f` to do the update, but this one allows you to easily do inline updates.

I will probably do the release sometime next week.  I want to try and get the code-gen working, I think that's when it'll be really powerful.

**Comment by louthy** [comment]
Ok, the code-gen works, although it'll need some more bulletproofing for when poorly formed types are used.

But, you can see from the unit-tests that the record types all now have `[WithLens]` and I have removed the `With` and the manual implementations of the lens fields.

https://github.com/louthy/language-ext/blob/master/LanguageExt.Tests/LensTests.cs

This will make using lenses trivial (as well as removes the need to manually implement the `With` method for immutable types).

**Comment by slimshader** [comment]
So [WithLens] adds With() methods AND Lenses for such Records? Does it add external dependencies for code-gen? I use it with Unity, so far no issues with latest release.

**Comment by louthy** [comment]
When you add the `LanguageExt.CodeGen` library if you include:
```xml
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
```
Within the `PackageReference` then the dependency doesn't flow through to your output.  I haven't yet got around to build the nu-get package for this yet, but I think I should be able to get it to do this by default.  So, there's no additional dependencies (the attributes are wiped too).

**Comment by slimshader** [comment]
Unity doesn't have XML / build system configurations unfortunately, it automatically adds references to .dlls placed in specific directories tho. Hope it will be enough

**Comment by louthy** [comment]
Now deployed in [v3.1.16](https://github.com/louthy/language-ext/releases/tag/v3.1.16)
