### ISSUE TITLE
Discussion: Naming for Add, Subtract, Divide and, um, Product?

### ISSUE THREAD

**Issue by Jagged** [louthy/language-ext#57]
Add, Subtract and Divide are all actions.
Whereas Product is the result of an action.  

A name that would be consistent with the others would be Multiply.

I can't help but wonder if this naming was copied from elsewhere perhaps?  Thoughts?  

If you'd like me to tidy it up I'm more than happy to.  I'd keep the old signatures and obsolete them for backwards compatibility.

**Comment by louthy** [comment]
I agree, I've renamed it to Multiply.  No need to keep the old signatures here, this hasn't yet been released.
