### ISSUE TITLE
Change to the way select and implicit casting works from v1.9.7 to v3.1.15

### ISSUE THREAD

**Issue by andyigreg** [louthy/language-ext#572]
We have a lot of code written against version 1.9.7 of the library which we are looking to upgrade to 3.1.15.

In our testing we have found an issue with code that looked like:

`Option<int> someOption;`

`return`
`from val in someOption`
`select someList.FirstOrDefault(item => item.id == val);`

Or in other places, the same type of code written in a similar way:
`someOption.Map(val => someList.FirstOrDefault(item => item.id == val));`

This code no longer works because now, if the expression in the select returns a null, it throws a null exception rather than the old behaviour of implicitly casting the null to a None.

Unfortunately v1.9.7 of the library is in a project with tens of thousands of lines of code and not enough unit tests, and since the code still builds the only way of finding the issues would be by eye or by attempting to test every use case of the system which is impractical.

Is this new behaviour how the library now works? Does the implicit cast of a null to a None work differently in 3.1.15 to 1.9.7? Or am I missing something?

Thanks
Andy

**Comment by andyigreg** [comment]
Ok, so it looks like this was a bug that was fixed - issue 517. I guess I’ll have to start trawling through our code looking for examples where a null could be being used as the inner value of a Map.

**Comment by louthy** [comment]
@andyigreg Yes, it's unfortunate I'm afraid, but the result of `Map` (or `Select`) is a bound value, not a monadic value.  If you returned `null` from `Bind` then that would be a different story as that would implicitly cast to `None`.

**Comment by louthy** [comment]
Addtional notes on the approach you're using:
```c#
from val in someOption
select someList.FirstOrDefault(item => item.id == val);
```
Would be better as:
```c#
from val in someOption
from res in someList.Filter(item => item.id == val).HeadOrNone()
select res;
```
Which can be simplified somewhat to:
```c#
someOption.Bind(val => someList.Filter(item => item.id == val).HeadOrNone())
```
And this:
```c#
someOption.Map(val => someList.FirstOrDefault(item => item.id == val));
```
Can be:
```c#
someOption.Bind(val => someList.Filter(item => item.id == val).HeadOrNone());
```
_which is the same as the first example_

You could probably simplify this further by building an extension that combines `Filter` and `HeadOrNone`:
```c#
public static class EnumExts
{
    public static Option<A> HeadOrNone(this IEnumerable<A> ma, Func<A, bool> f) =>
        ma.Filter(f).HeadOrNone();
}
```
So your examples become:
```c#
from val in someOption
from res in someList.HeadOrNone(item => item.id == val)
select res;
```
Which simplifies to:
```c#
someOption.Bind(val => someList.HeadOrNone(item => item.id == val));
```

**Comment by andyigreg** [comment]
@louthy Thankyou. After thinking about it then it was clear that in this instance Map was incorrectly working more like Bind as you say, so I searched the issues to see if/when a fix had gone out and found issue 517. And we have started the code trawl. Most of our code is as per your first ‘from from’ (Bind) example and works as it should. Unfortunately a fair amount of code was written as we were getting to grips with functional concepts and your library, and is very sub-optimal. So for the time being we have upgraded to 3.1.14. We will upgrade again after we have trawled the code. Unfortunately we can’t think of a faster way of locating the malformed code other than by eye. Oh well. These are the joys of coding. :-)

**Comment by louthy** [comment]
@andyigreg A couple of thoughts:

* In VS, find all references on `Map` could help?
* One brutal way would be to do your own build on lang-ext where you rename `Map` to `MapX` or something, and perhaps even comment out the `Select` extension method for `Option` (and any other type that this might be a problem for).  Then your code won't compile in all the places where it's used.  This might be more of a curse than a blessing, but at least you'd know you audited everything.

**Comment by StanJav** [comment]
> One brutal way would be to do your own build on lang-ext where you rename Map to MapX

Or you can mark it with `[Obsolete("Review needed")]` and VS list of warning will give you all places.
