### ISSUE TITLE
Flatten/Join functions

### ISSUE THREAD

**Issue by tschmidt64-SC** [louthy/language-ext#573]
One thing I'm used to seeing in functional languages/frameworks is a flatten or join function. I see that you could use bind to achieve this result, as follows:
```c#
Either<string, int> esi1 = Right(1);
Either<string, int> esi2 = esi1.Bind<int>(e => Left("int"));
```
But what if I just want to join instead of bind? Something like:
```c#
Either<string, int> esi1 = Right(1);
Either<Either<string,int>, Either<string,int>> eesi = Left(esi1);
Either<string, int> esi2 = eesi.Join();
```

**Comment by TonyHernandezAtMS** [comment]
What are you expecting esi2 to be in your example?

**Comment by bender2k14** [comment]
`Either<,>` has an instance method called [`Join`](https://github.com/louthy/language-ext/blob/master/LanguageExt.Core/DataTypes/Either/Either.cs#L1301), but I don't think it is what you are looking for.

If you had a `Task<Task<A>>`, then there is an extension method called [`Flatten`](https://github.com/louthy/language-ext/blob/master/LanguageExt.Core/DataTypes/Task/Task.Extensions.cs#L34) that returns `Task<A>`.  I think you are looking for something similar to this method for `Either<,>`.

I don't think this equivalent for `Either<,>` exists.

The simplest way I can see to express what you want would be
```
Either<string, int> esi2 = eesi.Match(identity, identity)
```

**Comment by tschmidt64-SC** [comment]
Flatten is what I was looking for yes. 

The usual convention for a Right-biased Either monad is:
* `join (Right (Right (5))) —> Right (5)`
* `join (Right (Left ("err"))) —> Left (“err”)`

I don’t really know what the convention is for the other two combinations is of nesting is, but it would be the same as what happens in a BindLeft function presumably

**Comment by bender2k14** [comment]
One thing I love about functional programming is that many functions are so simple that the types completely specify the behavior.  In the case of mapping `Either<Either<L, R>, Either<L, R>>` to `Either<L, R>`, I think the only option is

- `Right(Right(r))` to `Right(r)`,
- `Right(Left(l))` to `Left(l)`,
- `Left(Right(r))` to `Right(r)`, and
- `Left(Left(l))` to `Left(l)`,

which is what
```
Either<string, int> esi2 = eesi.Match(identity, identity)
```
does.

Is this the behavior that you want @tschmidt64-SC?

**Comment by tschmidt64-SC** [comment]
Yes this is the desired output. 

I am not sure how this libs bind/flatMap methods are written but I think it might be worthwhile to document that this is the way to do flatten. In my experience, FP users tend to expect bind/flatMap to be implemented as some identity of `flatten(map(myMonad))` and usually expect both of these functions to be available for use elsewhere

**Comment by tschmidt64-SC** [comment]
Also, usually in FP, join/flatten can be written in terms of binding using the identity function: 
``` haskell
join :: Monad m => m (m a) -> m a
join mma = mma >>= id
```
which is similar to what you've given, but not exactly the same. Using language-ext:
``` c#
Either<string, int> esi1 = Right(1);
Either<Either<string, int>, Either<string, int>> eesi = Left(esi1);
Either<string, int> esi2 = eesi.Bind(identity);  // This does not work
```
Interestingly, this does work fine for other monads in the library. Option (which doesn't have a flatten function) for example:
```c#
Option<int> opt = None;
Option<Option<int>> oopt = Some(opt);
Option<int> opt2 = oopt.Bind(identity);  // This works fine
```

**Comment by louthy** [comment]
As noted above `ma.Bind(identity)` is the equivalent of `join` or `flatten`.  It does work for `Either` also, even though it's stated above that it doesn't.

However, seeing as it's twice in a week that this same question has come up, I will implement the convenience functions `flatten(ma)` and `ma.Flatten()` for all monadic types

**Comment by louthy** [comment]
Deployed in: https://github.com/louthy/language-ext/releases/tag/v3.1.16
