### ISSUE TITLE
Logically AND two eithers

### ISSUE THREAD

**Issue by davidames** [louthy/language-ext#576]
Hey all,

I'm totally new to FP. I have been using LanguageExt for a month or two now for validation workflows. I love how it can clean up error handling for the failure path.

I'm a little stuck now because I have two operations - both return an either - and if both are right then I want to return the first right. If either of them are left, then I'd like to return the first left.

The closest I can find is your logical OR from this post: https://github.com/louthy/language-ext/issues/231  however obviously the result isn't what i want. 
```

        [Fact]
        public static void DoTest()
        {
            Either<ValidationError, Step> a = new Step();
            Either<ValidationError, Step> b = new ValidationError();
            
            var result = a || b;
            Assert.True(result.IsRight); 
            
        }

```

**Comment by bender2k14** [comment]
Have you considered using the Validation monad for this?

If both of your Eithers are in the left/error state, why do you only want the first error instead of both errors?

**Comment by bender2k14** [comment]
My guess is that the OR (`||`) operator for the Validation monad returns the first success value if either is in the success state and the union of their errors otherwise.  I think that might be the behavior that you want.

**Comment by davidames** [comment]
Cheers for that - I'm happy to return the union of errors if A or B has errors.  

But I'd like to be in a left state if either of the either types has a validation error.  

Ie, both have to be successful to return success.

Here is a complete example of what I'm after


```
  public class Step
        {

        }

        public class ValidationError
        {

        }
        [Fact]
        public static void Test11()
        {
            Either<IEnumerable<ValidationError>, Step> a = new Step();
            Either<IEnumerable<ValidationError>, Step> b = new List<ValidationError>();
            Assert.True((a || b).IsLeft); //b in error, I'd like to return left

            Either<IEnumerable<ValidationError>, Step> c = new List<ValidationError>();
            Either<IEnumerable<ValidationError>, Step> d = new Step();
            Assert.True((c || d).IsLeft); //c in error, I'd like to return left


            Either<IEnumerable<ValidationError>, Step> e = new List<ValidationError>();
            Either<IEnumerable<ValidationError>, Step> f = new List<ValidationError>();       
            Assert.True((e || f).IsLeft); //e and f in error, return error. This works


            Either<IEnumerable<ValidationError>, Step> g = new Step();
            Either<IEnumerable<ValidationError>, Step> h = new Step();
            Assert.True((g || h).IsRight); //g and h both in success, return firs. this works

        }
```

**Comment by louthy** [comment]
What you're asking for is monadic bind, which is a sequence of `from` statements in LINQ:

```c#
        [Fact]
        public static void DoTest()
        {
            Either<ValidationError, Step> a = new Step();
            Either<ValidationError, Step> b = new ValidationError();
            
            var result = from x in a
                         from y in b
                         select ...;

            Assert.True(result.IsRight); 
        }
```
A sequence of `from` can be read as AND.  

You can also use `Bind`, but it's slightly harder to use:

```c#
        [Fact]
        public static void DoTest()
        {
            Either<ValidationError, Step> a = new Step();
            Either<ValidationError, Step> b = new ValidationError();
            
            var result = a.Bind(x=> b.Map(y => ...));

            Assert.True(result.IsRight); 
        }
```

**Comment by bender2k14** [comment]
Specifically, I think you want `x` in place of the `...`s in @louthy's examples.

Still though, I think you will like using the Validation monad better than the Either monad for this problem.

**Comment by davidames** [comment]
Thanks Guys, will check out the Validation monad.

I've been playing with the LINQ syntax and struggling to get it to compile at the "from y in b" statement

I get "Cannot implicitly convert type Either<ValidationError, Step> to EitherRight<ValidationError>"

Here is the complete code sample

```
public class Step {}
    public class ValidationError {}

    public class GithubExample
    {
        [Fact]
        public static void DoTest()
        {
            Either<ValidationError, Step> a = new Step();
            Either<ValidationError, Step> b = new ValidationError();

            var result = 
                from x in a
                from y in b
                select a + b;

        }        
    }
```

**Comment by bender2k14** [comment]
I said
> I think you want `x` in place of the `...`s in @louthy's examples.

So in the code you just shared, that would be
```
var result =
    from x in a
    from y in b
    select x;
```

**Comment by davidames** [comment]
Thanks for all of your help - that really clears things up!
