### ISSUE TITLE
Add functionality to TryResult to allow functions to handle success and failure cases

### ISSUE THREAD

**Issue by Woodz** [louthy/language-ext#58]
For the case where you want to handle the result of the try test after the execution, there is no way to run functions on the success and failure cases of the TryResult.

Psuedo-code for desired behaviour
```
var result: TryResult = doRiskyFunction();
result.match(success: result => handleResult(result), failure: exception => handleException(exception));
```

**Comment by louthy** [comment]
Hi Woodz, you should work with the extension methods for `Try<T>`
```C#
   var res = doRiskyFunction.Match(
        Succ: val => ...,
        Fail: ex => ....
    );
```
`TryResult` is very much an intermediate state that only exists to facilitate the extension methods.
