### ISSUE TITLE
Enhancement: CodeGen RecordWith/RecordWithAndLenses should work for non public modifiers

### ISSUE THREAD

**Issue by alaendle** [louthy/language-ext#589]
E.g. support:
```
    [WithLens]
    **internal** partial class TestWith : Record<TestWith>
```

Maybe the code used for generation could even be simplified - 
`            var partialClass = SyntaxFactory.ClassDeclaration($"{applyToClass.Identifier}")
                                            .WithModifiers(applyToClass.Modifiers);`
instead of
`            var partialClass = SyntaxFactory.ClassDeclaration($"{applyToClass.Identifier}")
                                            .WithModifiers(
                                                 SyntaxFactory.TokenList(
                                                     SyntaxFactory.Token(SyntaxKind.PublicKeyword),
                                                     SyntaxFactory.Token(SyntaxKind.PartialKeyword)));
`

The only possible disadvantage I see is that the error message of the compiler is a harder to understand in the case that you've missed to add the partial modifier to an annotated class.

**Comment by louthy** [comment]
Seems reasonable.  Do you want to do a PR?

**Comment by louthy** [comment]
@alaendle Never mind, I've built it now.  It works for `internal`, not for `private` right now.  I also got it to deal with the missing `partial`.

I'll either look to deploy this evening or next week.

**Comment by alaendle** [comment]
Thanks for your effort; it's really a pleasure to work with your library ;-)

**Comment by louthy** [comment]
Deployed in `v3.1.24`
