### ISSUE TITLE
SeqTrans / Select vs. Map

### ISSUE THREAD

**Issue by StefanBertels** [louthy/language-ext#594]
Strange behaviour of nested monads `Select` method (`SeqTrans`):
```
        [Fact]
        public static void ArrOptionMatch()
        {
            var x = Array(Some(1), 2, None);
            // Assert.ThrowsAny<Exception>(() => x.Select(i => i * 2));
            Assert.Equal(x.Select(toString).AsEnumerable(), x.Map(toString).AsEnumerable());
        }
```

I guess this is a bug or at least I would expect that `Select` and `Map` have same semantics. The current `Arr<Option<T>>.Select` looks like `MapT`.

Compare this to:
```
        [Fact]
        public static void OptionOptionMatch()
        {
            var x = Some(Some(1));
            Assert.Equal(x.Select(toString).AsEnumerable(), x.Map(toString).AsEnumerable());
        }

        [Fact]
        public static void OptionOptionArrOptionMatch()
        {
            var x = Some(Some(1));
            var y = Array(Some(1));
            Assert.Equal(x.Select(toString).AsEnumerable(), y.Select(toString).AsEnumerable());
        }
```

**Comment by bender2k14** [comment]
I am not following.  All three tests pass for me.  Did you expect some (all?) of them to fail?  What is the specific issue that you are having?

**Comment by StefanBertels** [comment]
Are you sure? The tests `OptionOptionArrOptionMatch` and `ArrOptionMatch` don't compile, when I paste them to e.g. `TraverseTests.cs` (on branch `master`).  I tried latest VS 2019 and command line build (Microsoft (R) Build Engine version 16.0.462+g62fb89029d for .NET Core).

```
TraverseTests.cs(153,61): error CS1503: Argument 2: cannot convert from 'System.Collections.Generic.IEnumerable<string>' to 'System.Collections.Generic.IEnumerable<LanguageExt.Option<string>>' [D:\github\louthy\language-ext\LanguageExt.Tests\LanguageExt.Tests.csproj]
TraverseTests.cs(168,26): error CS1503: Argument 1: cannot convert from 'LanguageExt.Seq<string>' to 'System.Collections.Generic.IEnumerable<LanguageExt.Option<string>>' [D:\github\louthy\language-ext\LanguageExt.Tests\LanguageExt.Tests.csproj]
```

**Comment by bender2k14** [comment]
I had also originally tested on whatever commit was the `head` of `master` at the time.  Now I tested on the [commit tagged 3.1.23](https://github.com/louthy/language-ext/tree/v3.1.23).  Here is a screenshot on my system for that.  It builds and all tests, including your three, pass.

![Screenshot 2019-05-31 09 37 29](https://user-images.githubusercontent.com/34664007/58717677-61740200-8391-11e9-99ce-74c4ee7ef1f0.png)

Confusingly, I don't see anything [tagged](https://github.com/louthy/language-ext/releases) 3.1.24 but [NuGet.org claims to be hosting that version](https://www.nuget.org/packages/LanguageExt.Core/3.1.24).

**Comment by louthy** [comment]
> Confusingly, I don't see anything tagged 3.1.24 but NuGet.org claims to be hosting that version.

I don't always do official releases for minor updates.  It's usually in the commit log, [although in this case it looks like I didn't flag it](https://github.com/louthy/language-ext/commit/c56ac23f2a11a4cf78ff9797ce37f666939bb7e7)
