### ISSUE TITLE
CodeGen requires DotNetCliToolReference configuration

### ISSUE THREAD

**Issue by tana-gh** [louthy/language-ext#595]
I tried building with CodeGen, did not work this↓

README.md:
> open up your csproj and set the PrivateAssets attribute to all:
> ```xml
> <PackageReference Include="LanguageExt.CodeGen" Version="..." PrivateAssets="all" />
> ```

To make it work, I did the following↓

```xml
<DotNetCliToolReference Include="dotnet-codegen" Version="0.5.13" />
<PackageReference Include="LanguageExt.CodeGen" Version="3.1.24" PrivateAssets="all" />
```

Thanks,

**Comment by louthy** [comment]
I assume this was on a .NET Framework project not a .NET Core project?
