### ISSUE TITLE
Failed to install LanguageExt.CodeGen nuget package VS2015 / .net framework 4.6.1

### ISSUE THREAD

**Issue by rantri** [louthy/language-ext#600]
Hi,

I tried to install LanguageExt.CodeGen nuget package and get the following error:
```
The attribute "Version" in element <DotNetCliToolReference> is unrecognized.  c:\users\xxx\documents\visual studio 2015\Projects\LanguageExtTester\packages\CodeGeneration.Roslyn.BuildTime.0.5.13\build\CodeGeneration.Roslyn.BuildTime.props
```
Env:
LanguageExt.CodeGen version 3.1.25
Window 10
Visual Studio 2015
.Net Framework 4.6.1

Thanks,

Ran

**Comment by louthy** [comment]
You’ll need to use VS2019 I’m afraid

**Comment by rantri** [comment]
Thanks @louthy , I hope we will upgrade soon.
