### ISSUE TITLE
IEnumerable<EitherData<Error, int>> , error handling 

### ISSUE THREAD

**Issue by reallythis** [louthy/language-ext#603]
How does the **ToEither(Errors.UnableToFindFiled($"Unable to find a Field corresponding to x: {key} {Environment.NewLine} {field.AsString()}"))** 
work when using 
**IEnumerable<EitherData<Error, int>> in a method**

**Comment by louthy** [comment]
Could you be a bit more specific of what problem you're seeing?  On an initial guess it looks like you're combining an `Either` and an `IEnumerable` of some type in the same LINQ statement, this forces the `Either` to be an `IEnumerable<EitherData<...>>`, i.e. it stops being an `Either`.
```c#
    from x in list
    from y in either
    select ...
```
If you want to do something like that, then you'll need to convert it to a enumerable type explicitly.
```c#
    from x in list
    from y in either.ToSeq()
    select ...
```
