### ISSUE TITLE
NewValueType<T>

### ISSUE THREAD

**Issue by slimshader** [louthy/language-ext#604]
Hi,

since NewType is often used to avoid "primitive obsession" only wrapping single int or string, wouldn't it be good idea to create thin struct version?

**Comment by gwintering** [comment]
The challenge is that structs can't use inheritance, and inheritance is how `NewType` provides you with the equality machinery for free.  So you'd have to remember to define all the equality stuff yourself, which would defeat the purpose of `NewType`.

Maybe someone else can imagine some sort of clever IL codegen way to do this?

**Comment by louthy** [comment]
As @gwintering states it's not currently possible with `struct`, but a new approach might be available to us soon with the new _default interface members_ feature of C# 8.  Beyond that I will be looking to expand the `CodeGen` project to build record-types without having to derive from `Record<>` and build new-types without having to derive from `NewType<>`, that would allow for `struct` records and new-types.  

There's also potential for doing lots of other lovely things around monad transformers.  

So, I guess _watch this space_.  Although it won't be happening super quickly.  My main focus at the moment is performance improvements across the board.

**Comment by slimshader** [comment]
All clear, thanks a lot for your detailed answers. Looking forward to the new codegen features tho it is impossible to use it in Unity atm afaik :(

**Comment by mrt181** [comment]
Can this be achieved using attributes instead of inheritance?
mark a struct as partial with some newtype attribute and code-gen the needed code during compilation in a new partial companion struct?

https://devblogs.microsoft.com/dotnet/introducing-c-source-generators/
