### ISSUE TITLE
Option.SelectMany lacks an overload?

### ISSUE THREAD

**Issue by dzendras** [louthy/language-ext#605]
I have a class which mixes Linq extension methods and Option<T>.
Let's say I have a function: 
`Option<T> SomeTOrNone(T input)`
which I want to use like this:

`var result = optionalVariable.SelectMany(value => SomeTOrNone(value))`

The issue I'm having is that LanguageExt doesn't have an overload of 
`Option<T>.SelectMany(Func<T, Option<T>> bind).`
As a result, the type of result is `IEnumerable<T>` (as Linq's SelectMany was chosen), which is not what I want, as I'd like to carry on treating it as an Option.
The workaround is to add a parameter which makes compiler choose Option's member method:

`var result = optionalVariable.SelectMany(value => SomeTOrNone(value), , (_, y) => y)`

but it seems like an overkill.

Am I missing here? What should I do?

**Comment by dragosIDL** [comment]
`Option` has an implementation for `SelectMany` with a projector because it is useful to construct LINQ  expressions like: 
```
from value in optional
from result in ResultFor(value)
select result
```
In your case you should use `.Bind` instead of `.SelectMany`

**Comment by dzendras** [comment]
Thanks!
