### ISSUE TITLE
Some async unit-tests are failed

### ISSUE THREAD

**Issue by rantri** [louthy/language-ext#610]
The following unit tests are failing on my computer (Dell Laptop, Won10, i7, 16G, SSD):
TraverseAsync:  run in 6005 ms instead of 3500
BindingFail: Supposed to complete in 2000ms.  It took 2914ms.
LinqBindingSuccess: Supposed to complete in 2000ms.  It took 2305ms. 

Is there a better way to test async operations?  Or just change the threshold?

**Comment by louthy** [comment]
I end up running them manually one-by-one to make sure they pass.  It's not ideal, I'm sure there must be a better way.
