### ISSUE TITLE
Map & BiMap equals

### ISSUE THREAD

**Issue by ofarla** [louthy/language-ext#611]
I see that in another issue (#559), Map.Equals only checks the keys (by design), and BiMap appears to also only check the left keys. I'm using HashMap instead of Map to get the behavior I would like, but I don't see an alternative for BiMap. Is my best bet to create a wrapper for it that behaves in the way I would like it or is there a simpler option?

**Comment by gwintering** [comment]
@ofarla - Are you asking if BiMap should check the associated values in addition to the keys when comparing for equality?
