### ISSUE TITLE
Record<A> ordering reliable?

### ISSUE THREAD

**Issue by StefanBertels** [louthy/language-ext#616]
Currently the `Ord` feature of `Record<>` internally uses `OrderBy(MetaDataToken)` to get the field order. 

The question is: If I want to use ordering and want to have a reliable order (field A having higher prio than field B) should I build my custom logic (explicitly) or can I use `Record<>.CompareTo()`?

A similar question with some interesting answers:
https://stackoverflow.com/questions/9062235/get-properties-in-order-of-declaration-using-reflection

From what I could find there is not really guaranteed order in the language / runtime spec. Seems even layout attributes (SequentialLayout) are only recommendations for the runtime ("shall"). In practise the solution via `MetaDataToken` is probably quite safe. Obviously most serializers will work similar ... and don't have a guarantee, either.

My primary idea is to rely on `MetaDataToken` / `Record<A>` and use unit tests to make sure  this will at least fail if getting unreliable.

Another question / idea / feature request: Could there be a attribute similar to [NonOrd] that allows explicit specification for record type fields? Like `[Ord(int)]` and then using something like `OrderBy(...OrdAttribute...).ThenBy(MetaDataToken)` in https://github.com/louthy/language-ext/blob/master/LanguageExt.Core/Utility/Reflect.cs#L18

Then I would define my classes like 

```
class MyClass : Record<MyClass>
{
   public DateTimeOffset UnimportantTimestamp3 {get; set;}

   public DateTimeOffset UnimportantTimestamp4 {get; set;}

   [Ord(1)]
   public DateTimeOffset SecondaryTimestamp2 {get; set;}

   [Ord(0)]
   public DateTimeOffset MostImportantTimestamp1 {get; set;}
}
```
and get effectively the order I want -- having a hard guarantee that 1 and 2 aren't reversed.

**Comment by louthy** [comment]
> My primary idea is to rely on MetaDataToken / Record<A> and use unit tests to make sure this will at least fail if getting unreliable.

They fields are already sorted by `MetadataToken`

https://github.com/louthy/language-ext/blob/master/LanguageExt.Core/Utility/Reflect.cs#L18

**Comment by StefanBertels** [comment]
Yes. (Wrote that in my first sentence...)

**Comment by louthy** [comment]
Sorry missed that.  I'll pick this up next week, going to be away for a few days.

**Comment by louthy** [comment]
This is dealt with by the `[Record]` code-gen, which will be the focus of future improvements to the record system
