### ISSUE TITLE
CodeGen fails to generate With for Records with field backed properties

### ISSUE THREAD

**Issue by koffmoff** [louthy/language-ext#622]
To my understanding, both of the below `Record` implementations should be valid.

```cs
    [With]
    public partial class Works : Record<Works>
    {
        public readonly String A;
        
        public Works(string a)
        {
            this.A = a;
        }
    }

    [With]
    public partial class Fails : Record<Fails>
    {
        public string A { get; }

        public Fails(string a)
        {
            this.A = a;
        }
    }
```

However, the CodeGen-generated code differs:

```cs
    public partial class Works
    {
        public Works With(String A = null) => new Works(A ?? this.A);
    }

    public partial class Fails
    {
        public Fails With() => new Fails();
    }
```

Which obviously doesn't compile since `Fails` does not have a default constructor.

A CodeGen bug or some misunderstanding on my behalf?

**Comment by louthy** [comment]
Yes, it's very much set up to work with `readonly` fields rather than field-backed properties which have a nasty habit of not necessarily being setup in a constructor.

So, use `public readonly string A` instead of `public string A { get; }`.  

There's probably more that could be done to spot the use of auto-field backed properties, but there's also a value to keeping the analyser fast and simple.

**Comment by koffmoff** [comment]
The reason I wan't to use properties is I have a WPF application and WPF can only bind to properties. Now I have to wrap my Records in other, WPF-friendly classes which is not very nice.

I though it'd be a simple fix but I suspect from your answer that you've already been down this road and that it's more complicated than it seems. Care to give some pointers and maybe I could take a look if I could find some time?

**Comment by louthy** [comment]
>  Care to give some pointers and maybe I could take a look if I could find some time?

No problem, it's not super hard to do this, it's just a bit of experimentation and typing (i.e. time, which isn't always available).

[This function](https://github.com/louthy/language-ext/blob/master/LanguageExt.CodeGen/CodeGenUtil.cs#L14) returns a `List<FieldDeclarationSyntax> Fields`, which is built from:
```c#
var fields = applyToClass.Members
                         .Where(m => m is FieldDeclarationSyntax)
                         .Select(m => m as FieldDeclarationSyntax)
                         .Where(f => f.Declaration.Variables.Count > 0)
                         .Where(f => FirstCharIsUpper(f.Declaration.Variables[0].Identifier.ToString()))
                         .Where(f => f.Modifiers.Any(SyntaxKind.PublicKeyword))
                         .Where(f => f.Modifiers.Any(SyntaxKind.ReadOnlyKeyword))
                         .Where(f => !f.Modifiers.Any(SyntaxKind.StaticKeyword))
                         .ToList();
```
Those are the fields for the `With` (and the lenses).  It would need to not return a `FieldDeclarationSyntax`, but a `MemberDeclarationSyntax`.  And the filter would need updating to include any `PropertyDeclarationSyntax` that are auto-field backed properties  (i.e. `T prop { get; }`); 

Working with properties that have code is likely to be a problem, so you'd probably need to query the Roslyn syntax tree for a body or expression body and filter out those properties.

For example:
```c#
public static class Test
{
    public int Prop1 { get; }

    public int Prop2 { get => 123; }

    public int Prop3 { get { return 123 }; }
}
```
`Prop1` is the one we want to keep.  If you take a look at the difference in Roslyn, it might give you an idea of where to start:
```c#
PropertyDeclaration(
    PredefinedType(Token(SyntaxKind.IntKeyword)), Identifier("Prop1"))
    .WithModifiers(TokenList(Token(SyntaxKind.PublicKeyword)))
    .WithAccessorList(
        AccessorList(
            SingletonList<AccessorDeclarationSyntax>(
                AccessorDeclaration(
                    SyntaxKind.GetAccessorDeclaration)
                .WithSemicolonToken(
                    Token(SyntaxKind.SemicolonToken))))),
PropertyDeclaration(
    PredefinedType(Token(SyntaxKind.IntKeyword)), Identifier("Prop2"))
    .WithModifiers(TokenList(Token(SyntaxKind.PublicKeyword)))
    .WithAccessorList(
        AccessorList(
            SingletonList<AccessorDeclarationSyntax>(
                AccessorDeclaration(
                    SyntaxKind.GetAccessorDeclaration)
                .WithExpressionBody(
                    ArrowExpressionClause(
                        LiteralExpression(
                            SyntaxKind.NumericLiteralExpression,
                            Literal(123))))
                .WithSemicolonToken(
                    Token(SyntaxKind.SemicolonToken))))),
PropertyDeclaration(
    PredefinedType(Token(SyntaxKind.IntKeyword)), Identifier("Prop3"))
    .WithModifiers(TokenList(Token(SyntaxKind.PublicKeyword)))
    .WithAccessorList(
        AccessorList(
            SingletonList<AccessorDeclarationSyntax>(
                AccessorDeclaration(
                    SyntaxKind.GetAccessorDeclaration)
                .WithBody(
                    Block(
                        SingletonList<StatementSyntax>(
                            ReturnStatement(
                                LiteralExpression(
                                    SyntaxKind.NumericLiteralExpression,
                                    Literal(123)))
                            .WithSemicolonToken(
                                MissingToken(SyntaxKind.SemicolonToken)))))
                .WithSemicolonToken(
                    Token(SyntaxKind.SemicolonToken))))
```

In [`RecordWith`](https://github.com/louthy/language-ext/blob/master/LanguageExt.CodeGen/RecordWith.cs) there's a call to:
```c#
partialClass = CodeGenUtil.AddWith(context, partialClass, returnType, fields);
```
Which adds the `With` function.  That takes the list of fields and would need updating to take a list of members.

Then the first block of code that builds the parameters would need updating to work with fields or properties:
```c#
var withParms = fields.Where(f => f.Declaration.Variables.Count > 0)
                        .Select(f => (Field: f, Type: context.SemanticModel.GetTypeInfo(f.Declaration.Type)))
                        .Select(f => (Id: f.Field.Declaration.Variables[0].Identifier, 
                                    Type: f.Field.Declaration.Type,
                                    Info: f.Type))
                        .Select(f => (f.Id, 
                                    f.Type, 
                                    f.Info,
                                    IsGeneric: !f.Info.Type.IsValueType && !f.Info.Type.IsReferenceType,
                                    ParamType: f.Info.Type.IsValueType 
                                        ? SyntaxFactory.NullableType(f.Type)
                                        : f.Type))
                        .Select(f =>
                            SyntaxFactory.Parameter(MakeFirstCharUpper(f.Id))
                                        .WithType(f.ParamType)
                                        .WithDefault(
                                            f.IsGeneric
                                                ? SyntaxFactory.EqualsValueClause(SyntaxFactory.DefaultExpression(f.Type))
                                                : SyntaxFactory.EqualsValueClause(SyntaxFactory.LiteralExpression(SyntaxKind.NullLiteralExpression))))
                        .ToArray();
```
To complete the job you'd need to follow a similar path for updating the [`AddLenses`](https://github.com/louthy/language-ext/blob/master/LanguageExt.CodeGen/CodeGenUtil.cs#L72) and [`AddLens`](https://github.com/louthy/language-ext/blob/master/LanguageExt.CodeGen/CodeGenUtil.cs#L81) functions.

A useful tip to working with Roslyn is to use [this online quoter](https://roslynquoter.azurewebsites.net/) - I've found it invaluable in building out these code gen tools.

**Comment by louthy** [comment]
Deployed in `v3.3.17`
