### ISSUE TITLE
Instance creation of Either<T,T>

### ISSUE THREAD

**Issue by yury-fedorov** [louthy/language-ext#631]
ie. `Either<string,string> a = ""; `  leads to the error:
_CS0457	Ambiguous user defined conversions 'Either<string, string>.implicit operator Either<string, string>(string)' and 'Either<string, string>.implicit operator Either<string, string>(string)' when converting from 'string' to 'Either<string, string>'_	

Enrico solves it with:
`Either<L, R> = Left(L) | Right(R)`
See for more details: https://github.com/la-yumba/functional-csharp-code/blob/master/LaYumba.Functional/Either.cs#L11

**Comment by gwintering** [comment]
All you need to do is use `Right` or `Left` to specify which value you are providing
```csharp
Either<string, string> dexter = Right("");
Either<string, string> sinister = Left("");
```

**Comment by bender2k14** [comment]
> Enrico solves it with `Either<L, R> = Left(L) | Right(R)`

And @louthy solves it the same way.

```
using Xunit;
using static LanguageExt.Prelude;

namespace LanguageExt.Tests
{
    public class Tests
    {
        [Fact]
        public void EitherRightLeftTest()
        {
            Either<string, string> right = Right("");
            Assert.True(right.IsRight);

            Either<string, string> left = Left("");
            Assert.True(left.IsLeft);
        }
    }
}
```

**Comment by yury-fedorov** [comment]
Thanks a lot for the immediate feedback @gwintering and @bender2k14! 
I missed these functions from `using static LanguageExt.Prelude;` 
Have a great day!
    _Yury_
