### ISSUE TITLE
Create object that inherit from Record<T> crashes on iOS on Language-Ext versions later than 3.1.24

### ISSUE THREAD

**Issue by 1iveowl** [louthy/language-ext#632]
I have observed, that every version later than 3.1.24 causes a crash on iOS, when creating an object that inherits from Record<T>.

I've created a simple project to illustrate this issue here: https://github.com/1iveowl/Language-Ext-Issue-Recreate. 

Run the iOS project on a real device and press the button number **1** , and you will get a SIGSEGV native crash from the line `var objA = new ObjectA<object>(new object());`.

ObjectA is defined as:

```csharp
public sealed class ObjectA<T> : Record<ObjectA<T>>
    {
        public T Obj { get; }

        public ObjectA(T obj)
        {
            Obj = obj;
        }
    }
```

In the project I use Language-Ext version 3.3.20. If I change the project to use Language-Ext version 3.1.24 then the crash will no longer occur. 

Note: I've only seen the issue on a real iOS device. If I run the project in the simulator I do not see a crash. 

Might be related to #633

**Comment by bender2k14** [comment]
When the platform is iPhone, the architecture is `ARM64`.

Is there a way to reproduce this behavior for `ARM64` without needing an iPhone?

**Comment by 1iveowl** [comment]
> Is there a way to reproduce this behavior for `ARM64` without needing an iPhone?

From my observations the issue only presents itself on a real device. I've tried to run the recreation project I refer to in the iPhone simulator and here I do not see the crash.

**Comment by bender2k14** [comment]
Have you submitted a bug report against the iPhone simulator for not having the same behavior as the real hardware in this case?

**Comment by 1iveowl** [comment]
I might, but will probably choose to save my breath on that one.  

First off. This will not solve the real issue. There is  an issue when running the code on a device. Fixing the simulator will only mean the the issue also sufaces in the simulator. It will not eliminate the real issue on the device.

Secondly, no one have ever promised that the simulator is identical to the device. From my experience the simulator speeds up the dev process, but never eliminates the need for testing on a device.

**Comment by bender2k14** [comment]
I agree that integrations tests should not be forsaken.

>  Fixing the simulator will only mean the the issue also surfaces in the simulator.

I think fixing the simulator will do more.  As you say:
> ...the simulator speeds up the dev process...

I would expect this issue to be fixed more quickly if the issue were reproducible in the simulator, and I would also expect that a more accurate simulator would facilitate the creation of tests that could prevent us from introducing iPhone-specific bugs in the future.

**Comment by 1iveowl** [comment]
@bender2k14 fair point.

**Comment by louthy** [comment]
I'm closing this as there's not been a follow up from @1iveowl with any details of the exception or anything we can really look into.  Please reopen if you have more info.

**Comment by 1iveowl** [comment]
Making sure that the linker works its magic on LanguageExt.Core fixed the issue as outlined here: https://github.com/louthy/language-ext/issues/537#issuecomment-451542942 

It seems that this could very well be the explanation: https://github.com/louthy/language-ext/issues/537#issuecomment-460711504.
