### ISSUE TITLE
fun(...) crashes in iOS for versions of Language-Ext later than 3.1.24

### ISSUE THREAD

**Issue by 1iveowl** [louthy/language-ext#633]
I have observed, that every version later than 3.1.24 causes a crash on iOS, when creating a function using `fun(...)`.

I've created a simple project to illustrate this issue here: https://github.com/1iveowl/Language-Ext-Issue-Recreate. 

Run the iOS project on a real device and press the button number **2**, and you will get a crash from the line `var testFunc = fun((int x) => Task.Delay(TimeSpan.FromSeconds(x)));`.

In the project I use Language-Ext version 3.3.20. If I change the project to use Language-Ext version 3.1.24 then the crash will no longer occur. 

Note: I've only seen the issue on a real iOS device. If I run the project in the simulator I do not see a crash. 

Might be related to #632

**Comment by bender2k14** [comment]
I don't think your first paragraph matches your example code.

Did you mean to say something about the function `fun` instead of the type `Record<>`?

**Comment by louthy** [comment]
I have no way of testing this.  Do you have any details of the exception and stack-trace?

The implementation of `fun` is trivial:
```c#
    public static Func<T1, R> fun<T1, R>(Func<T1, R> f) => f;
```
And is more of a coercion of the C# compiler than anything significant at run-time.  The only other run-time behaviour that might get triggered is the loading of `static` values, but I'd need more information before going digging.

**Comment by 1iveowl** [comment]
Thanks for the input.

I'll take a close look at the code and see if I can debug deeper to narrow down a root cause. 

Any hint about what might have changed after 3.1.24 that might have caused this?

**Comment by bender2k14** [comment]
> Any hint about what might have changed after 3.1.24 that might have caused this?

I am still very confused about what the issue even is.

Your first paragraph says...
> I have observed, that every version later than 3.1.24 causes a crash on iOS, when creating an object that inherits from Record.

...and then you say
> Run the iOS project on a real device and press the button number 2, and you will get a crash from the line var test 1Func = fun((int x) => Task.Delay(TimeSpan.FromSeconds(x)));`

Those seem unrelated to me.  It seems to me like you copied this first paragraph from #632.

**Comment by 1iveowl** [comment]
My mistake. The first paragraph have now been updated.

**Comment by 1iveowl** [comment]
I've done some testing. I'm not all done and I have not narrowed it down to the root cause yet. 

However, so far I've been able to detimer that it's not the this line: `public static Func<T1, R> fun<T1, R>(Func<T1, R> f) => f;` of code, which is hardly a surprise, since not much is going on here.

So, I've stripped away all the partial parts of the `Prelude` class, trying to introduce all the `static` values one by one, to pinpoint when the crash happens, so that I can start creating a possible fix/workaround. This is obviously tedious work, as I have to build and run the iOS app on a device for every single try.

Anyhow, I will continue tomorrow. Obviously, any hints/guesses etc. to what `static` variable, method, attribute that might be the culprit, is highly appreciated.

**Comment by bender2k14** [comment]
> So, I've stripped away all the partial parts of the `Prelude` class, trying to introduce all the `static` values one by one, in an effort to pinpoint when the crash happens, so that I can start creating a possible fix/workaround. This is obviously tedious work, as I have to build and run the iOS app on a device for every single try.

Don't do this "one by one".  Cut your search space in half each time just like [binary search](https://en.wikipedia.org/wiki/Binary_search_algorithm).

Start with some set of `static` values such that the program crashes.  Comment out half of them.  Test.  If the program crashes, then repeat with the set of `static` values still commented in.  If the program did not crash, then repeat with the set of `static` values that were just commented out.

My guess is that you are merely searching in `Prelude` for some static value that extends from `Record<>`, which means that this issue is a special case of #632.

**Comment by 1iveowl** [comment]
I’m pulling out my hairs here. Been testing for hours still without getting closer to what is causing the crashes. 

Is there some way to determine what changes was made between v3.1.24 and 3.3.0? As mentioned 3.1.24 works, but later version do not.

**Comment by bender2k14** [comment]
There were many changes for the purpose of optimization.  There were 15 beta release between 3.1.24 and 3.3.0.

Have you tried any of those?  Can you binary search though those and determine which (if any) prelease introduced the issue you are having?

**Comment by louthy** [comment]
I'm closing this as there's not been a follow up from @1iveowl with any details of the exception or anything we can really look into.  Please reopen if you have more info.

**Comment by 1iveowl** [comment]
Making sure that the linker works its magic on LanguageExt.Core fixed the issue as outlined here: https://github.com/louthy/language-ext/issues/537#issuecomment-451542942 

It seems that this could very well be the explanation: https://github.com/louthy/language-ext/issues/537#issuecomment-460711504.
