### ISSUE TITLE
Please, some other examples...

### ISSUE THREAD

**Issue by andreabioli** [louthy/language-ext#639]
I'm trying to use your library, but I'm having trouble designing a form validation sequence, where I would like to concatenate (eventual) errors from the previous calls.
An example, in pseudo code, could be the following:

Either<List<string>, User> result =
    ... (? I don't know how to start...)
    .CheckStringLength(firstName, 5, 20, errorMsg: "First Name is not in the range 5-20")
    .CheckStringLength(lastName, 5, 20, errorMsg: "Last Name is not in the range 5-20")
    .CheckIntValue(salary, 100, 10000, errorMsg: "Salary is not in the range 100-1000")
    .CreateUserInDatabase(firstName, lastName, salary);

And have in result an Either that tells me the list of errors (validation or db-related), or the newly created user, if all is ok.

I think that some minimum examples of various use cases of the library would be really beneficial, for users, probably even more than adding new features! :-)

Thanks in advance, and congratulations for the wonderful work!
Andrea

**Comment by bender2k14** [comment]
Look at this test and the ones after it

https://github.com/louthy/language-ext/blob/master/LanguageExt.Tests/ValidationTests.cs#L136

**Comment by andreabioli** [comment]
Oh, very interesting! :-) Thanks a lot!
A
