### ISSUE TITLE
Either.Equals throws exception when trying to compare Bottom eithers

### ISSUE THREAD

**Issue by pahomovda** [louthy/language-ext#64]
Equals method of Either throws an exception when you try to compare eithers in the Bottom state.
Seems like Bottom Either must be equal to other Bottom Either which is returned from FirstOrDefault method for example. But i have got:
`LanguageExt.BottomException: Either is in a bottom state and therefore not valid.  This can happen when the value was filterd and the predicate returned false and there was no valid state the value could be in.  If you are going to use the type in a filter you should check if the IsBottom flag is set before use.  This can also happen if the struct wasn't initialised properly and then used.`

Here is the code from which i am getting the error:
```c#
public foo()
{
    List<Either<Error, T>> results = ...;
    var firsterror = results.FirstOrDefault(i => i.IsLeft);
    if (!firsterror.IsDefault()) // <-- here i get exception
    {
        ...
    }
}

public static bool IsDefault<T>(this T obj) => 
    EqualityComparer<T>.Default.Equals(obj, default(T));
```

I know i may use IsBottom for this case, but comparing with default is more safety for a FirstOrDefault method result, is it? I mean someday Bottom state may become not default state of Either and i will get ultra strange behaviour of my program.

**Comment by louthy** [comment]
Hi @pahomovda - thanks for reporting this.  If you build from the latest source then you'll find this is fixed.
