### ISSUE TITLE
Explanation or examples on how to write a new (simple) monad from scratch

### ISSUE THREAD

**Issue by andreabioli** [louthy/language-ext#646]
I think it's all in the title: it would be interesting to have some explanation on how to write a new monad.
I think it would be very helpful: the actual implemented monads are very powerful, but the code is incredibly complex, even in the tests!
Thanks.

**Comment by andreabioli** [comment]
I clarify my thoughts: going through the internet, I see 'simpler' implementations of monads (if less lines of code can be classified as 'simpler'... :-)), while here every construct is filled with variations, extra support code, whatever...
I would like to know what is fundamental, and what can be skipped if not directly needed, with some simple examples, so to learn incrementally... do I ask too much? :-)
Thanks again.

**Comment by bender2k14** [comment]
I recommend reading this book
https://www.manning.com/books/functional-programming-in-c-sharp

**Comment by andreabioli** [comment]
I actually read it :-)
My question was really more related to the code: even though I started writing some test code by myself, following many sources, and (also) using this excellent library, my question was, and is, really narrowly focused. 
I see that in this library monads derive from base classes monads, or M<something>, and I would like to understand how to reuse these services without inventing everything each time.
Thank you anyway for your suggestion!

**Comment by bender2k14** [comment]
When you are writing such things for the first time as you are, it is _beneficial_ to "invent everything" again.  I do not recommending trying "skip ahead" as you are now, both for the sake of your own learning as well as trying not to run afoul of the [YAGNI principle](https://en.wikipedia.org/wiki/You_aren%27t_gonna_need_it).

Besides, I think the code you are referring to is trying to make C# look like it has [type classes](https://en.wikipedia.org/wiki/Type_class), which involves having to auto generate a significant amount of code.  In my few attempts, I have never been able to make even a trivial change to Language Ext's auto generated code template, but maybe that just speaks to my limited experience auto generating code.

On the other hand, you might find what you are looking for in an [issue tagged with `examples / documentation`](https://github.com/louthy/language-ext/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A%22examples+%2F+documentation%22+).  @louthy is often extremely thorough in his explanations, and I vaguely recall that some of them were about custom monads.

**Comment by louthy** [comment]
@andreabioli The lang-ext wiki has an article titled: [Does C# Dream of Electric Monads?](https://github.com/louthy/language-ext/wiki/Does-C%23-Dream-Of-Electric-Monads%3F) - that should get you started.

**Comment by andreabioli** [comment]
@bender2k14 Your comment is full of common sense, of course, and I agree with all what you say: but there's a difference between taking a shortcut, and only smoothing edges... :-)
@louthy I remember that was one of the first articles I gave a quick look to, but probably I didn't understanding anything, at the time! :-) Re-reading it now is really beneficial, so thank you again also for that! ;-)

**Comment by louthy** [comment]
@andreabioli Also, in the ['Thinking functionally'](https://github.com/louthy/language-ext/wiki/Thinking-Functionally) series on the wiki, there's a ['What is LINQ really?'](https://github.com/louthy/language-ext/wiki/Thinking-Functionally:-What-is-LINQ-really%3F) page which goes through the basics.

**Comment by andreabioli** [comment]
Wonderful articles, indeed! Thanks again! :-)
A

Il giorno gio 17 ott 2019 alle ore 16:24 Paul Louth <
notifications@github.com> ha scritto:
