### ISSUE TITLE
Missing Integer constants in Integer.cs? (Range 41-50)

### ISSUE THREAD

**Issue by andreabioli** [louthy/language-ext#656]
Everything in the title... :-)

**Comment by bender2k14** [comment]
Can you give a specific integer constant that you expected to see but is missing in `Integer.cs`?

**Comment by andreabioli** [comment]
I wrote it! 🙂 From 41 to 50!

Il mar 29 ott 2019, 01:39 Tyson Williams <notifications@github.com> ha
scritto:

**Comment by bender2k14** [comment]
Ok, I see what you are talking about now.  Here is a link that embed's that code in this comment.

https://github.com/louthy/language-ext/blob/035aadb79f2bd6222f64ea2c4f8f6a4eb1b19ef9/LanguageExt.Core/ClassInstances/Const/Integer.cs#L47-L48

This is also a problem.
https://github.com/louthy/language-ext/blob/035aadb79f2bd6222f64ea2c4f8f6a4eb1b19ef9/LanguageExt.Core/ClassInstances/Const/Integer.cs#L67
