### ISSUE TITLE
Simple parsec code from the docs doesn't work

### ISSUE THREAD

**Issue by lucabol** [louthy/language-ext#659]
Unless I am missing something, this code from the docs should work.

```csharp
    static void Main() {
        var parser = many1(letter);
        var r = parse(parser, "abcde");
        WriteLine($"IsFaulted: {r.IsFaulted}\nResult: {r.Reply.Result}\nState: {r.Reply.State}\nError: {r.Reply.Error}");
    }
```
gives:
```
IsFaulted: False
Result: LanguageExt.Seq`1[System.Char]
State: 
Error: error at (line 1, column 6): unexpected end of stream, expecting letter
```

**Comment by bender2k14** [comment]
Can you direct us to the specific location in the docs?

Can you provide more complete code?  Specifically, what `using`s are needed to make that code compile and have that behavior?

**Comment by lucabol** [comment]
https://github.com/louthy/language-ext/wiki/Thinking-Functionally:-Combinators

after the phrase: "How do we keep parsing all of the letters?"

The `usings` are the same as in the docs, reproduced below:

using LanguageExt;
using LanguageExt.Parsec;
using static LanguageExt.Prelude;
using static LanguageExt.Parsec.Prim;
using static LanguageExt.Parsec.Char;
using static LanguageExt.Parsec.Expr;
using static LanguageExt.Parsec.Token;

**Comment by bender2k14** [comment]
Thanks.  The `using`s
```
using static System.Console;
using static LanguageExt.Parsec.Char;
using static LanguageExt.Parsec.Prim;
```

sufficed.

> Title: Simple parsec code from the docs doesn't work
> ...this code from the docs should work.
> ...
> gives...

You have claimed that this parsec code doesn't work, but you have not stated why you think that or what behavior you expected instead.

I think this parsec code from the docs works as intended.  Specifically, the following test passes.

```using Xunit;
using static LanguageExt.Parsec.Char;
using static LanguageExt.Parsec.Prim;
using static LanguageExt.Prelude;

namespace LanguageExt.Tests
{
    public class Tests
    {
        [Fact]
        public void Test()
        {
            var parser = many1(letter);
            var result = parse(parser, "abcde");
            Assert.False(result.IsFaulted);
            Assert.Equal(Seq('a', 'b', 'c', 'd', 'e'), result.Reply.Result);
            Assert.Equal("", result.Reply.State.ToString());
        }
    }
}
```

**Comment by lucabol** [comment]
You are correct. Apologies for the bother. I got confused by the error message.
