### ISSUE TITLE
WithLens fails when class contains expression-bodied properties

### ISSUE THREAD

**Issue by AkilaeTribe** [louthy/language-ext#664]
Given the following class, and LanguageExt.Core 3.3.39 used

```
[WithLens]
public partial class CustomClass : Record<CustomClass>
{
	public readonly Option<string> Value;

	public CustomClass(Option<string> value)
	{
		Value = value;
	}

	public Option<int> ValueLengthAsExpressionBodiedProperty => Value.Map(x => x.Length);

	public Option<int> ValueLengthAsGetProperty
	{
		get { return Value.Map(x => x.Length); }
	}

	public Option<int> ValueLengthAsExpressionBodiedMethod() => Value.Map(x => x.Length);
}
```
The declaration of ValueLengthAsExpressionBodiedProperty member will cause a build failure, depending on the version of LanguageExt.CodeGen.

```
Error	MSB3073	The command "dotnet codegen "@obj\Debug\netstandard2.1\LanguageExtWithLens3339Tests.csproj.dotnet-codegen.rsp"" exited with code 3.

C:\Users\AkilaeTribe\.nuget\packages\codegeneration.roslyn.buildtime\0.6.1\build\CodeGeneration.Roslyn.BuildTime.targets	84
```
The build will succeed with LanguageExt.CodeGen 3.1.25.
The build will fail with LanguageExt.CodeGen 3.3.4 or higher.

[LanguageExtWithLens3125Tests.zip](https://github.com/louthy/language-ext/files/3853597/LanguageExtWithLens3125Tests.zip)
[LanguageExtWithLens3339Tests.zip](https://github.com/louthy/language-ext/files/3853598/LanguageExtWithLens3339Tests.zip)

**Comment by louthy** [comment]
Fixed in `3.3.40`
