### ISSUE TITLE
Discriminated [Union] Code generation issues

### ISSUE THREAD

**Issue by StefanBertels** [louthy/language-ext#665]
Hi,

I just checked the latest and greatest [Union] feature described here:
https://github.com/louthy/language-ext/releases/tag/3.3.34

I used v3.3.39.

Two things I stumbled upon:

1. If there are some imports (`using`) missing, this will raise errors. Probably generated code should add them or even better use full type names.

2. Defining Unions within a class (nested class) does not work without making the outer class `partial`.

**Comment by louthy** [comment]
> If there are some imports (using) missing, this will raise errors. Probably generated code should add them or even better use full type names.

Fix on its way.

> Defining Unions within a class (nested class) does not work without making the outer class partial.

This isn't supported behaviour, but it seems the solution of making the outer class partial is there if you need it.  I can't think of another way that _could_ work without the outer class being partial.

**Comment by louthy** [comment]
Fixed in `3.3.40`
