### ISSUE TITLE
How to extract the error from an Either in a simple way

### ISSUE THREAD

**Issue by feugen24** [louthy/language-ext#677]
We introduced language-ext in our project and we return Either's in our return types for now, where it makes sense.

In an mvc controller we want to return a BadRequest in case of Left value of Either with the following implementations:
1. 
if (either.IsLeft)
{
     return BadRequest(either.LeftAsEnumerable().First());
}
2.
string error = null;
either.IfLeft((issue) => error = issue);
return BadRequest(error);
3.
maybe do a flip in the monad to get the value of the error but the code seems strange for that

For now 2 seems preferable. 
What I also noticed is that .net programmers unused to this style tend to discover and use solution 1 and that seems to defy the purpose of the monad.

Any suggestion for simplest code to do this?

note, it is related to [231](https://github.com/louthy/language-ext/issues/231) but that one was closed

**Comment by colethecoder** [comment]
Ideally you would be doing a Match to handle both the Left and Right case. Without seeing more of the code it is hard to tell why you aren't doing that?

Using IsLeft in an `if` doesn't feel very functional, and the side effect-y null stuff in your second example is messy.

Can you post a more complete example?

**Comment by louthy** [comment]
I haven't used the MVC framework, but I am assuming that `BadRequest` comes [from here](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.controllerbase.badrequest?view=aspnetcore-3.0) and that _success_ would [be this](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.controllerbase.ok?view=aspnetcore-3.0)

And, so to make everything nicely functional I would provide an extension method to `Either` or `ControllerBase` to project the data-type into an `ObjectResult`:
```c#
public static ObjectResult ToResponse<L, R>(this ControllerBase ctrlr, Either<L, R> ma) =>
    ma.Case switch 
    {
        LeftCase<L, R> (var error) => ctrlr.BadRequest(error),
        RightCase<L, R>(var value) => ctrlr.Ok(value)
    };
```
That would allow (from within a controller) to do this:
```c#
    return this.ToResponse(either);
```
You could slightly alter the extension method to do:
```c#
public static ObjectResult ToResponse<L, R>(this Either<L, R> ma, ControllerBase ctrlr) =>
    ma.Case switch 
    {
        LeftCase<L, R> (var error) => ctrlr.BadRequest(error),
        RightCase<L, R>(var value) => ctrlr.Ok(value)
    };
```
Which would give
```c#
    return either.ToResponse(this);
```
Whatever feels more readable, really.

If you're not working with the latest language-ext then you can use `Match` for pattern-matching instead:
```c#
public static ObjectResult ToResponse<L, R>(this ControllerBase ctrlr, Either<L, R> ma) =>
    ma.Match(Left: error  => ctrlr.BadRequest(error),
             Right: value => ctrlr.Ok(value));
```
In terms of doing the _early out_ that you're suggesting, you should really try to leverage the in-built monadic functionality of `Either`.  It has _early out_ built-in to its bind function, and so using it in a LINQ expression will get you what you need.  Then your controller methods can become expressions:
```c#
    ObjectResult YourControllerMethod(...) =>
        (from x in DoSomethingThatReturnsAnEitherA()
         from y in DoSomethingThatReturnsAnEitherB()
         from z in DoSomethingThatReturnsAnEitherC()
         select (x, y, z))
        .ToReponse();
```
As soon as you start using `if(either.IsLeft)` or anything like that then you may as well not be writing functional code and `Either` may as well not be a monad, because you're then doing the exact job the `Either` is built to do.  It is built to take away all of the scaffolding of flow-control that you're trying to to do manually.  Let the `Either` do the work.

**Comment by feugen24** [comment]
"ma.Case switch" syntax requires c# 8 and we don't have that.

The match syntax requires a cast but then it compiles, still it's difficult to integrate

```
public static ObjectResult ToResponse<L, R>(this ControllerBase ctrlr, Either<L, R> ma) =>
            ma.Match(Left: error =>
                {
                    return (ObjectResult) ctrlr.BadRequest(error);
                },
                Right: value => ctrlr.Ok(value));
```
I understand that ideally I want to chain monads using linq syntax but it's in the context of an exsiting project...

the method I want to change is like this:

```
[ApiController]
public class FlowController : ControllerBase
{
.....................
[HttpPost("mapping")]
        public async Task<IActionResult> UpdateConfigMapping([FromQuery] int targetConfigId, [FromQuery] int? flowConfigId)
        {
            if (flowConfigId != null)
            {
                var flowConfigIdEither = await _flowRepository.GetFlowConfigAsync(flowConfigId.Value);
                if (flowConfigIdEither .IsLeft)
                {
                    return BadRequest(flowConfigIdEither .LeftAsEnumerable().First());
                }
//                await callFlowConfig.MatchAsync<ObjectResult>(
//                    Left: error => { return BadRequest(error); },
//                    RightAsync: async value =>
//                    {
//                        return ???
//                    });

            }

            await _flowRepository.UpdateFlowConfigMappingAsync(targetConfigId, flowConfigId);
            await _flowRepository.SaveChangesAsync();

            return NoContent();
        }
```
The logic is: if we get a not null flowConfigId check in db that it exists, if not get error from either and return; regardless update mapping.
Maybe if I also convert flowConfigId to an Option and try to chain them with linq.

**Comment by louthy** [comment]
@feugen24 There's a number of steps you need to walk through in your head for situations like this.

* How can I make this whole thing one expression?
* What control flow do I need?
* What information should carry through?

That should inform the decision making.  In my mind I see:

* Tasks with `if` statements (suggests `OptionAsync` to me)
* Apparent calls to IO, which suggests `TryAsync`
* Use of `Either`
* Mapping to `IActionResult`, which appears to be a poor man's `Either`.  
* Mapping to `Task<IActionResult>`, which appears to be a poor man's `EitherAsync`.  

And so, I'd start off with trying to unify whatever `_flowRepository`'s type is.  I don't know what you're using for that, so I've created a placeholder:

```c#

public class FlowRepo
{
    public EitherAsync<Error, Unit> UpdateFlowConfigMappingAsync(int targetConfigId, int? flowConfigId) =>
        Task.FromResult(unit);

    public EitherAsync<Error, int> GetFlowConfigAsync(int flowConfigId) =>
        Task.FromResult(1);

    public EitherAsync<Error, Unit> SaveChangesAsync() =>
        Task.FromResult(unit);
}
```
Then I'd look at the branches of control flow.  I would first make this:
```c#
if (flowConfigId != null)
{
    var flowConfigIdEither = await _flowRepository.GetFlowConfigAsync(flowConfigId.Value);
    if (flowConfigIdEither .IsLeft)
    {
        return BadRequest(flowConfigIdEither .LeftAsEnumerable().First());
    }
}
```
Into this:
```c#
static EitherAsync<Error, int> Validate(FlowRepo flowRepo, int targetConfigId, Option<int> flowConfigId) =>
    flowConfigId.Map(flowRepo.GetFlowConfigAsync)
                .IfNone(zero);

static readonly EitherAsync<Error, int> zero = 
    RightAsync<Error, int>(0);
```
Note how I'm not yet converting to an `IActionResult`.  What that does is succeeds if `flowConfigId` is `None` and runs `flowRepo.GetFlowConfigAsync` with the `id` if it's `Some`.  So, the only way this function could return an `Error` would be if `flowRepo.GetFlowConfigAsync(...)` failed.

Next, the section below the `if` block:
```c#
static EitherAsync<Error, Unit> UpdateAndSave(FlowRepo flowRepo, int targetConfigId, int? flowConfigId) =>
    from _1 in flowRepo.UpdateFlowConfigMappingAsync(targetConfigId, flowConfigId)
    from _2 in flowRepo.SaveChangesAsync()
    select unit;
```
We can then compose the two functions together:
```c#
static EitherAsync<Error, Unit> ValidateUpdateAndSave(FlowRepo flowRepo, int targetConfigId, int? flowConfigId) =>
    from val in Validate(flowRepo, targetConfigId, Optional(flowConfigId))
    from res in UpdateAndSave(flowRepo, targetConfigId, flowConfigId)
    select res;
```
Finally, add some extension methods to get a `EitherAsync` into `OK | NoContent | BadResult`

```c#
public static class EitherActionResultExtensions
{`
    static IActionResult NoContent() => null; // TODO: Fill these in
    static IActionResult BadRequest(Error err) => null; // TODO: Fill these in
    static IActionResult Ok<A>(A value) => null; // TODO: Fill these in

    public static Task<IActionResult> Respond(this EitherAsync<Error, Unit> ma) =>
        ma.Match(
            Left: BadRequest,
            Right: _ => NoContent());

    public static Task<IActionResult> Respond<A>(this EitherAsync<Error, A> ma) =>
        ma.Match(
            Left: BadRequest,
            Right: value => Ok(value));
}
```

Below is the full controller code.  Note how it's trivial to read this from top to bottom and follow the declarative function names, without any of the `if` scaffolding getting in the way.  Note also how they're all `static` functions, and so you can create reusable blocks that compose trivially for other controllers.

```c#
public Task<IActionResult> UpdateConfigMapping(int targetConfigId, int? flowConfigId) =>
    ValidateUpdateAndSave(_flowRepository, targetConfigId, flowConfigId)
        .Respond();

static EitherAsync<Error, Unit> ValidateUpdateAndSave(FlowRepo flowRepo, int targetConfigId, int? flowConfigId) =>
    from val in Validate(flowRepo, targetConfigId, Optional(flowConfigId))
    from res in UpdateAndSave(flowRepo, targetConfigId, flowConfigId)
    select res;

static EitherAsync<Error, int> Validate(FlowRepo flowRepo, int targetConfigId, Option<int> flowConfigId) =>
    flowConfigId.Map(flowRepo.GetFlowConfigAsync)
                .IfNone(zero);

static EitherAsync<Error, Unit> UpdateAndSave(FlowRepo flowRepo, int targetConfigId, int? flowConfigId) =>
    from _1 in flowRepo.UpdateFlowConfigMappingAsync(targetConfigId, flowConfigId)
    from _2 in flowRepo.SaveChangesAsync()
    select unit;

static readonly EitherAsync<Error, int> zero =
    RightAsync<Error, int>(0);
```
At every step I've leveraged the same monad: `EitherAsync`.  By staying in that context, or converting to it (in the case of the `Option` that becomes a `EitherAsync`), it makes composing each piece very simple.  Only at the last minute do I drop out of that context, and that's to get the final `Task<IActionResult>`.  I've leveraged the built-in control-flow features of the type to make the clutter go away.

Now, you may argue that there's a lot more typing there, but that's mostly to create those reusable components.  It could be this:
```c#
public Task<IActionResult> UpdateConfigMapping(int targetConfigId, int? flowConfigId) =>
    (from _1 in flowConfigId.Map(_flowRepository.GetFlowConfigAsync)
                            .IfNone(RightAsync<Error, int>(0))
     from _2 in _flowRepository.UpdateFlowConfigMappingAsync(targetConfigId, flowConfigId)
     from _3 in _flowRepository.SaveChangesAsync()
     select unit)
    .Respond();
```
Which is pretty concise ;)

**Comment by louthy** [comment]
By the way, you could do this with `Task` too:

So, if `FlowRepo` only returns tasks:
```c#
public class FlowRepo
{
    public Task<Unit> UpdateFlowConfigMappingAsync(int targetConfigId, int? flowConfigId) =>
        Task.FromResult(unit);

    public Task<int> GetFlowConfigAsync(int flowConfigId) =>
        Task.FromResult(1);

    public Task<Unit> SaveChangesAsync() =>
        Task.FromResult(unit);
}
```
And `Task<A>` had some extensions:
```c#
public static class TaskExtensions
{
    static IActionResult NoContent() => null;
    static IActionResult BadRequest(Error err) => null;
    static IActionResult Ok<A>(A value) => null;

    public static async Task<IActionResult> Respond(this Task<Unit> ma)
    {
        try
        {
            await ma;
            return NoContent();
        }
        catch(Exception e)
        {
            return BadRequest(Error.New(e));
        }
    }

    public static async Task<IActionResult> Respond<A>(this Task<A> ma)
    {
        try
        {
            var value = await ma;
            return Ok(value);
        }
        catch(Exception e)
        {
            return BadRequest(Error.New(e));
        }
    }
}
```
Then this would work the same as the `EitherAsync` example:
```c#
public Task<IActionResult> UpdateConfigMapping(int targetConfigId, int? flowConfigId) =>
    (from _1 in Optional(flowConfigId).Map(_flowRepository.GetFlowConfigAsync).IfNone(0.AsTask())
     from _2 in _flowRepository.UpdateFlowConfigMappingAsync(targetConfigId, flowConfigId)
     from _3 in _flowRepository.SaveChangesAsync()
     select unit)
    .Respond();

```
```
