### ISSUE TITLE
Example with Writer/Validation working together (logging)

### ISSUE THREAD

**Issue by andreabioli** [louthy/language-ext#678]
I still don't totally understand the Prelude.tell inner workings, but I would like to use a Writer with the Validation, to collect logging information.
Is there anyone willing to provide a good starting point?
Thanks in advance.
Andrea

**Comment by andreabioli** [comment]
I clarify better: the examples I see maintain the same type when used inside a LINQ query.
When using Validation, there's a generic type parameter, because we have Validation<Error, T>, with T changing (potentially) at each call. 
I cannot make Writer (tell) work, in this case. Is it even possible?
Thanks again.
Andrea

**Comment by louthy** [comment]
Writer and Validation are different monadic types and therefore can’t be composed.  If you need the functionality of both then you’d need to build a bespoke type that combines the behaviours of both

**Comment by andreabioli** [comment]
Thank you for your quick answer, as usual. I expected something like that...
Do you think it's difficult, for my (still) limited experience on FP?

**Comment by louthy** [comment]
It's certainly not a trivial type to build generically.  Building something more bespoke for your needs would be less problematic (i.e. if you don't use monoids for the writer output and also for the validation fails).  You'd need to understand the applicative behaviour as well as the monadic behaviour of the validation type too. 

It's all there in the source for the Validation and Writer types, it's really a case of combining the functionality.

This is something that will hopefully be much easier to do in future lang-ext versions, as I'm working on a general 'monad builder' that'll allow you to pick-n-choose which features of the core monads you require and the code-gen will build it for you in to a new type.  For example, an asynchronous, writer, with an alternative value (so, taking the logic of `Task<A>`, `Writer<W, A>`, and `Either<L, R>`).

But that's not likely to happen super fast, it'll be pretty complicated to build.

**Comment by louthy** [comment]
Here's the fully generic version in gist form (I haven't done much testing on it):

https://gist.github.com/louthy/7f8f2228a0ddacaa1cf2505412dc0a81

I would advise you to take that and make a bespoke one that doesn't need the `W` and `FAIL` types providing (and therefore it won't need the `MonoidW` and `MonoidFail` types either).  It would be much more manageable then.

**Comment by andreabioli** [comment]
Hey man, you are the one! :-) If you wrote all of that for me, I have to at least offer you a beer! I'm in London as well! :-)
Really thank you, I have to study, now! :-)
