### ISSUE TITLE
Option OrElse?

### ISSUE THREAD

**Issue by bgrounds** [louthy/language-ext#683]
Fantastic library!

I've been porting a Haskell application I wrote at work into C#, and this library has allowed me to maintain the same overall application structure!

I'm currently working on the `With` function for a "record" (class) containing many optional values (I'd use the lenses, but I'm very new to C# and haven't figured out how to get the codegen working yet - may not be using a compatible version of dotnet core).

Here's a simplified version of a `With` method I've written for my `X` class:
```cs
public X With(Option<AType> a = default, Option<BType> b = default) =>
    new X(a: a.OrElse(AValue), b: b.OrElse(BValue));
```
(AType, BType, and X are all concrete types, not generic type parameters. The class contains AValue and BValue members, which is why I can pass those to `OrElse`)

But I had to write my own `OrElse` function:
```cs
public static Option<A> OrElse<A>(this Option<A> optionalValue, Option<A> defaultValue) =>
    optionalValue.IsSome ? optionalValue : defaultValue;
```

This `OrElse` function was inspired by this:
https://hackage.haskell.org/package/syb-0.7.1/docs/Data-Generics-Aliases.html#v:orElse
And is also found under the name `firstJust` here:
https://hackage.haskell.org/package/ghc-8.6.5/docs/Maybes.html#v:firstJust

Is `OrElse` a function you'd consider adding to language-ext, or would you recommend an alternative solution?

**Comment by louthy** [comment]
Make the Options nullable, then only assign if not null.  Take a look at my Stackoverflow answer for how

https://stackoverflow.com/questions/38575646/general-purpose-immutable-classes-in-c-sharp/38596298#38596298

**Comment by louthy** [comment]
Also, there’s an IfNone method to get a concrete value out of the option, or a || or operator to do value coalescing

**Comment by bgrounds** [comment]
Thanks for the quick response!

Looks like `||` is exactly `OrElse`. I hadn't noticed it before, but that'll work perfectly.

Do you see any reason to prefer one of the following two definitions?

```cs
    public X With(Option<AType> a = default, Option<BType> b = default) =>
        new X(a: a || AValue, b: b || BValue);
```

```cs
    public X With(Option<AType>? a = null, Option<BType>? b = null) =>
        new X(a: a ?? AValue, b: b ?? BValue);
```

The Haskeller in me wants to avoid nulls and so leans to the former, but I'm not sure if there's a practical reason to prefer the latter.

**Comment by bgrounds** [comment]
Hmm.. I guess the former definition doesn't allow a caller to set a member value to `None`, and the latter does.

So if I want the ability to reset `Some(BValue)` to `None`, I'd need the latter definition.
