### ISSUE TITLE
Difference between Seq<A> and Lst<A>

### ISSUE THREAD

**Issue by qwas368** [louthy/language-ext#687]
Like louthy said 「I prefer it over `Lst<A>` for all list like operations other than where mid-sequence inserts/removals are required.」in [issues 558](https://github.com/louthy/language-ext/issues/558).

I try to write sample code to prove that both are idempotent.
```c#
// idempotent test
var a = Seq("1", "2", "3").Select(x => { Console.WriteLine(x); return unit; });
var b = List("a", "b", "c").Select(x => { Console.WriteLine(x); return unit; });

a.Count();
a.Count();
b.Count();
b.Count();

// Output:
// 1
// 2
// 3
// a
// b
// c
```
So ... it seems that `Lst<A>`  is useful than `Seq<A>` ? 
I don't think the only difference is inserts/removals function, but I don't know other difference ...
Is there any comparison table ? And how to choice when you are programming ?

**Comment by louthy** [comment]
> I don't think the only difference is inserts/removals function, but I don't know other difference ...

Always choose `Seq<A>` over `Lst<A>` unless you need mid-sequence inserts or removals.  The main reason for this preference is that `Seq<A>` is much faster than `Lst<A>` at all the operations _it_ does.  

`Seq<A>` is represented internally by a growing array (like the .NET `List<T>`).  This has a number of performance benefits in terms of helping avoid cache misses, simplification of iteration, faster indexing etc.  

`Lst<A>` uses an AVL tree to allow for random inserts and removals.  It is very fast, but nowhere near as fast as `Seq<A>`.  

I could add `Insert` and `Remove` to `Seq<A>` but then the performance wouldn't be particularly good.  If you take a look at the [Performance wiki page](https://github.com/louthy/language-ext/wiki/Performance) you'll see the `Insert(0, x)` for the .NET `List<T>` is 10320 ns; whereas `Cons` on `Seq<A>` - which is like `Insert(0,x)` - is 20 ns.  It gets worse as the collection size grows.

`Seq<A>` would have a similar slow insert speed if I implemented for any point in the sequence.  This is the kind of performance loss that is hidden by the interface I think - there is an expectation that insert is fast, and so to keep the type _honest_ I decided to not add those features to `Seq<A>`.  Especially when there's an alternative in `Lst<A>`.

And so, that should be the only reason you decide to pick `Lst<A>` over `Seq<A>`.  I will add this information to the `README.md` at some point.

> There is one caveat and that is that if you initialise `Seq<A>` with a lazy `IEnumerable` then it too will be lazy.  You should call `seq.Strict()` if you want to force evaluation.

**Comment by qwas368** [comment]
It’s clear ! Thanks for your detailed answer.
