### ISSUE TITLE
How to handle state in a event trigger program ?

### ISSUE THREAD

**Issue by qwas368** [louthy/language-ext#688]
I know that state monad can use to handle state by returning an updated state.
But most case in my job, we use event trigger, message bus and mediator pattern a lot.
Like below example, `Handler` is a entry point and some events trigger them.
How to use state monad and avoid side-effects? Or I shouldn't struggle with this issue because it's not worth it ?

```csharp
namespace Application
{
    static class Robot
    {
        public enum RobotStateEnum
        {
            Up,
            Down,
            Unknown
        }

        public static RobotStateEnum state = RobotStateEnum.Unknown;
    }

    public class Robot_Up : INotification { }

    public class Robot_Down : INotification { }

    public class Robot_Up_Handler : INotificationHandler<Robot_Up>
    {
        public Task Handle(Robot_Up notification, CancellationToken cancellationToken)
        {
            Robot.state = Robot.RobotStateEnum.Up; // change state
            // Do something
            return Task.CompletedTask;
        }
    }

    public class Robot_Up_Handler2 : INotificationHandler<Robot_Up>
    {
        public Task Handle(Robot_Up notification, CancellationToken cancellationToken)
        {
            // Do something
            return Task.CompletedTask;
        }
    }

    public class Robot_Down_Handler : INotificationHandler<Robot_Down>
    {
        public Task Handle(Robot_Down notification, CancellationToken cancellationToken)
        {
            Robot.state = Robot.RobotStateEnum.Down; // change state
            // Do something
            return Task.CompletedTask;
        }
    }
}
```

**Comment by louthy** [comment]
It's obviously hard to make any judgement based on what you've posted.  Although, there are a few red-flags that I'd personally try refactoring if it were my project:

* Global mutable state in the `Robot` type.  Even if your _real_ application doesn't work this way, the examples in the code are directly modifying it, which would be a concern.  This causes dependency problems throughout your code; it's better to use pure functions instead.
* The various notification classes are essentially a discriminated union, and so you could leverage that idea and build a data model around that.

So, thinking of the data first, you have and event which can be an instruction to do something `MoveUp | MoveDown | ...` and a state of the robot which is `Up | Down`.  So, something like this to represent the data model in your code:

```c#
/// <summary>
/// State
/// </summary>
public abstract class RobotState
{
    public enum Tag
    {
        Unknown,
        Up,
        Down
    }

    public Tag Type;

    public RobotState(Tag type) =>
        Type = type;

    public class Unknown : RobotState { public Unknown() : base(Tag.Unknown) { } }
    public class Up : RobotState { public Up() : base(Tag.Up) { } }
    public class Down : RobotState { public Down() : base(Tag.Down) { } }
}

/// <summary>
/// Single event
/// </summary>
public abstract class RobotEvent
{
    public enum Tag
    {
        MoveUp,
        MoveDown
    }

    public Tag Type;

    public RobotEvent(Tag type) =>
        Type = type;

    public class MoveUp : RobotEvent { public MoveUp() : base(Tag.MoveUp) { } }
    public class MoveDown : RobotEvent { public MoveDown() : base(Tag.MoveDown) { } }
}
```
Obviously, if you're using the `LanguageExt.CodeGen` then these can be generated automatically like so:
```c#
[Union]
public interface RobotEvent
{
    RobotEvent MoveUp();
    RobotEvent MoveDown();
}

[Union]
public interface RobotState
{
    RobotState Up();
    RobotState Down();
}
```
Next, we need to have a pure/referentially-transparent way of working with the robot.  So, we should split the logic out of the notification handlers:
```c#
/// <summary>
/// Module like class for handling robot interactions
/// </summary>
public static class Robot
{
    /// <summary>
    /// Initialises a state monad with the previous state and runs the event inbox
    /// </summary>
    public static RobotState Inbox(RobotState state, RobotEvent e) =>
        put(state).Bind(_ => Inbox(e)).Run(state).Item2;

    /// <summary>
    /// Main event inbox that distributes the event to the action functions
    /// </summary>
    static State<RobotState, Unit> Inbox(RobotEvent e) =>
        e switch
        {
            RobotEvent.MoveUp up     => MoveUp,
            RobotEvent.MoveDown down => MoveDown,
            _                        => from _ in get<RobotState>()
                                        select unit
        };

    /// <summary>
    /// Move up action - moves up if it's not currently up
    /// </summary>
    static readonly State<RobotState, Unit> MoveUp =
        from s in get<RobotState>()
        from _ in s is RobotState.Up 
            ? put(s)
            : put<RobotState>(new RobotState.Up())
        select unit;

    /// <summary>
    /// Move down action - moves down if it's not currently down
    /// </summary>
    static readonly State<RobotState, Unit> MoveDown =
        from s in get<RobotState>()
        from _ in s is RobotState.Down
            ? put(s)
            : put<RobotState>(new RobotState.Down())
        select unit;
}
```
This has one `public static` function which tells you everything you need to know:
```c#
    RobotState Inbox(RobotState state, RobotEvent e)
```
An event and some state is passed in and we get a new state out.

This looks very much like the `Fold` signature: `S Fold<S, A>(S state, F<S, A, S> f)`.  The intuition here is that we're working with a _stream_ of events that has an aggregate effect on the state over time.

That means we could use an `IObservable<RobotEvent>` from `Rx.NET` for example, or create an actor using the [`Echo.Process` system](https://github.com/louthy/echo-process/) (which is another of my open-source projects, and it's built for situations like this.

But, just as an example, I'll keep some global data, but make it safe:
```c#
/// <summary>
/// Thread-safe global state
/// </summary>
public static class RobotGlobal
{
    public static readonly Atom<RobotState> State =  Atom<RobotState>(new RobotState.Unknown());
}
```
The handlers can then look like this:
```c#
public Task Handle(Robot_Up notification, CancellationToken cancellationToken)
{
    RobotGlobal.State.Swap(s => Robot.Inbox(s, new RobotEvent.MoveUp()));
    return Task.CompletedTask;
}
```
You don't have to use the state monad.  It looks like you want to work with `async` and so you may want to consider writing your own state monad that also leverages `Task`.  Something like this:
```c#
public delegate Task<(RobotState State, A Value)> MRobot<A>(RobotState state);

public static class MRobot
{
    public static MRobot<A> Return<A>(A value) =>
        state => Task.FromResult((state, value));

    public static MRobot<A> Return<A>(Task<A> value) =>
        async state => (state, await value);

    public static MRobot<Unit> put(RobotState state) =>
        _ => Task.FromResult((state, unit));

    public static MRobot<RobotState> get =>
        state => Task.FromResult((state, state));

    public static MRobot<Unit> modify(Func<RobotState, RobotState> f) =>
        get.Map(f).Bind(put);

    public static MRobot<B> Bind<A, B>(this MRobot<A> ma, Func<A, MRobot<B>> f) => async state =>
    {
        var (s, a) = await ma(state);
        return await f(a)(s);
    };

    public static MRobot<B> Map<A, B>(this MRobot<A> ma, Func<A, B> f) =>
        Bind(ma, x => Return(f(x)));

    public static MRobot<B> Select<A, B>(this MRobot<A> ma, Func<A, B> f) =>
        Bind(ma, x => Return(f(x)));

    public static MRobot<B> SelectMany<A, B>(this MRobot<A> ma, Func<A, MRobot<B>> f) => 
        Bind(ma, f);

    public static MRobot<C> SelectMany<A, B, C>(this MRobot<A> ma, Func<A, MRobot<B>> bind, Func<A, B, C> project) =>
        ma.Bind(a => bind(a).Map(b => project(a, b)));
}
```
Your robot class could then look like this:
```c#
/// <summary>
/// Module like class for handling robot interactions
/// </summary>
public static class Robot
{
    /// <summary>
    /// Initialises a state monad with the previous state and runs the event inbox
    /// </summary>
    public static async Task<RobotState> Inbox(RobotState state, RobotEvent e) =>
        (await (from _ in MRobot.put(state)
                from r in Inbox(e)
                select r)(state))
                .State;

    /// <summary>
    /// Main event inbox that distributes the event to the action functions
    /// </summary>
    static MRobot<Unit> Inbox(RobotEvent e) =>
        e switch
        {
            RobotEvent.MoveUp up     => MoveUp(up),
            RobotEvent.MoveDown down => MoveDown(down),
            _ => from _ in MRobot.get select unit
        };

    /// <summary>
    /// Move up action - moves up if it's not currently up
    /// </summary>
    static readonly MRobot<Unit> MoveUp =
        from s in MRobot.get
        from _ in s is RobotState.Up
            ? MRobot.put(s)
            : MRobot.put(new RobotState.Up())
        select unit;

    /// <summary>
    /// Move down action - moves down if it's not currently down
    /// </summary>
    static readonly MRobot<Unit> MoveDown =
        from s in MRobot.get
        from _ in s is RobotState.Down
            ? MRobot.put(s)
            : MRobot.put(new RobotState.Down())
        select unit;
}
```
Then your handler methods will work properly with tasks:
```c#
public Task Handle(Robot_Up notification, CancellationToken cancellationToken) =>
    RobotGlobal.State.SwapAsync(s => Robot.Inbox(s, new RobotEvent.MoveUp()));
```
> Or I shouldn't struggle with this issue because it's not worth it ?

It's always worth factoring code like this.  It makes all future development easier.  It may take a few mental leaps to get out of OO-mode, but once you do you'll start making real productivity gains.  For example you can now trivially compose robot movements:
```c#
            static MRobot<Unit> MoveUpAndDown =
                from a in MoveUp
                from b in MoveDown
                select unit;
```
Also, at a later date you could modify your `MRobot` monad to not actually perform any IO and instead return a set of actions to perform.  Those resulting actions can be run by an interpreter.  

That means you could have a _unit test interpreter_ and a _real world interpreter_ (See the [banking app sample](https://github.com/louthy/language-ext/tree/master/Samples/BankingAppSample) to see how this is done), creating true separation of concerns.  

What's great is you don't need to make that call now, you can just update your `MRobot` monad later if that's the approach you want to take.

**Comment by qwas368** [comment]
Thanks for detailed explanation and sample code. I have a further problem.
Why use __Discriminated Union__ instead of __Enum__ ?  I know __Discriminated Union__ have sum  and product type, but  __Enum__ is more friendly for me. Should I use __Discriminated Union__ in all case or not?
In this case, it seems like they are no different ... 
```csharp
// Discriminated Union
public abstract class RobotEvent
{
    public class MoveUp : RobotEvent { public MoveUp() { } }
    public class MoveDown : RobotEvent { public MoveDown() { } }
}
// Enum
public enum RobotEventEnum
{
    MoveUp,
    MoveDown
}
```

**Comment by orthoxerox** [comment]
@qwas368 

1. enums are not guaranteed to be restricted to the variants you've defined, `(RobotEventEnum)42` is a valid enum value
2. DUs can have properties, e.g.,  `MoveUp(int distance)`

**Comment by louthy** [comment]
> Why use Discriminated Union instead of Enum

What @orthoxerox says is exactly right.  My assumption was that your example was a minimal version of what your code actually does, I assumed you'd need more information in your state machine and your events.  An `enum` is sufficient if you don't need to carry more data around (and you don't do silly things like `(RobotEventEnum)42`.

> I know Discriminated Union have sum and product type

Sum-types, not product-types.  Product-types are records (and tuples), sum-types are discriminated-unions.  I have written [a short wiki article on this](https://github.com/louthy/language-ext/wiki/What-are-Discriminated-Unions%3F)

**Comment by louthy** [comment]
@qwas368 Another thing you could do if you go with your own `MRobot` monad is to stick an environment in with actions for performing the IO (i.e. really talking to the robot):

```c#
    public interface Env
    {
        MRobot<RobotState> WhereAreYou();
        MRobot<Unit> MoveRobotUp();
        MRobot<Unit> MoveRobotDown();
    }
```
Then the `delegate` can be updated to take an `Env`:
```c#
    public delegate Task<(RobotState State, A Value)> MRobot<A>(Env Env, RobotState state);
```
With some minor tweaks to `MRobot`, you get:
```c#
    public static class MRobot
    {
        public static MRobot<A> Return<A>(A value) =>
            (env, state) => Task.FromResult((state, value));

        public static MRobot<A> Return<A>(Task<A> value) =>
            async (env, state) => (state, await value);

        public static MRobot<Unit> put(RobotState state) =>
            (env, _) => Task.FromResult((state, unit));

        public static MRobot<RobotState> get =>
            (env, state) => Task.FromResult((state, state));

        public static MRobot<Unit> modify(Func<RobotState, RobotState> f) =>
            get.Map(f).Bind(put);

        public static MRobot<B> Bind<A, B>(this MRobot<A> ma, Func<A, MRobot<B>> f) => async (env, state) =>
        {
            var (s, a) = await ma(env, state);
            return await f(a)(env, s);
        };

        public static MRobot<B> Map<A, B>(this MRobot<A> ma, Func<A, B> f) =>
            Bind(ma, x => Return(f(x)));

        public static MRobot<B> Select<A, B>(this MRobot<A> ma, Func<A, B> f) =>
            Bind(ma, x => Return(f(x)));

        public static MRobot<B> SelectMany<A, B>(this MRobot<A> ma, Func<A, MRobot<B>> f) =>
            Bind(ma, f);

        public static MRobot<C> SelectMany<A, B, C>(this MRobot<A> ma, Func<A, MRobot<B>> bind, Func<A, B, C> project) =>
            ma.Bind(a => bind(a).Map(b => project(a, b)));

        public static MRobot<Env> ask =
            (env, state) => Task.FromResult((state, env));

        public static MRobot<Unit> moveRobotUp =
            from e in ask
            from r in e.MoveRobotUp()
            from _ in put(new RobotState.Up())
            select r;

        public static MRobot<Unit> moveRobotDown =
            from e in ask
            from r in e.MoveRobotDown()
            from _ in put(new RobotState.Down())
            select r;

        public static MRobot<RobotState> whereAreYou =
            ask.Bind(env => env.WhereAreYou());
    }
```
> NOTE: `ask`, `moveRobotUp`, `moveRobotDown`, and `whereAreYou` are all ways with interacting with the real environment.

And then your `Robot` event handlers look like this:
```c#
    /// <summary>
    /// Module like class for handling robot interactions
    /// </summary>
    public static class Robot
    {
        /// <summary>
        /// Initialises a state monad with the previous state and runs the event inbox
        /// </summary>
        public static async Task<RobotState> Inbox(Env environment, RobotState state, RobotEvent e) =>
            (await (from _ in MRobot.put(state)
                    from r in Inbox(e)
                    select r)(environment, state))
                    .State;

        /// <summary>
        /// Main event inbox that distributes the event to the action functions
        /// </summary>
        static MRobot<Unit> Inbox(RobotEvent e) =>
            e switch
            {
                RobotEvent.MoveUp up     => MoveUp,
                RobotEvent.MoveDown down => MoveDown,
                _ => from _ in MRobot.get select unit
            };

        /// <summary>
        /// Move up action - moves up if it's not currently up
        /// </summary>
        static readonly MRobot<Unit> MoveUp =
            from s in MRobot.whereAreYou
            from _ in s is RobotState.Up
                ? MRobot.put(s)
                : MRobot.moveRobotUp
            select unit;

        /// <summary>
        /// Move down action - moves down if it's not currently down
        /// </summary>
        static readonly MRobot<Unit> MoveDown =
            from s in MRobot.whereAreYou
            from _ in s is RobotState.Down
                ? MRobot.put(s)
                : MRobot.moveRobotDown
            select unit;
    }
```
That makes it much easier to build unit tests for your robot and to have purity in the implementation.

**Comment by qwas368** [comment]
`MRobot` monad is very complex for me. I only know how to use but not implement. It's compose of `Reader`, `State` and `Async`, right ?
Furthermore, if I want to control many robots, should I modify `MRobot` like this:
```csharp
public delegate Task<(RobotState State, A Value)> MRobot<A>(IEnumerable<Env> Env, RobotState state);

public static class MRobot
{
   // some magic which I don't know how to implement :(
}
```

Then use `MRobot` like this:

```csharp
static async Task Main(string[] args)
{
    Seq<ConcreteEnv> robots = Seq(new ConcreteEnv(robotName: "robot_One"), new ConcreteEnv(robotName: "robot_Two"));

    var robotsStatus = (await (from _ in MRobot.moveRobotUp
                               from g in MRobot.whereAreYou
                               select g)
                        (robots, RobotState.Unknown))
                        .Value
                        .Zip(robots.Select(x => x.RobotName));

    Console.WriteLine(string.Join(", ", robotsStatus.Select(x => $"{x.Item2} State is {x.Item1}")));

    // Output: robot_One State is Up, robot_Two State is Up
}
```
or use `Seq` directly : 
```csharp
static async Task Main()
{
    Seq<ConcreteEnv> robots = Seq(new ConcreteEnv(robotName: "robot_One"), new ConcreteEnv(robotName: "robot_Two"));

    var moveUpAndWhere = from _ in MRobot.moveRobotUp
                         from g in MRobot.whereAreYou
                         select g;

    var robotsStatus = (await robots
        .Select(robot => moveUpAndWhere(robot, RobotState.Unknown))
        .Sequence())
        .Zip(robots.Select(x => x.RobotName));

    Console.WriteLine(string.Join(", ", robotsStatus.Select(x => $"{x.Right} State is {x.Left.State}")));
    // Output: robot_One State is Up, robot_Two State is Up
}
```

As a FP beginner, I am not sure which one is correct or depends on the situation ?

**Comment by louthy** [comment]
Ok, so a quick run-down on what we have here:

* `MRobot<A>` is a _monad_ and a _functor_
* Monads and functors _wrap_ a _bound value_ `A` with special behaviours.  So, it can be seen as a container of `A` with _some additional stuff for free_
* It is a monad because it implements the `M<B> Bind(M<A>, A -> M<B>)` and `M<A> Return(A)` functions
* It is a functor because it implements the `M<B> Map(M<A>, A -> B)` function
* `Return` is used to construct a new monad `M<A>` from an `A`
* `Bind`, `Map`, and `Return` are used to implement `Select` and `SelectMany` - this makes `MRobot<A>` work with LINQ for maximum ease of composition
* `MRobot<A>` is also a _state monad_ which means it threads some _state value_ through the computation.
   * The `get` and `put(x)` are the way of getting at the state from within the computation and use it as the _bound value_
* `MRobot<A>` is also a _reader monad_ which means it threads through some _environment value_, which represents the _state of the world_ just before the computation started.  This allows the `MRobot<A>` behaviour to work in an entirely pure way, only relying on the information it is given, and never interacting with the outside world (obviously we are moving a robot, but there is an abstraction from the robot interaction, maintaining purity).  The environment value can be used as the _bound value_ by using `ask`.
* After this you don't really need much else other than to compose behaviours. 

So, you're right, `MRobot<A>` a is a composition of `Reader`, `State` and `async`.  If the `RWS` code-gen supported `async` then you could have built it like so:
```c#
    [RWS(WriterMonoid: typeof(MUnit), Env: typeof(Env), State: typeof(RobotState))]
    public partial struct MRobot<A>
    {
    }
```
> The ability to build monads from the various features required is coming soon with the _monad builder_ code-gen I am working on.  But, for now you'll need to manage it yourself.

The key thing to look at here is that `MRobot<A>` (in my examples earlier, not the code-gen'd version) is just a `delegate`:
```c#
public delegate Task<(RobotState State, A Value)> MRobot<A>(Env Env, RobotState state);
```
Everything is about composition.  We are composing functions with other functions to make more complex functions.  It just so happens that the functions we're composing follow some rules that make them fit into the functor and monad laws, but they are all still just regular functions.

So, it's a function that takes an `Env` and a `RobotState` and returns a `RobotState` and an `A` - the _bound value_.  And, so anything you write, that follows that pattern, can be used to make code that works with the `MRobot<A>` monadic functionality.

If you take a look at `Return`, you can see those delegates being built:
```c#
        public static MRobot<A> Return<A>(A value) =>
            (env, state) => Task.FromResult((state, value));

        public static MRobot<A> Return<A>(Task<A> value) =>
            async (env, state) => (state, await value);
```
Then something like `put`, which sets a new state, is simply ignoring the existing state (the underscore) and returning the new one:
```c#
        public static MRobot<Unit> put(RobotState state) =>
            (env, _) => Task.FromResult((state, unit));
```
The `get`, which gets the state and makes it into the _bound value_, simply copies it into the second part of the tuple `(state, **state**)`:
```c#
        public static MRobot<RobotState> get =>
            (env, state) => Task.FromResult((state, state));
```
`Bind`, which is where the _'magic'_ happens, first runs the monad `ma` with the arguments from the `delegate`:
```c#
var (s, a) = await ma(env, state);
```
`(s, a)` is the new state and bound value.  Then it runs the new bound value through the provided bind function `f`, which returns a new `MRobot<B>`:
```c#
   f(a)
```
Which we then run by applying `(env, s)` to the result.  So, that threads the updated _state value_ through the computation, and threads the same _environment value_ through also.

This effectively _chains_ two operations together (composes them into a new more complex operation).  So, the result of `Bind` is the result of composing two monads into one.  But, it is _still just function composition_.

> Furthermore, if I want to control many robots, should I modify MRobot like this:

It depends what you mean by control.  Because, in your earlier requirements, you had one robot that listened to events, but this new requirement seems to not take into account events at all and just runs in `Main`.  So, it would be good to know what the end goal is.

The existing `MRobot<A>` has `RobotState` built-in, which means it is for managing a single robot only.  There are a number of ways you could go, but it would depend on the end goals:

1. Make `MRobot<S, A>` instead, so the state is explicit, this would allow for `MRobot<Seq<RobotState>, A>`
2. Create another new monad called `MRobots<A>` which internally manages a collection of `RobotState` values and then invokes the `MRobot<A>` computation needed.

The second one would be what I suspect would be best for you, but I don't know enough about your requirements to make a call.  Something like:

```c#
    public class MRobots<A>
    {
        public readonly A Value;
        public readonly HashMap<RobotId, RobotState> States;

        MRobots(A value, HashMap<RobotId, RobotState> states) =>
            States = states;

        public static MRobots<Unit> Setup(Seq<RobotId> ids) =>
            new MRobots<Unit>(default, ids.Map(id => (id, new RobotState.Unknown() as RobotState)).ToHashMap());

        // logic needed to manage N robots
    }
```
The reason I suggest this, is because a lot of people use this library think that monads begin and end with `Option` or the other in-built monads.  But, in fact, bespoke monads that capture a _sub-domain_ within your application are awesome.  So, we currently have a `MRobot` monad that captures all the rules of one robot, if you then build layers of monads around it for managing `N` robots then you have built a system that separates concerns and captures the domain, this is good for architecting complex solutions and can enforce control flow extremely well.

**Comment by qwas368** [comment]
Thanks for your detail explanation! I need more practice, now. :)
> The reason I suggest this, is because a lot of people use this library think that monads begin and end with Option or the other in-built monads.

You are right. The reason is we don't need to reinvent the wheel. We can use `Option` such as `IEnumerable`.
