### ISSUE TITLE
Happy new year!

### ISSUE THREAD

**Issue by louthy** [louthy/language-ext#689]
Happy new year to you all!  I hope the ~~2010s~~ 2020s are good to you and your families 👍 

I have closed down some issues that it was unlikely I am going to deal with.  If those any of those issues were yours and you feel strongly about them, then please reopen with a message that you still care :)

**Comment by MrYossu** [comment]
@louthy Thanks for the good wishes, and for all the effort you put into helping us all.

By the way, shouldn't it be the 2020s, we are just finishing the 2010s aren't we?

**Comment by louthy** [comment]
> By the way, shouldn't it be the 2020s, we are just finishing the 2010s aren't we?

Heh, yeah, maybe I'm hoping we can write off the 2010s and start again ;-)

**Comment by MrYossu** [comment]
> Heh, yeah, maybe I'm hoping we can write off the 2010s and start again ;-)

:)
