### ISSUE TITLE
TryEither/TryEitherAsync

### ISSUE THREAD

**Issue by richbryant** [louthy/language-ext#690]
There are a few cases where a construct Success/Failure/Error would be extremely useful.  Authentication springs to mind.

Are there plans for anything along these lines or how do I go about producing a similar result?

**Comment by louthy** [comment]
@richbryant I don't have any immediate plans to do this, but you can use `Try<Either<L, R>>` and `TryAsync<EitherAsync<L, R>>` and then build some extension methods to help with the matching.

Another way would be to just jump in to `TryOption` and `TryOptionAsync` and then adapt them to support the nested `Either` state.  The `None` state would become `Left`.  I'd accept a PR if you're willing to do it, but it would need to implement everything the other key types do (using `TryOption` as a reference would be good here).

The main reason I built `TryOption` in the first place was to have at least one type that captured all possible outcomes of a method-call and turned them into a value:

* The expected result: `A`
* `None` (when returning reference types)
* `Exception` (if something throws whilst running)

So, you see it's the _one true type the rule them all_ when trying to capture outcomes of C# functions, other _transformer_ types weren't super high on the agenda, and probably the missing `*Async` variants would be higher up on my list before moving onto something like `TryEither`.
