### ISSUE TITLE
Is (a, b) => (a, b) defined?

### ISSUE THREAD

**Issue by bender2k14** [louthy/language-ext#694]
Does Language Ext contain a function of type `Func<A, B, (A, B)>` naturally implemented as `(a, b) => (a, b)`?

**Comment by louthy** [comment]
It’s unclear whether (a, b) => (a, b) would be Func<(a, b), (a, b)>, or Func<a, b, (a, b)>

Either way, both functions exist, they’re called Prelude.identity and Prelude.VTuple<A, B>

**Comment by bender2k14** [comment]
I was looking for `Prelude.VTuple<A, B>`, which is here:
https://github.com/louthy/language-ext/blob/c412a962fac7110845b80d0f80a467cc929637ff/LanguageExt.Core/DataTypes/ValueTuple/ValueTuple.Prelude.cs#L26-L27

Thanks! :)
