### ISSUE TITLE
None when returned is converted to Some(None)

### ISSUE THREAD

**Issue by MercedeX** [louthy/language-ext#695]
I have a chain of functions which have the same signature 
```

Option<object> getNext(){
.. // some code
  return getInnernext();
}

Option<object> getInnerNext(){
// some code
}
```

so whatever is returned from getInnerNext is returned by getNext() as Some(Some(x))) or Some(None). Even the Map() functions aren't really helping and for each function we have to do Match(). how do we avoid an Option becoming another Option when returned in chain,

**Comment by bender2k14** [comment]
```C#
var result = from next in getNext()
                     from innerNext in getInnerNext()
                     select foo(next, innerNext)
```

**Comment by louthy** [comment]
I think your biggest issue here is that `object` is the bound value, which means `Some(x)` is valid as the value.  This is expected behaviour.  I guess the first question is why are you using `object`?
