### ISSUE TITLE
Add Validation<,Validaiton<,>>.Flatten() and/or more ValueTuple<Validation<,>>.Sequence()

### ISSUE THREAD

**Issue by bender2k14** [louthy/language-ext#698]
I am heavily using `Validation<,>` right now to do some encoding and decoding (of binary data), and I am running into some missing functions.  I can explain via the existing validation test code.

-------------------

Consider this part of the validation test code.
https://github.com/louthy/language-ext/blob/2cc42b424ac44417d8b09fa61b270426d9ee95b0/LanguageExt.Tests/ValidationTests.cs#L267-L270

This code is not ideal because it only returns a validation error for `expMonth` when it is invalid even when `expYear` is also invalid.

My first instinct is to refactor this code to...
```C#
var monthYear =
    (ToInt(expMonth).Bind(ValidMonth),
     ToInt(expYear).Bind(PositiveNumber)
    ).Apply((m, y) => validToday(m, y))
     .Flatten(); // not defined
```
...but `Flatten()` isn't defined for `Validation<,>`.

My second instinct is to refactor this code to...
```C#
var monthYear =
    (ToInt(expMonth).Bind(ValidMonth),
     ToInt(expYear).Bind(PositiveNumber)
    ).Sequence()
     .Bind(t =>
     {
         var (m, y) = t;
         return validToday(m, y);
     });
```
...which works in this case because `Validation<,(,)>.Sequence()` is defined in ValueTuple2.Extensions.cs:
https://github.com/louthy/language-ext/blob/2cc42b424ac44417d8b09fa61b270426d9ee95b0/LanguageExt.Core/DataTypes/ValueTuple/Tuple2/ValueTuple2.Extensions.cs#L677-L678

However, in my case at work, I have a `ValueTuple` of arity seven.  There happens to be a file called [ValueTuple7.Extensions.cs](https://github.com/louthy/language-ext/blob/master/LanguageExt.Core/DataTypes/ValueTuple/Tuple7/ValueTuple7.Extensions.cs), but it doesn't contain the corresponding `Sequence()` extension method.

My third instinct is to refactor this code to...
```C#
var monthYear =
    (ToInt(expMonth).Bind(ValidMonth),
     ToInt(expYear).Bind(PositiveNumber)
    ).Apply(VTuple<int, int>)
     .Bind(t =>
     {
         var (m, y) = t;
         return validToday(m, y);
     });
```
...which works in my case because the function [`VTuple<,,,,,,>` (of arity seven) exists](https://github.com/louthy/language-ext/blob/2cc42b424ac44417d8b09fa61b270426d9ee95b0/LanguageExt.Core/DataTypes/ValueTuple/ValueTuple.Prelude.cs#L61-L62).  In fact, this form is how the arity-two `Sequence()` is implemented (after replacing the lambda expression `(a, b) => (a, b)` with the predefined function `VTuple<A, B>` (which [I only recently learned exists](https://github.com/louthy/language-ext/issues/694)!).

-----------

Can we add the missing `Flatten()` and `Sequence()` methods?

**Comment by louthy** [comment]
> Can we add the missing Flatten() and Sequence() methods

Seems reasonable if you want to do a PR
