### ISSUE TITLE
manyn is accepting fewer than expected matches if more than 1 away from n

### ISSUE THREAD

**Issue by Jmaharman** [louthy/language-ext#699]
I've found that manyn isn't failing if the input string isn't long enough to reach n by more than 1 away.

I added this test to ParsecTests and it fails:

```
[Fact]
public void ParseNTimesFailIfMoreThan1Away()
{
    var p = asString(manyn(digit, 4));

    var r = parse(p, "12").ToEither();
    Assert.True(r.IsLeft);
}
```

I believe it's all down to this line, although I can't understand why it's doing what it's doing to give any more pointers.

```
// eerr
return count == n
  ? ConsumedError<Seq<T>>(mergeError(error, t.Reply.Error))
  : EmptyOK(Seq(results), current, mergeError(error, t.Reply.Error));
```

P.S. Great library, thank you

**Comment by bender2k14** [comment]
FYI: I added a PR
