### ISSUE TITLE
Use IAsyncEnumerable for OptionAsync and EitherAsync

### ISSUE THREAD

**Issue by avonheimburg** [louthy/language-ext#701]
Option and Either already implement the IEnumerable interface. Since C# 8 has introduced the IAsyncEnumerable interface, it would make sense for OptionAsync and EitherAsync to implement that.

**Comment by louthy** [comment]
In principle this is a sound idea.  Does anyone know whether there are any backwards compatibility issues with .NET framework / older versions of C#?

At some point this year language-ext will migrate to .NET Core only - to start leveraging the newer features of C#.  But that won’t happen without a lot of advanced notice.

**Comment by colethecoder** [comment]
The async stream interfaces needed are .Net Standard 2.1 so anything below that (.Net Framework or older Core versions) needs: https://www.nuget.org/packages/Microsoft.Bcl.AsyncInterfaces/

**Comment by louthy** [comment]
Thanks Tom.  I’ll take a look when I get a chance

**Comment by louthy** [comment]
Released in [v3.4.0](https://github.com/louthy/language-ext/releases/tag/v3.4.0) for `netstandard 2.1` / `.NET Core 3` only
