### ISSUE TITLE
LanguageExt.CodeGen 3.3.49 nuget referencing alpha version of CodeGeneration.Roslyn.BuildTime

### ISSUE THREAD

**Issue by twaddell** [louthy/language-ext#702]
The Nuget Package for LanguageExt.CodeGen now has a dependency on a prerelease version of CodeGeneration.Roslyn.BuildTime.
`CodeGeneration.Roslyn.BuildTime (>= 0.7.5-alpha)`

In 3.3.48 the dependency is
`CodeGeneration.Roslyn.BuildTime (>= 0.6.1)`

I'd rather not include alpha packages and so don't have "Include Prerelese" ticked in my Nuget Package Manager. This results in me being unable to upgrade to 3.3.49. I would like to upgrade for the fix for #692 

Was this dependency bump deliberate for another fix? Or can LanguageExt reference "stable" versions of dependencies please.

**Comment by louthy** [comment]
Although `BuildTime` doesn't make it into your final build (as it's build-time only, not run-time); the alpha was added in error, so I have reverted it in `3.3.50`.
