### ISSUE TITLE
Could [Record] create a factory method (New)?

### ISSUE THREAD

**Issue by StefanBertels** [louthy/language-ext#704]
This is a feature request:

`NewType<>` gives us static `New` method and `[Union]` generates a `MyUnionTypeCon` factory for creating instances using a static method. `[Record]` just generates a constructor.

Can we have some static factory method with `[Record]`, e.g. `MyRecordType.New(....)`?

**Comment by louthy** [comment]
The only issue is possible clashes with field names, although I’d say this is the least problematic, so yes it seems reasonable.  The main reason for a separate static class was to make the use of generics easier, so perhaps non-generic Records could drop the static class and use New instead.

**Comment by louthy** [comment]
Just realised my mistake (sorry, our to lunch and wasn’t paying proper attention); ignore my comments about the static class, yes we can have a New method

**Comment by louthy** [comment]
Deployed in `v3.3.51`
