### ISSUE TITLE
Validation for record types

### ISSUE THREAD

**Issue by srivathsah** [louthy/language-ext#705]
First of all, thanks for an excellent library.

With the latest changes for record types codegen, is there any way of including optional validation when the fields/properties are assigned values ? This would be super powerful in using Records for domain modelling/value objects. Any guidance is highly appreciated

Eg:
[Record]
public partial class IP4Address
{
    public string Value{ get; }
}

for the above class, whenever the value is set via constructor or With, it is better to first validate

**Comment by louthy** [comment]
There currently isn’t a way to do this, but it’s on my list to think about possible solutions

**Comment by louthy** [comment]
https://github.com/louthy/language-ext/wiki/Frequently-Asked-Questions#why-doesnt-languageextcodegen-work
