### ISSUE TITLE
Pipe forward operator

### ISSUE THREAD

**Issue by blakeSaucier** [louthy/language-ext#711]
Hi,

I was wondering if there is any desire or interest to have a pipe forward operation implemented in this project. Of course, the desire for this comes from F#'s pipe `|>` operator. 

I can see that `compose` is defined statically in `Prelude` as well as an extension method on `Func<T>`. It behaves just like the `>>` compose in F#.

I can imagine `pipe` being implemented in a similar way:
```c#
static T2 pipe(T1 t, Func<T1,T2> f) => f(t);
static T3 pipe(T1 t, Func<T1, T2> f, Func<T2, T3> g) => compose(f, g)(t);
...
static T2 Pipe(this T1 t, Func<T1, T2> f) => f(f);
static T3 Pipe(this T1 t, Func<T1, T2> f, Func<T2, T3> g) => compose(f, g)(t);
``` 
And so on. It's easy to implement in terms of `compose`.

And would be used like this:
```c#
var split = fun((string s) => s.Split(' '));
var reverse = fun((string[] words) => words.Reverse());
var join = fun((string[] words) => string.Concat(words, " "));

var first = "April is the cruelest month".Pipe(split, reverse, join); // extension method
var second = pipe("April is the cruelest month", split, reverse, join); // from Prelude

```

Let me know what you think.

**Comment by bender2k14** [comment]
There is function named `Apply`. Have you seen that function? Is that what you are looking for?

**Comment by louthy** [comment]
@blakeSaucier Whilst I'm not against adding features for convenience.  Do we gain anything over:
```c#
    compose(split, reverse, join)("April is the cruelest month")
```

**Comment by bender2k14** [comment]
I prefer postfix function application.  With the current feature set, one could write
```C#
"April is the cruelest month".Apply(compose(split, reverse, join))
```

**Comment by blakeSaucier** [comment]
Thanks for the responses.

I'm familiar with `Apply` - I was thinking it would be nice to supply more than one Func as 'the pipeline'.

And I suppose you're right, we don't gain much over the baked in `compose` plus providing the arguments or doing an applicative. I found myself writing a pipe forward function in my own project and thought it might be of value here.

**Comment by louthy** [comment]
@blakeSaucier https://github.com/louthy/language-ext/releases/tag/v3.4.0
