### ISSUE TITLE
`Lst<T>` serialization broken for web forms pages

### ISSUE THREAD

**Issue by StanJav** [louthy/language-ext#712]
In the recent change https://github.com/louthy/language-ext/commit/ec7581797ccea0ee88afcdd4bedb6d754d3c4fd3?diff=split#diff-e3716380c0d06081191c51f2f160ec27R508  the `[Serializable]` attribute on `ListItem<T>` was commented. That broke the serialization via `LosFormatter` (Web Forms pages `ViewState` serialization - example below). 

What was a reason for it? Would you agree if I uncomment it + add an unit test for `LosFormatter`? 

```
var stringWriter = new StringWriter();
var format = new LosFormatter();
format.Serialize(stringWriter, List(1, 2, 3));
```

Error message: 
```
Type 'LanguageExt.ListItem`1[[System.Int32, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]' in Assembly 'LanguageExt.Core, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null' is not marked as serializable.
```

**Comment by louthy** [comment]
I removed it because the type was private and didn't think it would have an effect, clearly it does, so I've restored it.

**Comment by StanJav** [comment]
Hi @louthy, would you mind doing a release? We are waiting for this fix.
