### ISSUE TITLE
Set Equals

### ISSUE THREAD

**Issue by MaybeSacred** [louthy/language-ext#721]
https://github.com/louthy/language-ext/blob/3015d62f1e5866d56586a2e2d32fc0c4bd24c1e2/LanguageExt.Core/DataTypes/Set/Set.cs#L558-L559

Set Not Equals operator appears to return true when sets are equal
Expected Behavior:
```new Set(1,2) != new Set(1)``` returns ```true```
Actual Behavior:
```new Set(1,2) != new Set(1)``` returns ```false```

Also affects a few other Set classes in this folder

**Comment by louthy** [comment]
Wow, that slipped through the net!  Fixed in the next release.  Just working on the code-gen issues first, then I'll deploy.
