### ISSUE TITLE
Allow custom ToString() for [Record]

### ISSUE THREAD

**Issue by StefanBertels** [louthy/language-ext#722]
Currently code generation implements `ToString()` and I cannot use my own implementation:

`  JobId.CJ3hHYZ9.generated.cs(117, 32): [CS0111] Type 'JobId' already defines a member called 'ToString' with the same parameter types`

This probably applies to [Union], too.

**Comment by ffgiraldez** [comment]
I face the same problem, It is possible that the Generator check the current impl and not generate methods that is already defined, maybe should promt a compiler warning just to check is the desired behavior

**Comment by louthy** [comment]
Fixed.  Will be in the next release.
