### ISSUE TITLE
Seq TakeWhile issues

### ISSUE THREAD

**Issue by colethecoder** [louthy/language-ext#727]
RE: https://github.com/louthy/language-ext/pull/726

There seem to be a couple of issues with TakeWhile on Seq at the moment. Take the following example:

```cs
using static System.Console;

namespace ConsoleApp2
{
    class Program
    {
        static void Main(string[] args)
        {
            var test = "0000000011111111".ToSeq();

            var result = test.TakeWhile(Pred);

            WriteLine($"Expected 8 values. Actually {result.Count()} values");
            ReadLine();
        }

        static bool Pred(char c)
        {
            WriteLine($"Checking char: {c}");
            return c == '0';
        }
    }
}
```

The output of this is:

```
Checking char: 0
Checking char: 0
Checking char: 0
Checking char: 0
Checking char: 0
Checking char: 0
Checking char: 0
Checking char: 0
Checking char: 1
Checking char: 1
Checking char: 1
Checking char: 1
Checking char: 1
Checking char: 1
Checking char: 1
Checking char: 1
Expected 8 values. Actually 12 values
```

My assumption is that the predicate should not be applied to the entire sequence but only until the first time it returns `false`. Also some of the optimisation structure appears to be leaking through so an additional 4 chars are returned in the result:

![image](https://user-images.githubusercontent.com/992613/75525043-06963680-5a07-11ea-897b-3ff1d05dbc59.png)

**Comment by louthy** [comment]
Fixed in `3.4.12`
