### ISSUE TITLE
ToOption?

### ISSUE THREAD

**Issue by mhomde** [louthy/language-ext#739]
It's a minor thing, and maybe there's a reason for this not existing, but. Could we have a general .ToOption extension method?    adding the Prelude static extension using just to be able to do Optional(A) is a bit tedious :)

Like :
   public static Option<A> ToOption<A>(this A value)
        {
            return !LanguageExt.Prelude.isnull(value) ? new Some<A>(value) : new Option<A>();
        }

**Comment by bender2k14** [comment]
Why would you define `ToOption(A)` like that instead of just `Optional(a)`?

Have you considered using `a.Apply(Optional)`?

**Comment by louthy** [comment]
@mhomde As much as possible I don't want to pollute intellisense with lots of extensions.  There are implicit casts for `Option<A>` when returning from a function:
```c#
    Option<A> Foo() => default(A);
```
Simple constructors for `Option` in the `Prelude`:
```c#
    using static LanguageExt.Prelude;

    var mx = Some(123);
    var my = None;
    var mz = Optional(x);   // if null then None else Some(x)
```
I think _probably_ that's enough in terms of ease-of-use.  If I have `ToOption`, do then need `ToOptionUnsafe`, `ToEither`, `ToEitherUnsafe`, `ToEitherAsync`, `ToSeq`, `ToList`, `ToValidation`, etc?

Happy to take other feedback, but I think this is the pragmatic approach.

**Comment by mhomde** [comment]
> @mhomde As much as possible I don't want to pollute intellisense with lots of extensions. There are implicit casts for `Option<A>` when returning from a function:
> 
> ```cs
>     Option<A> Foo() => default(A);
> ```
> 
> Simple constructors for `Option` in the `Prelude`:
> 
> ```cs
>     using static LanguageExt.Prelude;
> 
>     var mx = Some(123);
>     var my = None;
>     var mz = Optional(x);   // if null then None else Some(x)
> ```
> 
> I think _probably_ that's enough in terms of ease-of-use. If I have `ToOption`, do then need `ToOptionUnsafe`, `ToEither`, `ToEitherUnsafe`, `ToEitherAsync`, `ToSeq`, `ToList`, `ToValidation`, etc?
> 
> Happy to take other feedback, but I think this is the pragmatic approach.

I understand your thinking, I would argue though that a common scenario is tagging method parameters as Some or Option  to kinda "fortify" your inner code. 

While Some<> isn't bulletproof it's a nice enforcement tool IMO.  When doing that you run into lots of situation where you need  to cast Some<> To Option<> and vice versa, so it feels more fundamental than the other types....

also just for consistency since there's a ToSome() You do expect there to be a ToOption()
