### ISSUE TITLE
CodeGen:[Union] does not respect access modifiers

### ISSUE THREAD

**Issue by tanxeel90** [louthy/language-ext#740]
Trying to do a `[Union]` type code gen for `**internal** interface` or `**internal** abstract class` causes compilation errors. For instance 
```
[Union]
internal abstract partial class Shape1 
{
    internal abstract Shape1 Rectangle(int width, int length);
}
```
generates following compilation error because the generated class is marked as `public`:
`CS0262	Partial declarations of 'Shape1' have conflicting accessibility modifiers`

OR in case of `interface` following code:
```
[Union]
internal interface Shape
{
    Shape Circle(float radius);
}
```
generates compilation error because `ShapeCon` is generated as `public`:
`CS0050	Inconsistent accessibility: return type 'Shape' is less accessible than method `

**Comment by louthy** [comment]
@tanxeel90 This is fixed, but I'm gathering a bigger set of changes in the `hand-written-traverse` branch (including this) - I'm probably building up to a `v4` major version change, and so won't get a full release until it's out of `beta`
