### ISSUE TITLE
CodeGen: [Record] does not work on derived class

### ISSUE THREAD

**Issue by qwas368** [louthy/language-ext#742]
**Test case**
```c#
namespace CodeGenTest
{
    [Record]
    public partial class Gam: Base
    {
        public string A { get; }

        public string B { get; }
    }

    public partial class Base
    {
        public Base(string Createby, DateTime Created)
        {
            this.Createby = Createby;
            this.Created = Created;
        }

        public string Createby { get; }

        public DateTime Created { get; }
    }
}
```

**My expected result**
```c#
public sealed partial class Gam : System.IEquatable<Gam>, System.IComparable<Gam>, System.IComparable
    {
        public Gam(string A, string B, string Createby, DateTime Created)
        : base (Createby, Created)
        {
            this.A = A;
            this.B = B;
        }
       // ...
}
```

**Current result** 
```c#
public sealed partial class Gam : System.IEquatable<Gam>, System.IComparable<Gam>, System.IComparable
    {
        public Gam(string A, string B)
        {
            this.A = A;
            this.B = B;
        }
       // ...
}
```

**Comment by louthy** [comment]
This is not a supported feature, and probably won’t be, for a few of reasons:

* records in other languages don’t typically support inheritance, they’re concrete data types, and that’s all
* lookup of types isn’t something the code-gen should do a lot of: the code-gen runs when types don’t exist, so looking up an inheritance ancestry would be problematic and would seem to fail for random reasons 
* inheritance messes up the intuition behind structural equality, ordering etc.  (Are two Base objects equal when one is a Gam and one is something else?);  

Inheritance is just a terrible system in general, so I don’t tend to chase ideas that support it.  

Consider using unions or record composition

**Comment by qwas368** [comment]
Got it. 
Have any plan to develop visual studio extension like [Generate Constructor](https://docs.microsoft.com/en-us/visualstudio/ide/reference/generate-constructor?view=vs-2019) for [Record], [With] and so on ? We can't use Code-gen tool because of related policy sometimes.

**Comment by louthy** [comment]
The constructor is already generated automatically.  Do you mean with argument validation?  If so, [it's on my list of things to-do](https://github.com/louthy/language-ext/issues/705)

Just to continue my last point:
```c#
    [Record]
    public class Created
    {
        public readonly string By;
        public readonly DateTime When;
    }

    [Union]
    public interface Base
    {
        Base Gam1(Created created, string A, string B);
        Base Gam2(Created created, int X, string Y);
    }
```
Then use pattern-matching to write your code against:
```c#
    public string Example(Base value) => value switch
    {
        Gam1 (var created, var a, var b) => $"{created.By} on {created.When} - {a} {b}",
        Gam2 (var created, var x, var y) => $"{created.By} on {created.When} - {x} {y}"
   }
```
That's the functional way to do it.  Unfortunately, C# pattern-matching doesn't have exhaustiveness checking, so you may want to make `Match` extension methods that work a bit like `Match` on `Option`.

**Comment by qwas368** [comment]
Sorry, I don't mean with argument validation. I mean that   Microsoft only provide Generate construction default in Visual Studio. Have any plan to develop VS Extension for more Quick Action to generate basic FP function (with, lens ... ) when we can't use Code-Gen.

Example:
![image](https://user-images.githubusercontent.com/26789196/76682309-f781cc00-6635-11ea-9312-660729a0de24.png)

**Comment by louthy** [comment]
No plans, sorry.  Lang-ext already takes up an enormous amount of my free time, that would be a bit too much.

You could take the code-gen source yourself and wrap it up into a vsx though, the license is permissive enough to clone and do with it whatever you like

**Comment by qwas368** [comment]
Thanks for your reply soon.  I will try to do.
