### ISSUE TITLE
Problem using Either.Map (related to issue #231)

### ISSUE THREAD

**Issue by MrYossu** [louthy/language-ext#747]
I've just been looking at issue #231, trying to follow Paul's sample, but am getting a compilation error.

I'm assuming that a Vin is a vehicle identification code, and have simplified it to be a 5-char string...

```c#
  public class VehicleIdentificationNumber {
    public string Vin { get; }

    private VehicleIdentificationNumber(string vin) =>
      Vin = vin;

    public static Either<Error, VehicleIdentificationNumber> Create(string vin) {
      if (vin.Length == 5) {
        return new VehicleIdentificationNumber(vin);
      }
      return Error.New("Invalid VIN");
    }
  }
```

So now `VehicleIdentificationNumber.Create("12345")` returns a `Right`, and `VehicleIdentificationNumber.Create("123")` returns a `Left`.

I have a very simple `Vehicle` class for testing...

```c#
  public class Vehicle {
    public string Vin { get; }

    public Vehicle(string vin) =>
      Vin = vin;
  }
```

The sample code there shows the following...

```c#
    static Either<Error, Vehicle> GetVehicleFromVin(string vinString, int stockNumber) =>
        VehicleIdentificationNumber.Create(vinString).Map(vin => new Vehicle(vin, stockNumber));
```

I didn't bother with the stock number, and was doing this inline, so had the following...

```c#
var car1 = VehicleIdentificationNumber.Create("12345")
      .Map(vin => new Vehicle(vin));
```

...however this gives a compilation error _Argument 1: cannot convert from 'LanguageExtPlay.VehicleIdentificationNumber' to 'string'_

What am I doing wrong? Thanks

**Comment by louthy** [comment]
Could you post up a full code sample?  `Vin.Create` is unknown, for example.

**Comment by MrYossu** [comment]
Sorry, that was a typo. The code is complete, it just has `Vin.Create` instead of `VehicleIdentificationNumber.Create`

**Comment by harrhp** [comment]
```
var car1 = VehicleIdentificationNumber.Create("12345")
      .Map(vin => new Vehicle(vin));
```

`vin` here is of type `VehicleIdentificationNumber`, so either change constructor of `Vehicle` to accept `VehicleIdentificationNumber` or change code to

```
var car1 = VehicleIdentificationNumber.Create("12345")
      .Map(vin => new Vehicle(vin.Vin));
```

**Comment by MrYossu** [comment]
Duh, I do feel stupid!

I had hovered my mouse over the `vin` parameter in the lambda, and VS showed it as being of type `Either<Error, VehicleIdentificationNumber>`, which is what confused me. I was under the (correct) impression that the parameter inside `Map` was the inner value, not the monad, and that tooltip threw me, making me think it was an `Either`. Now I read the actual compiler error, it's obvious what the issue was!

Thanks for the help. I'll try and read compiler errors before posting them in future!
