### ISSUE TITLE
Free monads composition

### ISSUE THREAD

**Issue by harrhp** [louthy/language-ext#748]
Assume i have 2 free monads
```
[Free]
interface ServiceAFree<A>
{
  [Pure]
  A Pure(A value);
  int GetA();
}

[Free]
public interface ServiceBFree<A>
{
  [Pure]
  A Pure(A value);
  int GetB(int value);
}
```

shouldn't it be possible to write

```
[Free]
public interface ProgramFree<A>
{
    [Pure]
    A Pure(A value);
    A ServiceA(ServiceAFree<A> free);
    A ServiceB(ServiceBFree<A> free);
}
```
?
Right now it's not because of compilation error in generated static class ProgramFree - methods ServiceA and ServiceB try to use generic parameter A which they don't define

```
public static ProgramFree<A> ServiceA(ServiceAFree<A> dsl) => new ServiceA<A>(dsl, Pure);
public static ProgramFree<A> ServiceB(ServiceBFree<A> dsl) => new ServiceB<A>(dsl, Pure);
```
The type or namespace name 'A' could not be found (are you missing a using directive or an assembly reference?)

**Comment by louthy** [comment]
Generic types aren’t possible as arguments in the free-cases.  C#’s type-system isn’t expressive enough for the generated Map and Bind functions to work, that’s why it’s not supported here.
