### ISSUE TITLE
How to collect multiple errors, but fail if there are any?

### ISSUE THREAD

**Issue by MrYossu** [louthy/language-ext#749]
Sorry for the slightly confusing title, but I couldn't think of a better way to phrase it.

I am playing with the validation sample shown in [the unit tests](https://github.com/louthy/language-ext/blob/master/LanguageExt.Tests/ValidationTests.cs#L267), and was looking at the code that validates the month and year...
```
            var monthYear = from m in ToInt(expMonth).Bind(ValidMonth)
                            from y in ToInt(expYear).Bind(PositiveNumber)
                            from my in validToday(m, y)
                            select my;
```
I understand why Linq is used, as you only want to pass the month and year to `validToday` if they are both valid individually (ie month is between 1 and 12, and year is a positive integer).

However, if both month and year are invalid, then you only get the first error back, not both.

Is there a way to make so that...

1. If month or year are both invalid, both errors are returned
2. If month or year are both valid, then any error from `validToday` is returned
3. If `validToday` does not return an error, then the two integers are returned

Thanks

**Comment by louthy** [comment]
Go a few lines down in the unit test to see how: https://github.com/louthy/language-ext/blob/master/LanguageExt.Tests/ValidationTests.cs#L277

**Comment by bender2k14** [comment]
Issue #698 is about that exact same section of code and includes many different ways to do what you want.

**Comment by MrYossu** [comment]
@louthy Thanks for the reply, but I don't see how that line helps. If I understand correctly (which I may not, so don't take that the wrong way!), that line collects the three validations, and if all are OK, creates the credit card, if not, returns a collection of the errors.

However, my problem is that the `monthYear` validation will only contain the first error if both month and year are invalid, so this line will only collect that one error, not both. The issue is to get the code further up (lines 267-270) to include all errors for month and year, not just the first.

@bender2k14 Yes, it looks like you asked exactly the same thing, although got a lot further than I did! I'll keep an eye on that issue, as it looks like it will solve mine as well.

Thanks to both of you for the replies.

**Comment by louthy** [comment]
You just use the same `Apply` technique as further down in the function.  The only reason this is shown in LINQ form is to give an example of various ways of validating.
```c#
var monthYear = (ToInt(expMonth).Bind(ValidMonth), ToInt(expYear).Bind(PositiveNumber))
                     .Apply((m, y) => validToday(m, y));
```

**Comment by MrYossu** [comment]
@louthy Thanks for the clarification. Didn't realise that was what you meant.

Is there any difference between the code you just showed and the way @bender2k14 showed in his second snippet in issue #698? For comparison, I wrapped the `monthV` and `yearV` variables inline, and used `PositiveNumber` as in the unit test, so your sample looks like this...

```
  var monthYear2 =
    from my in (ToInt(expMonth).Bind(ValidMonth), ToInt(expYear).Bind(PositiveNumber))
      .Apply((m, y) => (Month: m, Year: y))
    from r in validToday(my.Month, my.Year)
    select r;
```
...and his looks like this...
```
  var monthYear =
    (ToInt(expMonth).Bind(ValidMonth), ToInt(expYear).Bind(PositiveNumber))
      .Sequence()
      .Bind(t => {
        var (m, y) = t;
        return validToday(m, y);
      });
```

Anything to choose between the two, other than personal preference or readability?

Thanks again.

**Comment by louthy** [comment]
Mine's probably slightly more efficient, and the `Sequence` extension will only work with a two-item tuple as it stands.  

I just added an extra function `ApplyM` which will allow for the return type of the `delegate` to also be a `Validation`, that simplifies everything to this:

```c#
    var monthV = ToInt(expMonth).Bind(ValidMonth);
    var yearV = ToInt(expYear).Bind(PositiveNumber);

    var monthYear = (monthV, yearV).ApplyM(validToday);            
```
I'll probably deploy it as the latest beta this evening.

**Comment by MrYossu** [comment]
@louthy Excellent, thanks very much.
