### ISSUE TITLE
Code review - Is this a reasonable approach?

### ISSUE THREAD

**Issue by MrYossu** [louthy/language-ext#750]
Hello,

I've been examining the [`ValidateCreditCard` method in the unit tests](https://github.com/louthy/language-ext/blob/2cc42b424ac44417d8b09fa61b270426d9ee95b0/LanguageExt.Tests/ValidationTests.cs#L258),  and have been trying to use it as a base for rewriting some code I have, 

My code needs to take a string, check it is valid XML, extract the data from it and create a `WorkOrder` object. Based on that sample, I have something that works (with one caveat, see below), and would like some feedback on whether or not I'm doing this right.

I'll paste the entire thing in (this is a complete C# program in LinqPad, so you should be able to paste it as-is and run it), and add some comments below...

```c#
void Main() {
  // Sample XML. This is valid, but if you change it, you can see what happens when validation fails
  string xml = "<WorkOrder><SystemID>1</SystemID><DueDate>2020/04/15</DueDate><WorkOrderTypeID>3</WorkOrderTypeID><PrimaryEngineerID>9</PrimaryEngineerID><SecondEngineerID>2</SecondEngineerID><Description>Nowt</Description></WorkOrder>";
  ValidateWorkOrder(xml)
    .Match(
      workOrder => Console.WriteLine(workOrder.ToString()),
      errors => {
        foreach (Error error in errors) {
          Console.WriteLine(error.Message);
        }
      }
    );
}

static Validation<Error, WorkOrder> ValidateWorkOrder(string xml) =>
  ToXElement(xml)
    .Match(xe => {
      Validation<Error, int> systemIdV = ValidSystemID(xe);
      Validation<Error, DateTime> dueDateV = ValidDueDate(xe);
      Validation<Error, int> workOrderTypeV = ValidWorkOrderTypeID(xe);
      Validation<Error, int> primaryEngineerV = ValidPrimaryEngineerID(xe);
      // TODO - 2nd engineer ID is optional, so we shouldn't be using int below...
      Validation<Error, int> secondaryEngineerV = ValidSecondEngineerID(xe);
      Validation<Error, string> descriptionV = ValidDescription(xe);

      return (systemIdV, dueDateV, workOrderTypeV, primaryEngineerV, secondaryEngineerV, descriptionV)
        .Apply((sysId, dDate, typeId, primId, secndId, desc) => new WorkOrder(sysId, dDate, typeId, primId, secndId, desc));
    },
      errors => Fail<Error, WorkOrder>(Error.New(string.Join(", ", errors.Select(e => e.Message))))
    );

static Validation<Error, int> ValidSystemID(XElement xe) =>
  from idString in ElementExists(xe, "SystemID")
  from systemID in ToInt(idString)
    // TODO - Check the system exists in the database
  select systemID;

static Validation<Error, DateTime> ValidDueDate(XElement xe) =>
  from dueDateString in ElementExists(xe, "DueDate")
  from dueDate in ToDateTime(dueDateString)
  select dueDate;

static Validation<Error, int> ValidWorkOrderTypeID(XElement xe) =>
  from idString in ElementExists(xe, "WorkOrderTypeID")
  from workOrderTypeID in ToInt(idString)
    // TODO - Check the work order type exists in the database
  select workOrderTypeID;

static Validation<Error, int> ValidPrimaryEngineerID(XElement xe) =>
  from idString in ElementExists(xe, "PrimaryEngineerID")
  from engineerID in ToInt(idString)
    // TODO - Check the engineer exists in the database
  select engineerID;

static Validation<Error, int> ValidSecondEngineerID(XElement xe) =>
  from idString in ElementExists(xe, "SecondEngineerID")
  from engineerID in ToInt(idString)
    // TODO - Check the engineer exists in the database
  select engineerID;

static Validation<Error, string> ValidDescription(XElement xe) =>
  ElementExists(xe, "Description")
    .Match(
      description => AsciiOnly(description) | MaxStrLength(30)(description),
      errors => Fail<Error, string>(Error.New(string.Join(", ", errors.Select(e => e.Message))))
    );

static Validation<Error, string> ElementExists(XElement xe, string name) =>
  xe.Element(name) != null
        ? Success<Error, string>(xe.Element(name).Value)
        : Fail<Error, string>(Error.New($"<{name}> element does not exist"));

static Validation<Error, int> ToInt(string str) =>
  parseInt(str).ToValidation(Error.New("must be a number"));

static Validation<Error, DateTime> ToDateTime(string str) =>
  parseDateTime(str).ToValidation(Error.New("must be a valid date"));

public static Validation<Error, string> AsciiOnly(string str) =>
    str.ForAll(c => c >= ' ' && c <= 0x7f)
        ? Success<Error, string>(str)
        : Fail<Error, string>(Error.New("only ASCII characters are allowed"));

public static Func<string, Validation<Error, string>> MaxStrLength(int max) =>
    str =>
        str.Length <= max
            ? Success<Error, string>(str)
            : Fail<Error, string>(Error.New($"can not exceed {max} characters"));

static Validation<Error, XElement> ToXElement(string xml) {
  try {
    XElement xe = XElement.Parse(xml);
    return Success<Error, XElement>(xe);
  } catch (Exception ex) {
    return Fail<Error, XElement>(Error.New(ex.Message));
  }
}

class WorkOrder {
  public DateTime DueDate { get; set; }
  public int SystemID { get; set; }
  public int PrimaryEngineerID { get; set; }
  public int? SecondEngineerID { get; set; }
  public string Description { get; set; }

  public WorkOrder(int systemID, DateTime dueDate, int typeID, int primaryEngineerID, int? secondaryEngineerID, string description) {
    SystemID = systemID;
    DueDate = dueDate;
    PrimaryEngineerID = primaryEngineerID;
    SecondEngineerID = secondaryEngineerID;
    Description = description;
  }

  public override string ToString() =>
    $"Due: {DueDate.ToLongDateString()} for system {SystemID}. Engineers {PrimaryEngineerID} and {SecondEngineerID}. Description \"{Description}\"";
}
```

The code in `Main` just tests it.

The `ValidateWorkOrder` method is what does all the work. I've lifted and/or copied some of the utility methods from the sample, so a lot of this will look familiar. I've deliberately ignored database checking for the moment, as I want to take this one step at a time, without getting too confused.

As commented in the main method, the `SecondEngineerID` is optional (it's an `int?` in the `WorkOrder` class), so I guess  I should be using `Option<int>` for this one, but wasn't sure how to do this. The `<SecondEngineerID>` node must exist in the XML, but it does not have to have a value. If it has a value, it must be an integer, and must correspond to an engineer in the database (again, that bit is not checked here).

How would I modify `ValidPrimaryEngineerID` to account for this?

Thanks for any comments and feedback you can give.

**Comment by Liversage** [comment]
This is an old issue but I wanted to take a stab at the problem with the optional ID.

First change would be to provide an `Option<int>` instead of `int?` in the `WorkOrder` constructor and use the `ToNullable()` extension method to convert it:

```csharp
public WorkOrder(int systemID, DateTime dueDate, int typeID, int primaryEngineerID, Option<int> secondaryEngineerID, string description) {
    SystemID = systemID;
    DueDate = dueDate;
    PrimaryEngineerID = primaryEngineerID;
    SecondEngineerID = secondaryEngineerID.ToNullable();
    Description = description;
}
```

Next step is to change the signature of `ValidSecondEngineerID` so it returns `Validation<Error, Option<int>>` instead of `Validation<Error, int>`:

```csharp
static Validation<Error, Option<int>> ValidSecondEngineerID(XElement xe) =>
```

`ToInt` returns `Validation<Error, string>` and should be replaced with a function that returns `Validation<Error, Option<string>>` mapping the empty string to `Success(None)`. C# has conditional expressions:

```csharp
str == string.Empty ? None : Some(ToInt(str))
```

The problem is the the type of this expression is `Option<Validation<Error, int>>` and not `Validation<Error, Option<int>>` but `Validation` and `Option` can be "swapped" using `Sequence()`:

```csharp
static Validation<Error, Option<int>> ToIntOrNone(string str) =>
    (str == string.Empty ? None : Some(ToInt(str))).Sequence();
```
The validation function then becomes:

```csharp
static Validation<Error, Option<int>> ValidSecondEngineerID(XElement xe) =>
    from idString in ElementExists(xe, "SecondEngineerID")
    from engineerID in ToIntOrNone(idString)
    select engineerID;
```

If the `<SecondEngineerID>` element was optional instead of being mandatory with a value that optionally could be empty you can still do the validation. The code will be different: the `Option<T>` should be introduced when parsing the XML so the result is still `Option<Validation<Error, int>>`. This is then "inverted" to `Validation<Error, Option<int>>` using `Sequence()`.

**Comment by MrYossu** [comment]
@Liversage Thanks, that's really helpful. Now you show how to do it, it seems clear, I'm just sure I would have got there on my own!

Just one question please. I'm not clear what `Sequence()` does. I know you say it "swapped" the `Validation` and `Option`, and can see the result, but please could you explain the purpose of the function in general.

Thanks again.

**Comment by TysonMN** [comment]
Syntactically, converting a type of the form `A<B<C>>` to `B<A<C>>` is called `sequence` in functional programming.

Semantically, my experience is that there is only one "senseable" or "correct" implementation.  For example, converting from `IEnumerable<Option<int>>` to `Option<IEnumerable<int>>` could be trivally implemented by always ignoring the input and returning `None`, but that would be "wrong".  Instead, the "correct" implementation is to return `None` if and only if any `Option<>` in the sequence is in the `None` state.

In general, I find it to be a useful exercise or challenge to think of the "correct" behavior when converting a type of the form `A<B<C>>` to `B<A<C>>` for a given pair of types `A<>` and `B<>`.  For example, I am currently thinking about converting `List<Tree<C>>` to `Tree<List<C>>` as implemented [here](https://github.com/hedgehogqa/fsharp-hedgehog/blob/fa9a72b4630aac779bba8bb95bdee3b9aea669d6/src/Hedgehog/Gen.fs#L352-L353).

I recommend reading [Understanding traverse and sequence](https://fsharpforfunandprofit.com/posts/elevated-world-4/) by Scott Wlaschin.

**Comment by MrYossu** [comment]
@TysonMN Thanks for the explanation. I'll give that article a read. Anything by SW is usually worth reading!

**Comment by Liversage** [comment]
@MrYossu I'm a novice in this area but a good way to learn is to answer questions so with that disclaimer let me see what I can come up with.

`Sequence` is a specialization of `Traverse` and `Traverse` is about how to deal with lists of elevated values. As already mentioned [Understanding traverse and sequence](https://fsharpforfunandprofit.com/posts/elevated-world-4/) by Scott Wlaschin provides a good explanation using F#.

I'm somewhat confused by the fact that the `Traverse()` extension methods in LanguageExt seem to be different compared to the above definition so I'll just skip directly to `Sequence`. The canonical example is parsing strings to numbers where the result is `Seq<Option<int>>`:

```csharp
Seq("3", "1", "4").Map(parseInt);                 // [Some(3), Some(1), Some(4)]
Seq("3", ".", "1", "4").Map(parseInt);            // [Some(3), None, Some(1), Some(4)])
```

However, if you want `Option<Seq<int>>` you can use `Sequence`:

```csharp
Seq("3", "1", "4").Map(parseInt).Sequence();      // Some([3, 1, 4])
Seq("3", ".", "1", "4").Map(parseInt).Sequence(); // None
```

I can imagine that the name `Traverse` and `Sequence` were chosen because this is about traversing sequences. However, this idea can also be applied to "short sequences" like an option that either has a single value ("some") or no value ("none"). In other words `Option<Validation<int>>` can be converted to `Validation<Option<int>>` by using `Sequence`.

**Comment by MrYossu** [comment]
@Liversage Thanks Martin, that makes it really clear 😀
