### ISSUE TITLE
Add BiBind to Free

### ISSUE THREAD

**Issue by chadedrupt** [louthy/language-ext#757]
Firstly,
@louthy I note your info issue re: availability, all good, this is a non-urgent feature suggestion.

While rolling out some features using the `Free` Monad / Interpreter pattern we have found the `Free` code-gen to be great help in reducing some of the boilerplate needed for the pattern.

However we have come across one limitation with the current implementation and that is the lack of an ability to handle or manage the failure path. More specifically the `Free` is lacking a `BiBind` function that will allow you to recover from a failure path and get back on to the success path. This also limits your ability to hook into the failure path for error logging etc.

I tried implementing with the current `Free` but realised that the resulting tree that the `Free` builds up only stores the success path by means of the `Next` field. So my idea was to add an additional `FailNext` field that will allow the Interpreter to choose between the branches based on the outcome of the current action.

I have created a sample repo https://github.com/chadedrupt/free-monad-fail-state where this idea is implemented and demonstrated.

I could be missing something here, so if anyone is aware of something I'm missing that would be great.

Also happy to knock-up a PR for the `Free` code-gen if you feel this is a feature worth implementing.

**Comment by louthy** [comment]
@chadedrupt It certainly sounds interesting, and if you are happy to do a PR that'd be awesome, as I can see real value here.  The code in the code-gen isn't particularly pretty, so I'd totally understand if it feels a bit too overwhelming, I'll look into this when I free up some time.
