### ISSUE TITLE
Add method DoIfFail to Try, TryAsync, TryOption, TryOptionAsync

### ISSUE THREAD

**Issue by evgenles** [louthy/language-ext#763]
Can we implement new method DoIfFail to Try monads (Try, TryAsync, TryOption, TryOptionAsync) which execute action when fail is occurred and return unmodified structure

It can be used for logging error or metrics collection

If can I create PR for this

**Comment by pauledrupt** [comment]
hey mate, trivial to create your own extensions

```
        public static TryAsync<T> IfFailAsync<T>(this TryAsync<T> self, T ifFail)
        {
            return self
                .BiBind(
                    Succ: TryAsync,
                    Fail: _ => TryAsync(ifFail)
                );
        }
```

**Comment by evgenles** [comment]
Hello
I am speaking about method that do not impact on result (as same as exist `Do` method)

```c#
    public static TryAsync<A> DoIfFail<A>(this TryAsync<A> ma, Action<Exception> f) => async () =>
    {
        var r = await ma.Try();
        if (r.IsFaulted)
        {
            f(r.Exception);
        }
        return r;
    };
```

I can create own extensions in projects, but I think that method can be in library.
