### ISSUE TITLE
Codegen: Reader Map method uses Pure when Return specified as Constructor

### ISSUE THREAD

**Issue by appetere** [louthy/language-ext#765]
When generating a Reader with codegen, with the default Constructor attribute value of "Return":

`    [Reader(Env: typeof(string), Constructor: "Return")]
    public partial struct TestReader<A> { }`

The Map method method generated uses "Pure" instead of "Return":

`public TestReader<B> Map<B>(System.Func<A, B> f) => Bind(a => TestReader<B>.Pure(f(a)));`

Workaround identified by @louthy is to set the Constructor attribute value to "Pure":

`    [Reader(Env: typeof(string), Constructor: "Pure")]
    public partial struct TestReader<A> { }`

Fix will be in the next release.

**Comment by louthy** [comment]
Fixed in the latest beta
