### ISSUE TITLE
What's the point of NumType?

### ISSUE THREAD

**Issue by MrYossu** [louthy/language-ext#769]
Hello,

I was just reading the [wiki page on function signatures](https://github.com/louthy/language-ext/wiki/Thinking-Functionally:-Function-Signatures), and am confused as to when and why you would use NumType.

After explaining why primitive types are not good candidates for clear signatures, the page says "_But creating a new-type for every usage of an int (or any unconstrained base-type) would be extremely tedious._" However, it then goes on to do exactly that, albeit using NumType as a base class. Did I miss something here?

Anyway, my main question is what is the benefit of using NumType in this code...

```c#
    public class Year : NumType<Year, TInt, int>
    {
        Year(int x) : base(x) { }
    }
```

If you created your own class without the `NumType` base, you would get just the same benefits, and could add validation, etc as shown.

What did I miss? Thanks.

**Comment by CK-LinoPro** [comment]
`NumType` implements `IEquatable<T>`, `IComparable<T>` and numerous operators (calculation, morphism, comparison, equality, creation) for you so you don't have to do it for every single strong type alias. [See here](https://github.com/louthy/language-ext/blob/master/LanguageExt.Core/DataTypes/NumType/NumType.Predicate.cs).

**Comment by MrYossu** [comment]
@CK-LinoPro Ah, obvious now you mention it! Thanks.

Do you know what the middle generic type is supposed to be? I can see the first is the type you're creating, and I guess the last is the base type, but what is the middle one?

Thanks again

**Comment by CK-LinoPro** [comment]
`PRED` can be used for predicates that define what values the NumType wrapper may hold.
If an invalid value is supplied, it will raise an exception. See https://github.com/louthy/language-ext/blob/8c4ab0af13df54333584f3b427dfd6f76e21a313/LanguageExt.Core/DataTypes/NumType/NumType.Predicate.cs#L68.

Predefined predicates are in `LanguageExt.ClassInstances.Pred`, constants that you might need are in `LanguageExt.ClassInstances.Const`.

Example:

``` {.cs}
public sealed class Natural
    : NumType<Natural, TInt, int, GreaterOrEq<TInt, int, I0>>
{
    public Natural(int value)
        : base(value)
    {
    }
}

void foo()
{
    var ok = new Natural(5);
    var fails = new Natural(-8);
}
```

**Comment by MrYossu** [comment]
@CK-LinoPro That's excellent, thanks for the explanation.

Presumably the "right" way to create a `Natural` would be to wrap it in a `try/catch` block (or something more functional) and return an `Option<Natural>`. Do you know how I would do this?

Sorry to ask so many questions, but I really like the FP approach and am trying to learn as much as I can. I'm sure it will all be obvious at some point, but right now I'm getting lost trying to get going.

Thanks again.

**Comment by louthy** [comment]
There’s NewTry and NewOption

https://github.com/louthy/language-ext/blob/master/LanguageExt.Core/DataTypes/NumType/NumType.Predicate.cs#L51

**Comment by MrYossu** [comment]
@louthy Ah, good to see you back again!

Thanks for the reply. Sorry for being dumb, but how do I use this? Do I need to create another type, say OptionNatural which has both the GreaterOrEq and NewOption predicates (not sure how you'd to that though), or can I use the existing Natural type? If so, how?

Thanks again.

**Comment by louthy** [comment]
I’m not back yet, and won’t be for a little while more, just replying to a few bits that don’t take much time 

    var mx = Natural.New(123);
    var mx = Natural.NewTry(123);
    var mx = Natural.NewOption(123);
    var mx = new Natural(123);

**Comment by MrYossu** [comment]
@louthy OK, understood. Makes me even more grateful for your reply. Understand how to use this now, so should be able to play with some others.

Thanks again. Hope all goes well for you.

**Comment by MrYossu** [comment]
@louthy OK, one more if you have the time.

I'm exploring these base types, but don't see one for `DateTime`. How do I create my own date type? I tried the following...

```c#
class NewDate : NewType<NewDate, DateTime> {
  public NewDate(DateTime date) : base(date) { }
}
```

...which works, but I can't do the usual things I would want to do with dates, such as find the time between two of them.

Also, I would like to create a `FutureDate` type, which can only represent a date in the future. Can this be done?

Thanks again.

**Comment by MrYossu** [comment]
@louthy Sorry, it's past my bedtime, so I'm going to ask another question!

I tried to create a new string-based type, but couldn't work that out either. I tried...
```c#
class ProductName : NewType<ProductName, TString, string> {
  public ProductName(string name) : base(name) { }
}
```
...but got a compiler error as `string` is nullable. I tried removing the third type parameter, but then got a compiler error on the `base(name)` part, saying it couldn't convert from `string` to `TString`.

So I'm stuck? How do I create a string-based type?

Thanks again, sorry to bombard you with questions, especially when you're so busy.

**Comment by CK-LinoPro** [comment]
@MrYossu `NewType` has three versions: `NewType<NEWTYPE, A>`, `NewType<NEWTYPE, A, PRED>` and `NewType<NEWTYPE, A, PRED, ORD>`. See https://github.com/louthy/language-ext/tree/master/LanguageExt.Core/DataTypes/NewType.

`class ProductName : NewType<ProductName, TString, string>` translates to something like "`ProductName` a strong alias of `TString` that uses `string` to represent valid values".

Problems here are:
* `PRED` must be `PRED : struct, Pred<A>`, i.e. a specially implemented struct
* `TString` implements type class instances of the `string` type, it does not hold a representation of `string`.

What you probably want is `NewType<ProductName, string>`.

---

If you want to work on the `DateTime` instance held by `NewDate`, you can access it via `NewDate.Value` or perform operations on it via `NewDate.Map` and `NewDat.Bind`.

---

Your concept of `FutureDate` is flawed in my opinion. Imagine an instance of `FutureDate` is created with `DateTime.Now + 100 * s`. It will be invalid after 100 seconds. How do you account for that? Throwing an exception is certainly not an option. Verifying this only on instance creation makes no sense.

The type `FutureDate` would have to have some internal state to change from `valid` to `invalid` at a scheduled time. This is contrary to functional programming concepts.

`FutureDate` cannot be used in `Pure` functions for the same reason. It depends on external state `DateTime.Now`, has to be mutable and you cannot guarantee that a function using `FutureDate` evaluates to the same result when called with the same arguments at different times.

I hope this explanation makes sense to you.

**Comment by MrYossu** [comment]
@CK-LinoPro Thanks for the reply, for some reason I didn't get a notification, so only just saw it.

Got the string thing now, works fine.

I see what you mean about the future date, totally the wrong way of thinking about it. I'm still learning this FP concept, so haven't got it all clear yet.

Can you comment on my other date-related question. With a normal `DateTime` I get loads of convenience methods like `AddDays`,`DayOfWeek`, etc, but with a `NewType<NewDate, DateTime>` I don't seem to get any of that. How do I handle such a date?

Now I suspect the answer to this might be that I'm supposed to work with these kind of values inside "elevated" functions like `map` and `apply`, but the problem I have here is if I want to create a class that models (say) a product, and do something like the following...

```c#
class ProductID : NumType<ProductID, TInt, int, GreaterOrEq<TInt, int, I0>> {
  public ProductID(int value) : base(value) { }
}

class ProductName : NewType<ProductName, string> {
  public ProductName(string name) : base(name) { }
}

class NwProduct {
  private ProductID _productID;
  private ProductName _name;

  public NwProduct(int productID, string name, int supplierID, int categoryID, int unitsInStock) {
    _productID = new ProductID(productID);
    _name = new ProductName(name);
  }

  public static NwProduct FromProduct(Product product) =>
    new NwProduct(product.ProductID, product.ProductName);
}
```

...I'm not sure how I would access the values.

Hope that was clear.

**Comment by louthy** [comment]
You can still add functionality to your classes, like `AddDays`.  Num-types and float-types, are purely there to give you all of the behaviour of numerics without you having to write them yourself.
