### ISSUE TITLE
Partition extension method should return two Lists, not IEnumerables

### ISSUE THREAD

**Issue by Richiban** [louthy/language-ext#771]
I'm suspicious of the fact that partition on an `IEnumerable<Either<A, B>>` enumerates the input sequence twice

```
public static (IEnumerable<A> Lefts, IEnumerable<B> Rights) partition<CHOICE, CH, A, B>(
      IEnumerable<CH> ma)
      where CHOICE : struct, Choice<CH, A, B>
    {
      return (Choice.lefts<CHOICE, CH, A, B>(ma), Choice.rights<CHOICE, CH, A, B>(ma));
    }
```

As far as I can tell this is because the method returns two _enumerables_: One that walks the input sequence collecting only the lefts, and another that walks the sequence *again* collecting only the rights.

Rather than returning two sequences, shouldn't it return two lists? That's what the F# method does (and you can see here https://stackoverflow.com/questions/31750553/why-is-there-no-seq-partition-in-f the difficulties in trying to properly partition a lazy sequence).

**Comment by louthy** [comment]
Fixed in the latest beta
