### ISSUE TITLE
Collect Valids only of IEnumerable<Validation<Error,T>>

### ISSUE THREAD

**Issue by aage** [louthy/language-ext#773]
I cannot seem to find an equivalent of `.Somes` (for `IEnumerable<Option<T>>`) for `IEnumerable<Validation<Error,T>>` where I end up with an `IEnumerable<T>` (using only the `SUCC`s and disregarding all the `errors` of the `FAIL`s).

Is it available? Or is it a conscious choice to leave this out, since there isn't always a clear usecase for this?

**Comment by louthy** [comment]
It doesn't currently exist, not for any conscious reason, I will add it.  There is functionality existing to do it, but it's a little _generic heavy_:

```c#
var vs = new[] {Success<string, int>(1), Success<string, int>(2), Success<string, int>(3)};

var xs = Choice.rights<MValidation<string, int>, Validation<string, int>, Seq<string>, int>(vs);

```

**Comment by aage** [comment]
@louthy Instead of the example you give for a current workaround, you could also do this right?
```
var vs = new[] {Success<string, int>(1), Success<string, int>(2), Success<string, int>(3)};
var xs = vs.Bind((v) => v.SuccessAsEnumerable());
```
Or am I missing something?

**Comment by louthy** [comment]
It's now in the latest `beta`, which I consider to be stable (it's staying as beta for a while as I'm looking to make this into version 4.0.0 of lang-ext.
