### ISSUE TITLE
System.Text.Json deserialization of Option gives null reference exception

### ISSUE THREAD

**Issue by ethanwork** [louthy/language-ext#775]
Hi, I googled around for awhile but didn't have any luck in finding solutions to this exception message, hopefully it hasn't been brought up previously. When using Newtonsoft I can successfully serialize and deserialize a class that has an Option string as one of its properties as shown below.

When trying the same with Microsoft's System.Text.Json library that is used as the default in Blazor web assembly apps, it triggers a null reference exception during deserialization. If the Option string is changed to just a string the deserialization succeeds. Both Newtonsoft and System.Text.Json appear to create the same serialized text.

```public Weather SerializationTest()
        {
            Weather weather = new Weather() { Date = DateTime.Now, Summary = "Sunny", TemperatureC = 30 };
            
            // works
            string newtonsoftJsonOutput = JsonConvert.SerializeObject(weather);
            // newtonsoftJsonOutput = "{\"Date\":\"2020-04-30T17:34:39.1212619-07:00\",\"TemperatureC\":30,\"Summary\":[\"Sunny\"],\"TemperatureF\":85}"
            Weather newtonWeather = JsonConvert.DeserializeObject<Weather>(newtonsoftJsonOutput);

            // breaks on deserialization with null reference exception
            string systemTextJsonOutput = System.Text.Json.JsonSerializer.Serialize(weather);
            // systemTextJsonOutput = "{\"Date\":\"2020-04-30T17:27:30.9415292-07:00\",\"TemperatureC\":30,\"Summary\":[\"Sunny\"],\"TemperatureF\":85}"
            Weather deserializedWeather = System.Text.Json.JsonSerializer.Deserialize<Weather>(systemTextJsonOutput);
            return deserializedWeather;
        }

        public class Weather
        {
            public DateTime Date { get; set; }

            public int TemperatureC { get; set; }

            public Option<string> Summary { get; set; }

            public int TemperatureF => 32 + (int)(TemperatureC / 0.5556);
        }`

**Comment by louthy** [comment]
This honestly looks like a bug in the `System.Text.Json`, the stack trace isn't in code I control.

**Comment by ethanwork** [comment]
Thanks for taking a look, I've run into a few different issues when trying to use system.text.json instead of Newtonsoft, so it doesn't seem too surprising system.text.json has a bug in it. I only started using it since system.text.json is now the default json library for asp.net core 3.x templates and thought it would be good to migrate to it, but maybe it's time to shift back to Newtonsoft for awhile longer.
