### ISSUE TITLE
Reader codegen allows constructor name override yet Map refers to Pure

### ISSUE THREAD

**Issue by colethecoder** [louthy/language-ext#783]
When the Reader codegen runs it generates a Map function that looks like:

```cs
public ReaderDSL<B> Map<B>(System.Func<A, B> f) => Bind(a => ReaderDSL<B>.Pure(f(a)));
```

but when annotating the struct to base the monad on, the Constructor attribute is optional and defaults to `Return`.

https://github.com/louthy/language-ext/blob/73157ba46893290c85f310d32730d41d64ce1fe7/LanguageExt.CodeGen/ReaderAttribute.cs#L19

I believe this can be rectified by making this line refer to `ctorName`

https://github.com/louthy/language-ext/blob/73157ba46893290c85f310d32730d41d64ce1fe7/LanguageExt.CodeGen/ReaderGenerator.cs#L770

**Comment by louthy** [comment]
Already fixed

**Comment by louthy** [comment]
https://github.com/louthy/language-ext/commit/9638eb761735a1b2b4d1c88f7b68a58124961c77
