### ISSUE TITLE
windowSize parameter is ignored in the TryAsyncT.SequenceParallel with bind function

### ISSUE THREAD

**Issue by dgrozenok** [louthy/language-ext#785]
https://github.com/louthy/language-ext/blob/10367b27e725af4eba477d8a1bb32240b72c5e50/LanguageExt.Core/Transformer/Sequence/TryAsyncT.cs#L29

**Comment by louthy** [comment]
Well spotted!  Fixed in `3.4.24-beta`

**Comment by dgrozenok** [comment]
Wow. So fast! Thank you so much!

I believe it's in 3.4.23-beta package even though the comment in the commit is 3.4.24-beta.
