### ISSUE TITLE
Stacktrace getting lost / ExceptionDispatchInfo

### ISSUE THREAD

**Issue by StefanBertels** [louthy/language-ext#787]
As far as I can see with `raise` (and caller `OtherwiseReThrow`) stacktrace of the original exception gets lost.

This should be a solution:

https://docs.microsoft.com/en-us/dotnet/api/system.runtime.exceptionservices.exceptiondispatchinfo?view=netcore-3.1

Calling `ExceptionDispatchInfo.Throw()` will re-use the original stacktrace.

**Comment by louthy** [comment]
Yes, good call.  I have used that elsewhere in lang-ext, but wasn't aware of it at the time of writing `raise`.  It's fixed, will be in the next `beta`

**Comment by StefanBertels** [comment]
Great. Meanwhile I use this custom extension with stable version: 

```
 public static R OtherwiseReThrowWithStacktrace<R>(this ExceptionMatch<R> exceptionMatch) =>
            exceptionMatch.Otherwise(ex =>
            {
                ExceptionDispatchInfo.Throw(ex);
                throw ex; // dummy
            });
```

One thought: I'm not sure if this works fine with not yet thrown exceptions like `raise(new Exception("fail"))` because of the missing stacktrace, then (it's null).
Even if it does it _might_ be worth to think about performance (allocations). I personally wouldn't mind of performance on this level. 

Anyway: I'll add a test for this.
