### ISSUE TITLE
BottomException, InnerException

### ISSUE THREAD

**Issue by StefanBertels** [louthy/language-ext#789]
Question regarding this function (and related code):

https://github.com/louthy/language-ext/blob/master/LanguageExt.Core/DataTypes/Try/Try.Extensions.cs#L321-L322
```
   [Pure]
    public static A IfFailThrow<A>(this Try<A> self)
    {
        try
        {
            var res = self();
            if (res.IsBottom) throw new BottomException();
            if (res.IsFaulted) throw new InnerException(res.Exception);
            return res.Value;
        }
        catch (Exception e)
        {
            TryConfig.ErrorLogger(e);
            throw;
        }
    }
```

Seems this makes sure that the raised exception is never a BottomException if not in bottom (result) state -- non-bottom Faulted state will cause exception wrapping.

But there is no real problem because `IsBottom` is true if res.Exception is BottomException: 

https://github.com/louthy/language-ext/blob/master/LanguageExt.Core/Common/Result/Result.cs#L92

I personally would opt for not wrapping exceptions. Maybe the idea was to safe stack trace (#787)?
If yes maybe `InnerException` can be dropped in favor of `ExceptionDispatchInfo.Throw`...

**Comment by louthy** [comment]
I've deprecated `InnerException` and added a `Rethrow` extension to `Exception` which uses:
```c#
ExceptionDispatchInfo.Capture(exception).Throw()
```
... to keep the exception context (negating the need for `InnerException`).
