### ISSUE TITLE
Stackoverflow using Union code-gen CompareTo

### ISSUE THREAD

**Issue by appetere** [louthy/language-ext#798]
To reproduce:-
    LanguageExt.CodeGen (3.4.20-beta)
    LanguageExt.Core (3.4.14)
   .NET Standard 2.0 library

Create a Union:

        [Union]
        public interface State
        {
            State Idle();
            State LoggedIn();
        }

Run this code:

            LoggedIn loggedIn = LoggedIn.New();
            State state = (State)loggedIn;
            var result = loggedIn.CompareTo(state);

This causes a stack-overflow with the `CompareTo(object obj)` method recursively calling itself.

For reference, the `LoggedIn` state generated implementation has:

            public int CompareTo(object obj) => obj is State p ? CompareTo(p) : 1;
            public int CompareTo(LoggedIn other)
            {
                if (LanguageExt.Prelude.isnull(other))
                    return 1;
                // etc

This is possibly related to https://github.com/louthy/language-ext/issues/797

**Comment by louthy** [comment]
That's fixed in the `beta` I believe
