### ISSUE TITLE
Serialization

### ISSUE THREAD

**Issue by ncthbrt** [louthy/language-ext#80]
Serialization and Derialization is a common activity in the .NET world. As it is IO and hence more susceptible to faulty, invalid or null input, it would be nice if LanguageExt's Option, Some and other classes all supported serialization, which is as simple as adding an attribute to each class. 

I do not mind modifying the code and submitting the pull request myself, but I thought I'd check with you first, as I'd like this ideally to be available on Nuget.

Thank you

**Comment by louthy** [comment]
@ncthbrt - Hi Nick, I had actually removed the Serialization attribute when updating the project to support DNX.  It seems the Serialization attribute is on its way out, and isn't supported in DNX.  I guess most serialisation is done with Json.NET or similar these days.

Anyway, I've now restored it for non-DNX builds.  Please grab the latest version from nu-get: 1.7.29

**Comment by ncthbrt** [comment]
Thanks Paul. Good to hear about its depreciation.
