### ISSUE TITLE
How much will the new C#9 features change the way we use LanguageExt?

### ISSUE THREAD

**Issue by MrYossu** [louthy/language-ext#800]
I was just reading about [the upcoming C#9](https://devblogs.microsoft.com/dotnet/welcome-to-c-9-0/), and am amazed how much it's looking like F#! The C# team are really going heavily into functional programming (hurray) at last. The only major feature I can see that's missing are discriminated unions, but I guess that those will come along at some point.

Once C#9 is released, how much will it affect this package? There are some features there that cover some of the issues that LanguageExt seems to have been designed to fix.

Any comments from the experts?

**Comment by louthy** [comment]
Many things that I've put into language-ext, or written about, has now got some direct language support:

* [poor tuple support](https://github.com/louthy/language-ext#poor-tuple-support) - C# now supports `(1,2,3)`
* [null reference problems](https://github.com/louthy/language-ext#null-reference-problem) - C# now has _nullable references_
* [if( arg == null ) throw new ArgumentNullException("arg")](https://github.com/louthy/language-ext#if-arg--null--throw-new-argumentnullexceptionarg) - C# now has exceptions that can work in expressions
* [Record<A>](https://github.com/louthy/language-ext#recorda) - C# now has support for records
* [ad-hoc polymorphism](https://github.com/louthy/language-ext#ad-hoc-polymorphism) - C# team is championing ['Roles, Extension Intefaces, and Static Interface members'](https://github.com/dotnet/csharplang/issues/1711) which allows for ad-hoc polymorphism

> Not that I'm claiming the C# team is following the lang-ext playbook, by the way.  But it is scary how my list of issues with C# is being progressively worked through by the C# team ;)  

Some aspects of language-ext are now not required, like using `Tuple(1, 2)` to construct tuples.  Over time some things might get deprecated, but ultimately functional C# still needs a functional base-class library.  This is true in all other functional languages, they all have a core `Prelude` which brings in the common tools, and libraries that support features like immutable collections.  

And so, the future of language-ext will continue to provide a more comprehensive feature-set of types and functions that promote functional programming in C#.  I will, of course, adapt language-ext to these new language features where appropriate.  The next big job is working out how to make the library play nice with nullable references.  Another example would be the features of language-ext's records that aren't in C#'s records, so I will look to supplement the core language's features too.

Ultimately, if the C# team can allow me to remove code from this library, that's awesome.  But it'll never get to the point where the library isn't needed.

**Comment by MrYossu** [comment]
Hi Paul, thanks for the reply.

>Not that I'm claiming the C# team is following the lang-ext playbook, by the way.

It wouldn't surprise me in the least if they were keeping a keen eye n this project and taking ideas. By your own admission, LanguageExt has become the de-facto standard for FP in C#. Given the way Microsoft are embracing FP, it makes sense that they would watch this project.

Anyway, don't do yourself down, take a bit of credit!

>But it is scary how my list of issues with C# is being progressively worked through by the C# team ;)

Scary? I think it's fantastic. Not that I want to do you out of your project, but it's wonderful to see C# moving in this direction.

All we need now are discriminated unions and my cup of happiness would overflow!
