### ISSUE TITLE
missing async overloads for fluent some and none

### ISSUE THREAD

**Issue by cubed-it** [louthy/language-ext#801]
Hey I just started using your libraray to minimize this annoying null reference problem.
So far everything works fine, good work!

But I have a first question:
Here's what I can write:
```
            result = await testi.MatchAsync(Some: async x => 
            {
                return await Task.FromResult(12);
            },
            None: () => 1);
```
The some case produces a Task<int> while the none case just an int.

But I cannot express this in the fluent variant, because the none case does not offer a suitable overload out of the box.
Would it be possible to achieve this in the fluent variant, or am I missing something?
What I can do:
```
            result = await testi.Some(async x => 
            {
                return await Task.FromResult(12);
            })
            .None(Task.FromResult(1));
```
Task.FromResult(1) is not nice to write or read. So what I would like to do is:
```
            result = await testi.Some(async x => 
            {
                return await Task.FromResult(12);
            })
            .None(1);
```

**Comment by louthy** [comment]
The fluent overrides definitely cover a smaller set than the `Match` variants.  You can use `val.AsTask()` in the meantime, which still isn't quite as pretty, but it's less bad than `Task.FromResult(1)`

**Comment by cubed-it** [comment]
Okay, thanks for the feedback. I can live with the MatchAsync variant, I was just a little confused.
If some day a SomeAsync falls from the sky, I wouldn't be averse to it. I would even create a PR, but the code base looks a bit complex for a quick add 👌
Feel free to close the issue anytime.

AsTask() is indeed less bad. Obviously another useful language-ext feature. 👍
