### ISSUE TITLE
HashSet does not serialize & deserialize with JsonConvert

### ISSUE THREAD

**Issue by appetere** [louthy/language-ext#802]
When `HashSet<T>` is serialized and then deserialized with JsonConvert, the HashSet does not deserialize correctly.

The following XUnit tests (_which are set to pass when serialization fails_) illustrate the problem.  I've tried `HashSet<string>` and `HashSet<Guid>` with the same results:

    using Newtonsoft.Json;
    using System;
    using Xunit;
    using static LanguageExt.Prelude;

    namespace Tests
    {
        public class SerializationTests
        {
        [Fact]
        public void HashSet_WithDefaultSettings_WillNotSerialize()
        {
            var source = HashSet(Guid.NewGuid(), Guid.NewGuid());
            var json = JsonConvert.SerializeObject(source);
            var result = JsonConvert.DeserializeObject(json);

            // Expected: HashSet<Guid> [5c18c141-63c2-4758-8968-2bd14dd0f0bc, 4adb9705-13cb-4d5e-ae58-fc2d369dafca]
            // Actual: JArray[[], []]
            Assert.NotEqual(source, result);
        }

        [Fact]
        public void HashSet_WithEchoCustomSettings_WillNotSerialize()
        {
            // From https://github.com/louthy/echo-process/blob/main/Echo.Process/ActorSys/ActorSystemConfig.cs
            var settings = new JsonSerializerSettings
            {
                TypeNameHandling = TypeNameHandling.All,
                TypeNameAssemblyFormatHandling = TypeNameAssemblyFormatHandling.Simple,
                MissingMemberHandling = MissingMemberHandling.Ignore
            };

            var source = HashSet(Guid.NewGuid(), Guid.NewGuid());
            var json = JsonConvert.SerializeObject(source, settings);

            Assert.Throws<JsonSerializationException>(() => JsonConvert.DeserializeObject(json, settings));
        }
    }

**Comment by louthy** [comment]
This is fixed in `v3.5.20-beta`

Note: 

```c#
JsonConvert.DeserializeObject(json, settings)
```
Needs to be typed:
```c#
JsonConvert.DeserializeObject<HashSet<Guid>>(json, settings)
```
