### ISSUE TITLE
Nullable primitive inside [Record]

### ISSUE THREAD

**Issue by ipostanogov** [louthy/language-ext#805]
Making primitive types nullable leads to CS1001 CS1003:

```csharp
using LanguageExt;

namespace NullableDemo
{
    [Record]
    public partial class Foo
    {
        public readonly long? Bar;
    }
}
```

```xml
<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>netcoreapp3.1</TargetFramework>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="LanguageExt.CodeGen" Version="3.4.15" PrivateAssets="all" />
        <PackageReference Include="CodeGeneration.Roslyn.BuildTime" Version="0.6.1" PrivateAssets="all" />
        <DotNetCliToolReference Include="dotnet-codegen" Version="0.6.1" />
    </ItemGroup>

</Project>
```

The error in the generated code is here
```csharp
        public Foo With(long? ? Bar = null) => new Foo(Bar ?? this.Bar);
```

The related discussion was [here](https://gitter.im/louthy/language-ext?at=5f4cacb949a1df0a12bae096).

**Comment by louthy** [comment]
@ipostanogov [Fixed in `3.5.15-beta`](https://github.com/louthy/language-ext/commit/7be645261bb8edfd457cc04c5e0d3e558e621da8) on nu-get now.

__NOTE__: Nullable fields can only be _set_ with the `With` method.  They can't be cleared to `null`.  You would need to add your own setters for that.
