### ISSUE TITLE
Argument is not passed in Concurrency Prelude.Ref

### ISSUE THREAD

**Issue by MarcinGajda36** [louthy/language-ext#806]
I noticed bug in LanguageExt.Core\Concurrency\Prelude.cs where on line 67 methods receives 'validator' argument but is not passing it forward.

**Comment by MarcinGajda36** [comment]
i created pr for this, https://github.com/louthy/language-ext/pull/807  i am new here so not sure how can i connect pr to issue

**Comment by bender2k14** [comment]
Here is the [documentation for linking an issue to a PR](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) on GitHub.

I recommend putting `Fixes #806` as the first line in https://github.com/louthy/language-ext/pull/807#issue-482972500 as [described here](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

**Comment by MarcinGajda36** [comment]
Thank you, i linked pr to issue now.
