### ISSUE TITLE
TypeInitializationException: The type initializer for 'LanguageExt.ClassInstances.Class`1' threw an exception.

### ISSUE THREAD

**Issue by vitalmiguel** [louthy/language-ext#809]
Hello everyone,

I've been using this library for some months now but I can't go full functional because some of the features doesn't work like Records, Map, etc.
For now I've been using Map,Bind,Traverse and so on extensions without any problem. I can also create sequences.
But things like records, descriminated unions, Map and others I get a lot the following error:

`TypeInitializationException: The type initializer for 'LanguageExt.ClassInstances.Class`1' threw an exception.`

I've already created a new solution with a console application and everything works fine, but I really need this to work on our current solution.

I installed the latest (3.5.16-beta) and still no luck.

I've done this easy to understand request to show you what's happening.

![imagem](https://user-images.githubusercontent.com/5750030/93361118-6259cd00-f83c-11ea-8691-a22db43a7c96.png)

RecordTest class:
![imagem](https://user-images.githubusercontent.com/5750030/93362050-718d4a80-f83d-11ea-8bac-50df157a67b1.png)

Right now I only have installed the LanguageExt.Core package, I do understand that to have Discriminated Union and some other stuff I need roslyn and I've already done that also. But currently I don't have it cause I can't put things to work.

Stack:
```
System.TypeInitializationException
  HResult=0x80131534
  Message=The type initializer for 'LanguageExt.RecordTypeEqualityTyped`1' threw an exception.
  Source=LanguageExt.Core
  StackTrace:
   at LanguageExt.RecordType`1.get_EqualityTyped()
   at LanguageExt.Record`1.op_Equality(Record`1 x, Record`1 y)

Inner Exception 1:
TypeInitializationException: The type initializer for 'LanguageExt.ClassInstances.Class`1' threw an exception.

Inner Exception 2:
NullReferenceException: Object reference not set to an instance of an object.
```

If you need more information to resolve this issue pls let me know. I'd really appreciate any help.

**Comment by louthy** [comment]
What framework are you using?

**Comment by vitalmiguel** [comment]
I'm using netcoreapp3.1

**Comment by louthy** [comment]
I'm able to repro this, so hopefully it'll be resolved today.

**Comment by louthy** [comment]
Fixed in `v3.5.19`

**Comment by vitalmiguel** [comment]
It's working @louthy ! 
Thanks a lot for putting your effort into this issue and being so fast at resolving it.

**Comment by louthy** [comment]
@vitalmiguel  No problem, glad it's working!  btw, you don't need to make your records `partial`, that's only if you're using the code-gen `[Record]` feature.
