### ISSUE TITLE
async example

### ISSUE THREAD

**Issue by cocogorilla** [louthy/language-ext#81]
In TryMonadTests.cs strating line 151, there was a very helpful chain for the try and use scenarios.  I would benefit from seeing an example using HttpClient which all but forces the use of async/await.  For at least my current project, I cannot adopt the .Process library and its components, but I'm very keen on pushing the use of Options, Eithers and the Try and Use patterns.  I've just encountered difficulty working with them in context of async/await, which forces me to return Task<T>.

Thank you

**Comment by louthy** [comment]
Have you considered converting your Tasks to Observables using Rx?  I'm not near an editor at the moment so can't provide any examples.  Option has various MatchAsync and MatchObservable extensions which may be worth looking at too (not sure if I got around to putting them into Either).  

I suspect what you actually need is an Async monad type, that can work with the monad transformer system.  That would allow for Async<Option<T>>.  I'll have a think about that tomorrow.

**Comment by louthy** [comment]
@cocogorilla I have added `Task<T>` extension methods to LanguageExt.Core that turn it into a monad.  And have added the standard set of functions that work with the higher-kinded type system, so you get to work with `Option<Task<T>>` and `Task<Option<T>>` as though they were a single value.

Here's a simple example with `Task<int>` and `Task<Option<int>>`.  Note that `Action3()` returns an `Option<int>`, so it then needs to be unwrapped in the select.  The result of the computation is `Task<Option<int>>`.  

```C#
        public void TaskLINQTest2()
        {
            var computation = from x in Action1(0)
                              from y in Action2(x)
                              from opt in Action3(y)
                              select from z in opt 
                                     select x + y + z;

            Assert.True(computation.Result == 10);
        }

        public async Task<int> Action1(int x)
        {
            await Task.Delay(100);
            return x + 1;
        }

        public async Task<int> Action2(int x)
        {
            await Task.Delay(200);
            return x + 2;
        }

        public async Task<Option<int>> Action3(int x)
        {
            await Task.Delay(300);
            return x + 3;
        }
```

You mentioned the TryMonadTests, unfortunately that code didn't work, and has been fixed for both `Try<T>` and `Task<T>`.  This is the example with `Task<T>`:
```C#
        public Task<IEnumerable<string>> getURLContent(string url) =>
            from u in parseUri(url)
            from conn in openConnection(u)
            from result in use(
                getInputStream(conn),
                stream => use(getSource(stream), getLines)
                )
            select result;

        [Fact]
        public void UrlTest()
        {
            getURLContent("http://www.google.com").IterT(x => Console.WriteLine(x));
        }
```
Notice how `getURLContent` returns `Task<IEnumerable<string>>`, but I'm able to iterate the wrapped list.  

You need to include `LanguageExt.Trans` if you want to use the transformer functions (the functions that work on wrapped monads and are appended with the `T`).

The available `Task<T>` functions are:

| `Task<T>` extension | `Task<M<T>>` transformer | `M<Task<T>>` transformer |
| ----------------------------| ------------------------------------| -------------------------------------|
| `Select`                     | n/a                                      | n/a |
| `SelectMany`             | n/a                                      | n/a |
| `Where`             | n/a                                      | n/a |
| `Map`             | `MapT`                                     | `MapT` |
| `Filter` | `FilterT` | `FilterT` | 
| `Bind` | `BindT` | `BindT` | 
| `Fold` | `FoldT` | `FoldT` | 
| `Iter` | `IterT` | `IterT` | 
| `Sum` | `SumT` | `SumT` | 
| `Count` | `CountT` | `CountT` | 
| `Exists` | `ExistsT` | `ExistsT` | 
| `ForAll` | `ForAllT` | `ForAllT` | 


| Prelude | `Task<M<T>>` transformer | `M<Task<T>>` transformer |
| ----------------------------| ------------------------------------| -------------------------------------|
| `map`             | `mapT`                                     | `mapT` |
| `filter` | `filterT` | `filterT` | 
| `bind` | `bindT` | `bindT` | 
| `fold` | `foldT` | `foldT` | 
| `iter` | `iterT` | `iterT` | 
| `sum` | `sumT` | `sumT` | 
| `count` | `countT` | `countT` | 
| `exists` | `existsT` | `existsT` | 
| `forall` | `forallT` | `forallT` | 

The latest is on nu-get now (1.7.37)

**Comment by cocogorilla** [comment]
I slightly modified the tests and had trouble getting them to work.  I
thought for certain the second version would work... yet it did not appear
to.

        [Fact]
        public void UrlTest()
        {
            var results = new List<string>();
            var lines = getURLContent("http://www.google.com").IterT(
                (x) => results.Add(x));
            Assert.NotEmpty(results);
        }

        [Fact]
        public async void UrlTestAsync()
        {
            var results = new List<string>();
            var lines = await getURLContent("http://www.google.com");
            lines.Iter(
                (x) => results.Add(x));
            Assert.NotEmpty(results);
        }

btw, awesome work, way above and beyond what I anticipated, and in short
order as well.

Thanks,

-Ethan Nelson

**Comment by louthy** [comment]
Sorry I should have said, the test is just an example of use/Lina/etc with tasks, it doesn't do the bit where it requests anything from the domain (didn't want to get bogged down on the streaming bit).  Let me know if it's still unclear and I'll work on some examples tomorrow.

> btw, awesome work, way above and beyond what I anticipated, and in short
> order as well.

No probs. I tend to try to fill the gaps in the library as I come across them in real world use, but we all write code differently so when an idea comes along I'll grab it :)

**Comment by louthy** [comment]
@cocogorilla Hi Ethan, just to follow up on this (I was replying from my phone last night, so couldn't give much info).  The example in the unit tests file was primarily a demo from a previous conversation comparing Scala `Try` to lang-ext `Try` (see here)[https://github.com/louthy/language-ext/issues/33]

For a fully working example, that works better in .NET world you could try this.  It fully disposes the `WebClient` after use and also demos `MapT`, `SumT` and `IterT`.  
```C#
        Task<Uri> parseUri(string uri) => 
            new Uri(uri).AsTask();

        Task<WebClient> getClient() =>
            Task.FromResult(new WebClient());

        Task<string> getContent(Uri uri, WebClient client) =>
            client.DownloadStringTaskAsync(uri);

        Task<Lst<string>> getLines(string text) =>
            Task.FromResult(text.Split('\n').Freeze());

        Task<Lst<string>> getURLContent(string uri) =>
            from address in parseUri(uri)
            from result  in use(
                getClient(),
                client => from content in getContent(address, client)
                          from lines   in getLines(content)
                          select lines)
            select result;

        public void UrlTest()
        {
            // Iterates all lines of content
            getURLContent("http://www.google.com").IterT(x => Console.WriteLine(x));

            // Counts the number of lines
            int numberOfLines = getURLContent("http://www.google.com").CountT();

            // Maps the lines to line-lengths, then sums them
            int totalSize = getURLContent("http://www.google.com")
                                .MapT(x => x.Length)
                                .SumT();
        }
```

**Comment by cocogorilla** [comment]
Thanks. Post fact, I did sort of figure that out with a little
troubleshooting. Thanks again.

**Comment by ABIOLI-COM** [comment]
I have a curiosity about the code in the very first post.  
If I change that code to:  

```
public class Something
{
    public void TaskLINQTest2()
    {
        Task<Either<string, int>> computation =
                from x in Action1(1)
                from y in Action2(2)
                from z in Action1(3)
                select x + y + z;
    }

    public async Task<Either<string, int>> Action1(int x)
    {
        await Task.Delay(100);
        return x + 1;
    }

    public async Task<Either<string, int>> Action2(int x)
    {
        await Task.Delay(200);
        return x + 2;
    }

    public async Task<Either<string, int>> Action3(int x)
    {
        await Task.Delay(300);
        return x + 3;
    }
}

```

I get an error on the call to Action2:   

error CS1940: Multiple implementations of the query pattern were found for source type 'Task<Either<string, int>>'.  Ambiguous call to 'SelectMany'.
  
I really cannot track it down to what it is...

**Comment by louthy** [comment]
It is very strange, because I have [almost exactly the same code working in the unit-tests](https://github.com/louthy/language-ext/blob/bd31a0b85c3866554292c45f77c9a14fec8d3f2c/LanguageExt.Tests/IssuesTests.cs#L30):

I have got your code and the unit-test code side-by-side, the unit-test code compiles, but yours doesn't.  And it's not entirely clear why.  I know which two `SelectMany` calls that are conflicting, it's the transformer version and the `Task` version of `SelectMany`.

To be honest, I am minded to remove the transformer versions, as they were probably a bad decision born out of the lack of pre-built transformer monads like `EitherAsync`.  This works:
```c#
    static EitherAsync<string, int> computation =
        from x in Action1(1).ToAsync()
        from y in Action2(2).ToAsync()
        from z in Action3(3).ToAsync()
        select x + y + z;
```
Still, I am confused as to why it works for this, and not for yours:
```c#
        public Task<Either<Exception, int>> Issue207_2() =>
            from us in Initialization
            from mu in createUserMapping(us).AsTask()
            from id in addUser(mu)
            select id;
```
So, my advice would be to use `EitherAsync`, as I'll probably remove the transformer `SelectMany` extensions.
