### ISSUE TITLE
Deserialization problem in Blazor application using Record-derived class with GetFromJsonAsync

### ISSUE THREAD

**Issue by ABIOLI-COM** [louthy/language-ext#811]
I don't know if you checked this scenario, or if I'm making something wrong, but when deserializing a call to GetFromJsonAsync (it should be a normal server call with a deserialization) I don't get back the original items.  
My class is like:  

```
public TestClass : Record<TestClass>
{
    ...
    public readonly string SomeField;
    ...
}
```

so very normal. The data comes back from the server (I can check in google chrome developer tools), but then I get different errors depending on what I try.  
I tried adding  

```
public AppMessage(SerializationInfo info, StreamingContext context)
            : base(info, context) { }

```

and no luck.  
I tried changing the properties to something like  

`public string SomeField { get; private set; }
`

and no luck again.

I then added an empty constructor, just to see if with that, it could work. No luck again.
I don't know what to try, now... :-)

Thanks
Andrea

**Comment by ABIOLI-COM** [comment]
...I add that if I make the properties writable,

`public string SomeField { get; set; }`

with the empty constructor, everything works fine. May I suspect that the new json serializer doesn't use the 'canonical' approach?

**Comment by louthy** [comment]
Try this:
```c#
public TestClass : Record<TestClass>, ISerializable 
{
   ...
}
```
The reason `ISerializable` isn't in implemented interfaces of `Record<>` is because JSON.NET freaks out.  So, if you're using something other than JSON.NET then you also need to add `ISerializable` to the inheritance list.  _Should_ work, but let me know if it doesn't.

**Comment by ABIOLI-COM** [comment]
Thank you for your fast response, and your support.
Unfortunately, it still works only if the property is writeable... :-( (Just to check if I made some other error...)
