### ISSUE TITLE
New feature - Support Option(null) construction.

### ISSUE THREAD

**Issue by JohnSColeman** [louthy/language-ext#815]
In Scala an Option can be constructed from a null reference which is typically used for wrapping return values from unsafe library calls.

`if (Option(null) == None) println("true"); // prints true`

This would be a useful addition.

**Comment by TysonMN** [comment]
With `using static LanguageExt.Prelude;` at the top of the file, have you tried using [`Optional`](https://github.com/louthy/language-ext/blob/3df8c837961a502d7a03268b6cac636a57c49056/LanguageExt.Core/DataTypes/Option/Option.Prelude.cs#L117-L120)?  It would look like this.
```csharp
if (Optional(null) == None) println("true"); // prints true
```

**Comment by JohnSColeman** [comment]
@TysonMN Thanks, I just saw that after digging into the code.
