### ISSUE TITLE
Does memo correctly memoize a recursive function?

### ISSUE THREAD

**Issue by khtan** [louthy/language-ext#819]
Hi,

I am not sure if this is a problem or just need some clarifications. I hope it is OK to submit this as an issue.

Consider the classical recursive function fib ( for Fibonacci ). It takes an int and returns a long.

If I memoize it, it would be like:  var memo_fib = Prelude.memo<int, long>(fib).
However if memo_fib is called, like memo_fib(50), the memoized function is only called once, and the fib internally calls itself, thus not able to use the memoization. Is this a limitation of memo or am I not using it correctly?

I attach a test file, MemoizeRecursiveFunction.cs, that can be dropped into the language-ext/LanguageExt.Tests folder to be run to illustrate the results that I am getting. Also attached is a picture of my VS Community with the test run results on my end.

![MemoizeRecursiveFunctionTests](https://user-images.githubusercontent.com/8535034/97098804-8334ef80-163e-11eb-839c-70c2eb325f10.png)
[MemoizeRecursiveFunctionTests.cs.log](https://github.com/louthy/language-ext/files/5434163/MemoizeRecursiveFunctionTests.cs.log)

Note I added a .log extension to the .cs so that Github would allow the file to be uploaded.

Thanks in advance,

**Comment by louthy** [comment]
@khtan  `memo<A, B>` memoises using a weak-ref dictionary, so that it frees up objects on a GC collect.  This stops it being a potential source of memory leaks.  You can use `memoUnsafe<A, B>` for behaviour you expect.

**Comment by khtan** [comment]
@louthy Thanks for your reply. I added a test "test_unsafememo_fib2_50" to use the memoUnsafe and got the same performance as the memo wrapped call, around 2.3 min.

I still suspect that because fib2 is recursive and calls itself, the memo-wrapped version only got called once, and thereafter, fib2 called itself. 

Attached updated MemoizeRecursiveFunctionTests.cs.log. ( Remove .log extension before dropping into LangaugeExt.Tests folder )
[MemoizeRecursiveFunctionTests.cs.log](https://github.com/louthy/language-ext/files/5461124/MemoizeRecursiveFunctionTests.cs.log)

**Comment by StefanBertels** [comment]
`memo` will not change the original function but create a caching wrapper function. You want to recursively call the (memo) wrapper. Fast fib2:

```
static Func<int, long> memo_fib2 = Prelude.memo<int, long>(n => n < 2 ? n : memo_fib2(n-1) + memo_fib2(n-2));

[Fact]
public void test_memo_fib2_50()
{
    Assert.Equal(12586269025, memo_fib2(50)); // 97ms
}
```
