### ISSUE TITLE
[Question] BottomException when using BindT on Either<L, Option<R>>

### ISSUE THREAD

**Issue by KiritchoukC** [louthy/language-ext#826]
Hi,

I'm just playing around with the library and I have to say it's a lot of fun 🙂.

But there is one thing I'm struggling with...

Context: 
I want to 
- retrieve bytes from cache
- decode bytes to string
- deserialize string to object

Here's how I tried to do it:
```csharp
public async Task<Either<CacheFailure, Option<T>>> GetAsync()
{
    var fetchBytes = fun(async () => await GetCacheAsync()));

    var decodeBytes = fun((byte[] bytes) => DecodeBytesToString(bytes).Map(Optional));

    var deserializeString = fun((string json) => DeserializeStringToObject<T>(json).Map(Optional));

    return
        from bts in (await fetchBytes())
        from str in decodeBytes(bts)
        from obj in deserializeString(str)
        select obj;
}
```

When there is no data cached yet, the `GetCacheAsync` method returns `Right(None)`
but then, when going through the `decodeBytes` method, I get a bottom state.
I expected that `Right(None)` would short-circuit the workflow.

Any help is greatly appreciated

**Comment by louthy** [comment]
Monads don't delve automatically into the wrapped monads, so `Right` means continue, doesn't matter what value it wraps.  So returning `Left` from `fetchBytes` is what you'd need to short-cut this.  

This properly handles failure at various points:

```c#
    public enum Failure
    {
        CacheFailure,
        InvalidByteString,
        DeserialisationError
    }

    public static EitherAsync<Failure, byte[]> fetchBytes() =>
        Failure.CacheFailure;

    public static Option<string> decodeBytes(byte[] bytes)
        DecodeBytesToString(bytes);

    public static Option<T> deserializeString<T>(string str)
        DeserializeStringToObject(bytes);

    public static EitherAsync<Failure, T> GetAsync<T>() =>
        from bts in fetchBytes()
        from str in decodeBytes(bts).ToAsync().ToEither(Failure.InvalidByteString)
        from obj in deserializeString<T>(str).ToAsync().ToEither(Failure.DeserialisationError)
        select obj;
```
* It uses `EitherAsync<..>` which is a more powerful type than `Task<Either<...>>`
* The non-async functions of `decodeBytes` and `deserializeString` are simply `Option` returning functions
   * They get lifted, first with: `ToAsync()` which turns an `Option<A>` into an `OptionAsync<A>` and then with `ToEither` which turns an `OptionAsync<A>` into an `EitherAsync<L, A>`.  It allows you to provide a meaningful `Left` value which is your error.
* The return type of `GetAsync` removes the `Option<T>` and instead is _either_ a `Failure` or a `T` result.

**Comment by KiritchoukC** [comment]
Thanks @louthy for taking the time to respond to me.

I really need the signature to be `EitherAsync<Failure, Option<T>>` because the fact that there is no cache is not a failure.
But now I know why it does not work, I'll adapt the code you provided.

Thanks again for this nicely done library 👍

**Comment by KiritchoukC** [comment]
If anyone is interested, I wrote those 2 extensions. It might be a bad thing to do... I don't know 🤷‍♂️

```csharp
public static Either<TFailure, Option<T>> BindO<TFailure, T>(
            this Either<TFailure, Option<T>> @this,
            Func<T, Either<TFailure, T>> f)
            => @this.Bind(opt => opt.Match(t => f(t).Map(Optional), () => Right(Option<T>.None)));

public static Either<TFailure, Option<TResult>> MapO<TFailure, TSource, TResult>(
            this Either<TFailure, Option<TSource>> @this,
            Func<TSource, Either<TFailure, TResult>> f)
            => @this.Bind(opt => opt.Match(t => f(t).Map(Optional), () => Right(Option<TResult>.None)));
```

And used them like this

```csharp
public async Task<Either<CacheFailure, Option<T>>> GetAsync()
            => (await CacheHelper.GetBytes(async () => await _cache.GetAsync(_cacheKey)))
                .MapO(CacheHelper.DecodeBytesToString)
                .MapO(CacheHelper.DeserializeStringToObject<T>);
```

please don't hurt me FP people.

**Comment by louthy** [comment]
Those functions exist already, BindT and MapT.

There’s a mass of generated ‘transformer’ extension methods, that will work with any two nested monadic types (from this library)

There’s also FoldT, FoldBackT, FilterT, ForAllT, ExistsT, CountT, SumT, PlusT, etc. all to make nested monads slightly easier to work with.

**Comment by KiritchoukC** [comment]
Yes, I already use some of them but in this case, it doesn't do what I'm expecting.

I guess I need to play a bit more and it will become natural to use those.
