### ISSUE TITLE
Feature: Create Validation<F,S> off List of <F>

### ISSUE THREAD

**Issue by gregberns** [louthy/language-ext#832]
I'd like to take a list of errors (say from a monaic Either - like a series of IO calls: IEnumerable<EitherAsync<Error, Unit>>), and create a Validation<Error, Unit>, if possible through the constructor.

Example:

```csharp
//Do several IO things (IEnumerable<EitherAsync<Error, Unit>>), get the errors out
IEnumerable<Error> es = ...;
// Take the errors and pass them directly into a validation:
return Validation<Error, Unit>(es);
```

My current solution is to apply all the errors with an Aggregate (`errors.Aggregate(Success<Error, Unit>(unit), (agg, error) => agg | errors)`).

```
IEnumerable<EitherAsync<Error, Unit>>
.Lefts()
.Bind(
    errors => errors.Count() == 0
        ? Right<Error, Unit>(unit).ToValidation().AsTask()
        : errors.Aggregate(Success<Error, Unit>(unit), (agg, error) => agg | errors).AsTask());
```

So, is there a way to take a list of errors and put them into a Validation in one go?

Or, is there a `SequenceLeft()` that would allow me to capture all the errors from a bunch of IO<Unit>? I've run into this several times now.

**Comment by TysonMN** [comment]
Is this what you want?
```csharp
IEnumerable<EitherAsync<string, Unit>> eithers = ...
Task<Validation<string, IEnumerable<Unit>>> validation =
    eithers
    .Map(e => e.ToValidation())
    .TraverseSerial(identity)
    .Map(x => x.Sequence());
```

**Comment by gregberns** [comment]
@TysonMN Brilliant! Looks like `TraverseSerial` is newer, I was on `3.4.15` and moved up to `3.5.20-beta` to get it.

I've wrote the implimentation for TraverseSerial and TraverseParallel several times now... thanks for helping me find these!

Heres a type-change description for each step, for anyone in the future:
```
// IEnumerable<EitherAsync<Error, Unit>>
.Map(e => e.ToValidation())
// IEnumerable<Task<Validation<Error, Unit>>>
.TraverseSerial(identity)
// Task<IEnumerable<Validation<Error, Unit>>>
.Map(x => x.Sequence())
// Task<Validation<Error, IEnumerable<Unit>>>
```

**Comment by TysonMN** [comment]
Before `TraverseSerial` and `TraverseParallel`, there was just `Sequence` (as the deprecation message on `Sequence` says), so you could try using that in older versions.
