### ISSUE TITLE
C# 9

### ISSUE THREAD

**Issue by snielsson** [louthy/language-ext#838]
Hi Paul, 
Do you have any thoughts about new  C# 9 features, such as Records and enhanced pattern matching and how they can be utilized in language-ext ?

**Comment by louthy** [comment]
@snielsson Records are just classes, so they can just be used as-is.  The lang-ext records have some additional functionality, but I'd expect most to move over to the built-in ones over time.  

C# pattern-matching can be leveraged with the lang-ext types by using the `.Case` property on most types.  For example with `Option`:
```c#
var result = option.Case switch
             {
                 int x => x,
                 _     => 0
             };
```
And `Seq`:
```c#
int Sum(Seq<int> values) =>
    values.Case switch
    {
        null                 => 0,              // []
        int x                => x,              // [x]
        (int x, Seq<int> xs) => x + Sum(xs),    // x:xs  i.e. (head, tail)
    };
```
This removes the need to call `Match` and allows a little more flexibility in terms of matching (`Case` can also be used with `is` expressions, for example)

**Comment by glen-nicol** [comment]
@louthy Hi there, where can I find docs or info on what criteria a type must have to make the matching above work? I am trying to make something like the following work:

```csharp
var option1 = Some(new Derived1());
var option2 = Some(new Derived2());

var result = (option1.Case, option2.Case) switch
    {
        (Derived1 d1, _) => d1,
        (_, Derived2 d2) => d2,
        (Derived1 d1, Derived2 d2) => Combine(d1, d2),
        (_,_) => throw new NotSupportedException(),
    };
```

But I get errors like this for the top 3 cases:

```
Error	CS8121	An expression of type 'OptionCase<Derived1>' cannot be handled by a pattern of type 'Derived1'.	
```

Is there a better way to do this sort of matching?

**Comment by louthy** [comment]
I’m assuming you’re not using the latest beta, OptionCase isn’t used any more

**Comment by glen-nicol** [comment]
I am using 3.4.15. Which I don't actually see a tag for. I see in the release notes for the beta the transistion from SomeCase<> to just using the type directly.

Was that the only change in the beta? Is it still beta because you haven't decided to keep it or not?

**Comment by louthy** [comment]
https://www.nuget.org/packages/LanguageExt.Core/3.5.27-beta

**Comment by glen-nicol** [comment]
Oh there are a couple versions since that one? Not sure what point you're making with the link. But regardless, for now I will probably stay on 3.4.15 since I figured out the SomeCase/NoneCase stuff. 

Thanks again for the help and for all the work on this library!
