### ISSUE TITLE
Code Generation on MacOS

### ISSUE THREAD

**Issue by gregberns** [louthy/language-ext#848]
I've fought for quite a while trying to get CodeGen setup and working on MacOS with VSCode. Maybe we can add some notes in the [wiki article setup section](https://github.com/louthy/language-ext/wiki/Code-generation#setup) to help others in the future.

On MacOS, CodeGen seems to need Mono installed. I had installed it via Homebrew but errors (`The command "dotnet codegen --version" exited with code 1.`) seemed to prevent it from working. But today when I installed Mono via the official installer things started to work. [Installer](https://www.mono-project.com/download/stable/). Other's have had similar issues with Homebrew Mono.

It also seems like the [CodeGeneration.Roslyn](https://github.com/AArnott/CodeGeneration.Roslyn) project isn't moving forward. Not sure if the [wiki article](https://github.com/louthy/language-ext/wiki/Code-generation#setup) is just out of date or 'its working' so nothing to do. Just wanted to point it out.

**Comment by AlexGS74** [comment]
Can you please provide more details on how to make it to work on MacOS?

**Comment by AlexGS74** [comment]
Oh, what finally worked for me is building a project with `dotnet build .` from a terminal with `DOTNET_ROLL_FORWARD Major` set. This added the codegen tooling and now all IDEs work too.
