### ISSUE TITLE
Tooling support (Sonar)

### ISSUE THREAD

**Issue by dhalsim** [louthy/language-ext#85]
Hello,

To be able to use LanguageExt Immutable Collections (or Immutable Collections) we need to check the returning method's returning value is used or not. After that, a migration could be done without breaking existing code confidently.

I believe Resharper has this ability but as in our company we don't use it and we use this tool [SonarQube](http://www.sonarqube.org/) which is open source. So I found a Visual Studio extension for Sonar [here](https://github.com/SonarSource-VisualStudio/sonaranalyzer-csharp). 

And I found the related rule [here](http://www.sonarlint.org/visualstudio/rules/index.html#sonarLintVersion=2.1.0&ruleId=S2201).

This rule were checking value types' (and string's) methods in addition to ImmutableCollection types. But it wasn't working as expected. So I fixed it and added LanguageExt Immutable Collection types, too!

So you can check SonarSource-VisualStudio/sonaranalyzer-csharp#864 this pull request. I will close this issue once it will be accepted.

**Comment by louthy** [comment]
@dhalsim I think looking at the [link you posted](http://www.sonarlint.org/visualstudio/rules/index.html#sonarLintVersion=2.1.0&ruleId=S2201) it would make more sense for me to annotate the library with `[Pure]` attributes.  I had noticed those attributes in the BCL, but wasn't sure what the BCL team were using them for (other than internal tooling); suddenly it's a bit clearer!  

I'm currently midway through a few large changes on the multi-system branch.  Once that's settled down I'll start the annotations.

**Comment by louthy** [comment]
@dhalsim All pure functions in the Core library are now annotated with the `[Pure]` attribute which should hopefully solve your problem (v1.8.17-beta on nu-get).
