### ISSUE TITLE
[Feature request] Implement GitHub DevSecOps pipeline

### ISSUE THREAD

**Issue by aleks-ivanov** [louthy/language-ext#851]
#### 1. Outstanding issues

- no code quality assessment
- no third-party dependencies version management
- no security vulnerabilities discovery
- manual and error-prone deployment process

#### 2. Proposed improvements

Introduce DevSecOps pipeline utilizing free licenses for industry-standard DevSecOps tools with GitHub Actions:

1. Continuous Integration

- [CodeQL](https://securitylab.github.com/tools/codeql) - GitHub Actions' own native industry-leading static analysis engine
- [Dependabot](https://dependabot.com/) - GitHub Actions' own native dependency version and security update service

2. Continuous Deployment

- Automatic release - gathering all necessary artifacts and release information, safely tagging and publishing a complete, [GitHub release in your repository](https://docs.github.com/en/github/administering-a-repository/about-releases)
- Automatic package deployment - seamless and safe deployment to any package management system (e.g. NuGet, npm, Maven etc.)

3. General

- CI/CD Documentation - complete, step-by-step guide for every feature
- Free support included (up to 1 year)

Aleks from [Pipeline Foundation](https://pipeline.foundation/)

**Comment by TysonMN** [comment]
Hello @AleksIvanovSinglet.  Thanks for the suggestions.  Would you be willing to implement your proposal?

**Comment by AleksIvanovSinglet** [comment]
Hi @TysonMN ,
We would be happy to :)

**Comment by louthy** [comment]
No adverts here.

**Comment by kulov** [comment]
Hi @louthy,  @TysonMN,

[Pipeline Foundation](https://pipeline.foundation) is a non profit initiative that aims to help OSS projects with their DevSecOps pipelines.
There are no obligations and strings attached.
Please check out our latest implementation here.
https://github.com/JasonStein/Notepads/pull/760

If you are willing to reconsider, we will be happy to provide assistance to you.

**Comment by TysonMN** [comment]
That PR is yet to be completed. Can you share a link to a PR of yours that was recently completed?

**Comment by kulov** [comment]
@TysonMN, it is brand new initiative.
Work is still in progress.
I will update here when we have final delivery.
