### ISSUE TITLE
Either: How to indicate success/failure from a void method?

### ISSUE THREAD

**Issue by MrYossu** [louthy/language-ext#853]
Simple question. Suppose I have a method that does not return data, for example...

```
public async Task SaveCustomer(Customer customer) {
  // Save customer to the database
}
```

Now I want the return type to indicate if the operation succeeded. The obvious choice seems to be an `Either`, but that has two generic types, one usually used for the returned data, and one for the data. However, as I don't have any data to return, it seems pointless having a generic type that I won't use.

I don't think `Try` would be the right thing, as that assumes a return type for the happy path, whereas I don't have one. I only want to return something (an error message) if the operation failed.

Anyone able to advise? Thanks

**Comment by TysonMN** [comment]
> I don't think `Try` would be the right thing, as that assumes a return type for the happy path, whereas I don't have one. I only want to return something (an error message) if the operation failed.

This tells me that you are not thinking functionally.  The functional style to always return something.  That something can be a representation of nothing, which is also called `Unit`.

I think you want the return type to be `Either<string, unit>`.

**Comment by MrYossu** [comment]
> This tells me that you are not thinking functionally.
Probably, still trying to hammer this stuff into my thick head!

> The functional style to always return something. That something can be a representation of nothing, which is also called `Unit`.
> 
> I think you want the return type to be `Either<string, unit>`.

OK, thanks. I knew it had to have a simple answer 😀

**Comment by MrYossu** [comment]
Quick follow-up if you don't mind.

The previous, not-very-functional incarnation of this method had a return type of `Task<(bool, string)>`, which I was using as follows...

      (bool success, string errors) = await ViewModel.OnSubmitPersonalDetails(ec);
      if (success) {
        NavManager.NavigateTo("/Investors");
      } else {
        _inform.Display("Error saving the details: " + errors);
      }

`NavManager.NavigateTo` is a void method that navigates to another page (this is Blazor), and `_inform.Display` is a void method on a Blazor component.

Now I have changed the method to return an `Either<string, Unit>`, how do I do this?

I tried the following..

      Either<string, Unit> result = await ViewModel.OnSubmitPersonalDetails(ec);
      result.Match(
        NavManager.NavigateTo("/Investors"),
        errors => _inform.Display("Error saving the details: " + errors)
      );

...but that gave a compiler error "cannot convert from 'void' to 'System.Action<LanguageExt.Unit>'" on the line that calls `NavManager.NavigateTo`.

What should I do? Thanks again.

**Comment by MrYossu** [comment]
Duh, just realised that it should be this...

      result.Match(
        _ => NavManager.NavigateTo("/Investors"),
        errors => _inform.Display("Error saving the details: " + errors)
      );

Is that right? Thanks again.

**Comment by TysonMN** [comment]
Yes, that looks correct to me.

**Comment by MrYossu** [comment]
thanks
