### ISSUE TITLE
`Seq<T>.Take(int amount)` behaves inconsistently when `amount > Seq<T>.Count`

### ISSUE THREAD

**Issue by CK-LinoPro** [louthy/language-ext#859]
I've noticed that `Seq<T>.Take(int)` behaves incensistently depending on how the instance of `Seq<T>` is constructed.

In C# interactive:
``` cs
> var enumerable = Range(1, 5);
> var seqFromEnumerable = enumerable.ToSeq();
> var seqRaw = Seq(1, 2, 3, 4, 5);
> var seqEmpty = LanguageExt.Seq<int>.Empty;
> void Print(object o) => Console.WriteLine(o);
> string EnumerableToString<T>(IEnumerable<T> s) => "[" + string.Join(", ", s) + "]";
> Print(enumerable.Take(10).Apply(EnumerableToString));
[1, 2, 3, 4, 5]
> Print(seqFromEnumerable.Take(10));
[1, 2, 3, 4, 5, 0, 0, 0, 0, 0]
> Print(seqRaw.Take(10));
[1, 2, 3, 4, 5]
> Print(seqEmpty.Take(10));
[]
```

**Comment by louthy** [comment]
Are you running the latest beta?  Some issues with Seq take we’re fixed a while back, this looks like the same issue

**Comment by CK-LinoPro** [comment]
I'm sorry, I've only tried the latest stable version, i.e. 3.4.15.
It works as expected in 3.5.27-beta, so I guess this issue can be closed.

Just from curiosity: do you have a rough idea of when there will be another stable version?

**Comment by louthy** [comment]
@CK-LinoPro The beta has been stable for a long time (my team have been using in production for months now).  It's ready to go, I just have a lot of documentation to write before I take it out of beta.

**Comment by CK-LinoPro** [comment]
Thanks for your reply. I'm afraid my team won't use a beta build, but it's fine. :)
Thank you for your effort!
