### ISSUE TITLE
Cannot implicitly convert type 'LanguageExt.Validation<LanguageExt.Common.Error, string>' to 'string'

### ISSUE THREAD

**Issue by MrYossu** [louthy/language-ext#861]
Using the credit card validation example as a base, I'm trying to write some code that reads data from an Excel spreadsheet and creates a set of `InvestorPayment` objects, one from each row.

I started with conversion functions, basically taken from that sample...

```c#
    private static Validation<Error, DateTime> ToDate(string val) =>
      parseDateTime(val).ToValidation(Error.New($"{val} is not a valid date"));

    private static Validation<Error, decimal> ToDecimal(string val) =>
      parseDecimal(val).ToValidation(Error.New($"{val} is not a valid number"));

    private static Validation<Error, int> ToInt(string val) =>
      parseInt(val).ToValidation(Error.New($"{val} is not a valid number"));
```

I then used these in functions that pull the value from a spreadsheet cell and convert it. These use the Telerik document processing library, which isn't relevant here as it works fine, I'm just showing the code for context...

```c#
    private Validation<Error, int> GetIntFromCell(CellSelection cell) =>
      ToInt(cell.GetValue().Value.RawValue);

    private Validation<Error, DateTime> GetDateFromCell(CellSelection cell) =>
      ToDate(cell.GetValue().Value.RawValue);

    private Validation<Error, decimal> GetDecimalFromCell(CellSelection cell) =>
      ToDecimal(cell.GetValue().Value.RawValue);
````

I then wrapped this all together as follows...

```c#
    private Validation<Error, InvestorPayment> ValidatePayment(Worksheet worksheet, int row) {
      Validation<Error, string> id = Success<Error, string>(worksheet.Cells[row, WsIdCol].GetValue().Value.RawValue);
      Validation<Error, DateTime> dateV = GetDateFromCell(worksheet.Cells[row, WsDateCol]);
      Validation<Error, decimal> amountV = GetDecimalFromCell(worksheet.Cells[row, WsAmountCol]);
      Validation<Error, int> methodV = GetIntFromCell(worksheet.Cells[row, WsMethodCol]);
      Validation<Error, int> sourceV = GetIntFromCell(worksheet.Cells[row, WsSourceCol]);
      Validation<Error, string> notes = Success<Error, string>(worksheet.Cells[row, WsNotesCol].GetValue().Value.RawValue ?? "");
      return (id, dateV, amountV, methodV, sourceV, notes).Apply((i, d, a, m, s, n) => new InvestorPayment {
        InvestorID = id,
        Date = d,
        Amount = a,
        PaymentMethod = (PaymentMethods)m,
        PaymentSourceId = s,
        Notes = n
      });
    }
```

The problem here is that I get a compiler error on the line where I try to set the `InvestorId` property, see the title of the issue.

Anyone any idea what I'm doing wrong? The `Id` property is indeed a string, as is the `Notes` property, which doesn't give a complier exception.

Anyone able to help?

Thanks very much.

**Comment by MrYossu** [comment]
Hmm, if I call `ToString()` explicitly on `id`, it works fine...

```c#
    InvestorID = id.ToString(),
```

Why do I need to do that?

**Comment by MrYossu** [comment]
OK, so something is weird here. Having implemented a hack to get around the issue (declaring a `string` variable, then using `Match` on `idV` to set that variable to the contents of the `Validation`), I reverted the change to have another look at what was going wrong, and it worked absolutely fine! I didn't change anything, just went back to the code shown above, but instead of the compiler error, it worked.

So my problem has gone, but I would be really interested to know if anyone can explain what the compiler error was about.

Thanks

**Comment by louthy** [comment]
```
InvestorID = id
```
Should be:
```
InvestorID = i
```

**Comment by MrYossu** [comment]
@louthy Duh, obvious now you point it out!

Thanks
