### ISSUE TITLE
Is it OK to store the inner value of an Option<T> as a private variable?

### ISSUE THREAD

**Issue by MrYossu** [louthy/language-ext#865]
Might be doing this completely wrong, so please be patient.

This is in a Blazor project, although I suspect the question would be the same with other technologies such as WinForms and WPF that allow two-way data binding.

I have a view (Blazor component) that displays details for an investor, and this references an `InvestorDetailsViewModel`, which has various properties (used to display data and bind to form elements) and methods (called as a result of the user clicking buttons on the view).

The VM has the following...

````c#
    public Option<Investor>? Investor { get; private set; }
````

It has to be nullable, as the Blazor view tries to access it before the data is loaded (see below). I'm not sure if I have a way around that.

If the `Investor` is `null` or `None`, then the component shows a message saying the investor could not be found. Otherwise, it displays the investor details.

When the view is initialised, it calls the following VM method...

````c#
    public async Task SetInvestor(string id) {
      Investor = await _appDbContext.Investors
        // Various includes omitted for clarity
        .FirstOrDefaultAsync(i => i.Id == id);
    }
````

Whilst I'm happy for the public property to be an `Option<Investor>`, as this ensures that the Blazor code has to account for the investor not being found (say an invalid ID), it's proving to be a pain for the code inside the VM. I keep having to write things like this...

````c#
      Investor?.Match(investor => {
        // Do something with the investor
        }
      }, () => {
      });
````

As this code can only be called from a button that is only shown when the investor was found, I know that the `Option` is a `Some`, hence the second argument to `Match` is always an empty action.

I am tempted to modify my VM to have a private variable to hold the actual investor (ie, the inner value of the `Option`), change `SetInvestor` to look more like this...

````c#
    private Investor _investor;

    public async Task SetInvestor(string id) {
      Investor = await _appDbContext.Investors
        // Various includes omitted for clarity
        .FirstOrDefaultAsync(i => i.Id == id);
      Investor.Match(investor => {
          investor.IfSome(inv => {
            _investor = inv;
        },
        () => {
        });
    }
````

That way I can access `_investor` directly later on, without having to use `Match` in cases where I know the `Option` is definitely a `Some`.

Is this OK? As I said, I may be going about this completely wrong, in which case I would welcome some guidance as to how to do it better, Thanks

**Comment by tanxeel90** [comment]
Option is supposed to be either `Some` or `None` and the consumer is expected to deal with both cases. However, for the specific scenario where you are sure at code level that the Option is `Some`, you can always have an additional getter which throws an exception if the Option is None (I do not understand why the public property has to be nullable).

```
        public Option<Investor> Investor { get; private set; }
        private Investor InvestorOrThrow => Investor.IfNone(() => throw new Exception("Value not set"));
```

and then you can use `InvestorOrThrow` instead of  `Match`

**Comment by MrYossu** [comment]
@tanxeel90 Thanks for the reply, but maybe I didn't explain myself clearly enough. The consumer of the public property only sees an `Option`, so has to deal with both cases as you say.

My question was about adding a private variable for purely internal use in this class, in methods that will only be called when I know that the `Option` is `Some`. For such a case it would be overkill to add a `InvestorOrThrow` property, as I know it could never, ever throw the exception.

As for making the public property null, this is due to the way Blazor works. As there is full (and automatic) interaction between the code and the view, I can do the following in the view...

```razor
@if (_someVar == null) {
  <p>Loading...</p>
} else {
  <p>Add markup that uses _someVar</p>
}
```

The real code is a little more sophisticated, but it enables me to show a "Loading..." indicator very easily whilst the async code loads the data. When the data has loaded, the view is updated automatically, no need for me to do anything.

However, if `_someVar` is an `Option<T>`, the when the view first loads, it will be `None` until the data access has completed, at which point it would be either `Some` or `None` depending on the results of the data access. This means that during the data loading phase, the user will be told that the entity doesn't exist (or whatever message you show in the `None` case), which would be misleading and confusing when the entity is actually loaded.

I got around that by making the variable nullable, so the user sees "Loading..." during the data access, and then one of the two appropriate displays afterwards.

Don't know how much sense that makes. Basically, I need to be able to account for three states in the view, not just `None` and `Some`, and this seemed the best way to do it. I would be interested to hear if you have a better suggestion.

Thanks again.

**Comment by louthy** [comment]
> Don't know how much sense that makes. Basically, I need to be able to account for three states in the view, not just None and Some, and this seemed the best way to do it. I would be interested to hear if you have a better suggestion.

It sounds like your values represent a mini state-machine, so you could have a tri-state domain that represents it declaratively, instead of trying to shoehorn it into `Option`:

```c#
    [Union] 
    public interface Display<A>
    {
        Display<A> NotLoaded();
        Display<A> OK(A value);
        Display<A> Failed(Error value);
    }
```

**Comment by louthy** [comment]
> Investor.IfNone(() => throw new Exception("Value not set"));

**Comment by louthy** [comment]
@tanxeel90 

> `private Investor InvestorOrThrow => Investor.IfNone(() => throw new Exception("Value not set"));`

This can just be done with a cast:

```c#
        public Option<Investor> Investor { get; private set; }
        private Investor InvestorOrThrow => (Investor)Investor;
```

**Comment by MrYossu** [comment]
> > Don't know how much sense that makes. Basically, I need to be able to account for three states in the view, not just None and Some, and this seemed the best way to do it. I would be interested to hear if you have a better suggestion.
> 
> It sounds like your values represent a mini state-machine, so you could have a tri-state domain that represents it declaratively, instead of trying to shoehorn it into `Option`:
> 
> ```cs
>     [Union] 
>     public interface Display<A>
>     {
>         Display<A> NotLoaded();
>         Display<A> OK(A value);
>         Display<A> Failed(Error value);
>     }
> ```

I did wonder if some sort of 3-way monad might be a better approach, but wasn't sure how to do it. 

Is it possible you could provide a bit more detail as to how I would construct this. I can see the general idea, but am not sure what form the `NotLoaded`, `OK`, and ¬Failed` classes would take.

Thanks for the reply.

**Comment by MrYossu** [comment]
@louthy Sorry, forgot to ask, did you have any comments on my original question, that of storing the inner value as a private variable, for use in methods where I know for a fact that the `Option` is a `Some`?

Thanks
