### ISSUE TITLE
Implicit cast from Option<A> to bool?

### ISSUE THREAD

**Issue by TysonMN** [louthy/language-ext#867]
There is no implicit cast from [`Option<A>`](https://github.com/louthy/language-ext/blob/bd31a0b85c3866554292c45f77c9a14fec8d3f2c/LanguageExt.Core/DataTypes/Option/Option.cs) to `bool`.

In particular, this code does not compile.
```csharp
Option<int> a = 1;
bool b = a; // Error CS0029 Cannot implicitly convert type 'LanguageExt.Option<int>' to 'bool'
```

Why then does this code compile?
```csharp
Option<int> a = 1;
if (a) { }
```

The behavior of that code seems to be equivalent to
```csharp
Option<int> a = 1;
if (a.IsSome) { }
```

**Comment by Stanley-G** [comment]
At first glance I thought maybe this behavior was tied to the type of `A`; in the original code where we observed this behavior, `A` was a two-item enum, and in @TysonMN's example, `1` can be cast to . Further experimentation though shows that the following all do compile:

```csharp
private enum FooEnum
{
    One,
    Two,
    Three
}

private class FooClass
{
    public string Foo => "Foo";
}

public static void Test()
{
    Option<int> a = 1;
    if (a) { }
    var r = a ? 5 : 0;
    
    Option<char> b = 'Z';
    if (b) { }
    r = b ? 5 : 0;
    
    Option<string> c = "some";
    if (c) { }
    r = c ? 5 : 0;
    
    Option<FooEnum> d = FooEnum.Three;
    if (d) { }
    r = d ? 5 : 0;
    
    Option<FooClass> e = new FooClass();
    if (e) { }
    r = e ? 5 : 0;
}
```

**Comment by louthy** [comment]
It’s ‘operator true’ that gives the behaviour you’re seeing.  This allows operator ‘||’ to work and provide ‘lazy’ evaluation.

I don’t believe an implicit cast to bool makes sense, even if this seems to imply it.

**Comment by TysonMN** [comment]
Thanks for the explanation.  [Here is the documentation about `true` and `false` operators](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/true-false-operators).

One reason I couldn't figure out what was executing is because this operator is being inlined.
https://github.com/louthy/language-ext/blob/bd31a0b85c3866554292c45f77c9a14fec8d3f2c/LanguageExt.Core/DataTypes/Option/Option.cs#L325-L327

**Comment by Stanley-G** [comment]
All I can say is this could be a nasty bite to the unsuspecting. It was only by chance that I observed this behavior. I refactored the return type of a method return `bool` where `true` was the happy path, but then I wanted more detail on the type of error that occurred, so I changed it to a `Some<ErrorEnum`. You could say that was a design mistake right there; however I don't believe it is fair to say that `Some` is always the happy path (i.e. `true`).

However that shakes out, I was still very surprised when I observed that the code continued to compile even with the signature refactoring. And now there was a hidden bug, since `Some<A> == `true` is not what I intended.

**Comment by TysonMN** [comment]
I would never intentionally use the `true` or `false` operators of `Option<A>`.  I prefer explicit over implicit, so I would always explicitly call `IsSome` if I wanted this `bool`.

I closed the issue because I assumed that @louthy either likes these operators or at least doesn't want to introduce a breaking change by removing them.  Have I assumed correctly @louthy?

**Comment by TysonMN** [comment]
> The operators are a requirement for key functionality.
> [...]
> I would much prefer to read:
> 
> ```cs
>     var mr = mx || my;
> ```
> [...]
> It is designed in such a way as to work like the _alternative operator_ in Haskell (`<|>`).

Yes, that syntax is very good.  I know this operation as monoidal plus (for `Option<A>`).

> It is the _only_ way the `||` operator can be implemented, and it's the _only_ way to defer evaluation of the right-hand side of a coalescing operation [...]

I trust you and also verified this.  Without the `true` and `false` operators, the compiler has this error.
> Error CS0218 In order for 'Option<int>.operator |(Option<int>, Option<int>)' to be applicable as a short circuit operator, its declaring type 'Option<int>' must define operator true and operator false

Although not explicit as I would prefer, I think this behavior is implied by [this documentation](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/boolean-logical-operators#code-try-3:~:text=The%20conditional%20logical%20OR%20operator%20%7C%7C,the%20left%2Dhand%20operand%20evaluates%20to%20true.).
> The conditional logical OR operator || also computes the logical OR of its operands, but doesn't evaluate the right-hand operand if the left-hand operand evaluates to true.
