### ISSUE TITLE
NumTypeExtensions.Sum might be incompatible with the PRED of the type being summed

### ISSUE THREAD

**Issue by mario-d-s** [louthy/language-ext#869]
Consider the following `NumType` derivate:

```
public class PositiveNumber : NumType<PositiveNumber, TInt, int, GreaterThan<TInt, int, I0>>
{
    public PositiveNumber(int value)
        : base(value)
    {
    }
}
```

When trying to `.Sum()` a list of these, you will get an exception because the implementation uses `Fold` and tries to use a seed value of `0` with the same `PRED` as the type being summed.

I could work around it using:

```
public static class PositiveNumberExtensions
{
    public static PositiveNumber Sum(this IEnumerable<PositiveNumber> xs)
        => self.Aggregate((x1, x2) => LanguageExt.Prelude.add(x1, x2));
}
```

Easy fix, but it would be nice if LanguageExt actually did this right out of the box (cause it bites you at run-time).

**Comment by TysonMN** [comment]
Thanks for reporting this.

Can you contribute a PR to fix this?

**Comment by mario-d-s** [comment]
@TysonMN I would gladly help & contribute a fix! Only problem is that I'm really not all that familiar yet with the library and I'm using it mostly in a basic fashion. I'm not sure if you find my workaround acceptable (using LINQ Aggregate with `add`) or if a more idiomatic approach could be taken.

If you're fine with substituting the current implementation roughly with the code I've written then I can definitely open a PR.

By the way, is there a reason there is no `Fold` overload that takes no seed as it's first argument, just like `Aggregate` in LINQ? If something like that would be desirable, I would be happy to make a more substantial contribution that way too.

**Comment by TysonMN** [comment]
In this case, I am not sure what louthy would prefer, but since you already know a possible fix that is small, it is reasonable to create a PR containing it.

I also think it is reasonable to create the missing overload that you want. Much of the time, something like that doesn't exist because no one had spent the time yet to add it.
