### ISSUE TITLE
No MapT?

### ISSUE THREAD

**Issue by melston** [louthy/language-ext#87]
I am writing some test code to make sure I understand how to use this library properly and I am trying to make use of the MapT example in your Readme file. Unfortunately when I try to compile it I get the following:

'Lst<Option<int>>' does not contain a definition for 'MapT' and no extension method 'MapT' accepting a first argument of type 'Lst<Option<int>>' could be found (are you missing a using directive or an assembly reference?)

Your Readme doesn't say where this method is located and I can't find it in the source code anywhere (though I can see it is used in a couple of places).  How do I get access to it?

**Comment by louthy** [comment]
using LanguageExt.Trans;

Should do it.

**Comment by melston** [comment]
Thanks.  After playing with it for some time I finally got an intellisense
recommendation to try that and it worked.

Part of the docs (even the readme) should have something about what to use
to access these elements, I think.

Nice package, though.  It makes for some very robust C#.

Mark

**Comment by louthy** [comment]
This is now mentioned in the documentation.

> Nice package, though.  It makes for some very robust C#.

Cheers :+1:
