### ISSUE TITLE
Possible bug in Try.Memo

### ISSUE THREAD

**Issue by FrancoMelandri** [louthy/language-ext#870]
I've noticed there is a possible bug in the `Memo` extension of the `Try`  data type.

Actual code is:
```csharp
    public static Try<A> Memo<A>(this Try<A> ma)
    {
        bool run = false;
        var result = new Result<A>();
        return (() =>
        {
            if (run) return result;
            var ra = ma.Try();
            if (result.IsSuccess)
            {
                run = true;
                result = ra;
            }
            return ra;
        });
    }
```

in this case the check `if (result.IsSuccess)` is always `false`, because you are checking the closure `result` instead of the try result `ra`; in this way you never memoize the result for future calls.

I think the correct code is:
```csharp
    public static Try<A> Memo<A>(this Try<A> ma)
    {
        bool run = false;
        var result = new Result<A>();
        return (() =>
        {
            if (run) return result;
            var ra = ma.Try();
            if (ra.IsSuccess)
            {
                run = true;
                result = ra;
            }
            return ra;
        });
    }
```
In the `TryAsync` data type the code is right.

**Comment by TysonMN** [comment]
You say "possible but" and "I think the correct code".  Can you write a test that proves that this is a bug?

**Comment by louthy** [comment]
I think you’re right @FrancoMelandri.  I agree with @TysonMN , if you’re happy to do a PR with unit tests that’d be perfect 👌

**Comment by FrancoMelandri** [comment]
@louthy, @TysonMN as soon as I'm able to build the solution, I open a PR with unit tests and the fix.

**Comment by louthy** [comment]
This has no been deployed
