### ISSUE TITLE
Returning Aff<T> from an async method throws NullReferenceException

### ISSUE THREAD

**Issue by ProductiveRage** [louthy/language-ext#874]
The following code compiles because Aff has a `GetAwaiter` method but it fails at runtime with a `NullReferenceException` -

```
using System;
using System.Threading.Tasks;
using LanguageExt;

namespace Client
{
    class Program
    {
        static async Task Main()
        {
            var r = await GetResult();
            Console.WriteLine(r);
            Console.ReadLine();
        }

        static async Aff<string> GetResult()
        {
            await Task.Delay(1);
            return "abc";
        }
    }
}
```

The exception occurs when `GetResult` is awaited:

![image](https://user-images.githubusercontent.com/742348/119040704-a72a9a80-b9ad-11eb-813d-183b30bd620f.png)

The stack trace looks like this:

```
   at LanguageExt.Aff`1.RunIO()
   at LanguageExt.AffAwaiter`1..ctor(Aff`1 ma)
   at LanguageExt.Aff`1.GetAwaiter()
   at Client.Program.<Main>d__1.MoveNext() in C:\\repos\\Test\\Program.cs:line 11
```

It may (or may not!) be fairly simple to fix but I haven't looked into what's causing it yet, I just wanted to record it for now.

**Comment by ProductiveRage** [comment]
None of the tests fail if I remove the `GetAwaiter` method from `Aff<A>` (though obviously the example above won't compile any more as it won't be awaitable), so is this a bit experimental code?

(The problem is that it's creating a default `Aff<string>` and so the `thunk` reference is null, which is what causes the exception).

I guess if we don't want to remove that method then the example code here should be considered something of an anti-pattern? Maybe there's a way to fix it but I couldn't work it out!

**Comment by louthy** [comment]
As I can tell, the primary issue is mixing `Aff` and `Task`, they're not the same type and have different async state-machines.  It seems `SetResult` is never called on the `AffMethodBuilder`, so `"abc"` never makes it into the state-machine.  

I've done a bit of digging with ILSpy to see if I can spot what's going on, but it's non-obvious, and so my recommendation would be to use LINQ with `Aff`, and not the `async`/`await` machinery.  If you want to use tasks, then lift it using:

```c#
    Aff<A>(async () => ...)
```

If there isn't a fix to this that'd make issues like this obvious then I may have to deprecate the awaiter behaviour from `Aff`

**Comment by louthy** [comment]
Fixed in the latest release.  Awaiter support has been removed and the internal thunk of the `Aff` struct is now checked for null (if anyone uses `default(Aff<..>)` or new `Aff<..>()`
