### ISSUE TITLE
Empty enumerable with count == 0

### ISSUE THREAD

**Issue by pnowosie** [louthy/language-ext#88]
I wonder why one cannot create empty Enumerable with zero-count, instead exception is thrown here:
https://github.com/louthy/language-ext/blob/master/LanguageExt.Core/Range.cs#L19

**Comment by louthy** [comment]
@pnowosie Sorry for the slow reply on this, I've been bogged down with the multi-system refactor for the `Process` system.  I have updated the `IntegerRange` and `CharRange` types to allow zero length ranges.  Will be available on the next deployment `1.8.17-beta` (probably over this weekend).
