### ISSUE TITLE
Is Option<string> the right return type to use when only returning errors?

### ISSUE THREAD

**Issue by aryehsilver** [louthy/language-ext#880]
Firstly great package!

I have a save method that will only return an error if there is one otherwise it doesn't need to return anything. I'm currently using the Option<string> as the return type, and returning a Some with an error if there is one or else a None (on success). This seems wrong to me as it is usually used the other way around (None for when it fails and Some for a success).

Am I using the right option (mind the pun), or is there something else I should use instead?

Many thanks

**Comment by tanxeel90** [comment]
A `Validation` or an `Either` will be more suitable in this case:

```
        static Validation<Error, Unit> Function() =>
            SomeCondition()
            ? Success<Error,Unit>(unit)
            : Error.New("Failed.");

        static Either<Error, Unit> Function1() =>
            SomeCondition()
            ? Right<Error, Unit>(unit)
            : Error.New("Failed.");
```

**Comment by aryehsilver** [comment]
Thank you @tanxeel90 that looks much better.
