### ISSUE TITLE
System.Reflection.Emit incompatible to iOS

### ISSUE THREAD

**Issue by maxbartunik** [louthy/language-ext#887]
In a Xamarin.iOS project LanguageExt produces an exeption on all calls relying on System.Reflection.Emit. An example: 

{System.PlatformNotSupportedException} The type initializer for 'LanguageExt.Range3' threw an exception.
at LanguageExt.Prelude.Range (System.Int32 from, System.Int32 count, System.Int32 step)

As described here https://docs.microsoft.com/en-us/xamarin/ios/internals/limitations System.Reflection.Emit cannot be used on an iOS platform.

**Comment by louthy** [comment]
Hi @maxbartunik, could you run a little experiment for me?

```c#
var x = Expression.Parameter(typeof(int), "x");
var y = Expression.Parameter(typeof(int), "y");
var add = Expression.Add(x, y);
var lam = Expression.Lambda<Func<int, int, int>>(add, x, y);
var fun = lam.Compile();
var r = fun(2, 2);

Console.WriteLine(r);
```
If `Expression.Compile` works then I can probably fix this.

**Comment by maxbartunik** [comment]
Hi @louthy, the expression works. The console output is 4, as expected.
FYI: I implicitly assumed and used Linq.Expressions.

A fix would be great news!

**Comment by louthy** [comment]
Thanks for that, one final test if you don't mind.  Does `ILCapability.Available` return `false`:

```c#
    static class ILCapability
    {
        public static readonly bool Available;

        static ILCapability() =>
            Available = GetAvailability();

        static bool GetAvailability()
        {
            try
            {
                TestSystemExceptionCtor();
                return true;
            }
            catch (PlatformNotSupportedException)
            {
                return false;
            }
        }

        static Delegate TestSystemExceptionCtor()
        {
            var type = typeof(SystemException);
            var ctor = type.GetConstructor(new Type[0]);

            var dynamic = new DynamicMethod("CreateInstance",
                                            type,
                                            new Type[0],
                                            true);

            var il = dynamic.GetILGenerator();
            il.Emit(OpCodes.Newobj, ctor);
            il.Emit(OpCodes.Ret);

            return dynamic.CreateDelegate(type);
        }
    }
```

**Comment by maxbartunik** [comment]
@louthy: Yes, also works as expected.

**Comment by louthy** [comment]
Thanks, leave it with me, should have a fix pretty soon.

**Comment by maxbartunik** [comment]
Great, thanks!

**Comment by louthy** [comment]
Uploading to nu-get now: `v3.5.30-beta`

All IL usage has been removed.  Three IL based features won't work, but at least won't throw `System.PlatformNotSupportedException` 

* `ToString` on `Record<TYPE>` returns an empty string
* `GetObjectData` serialiser on `Record<TYPE>` throws a `NotSupportedException` on usage
* `SetObjectData` deserialiser on `Record<TYPE>` throws a `NotSupportedException` on usage

The migration of the IL to `Expression` is much more complex for those use cases, so I'll deal with them on a later release.  This release should fix all of the other common use-cases.

**Comment by maxbartunik** [comment]
Thanks! That fixed the issue.

**Comment by louthy** [comment]
`v3.5.31-beta` has full support for `Record<A>` - `ToString`, `GetObjectData`, and `SetObjectData`.
