### ISSUE TITLE
Need some help with thread safe Option

### ISSUE THREAD

**Issue by LukeJanPracuj** [louthy/language-ext#89]
Hi,
What is the best way to provide thread safe Match on Option ?

**Comment by louthy** [comment]
@LukeJanPracuj 

All matching with `Option` is thread-safe, it's an immutable type.

**Comment by LukeJanPracuj** [comment]
Thanks, but
What if the object on which we call the Match func can be changed by several threads

**Comment by louthy** [comment]
@LukeJanPracuj - I'm not sure if I'm misunderstanding your question, or if you're misunderstanding my response.  

>  the object on which we call the Match func

The 'object' would be the `Option`, and is immutable, and therefore you can call match on it (or any function you like) without locks and is entirely thread-safe - as is the case with all types in this library.  However if the type that you store your `Option` in is mutable then you will need a lock for the duration of the operation, i.e:
```C#
    class YourType<T>
    {
        Option<T> opt;
        object sync = new object();

        public void Map(Func<T,T> map)
        {
            lock(sync)
            {
                opt = opt.Map(map);
            }
        }
    }
```
If you just want to get a value from matching, then no locks are required, and there are zero threading issues.  i.e.

```C#
    class YourType<T>
    {
        readonly Option<T> opt;

        public R MapValue<R>(Func<T,T> map)
        {
            return opt.Match( Some: map, None: default(R) );
        }
    }
```
