### ISSUE TITLE
Question: using TryAsync together with async operations on collections of data

### ISSUE THREAD

**Issue by Malgefor** [louthy/language-ext#891]
Hi!
I have a question regarding how to work with possibly failing tasks (TryAsync) and collections of data .
Let's say I have the situation I have an `IEnumerable<Image>` containing x images which consist of a `FileName` and the content as a `Stream`. I want to check with a remote API whether or not the image already exists by filename and, if it doesn't exist, add it via a second API call.

Since the API could be unavailable, I wrapped the API calls with `TryAsync`, but that leaves me with, say, an `IEnumerable<TryAsync<Unit>>`, with each `TryAsync` containing Unit when the operation was successful and an Exception when the operation failed for whatever reason.

I could use `.Sequence()` to create a single `TryAsync<IEnumerable<Unit>>` and `Match()` to determine that one of the operations failed along the way, but I'm not sure if that is the way to go about these kinds of situations. 
Can anyone give some pointers on dealing with collections of `Try` / `TryAsync`?

**Comment by Malgefor** [comment]
To elaborate with some code:

```
private Task<Unit> Start(IReadOnlyList<ImageReference> imagesReferences, Insight article)
{
    return TryAddArticleToDatabase(article) // returns TryAsync<Unit>
        .Bind(_ => DownloadImagesToStorage(imagesReferences))
        .IfFail(exception =>
        {
            Log.Error(exception, "Error when handling article!");
            return Unit.Default;
        });
}

private TryAsync<Unit> DownloadImagesToStorage(IReadOnlyList<ImageReference> imageReferences)
{
    return imageReferences.Map(TryDownloadImageToStorage)
        .Sequence()
        .Map(_ => Unit.Default);
}

private TryAsync<Unit> TryDownloadImageToStorage(ImageReference reference)
{
    return TryAsync(() => this.fileRepository.DoesFileExist(reference.FileName, FolderPath))
        .Bind(doesFileExist =>
        {
            if (!doesFileExist)
            {
                return
                    from contentStream in TryAsync(() => this.imageWebClient.DownloadImage(reference.Url))
                    from unit in this.fileRepository.Add(contentStream, reference.FileName, FolderPath) // Returns TryAsync<Unit>
                    select unit;
            }

            return TryAsync(Unit.Default);
        });
}
```

When I run this and no exceptions are thrown the code does what I expect it to do. Suppose that `this.imageWebClient.DownloadImage(reference.Url)` throws an exception, I see a BottomException when I log the error in the `IfFail()`. Why does that happen?

**Comment by louthy** [comment]
Sorry for the delay.  Yes, `.Sequence()` and `.Traverse()` is the way to fire off many Trys and get the _first error_.  I note you're on an older version of lang-ext, the `beta` (which will become a full release any day now) has `SequenceParallel` and `SequenceSerial` for `TryAsync`.

I would encourage you to upgrade if you can, and consider switching from `TryAsync<A>` to `Aff<A>`.  `Aff<A>` is a much more opinionated way to handle side-effects and has a significantly better story for managing errors, doing retries with back-off, defining time-outs, etc.

There's a synchronous variant called `Eff<A>` which is notionally equivalent to `Try<A>`.  It's been designed to play nice with `Aff<A>`, to the point where you can use them together in the same monadic expression.  

On top of that, there's `Aff<RT, A>` and `Eff<RT, A>` which are designed to take a '_runtime_' that allows for injectable behaviours, and carrying an config environment through your computations.  These are also designed to play nice with `Aff<A>` and `Eff<A>`.

And finally, there's `LanguageExt.Pipes` which is a streaming composition system.  I'm still finessing that, but it's a monad transformer based on the [Haskell Pipes library](https://hackage.haskell.org/package/pipes-4.3.16/docs/Pipes-Tutorial.html).  It supports lifting of `Aff` and `Eff` computations into streams.

`Try` and `TryAsync` will continue to be supported, but I won't be focussing on any new features for them, because they're superfluous to requirements now `Eff` and `Aff` are eating their lunch.

[I've been writing up some documentation on them](https://github.com/louthy/language-ext/wiki/How-to-deal-with-side-effects), if you're interested in seeing whether they'd work for you.  And there's a [new sample project](https://github.com/louthy/language-ext/tree/main/Samples/EffectsExamples) to go along with it.

**Comment by Malgefor** [comment]
Thanks for the response, really appreciate it! 

I'm currently replacing `TryAsync<A>` with `Aff<A>` throughout my code. The change doesn't have much impact on the overall structure, which is nice. :) I did notice that there is not (yet) a `.MapT()` or `.BindT()` function for `Aff<IEnumerable<A>>`/`Eff<IEnumerable<A>>` which made me nest some `Map()` functions further.

I will have a look at the `LanguageExt.Pipes` package aswell! I will probably need a bit more time to dive into that one though haha.

**Comment by louthy** [comment]
Re: Pipes, I’ve had some breakthroughs with that over the past few days that massively reduces the generics burden.  

[I’m still working through it](https://github.com/louthy/language-ext/blob/main/Samples/TestBed/Program.cs) - so there’s a few examples here.

From readLine2 down is the heavy generics approach, above that is the newer approach.  There’s examples that work with IEnumerable, IObservable, and IAsynEnumerable

**Comment by Malgefor** [comment]
Hi Paul,

I have upgraded all the Try/TryAsync's to Eff/Aff's. I also implemented some new code with the latest Lang-Ext package version, which generated some new questions I hope you can help me with and/or give some context .

Let's say I have an operation that goes as follows: 

> Import a file from a remote ftp -> `Aff<T>`
> Parse T -> `Validation<Error, T>`
> Save T if Validation is in Success-state -> `Aff<Unit>`
> Evaluate the operation and log errors/return an error result based on the evaluation.

When I do this in LINQ (or a fluent chain for that matter) I want to gather both parsing errors and possible IO errors and relate them back to the file. The problem I run into is that inside the LINQ syntax I have access to the context of the operation and I can relate the parsing errors to, for instance, the filename. But when I use Run() on the Aff I lost that context so I don't know where or what went wrong for which file. Some example code below.

**Question 1**: Is this the correct approach when dealing with nested monads (e.g. Validation or Either) inside an Eff/Aff chain ?

**Question 2**: How do we know for which file one of the the Eff/Aff operations might have failed ?
     The operation-variable holds an Aff<IFileImportResult>, which captures the parsing errors that might have occurred but
     doesn't account for potential IO errors.
     
**Question 3:** Do you advise to stay inside the Eff/Aff monad for the whole operation or is using Run() in between to get an 
     intermediate result and parse that to, for instance, the Union below a valid strategy ?
     
**Question 4**: Why doesn't `.Match()` on an Eff/Aff return a T/ValueTask<T> since you already specify inside the Match() what 
    you want to do in the Success and Failure cases ?

```c#
public Task Run()
{
    var operation =
        from fileDto in GetFileDtoFromExternalSource()
        from parsedFile in Eff(() => TryParseFileEntityFromDto(fileDto))
        let intermediateResult = parsedFile.Match(entity => IFileImportResultCon.Success(entity.FileName), seq => IFileImportResultCon.Failure(fileDto.FileName, seq))
        from fileImportResult in intermediateResult.Match(success => SaveParsedFile(success.FileName), LanguageExt.Aff<IFileImportResult>.Success)
        select fileImportResult;

// Handle Aff    
}

private static Validation<Error, FileEntity> TryParseFileEntityFromDto(FileDto dto) =>
    Validation<Error, FileEntity>.Success(new FileEntity(dto.FileName, dto.Content, DateTime.UtcNow));

private static Aff<FileDto> GetFileDtoFromExternalSource() =>
    Eff(() => new FileDto("file1.txt", "content"));

private static Aff<IFileImportResult> SaveParsedFile(string fileName) =>
    LanguageExt.Aff<IFileImportResult>.Success(IFileImportResultCon.Success(fileName));

private record FileEntity(string FileName, string Content, DateTime CreatedOn);

private record FileDto(string FileName, string Content);
```

```c#
[Union]
public interface IFileImportResult
{
    IFileImportResult Success(string fileName);

    IFileImportResult Failure(string fileName, Seq<Error> errors);
}
```

**Comment by louthy** [comment]
I guess the key thing to think of, when using different kinds of monads, is less _pipeline_ and more _onion_.  The monadic types should be seen as _types with capabilities_.  The inner most capability (of the monadic onion) would be pure functions.  They exist without any extra capabilities.  Then as you step to the outer layers of the onion you'd get something like: `Option` which has the _no value capability_.  Something like `Validation` then has the

**Comment by Malgefor** [comment]
Thanks for the explanation! I was definitely thinking more of it as a pipeline than an union. Thinking about the problem in terms of layers instead of just trying to pipe output to the next function makes more sense now. I used Paint to draw the layers and how I am stepping through them. Visualizing the problem helped a lot.

Thanks again!
