### ISSUE TITLE
Try doesn't seem to catch errors

### ISSUE THREAD

**Issue by torontofangirl** [louthy/language-ext#892]
Hi. I tried to run the code sample you provided in this issue #32 , but it crashes.
```
Try<int> Divide(int x, int y) => () =>
    x / y;

var res = match(Divide(10, 0),
    Succ: v => v,
    Fail: 0);
```
```
System.DivideByZeroException: 'Attempted to divide by zero.'
```
Am I using Try incorrectly?

**Comment by AlexGS74** [comment]
The referenced issue has all the needed details. You are after this:
```
Try<int> Divide(int x, int y) => () =>
    Try(() => x / y);
```

The difference is that in your example the division is executed outside of the Try and thus the exceptions are not handled by it.

**Comment by louthy** [comment]
The original should work.  I’m away from my computer at the moment, but perhaps try Divide(10, 0).Match(…)

**Comment by torontofangirl** [comment]
`Try<int> Divide(int x, int y) => () => Try(() => x / y);` gets a compile-time error of `Cannot convert expression type LanguageExt.Try<int> to return type LanguageExt.Common.Result<int>`

```
Try<int> Divide(int x, int y) => () =>
                x / y;

            var res = Divide(10, 0).Match(
                Succ: v => v,
                Fail: 0);
```
throws the same Attempted to divide by 0 error

I'm on the 3.5.46 beta version of LanguageExt, if that makes a difference

**Comment by louthy** [comment]
That’s very odd, because Match call .Try

https://github.com/louthy/language-ext/blob/main/LanguageExt.Core/DataTypes/Try/Try.Extensions.cs#L209

Which definitely has a try/catch around the invocation.

https://github.com/louthy/language-ext/blob/main/LanguageExt.Core/DataTypes/Try/Try.Extensions.cs#L642

I’ll have to investigate when I’m back in front of my PC.  The version shouldn’t matter, it’s been the same code for years.

**Comment by AlexGS74** [comment]
> `Try<int> Divide(int x, int y) => () => Try(() => x / y);` gets a compile-time error of `Cannot convert expression type LanguageExt.Try<int> to return type LanguageExt.Common.Result<int>`

My bad, It should be this:
```
Try<int> Divide(int x, int y) => Try(() => x / y);
```

Though, your version works fine in my test: it doesn't throw.

**Comment by torontofangirl** [comment]
> `Try<int> Divide(int x, int y) => Try(() => x / y);`
It still throws for me with this -- would it have to do with my C# version? I'm using .NET 5 with C# 9.

**Comment by louthy** [comment]
> `Try<int> Divide(int x, int y) => Try(() => x / y);`

This isn't necessary, the original post is the same as this.  `Try<A>` is a delegate-type, and so this `Try<int> Divide(int x, int y) => () => x / y);` is all that's needed.

@torontofangirl I have just run your example and everything works as expected.  If you could post the full stack-trace maybe that will give some clues.

**Comment by torontofangirl** [comment]
```System.DivideByZeroException
  HResult=0x80020012
  Message=Attempted to divide by zero.
  Source=Test
  StackTrace:
   at <Program>$.<>c__DisplayClass0_0.<<Main>$>b__2() in C:\Users\username\source\repos\Test\Test\Program.cs:line 12
   at TryExtensions.Try[T](Try`1 self)
```

![image](https://user-images.githubusercontent.com/51888429/126915451-c8c1719e-6211-4f7c-94b8-8107708e11b3.png)

**Comment by louthy** [comment]
Ah ok, this is just Visual Studio breakpointing on the exception, it's not a problem of `Try`.  If you press F5, you should see that the program continues and you'll get `0` out of the match operation (or if you just rain the program without debugging).  

Visual Studio still continues to breakpoint on exceptions whilst debugging, and I'm not sure that's changeable (or even desirable to be changed).

**Comment by torontofangirl** [comment]
Ah!
Sorry for wasting your time, but I'm glad we were able to resolve this

**Comment by MartonBoda** [comment]
It can be changed, they might want to reset to default settings:
![image](https://user-images.githubusercontent.com/3929769/126915833-2f334bbb-ac87-436c-bb91-231ab659e251.png)

**Comment by louthy** [comment]
@torontofangirl 

> Sorry for wasting your time

No worries, it happens to the best of us! :)
