### ISSUE TITLE
Monad transformers for Writer

### ISSUE THREAD

**Issue by erwinkn** [louthy/language-ext#893]
## General overview
While there are implementations of `Traverse` and `Sequence` for the Writer monad and all collection monads, there are no implementations for `Bind` and the other methods of the `MonadTrans` typeclass.

When it comes to other monads, there does not seem to be any transformer methods.

Since I'm not familiar with all the details of the typeclass and monad transformers system, I was wondering: is this due to some inherent limitation of the Writer monad or is this planned for the future, but not yet implemented due to being lower priority?

If it's the latter, I may give it a shot!

## Context

I'm trying to make the Writer work with the Option or Either monads, since I'm accumulating sequences of instructions by doing operations that may fail (in which cases instructions are discarded and everything returns early).

Right now, I found it easier to work `Writer<MonoidW, W, Option<A>>`, although the intent is not as clear (-> the instructions up to the point of failure are not discarded).

Here's an example from within a fold function:
```cs
// result has type Writer<MSeq<Instruction>, Seq<Instruction>, Option<Foo>>
result = result.Bind(
    state => state.Match(
        Some: x => x.Bar(args)
        None: () => (Value: None, Output: Empty, IsBottom: true)))
``` 

Note that I may be missing a much better way to do this - I have only started using the Writer monad recently.

**Comment by louthy** [comment]
[Higher Kinds in C# by Paul Louth](https://paullouth.com/higher-kinds-in-c-with-language-ext/)
