### ISSUE TITLE
What is `Num<A>` and how is it used?

### ISSUE THREAD

**Issue by MrYossu** [louthy/language-ext#894]
Sorry if this is a dumb question!

I was just looking at the [code-gen wiki](https://github.com/louthy/language-ext/wiki/Code-generation#discriminated-union--sum-types), comparing the two ways of creating a `Union` (interface vs partial class), and came across this example...

```c#
[Union]
public abstract partial class Shape<NumA, A> where NumA : struct, Num<A>
{
    public abstract Shape<NumA, A> Rectangle(A width, A length);
    public abstract Shape<NumA, A> Circle(A radius);
    public abstract Shape<NumA, A> Prism(A width, A height);
}
```

Please can someone explain what the `NumA` type parameter is for, and what the `Num<T>` type is at the end?

Thanks

**Comment by louthy** [comment]
https://github.com/louthy/language-ext#ad-hoc-polymorphism

**Comment by MrYossu** [comment]
@louthy Thanks for the reminder. I think I have read that bit before, but probably didn't comprehend what it meant.

So did you add the `NumA`/`Num<A>` part so that the generic type `A` would be numeric? In other words, it forces the consumer of the `Shape` type to use a numeric type for the generic type, allowing the implementation of the actual shapes (`Circle`, `Rectangle` etc) to do arithmetic with the parameters, knowing that they are numeric.

Please can you confirm if I got that right, and if not, correct me.

Thanks again.

**Comment by louthy** [comment]
Yep, that’s it.  It also allows you to create new numeric types (like rationals, or complex numbers), and have them work with existing code.

the ad-hoc behaviour also allows you to make a type you don’t own retrospectively into a number.  Something that can’t be done with interfaces.

**Comment by MrYossu** [comment]
@louthy Ah-ha, even better. Thanks again.
