### ISSUE TITLE
Is there any practical difference between a `Union` being an interface or an abstract partial class?

### ISSUE THREAD

**Issue by MrYossu** [louthy/language-ext#895]
The [wiki](https://github.com/louthy/language-ext/wiki/Code-generation#discriminated-union--sum-types) shows the two ways of creating a `Union` (interface vs abstract partial class), and on [the latest release notes](https://github.com/louthy/language-ext/releases/tag/v3.5.34-beta), there is a comment about the interface approach only supporting top-level interfaces, not ones nested inside other classes. The same page also mentions that one of the interface approaches generates an extension method, and the abstract partial class approach generates an instance method.

So, assuming all my `Union` types are top-level, is there any practical difference in the two approaches? As the consumer of a type, I don't see that I would notice any difference between an extension method and an instance method. 

Thanks

**Comment by louthy** [comment]
There are additional benefits using abstract class because it can implement the structural operators like ==, !=, etc

**Comment by MrYossu** [comment]
@louthy Ah yes, you did mention that. Didn't really excite me as I rarely use those on my objects.

Anything else? Thanks again.
