### ISSUE TITLE
Prelude.use for effects hides error in effect that provides disposable

### ISSUE THREAD

**Issue by harrhp** [louthy/language-ext#898]
```
using System;
using System.Threading.Tasks;
using static LanguageExt.Prelude;

namespace ConsoleApp1
{
    class Program
    {
        static async Task Main(string[] args)
        {
            use(FailEff<IDisposable>("my error"), _ => SuccessEff(123)).Run().ThrowIfFail();
        }
    }
}
```
Should throw `LanguageExt.Common.ErrorException: my error` but i get `LanguageExt.ValueIsNoneException: Value is none`. I guess [this check](https://github.com/louthy/language-ext/blob/main/LanguageExt.Core/Effects/Eff/Prelude/Eff.Prelude.use.cs#L26) should be above try

**Comment by louthy** [comment]
Fixed in `3.5.56-beta`
