### ISSUE TITLE
redundant runtime generic in some @catch overloads

### ISSUE THREAD

**Issue by harrhp** [louthy/language-ext#900]
examples
https://github.com/louthy/language-ext/blob/main/LanguageExt.Core/Effects/Aff/Prelude/Aff.Prelude.catch.cs#L143
https://github.com/louthy/language-ext/blob/main/LanguageExt.Core/Effects/Aff/Prelude/Aff.Prelude.catch.cs#L131
https://github.com/louthy/language-ext/blob/main/LanguageExt.Core/Effects/Eff/Prelude/Eff.Prelude.catch.cs#L141
https://github.com/louthy/language-ext/blob/main/LanguageExt.Core/Effects/Eff/Prelude/Eff.Prelude.catch.cs#L129

**Comment by louthy** [comment]
Nice spot, fixed in `v3.5.55-beta`
