### ISSUE TITLE
Why don't we have a `FirstOrNone` method?

### ISSUE THREAD

**Issue by MrYossu** [louthy/language-ext#925]
Sorry if this is a stupid question, but you don't get anywhere if you don't ask!

As a slowly reforming OO programmer, I'm trying not to write code like this...

```c#
Customer jim = await ctx.Customers.FirstOrDefault(c => c.FirstName = "Jim");
if (jim != null) {
  // Do something with jim
} else {
  // Do whatever we do if Jim has gone on holiday
}
```

...but rather write code like this...

```c#
GetUser("jim")
  .Match(u => Console.WriteLine($"Found {u.FirstName} {u.Surname}"),
         () => Console.WriteLine("Nope"));

Option<AspNetUsers> GetUser(string firstName) =>
  AspNetUsers.FirstOrDefault(u => u.FirstName == firstName);
```

It seems it would be useful to have a `FirstOrNone` method...

```c#
  public static Option<T> FirstOrNone<T>(this IEnumerable<T> coll, Predicate<T> f) {
    return coll.FirstOrDefault(t => f(t));
```

...as this would enable us to achieve the same without needing our own `GetUser` method...

```c#
customers
  .FirstOrNone(u => u.FirstName == "Jim")
  .Match(u => Console.WriteLine($"Found {u.FirstName} {u.Surname}"), () => Console.WriteLine("Nope"));
```

Does LanguageExt have anything like this? If not, is there a good reason why not?

**Comment by MartonBoda** [comment]
Isn't "Find" what you're looking for?
Returns the first matching element or none.

customers.Find(u => u.FirstName == "Jim")
