### ISSUE TITLE
Asp.net JSON Serialization NewType

### ISSUE THREAD

**Issue by RollsChris** [louthy/language-ext#932]
Hi,

We want to use NewType in our project to give strongly typed IDs etc. 

We have written custom JSONconverters and placed on the new classes which work fine when using JsonConvert.SerializeObject. But when we try and return a JsonResult by passing the object into Json() in our actions, they are being serialized incorrectly.

With  JsonConvert.SerializeObject the out put is "GUIDHERE" (correct)
`Json(JsonConvert.SerializeObject(CipMakeupHistoryId.New(Guid.NewGuid())), JsonRequestBehavior.AllowGet)`

But without, it is  {value:"NewGuidHere"}.

`Json(CipMakeupHistoryId.New(Guid.NewGuid()), JsonRequestBehavior.AllowGet);`

I have tried registering the converter globallly like so:

`GlobalConfiguration.Configuration.Formatters.JsonFormatter.SerializerSettings.Converters.Add(new NewTypeConverter());
`

But its not taking effect. 

Just wondering if anyone has any pointers or solved the same issue. Cant see an issues similar which have been reported.

Thanks

**Comment by louthy** [comment]
https://github.com/louthy/language-ext/wiki/Frequently-Asked-Questions#where-have-the-newtype-numtype-and-FloatType-gone
