### ISSUE TITLE
TryMonadTests.cs FAILS in debug mode (but works in release mode)

### ISSUE THREAD

**Issue by josephr5000** [louthy/language-ext#934]
@louthy firstly thanks for such a wonderful library!  Your work is amazing and much appreciated.

I'm trying to understand how to use `Try<A>` and failing so thought I'd run your test.

https://github.com/louthy/language-ext/blob/master/LanguageExt.Tests/TryMonadTests.cs PASSES in RELEASE but FAILS in DEBUG.

**TO REPRO**
1. `dotnet new console` to create a new .Net Core 5.0 console app
2. `dotnet add package LanguageExt.Core --version 4.0.3` to install your latest release
3. Copy/paste your `TryMonadTests.cs` into the boilerplate `UnitTests1.cs` overwriting existing code, changing namespace to match my project.
4. Test/Run All Tests.  RESULT: 17 passed, 0 failed, 0 skipped.  GOOD!
5. Test/Debug All Tests.

**NOTICE**

Running tests under debug fails at line 192 when the `Exception` is thrown:

![image](https://user-images.githubusercontent.com/8585358/139560806-7e9261a9-aac0-4f88-96e4-1ffb5e0fd9c9.png)

**EXPECT**

No exception, as that's the whole point of using `Try<A>`.

**NOTES**
- Using Visual Studio Community 2019 version 16.11.3, and .Net 5.0.
- Can provide further config info on request if you need it.
- If **release** also failed that would be bad, but less confusing. What really mystifies me is why would this only fail when debugging?

Is this -- exceptions not captured by Try<A> in debug mode -- expected behavior?  Hopefully not!  Hopefully I'm just doing something wrong here.......

**Comment by louthy** [comment]
The link you posted was to the old `master` branch, which must be two years old now.  So, before I look into this, could you just make sure you've cloned the `main` branch, and are working with the latest code?

**Comment by louthy** [comment]
One other thing.  I notice you've posted a screenshot of the exception being thrown in the debugger.  Visual Studio will always break at the point of the exception *whilst debugging*, but you can press F5 to continue and the exception will be caught by the `Try` machinery.  There is no difference between debug and release modes in the `Try` system.

**Comment by louthy** [comment]
For reference: https://github.com/louthy/language-ext/issues/892#issuecomment-886267784

**Comment by josephr5000** [comment]
@louthy many thanks for your quick reply and sorry for the duplicate. My issue is precisely what #892 reported. 

And also thanks for your note about branches. I see the one I linked is from the `master` branch but you're now on `main`.

Case closed.

**Comment by josephr5000** [comment]
(ps: wondering if it would make sense to delete the unused `master` branch?)

**Comment by louthy** [comment]
> (ps: wondering if it would make sense to delete the unused master branch?)

Yep, I thought I had, it's gone now.
