### ISSUE TITLE
Why doesn't `TryAsync` wrap up this exception?

### ISSUE THREAD

**Issue by MrYossu** [louthy/language-ext#953]
I'm trying to use `TryAsync` to ensure that my methods return something the consumer can handle neatly. I thought that the point of `TryAsync` was that if an exception was thrown in the code inside, it would return the exception, which could be handled in the appropriate action passed to `Match`.

However, I have the following code. This makes calls to the Google Drive API, but the details of that aren't relevant...

```c#
public async Task<TryAsync<DriveFile>> GetParentFolder(string folderId) {
  FilesResource.GetRequest request = _service.Files.Get(folderId);
  request.Fields = "id, name, parents";
  DriveFile folder = await request.ExecuteAsync();
  request = _service.Files.Get(folder.Parents[0]);
  return TryAsync(() => request.ExecuteAsync());
}
```

This is fine when the `folderId` is not for the root folder. However, if I pass in the `Id` of the root folder, then the `folder.Parents` collection is `null` (why not empty? Don't ask me). This means that the penultimate line of code throws an NRE.

I was expecting the NRE to be caught and handled by `TryAsync`, but instead, my code crashes.

What am I doing wrong? Thanks

**Comment by Malgefor** [comment]
Because the exception is not thrown in the `TryAsync`-body, but before you get to the `return TryAsync(() => request.ExecuteAsync());`. And don't wrap a `TryAync` in a `Task` since `TryAync` is already async, but seeing your other questions you probably figured this out already 😁
