### ISSUE TITLE
MatchUnsafe on EitherUnsafe requires non-null bottom action

### ISSUE THREAD

**Issue by pzelmanski** [louthy/language-ext#955]
When running the code for below, I get `BottomException`. The solution is to add empty Bottom to last match:
``` 
xx.Value.MatchUnsafe(
    r => Console.WriteLine("right"),
    l => Console.WriteLine("left"),
    () => { });
```
When I was debugging, it goes into `match`, executes `right` function and then throws exception because `bottom` is null.

Minimal repro:
```
using System;
using System.Security.Cryptography;
using System.Threading.Tasks;
using LanguageExt;
using LanguageExt.ClassInstances.Const;

Console.WriteLine("Hello, World!");
var xx = await new EitherThing().DoStuff();

xx.Value.MatchUnsafe(
    r => Console.WriteLine("right"),
    l => Console.WriteLine("left"));

public class MyBox
{
    public EitherUnsafe<int, bool> Value { get; }
    public MyBox(EitherUnsafe<Int32, Boolean> value)
    {
        this.Value = value;
    }
}
public class EitherThing
{
    public async Task<MyBox> DoStuff() =>
        (await GetValue()).MatchUnsafe(
            b => new MyBox(true),
            i => null);

    private Task<EitherUnsafe<int, bool>> GetValue() => Task.FromResult<EitherUnsafe<int, bool>>(true);
}
```

**Comment by louthy** [comment]
This should only be needed if you have an `Either` in a bottom state, this can happen like so:

Using `default`:
```c#
    EitherUnsafe<int, bool> ma = default;
```
Or, an initialised field/property:
```c#
    class Foo
    {
        EitherUnsafe<int, bool> Bar;

        public Foo() { }
    }
```
Using `where` or `Filter`:
```c#
    var mb = from x in RightUnsafe<bool, int>(100)
             where x > 100
             select x;
```
In the above example, you can use `guard` to provide a `Left` value for when the predicate returns `false`:
```c#
    var mb = from x in RightUnsafe<bool, int>(100)
             from _ in guard(x > 100, false)
             select x;
```
Your example appears to be ok, other than `DoStuff` can return a `null` value, which you then dereference.  I assume this is an example you've created to raise the issue, so I am assuming that this isn't quite right?

**Comment by pzelmanski** [comment]
Yes, to this is a 'minified' representation of how I've tried to use it in already existing system.
I expect `xx` in this case to be null (so that `Either<int, bool>` can be null).
The problem is that when either is in `Right` state, and inspecting it manually while debugging shows that indeed it is in `Right` stane and not the `Bottom` one, I still get `BottomException` because of missing `Bottom` action in `MatchUnsafe` function.
