### ISSUE TITLE
Unity info in README.md

### ISSUE THREAD

**Issue by marcinjahn** [louthy/language-ext#981]
The Unity information in the README file seems a bit outdated. It mentions upcoming 2018 version of Unity. Is this bit of information still needed in 2022? Or maybe it could be updated?

**Comment by louthy** [comment]
That's the last time I got some positive feedback about Unity, so I leave it there as a benchmark of when it definitely worked.  I have no easy way of testing if this library continues to work with Unity.  If anyone has a mechanism to test this (maybe by providing a `\Sample\UnityTest` PR, I would be very grateful.

**Comment by louthy** [comment]
Removed from README
